### PR TITLE
test(storage): add emulator README.md and add `rest_only` for bucket

### LINKED ISSUE #1037: Enhance testbench to fully support fields parameter
The `fields` query parameter can include complex filter expressions:

https://cloud.google.com/storage/docs/json_api/v1/how-tos/performance#partial-response

But we current only support simple field names separated by comma (e.g. `field1,field2`).

### PR DESCRIPTION
**Pull request by vnvo2409**
This PR:
- adds README.md for the new emulator.
- adds `rest_only` for `Bucket` in order to support issue like #5491 .
- refactor `rest_only` of `Object` and `DataHolder`, after this PR, if we have new REST only fields, we could add it to `rest_only_fields` and the emulator will extract that field automatically.
- I accidentally call `blob.patch` in `object_update` ( which is fine because `patch` and `update` work similarly ). I change to `blob.update` in this PR. I also add tests for object's`update` and `patch`.
- `media_headers`'s in `parse_multipart` should be converted to lower.

Close #1037 ( It could be closed before but this PR is fine )
Part of #4751

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
looks good. We will probably need to iterate on the README (documents always seem to generate more nit-picky comments).  +kokoro:run 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-:-MMGs9mj41EeG2aaOD2L:bknvfo8)* status: all files reviewed, 6 unresolved discussions (waiting on @vnvo2409)

___
*[google/cloud/storage/emulator/README.md, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-MMGqNylEbWsBLqD-W7Y:-MMGqNylEbWsBLqD-W7Z:b-ia64pk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ac8c9ac1e0b8b3c9b98be6b419529342c199ef25/google/cloud/storage/emulator/README.md#L1)):*
> ```Markdown
> # Storage Emulator for Python 3
> ```

s/Storage/Google Cloud Storage/

I am not sure about "for Python 3" ... maybe "A Python 3 Google Cloud Storage Emulator", though often the programming language for the emulator is not that interesting, after all it can be used to test programs in C++, Python, Go, Java or any other language.
___
*[google/cloud/storage/emulator/README.md, line 3 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-MMGqCzs-tKpjMScpaWz:-MMGqCzs-tKpjMScpaX-:b-8egath) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ac8c9ac1e0b8b3c9b98be6b419529342c199ef25/google/cloud/storage/emulator/README.md#L3)):*
> ```Markdown
> # Storage Emulator for Python 3
> 
> This is a emulator for the Storage gRPC API, JSON API, and a limited support for the XML API. While it emulates most of the behaviors of Google Cloud Storage, it was developed mostly as an emulator for the client library, the emulator, for example, performs far fewer error checks and a little permission checks (ACL/IAM). Generally, the error codes are similar to the ones generated by GCS, but the error messages are not. In short, this is intended for testing, and not as a general purpose emulator.
> ```

s/library, the emulator/library. The emulator/
___
*[google/cloud/storage/emulator/README.md, line 3 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-MMGqHcO4gs5R8n5jsbZ:-MMGqHcO4gs5R8n5jsb_:b-kg6xh0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ac8c9ac1e0b8b3c9b98be6b419529342c199ef25/google/cloud/storage/emulator/README.md#L3)):*
> ```Markdown
> # Storage Emulator for Python 3
> 
> This is a emulator for the Storage gRPC API, JSON API, and a limited support for the XML API. While it emulates most of the behaviors of Google Cloud Storage, it was developed mostly as an emulator for the client library, the emulator, for example, performs far fewer error checks and a little permission checks (ACL/IAM). Generally, the error codes are similar to the ones generated by GCS, but the error messages are not. In short, this is intended for testing, and not as a general purpose emulator.
> ```

Use 80 columns in this README.
___
*[google/cloud/storage/emulator/README.md, line 3 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-MMGqvqcDRk2CzbPQTvs:-MMGqvqcDRk2CzbPQTvt:b-6a3782) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ac8c9ac1e0b8b3c9b98be6b419529342c199ef25/google/cloud/storage/emulator/README.md#L3)):*
> ```Markdown
> # Storage Emulator for Python 3
> 
> This is a emulator for the Storage gRPC API, JSON API, and a limited support for the XML API. While it emulates most of the behaviors of Google Cloud Storage, it was developed mostly as an emulator for the client library, the emulator, for example, performs far fewer error checks and a little permission checks (ACL/IAM). Generally, the error codes are similar to the ones generated by GCS, but the error messages are not. In short, this is intended for testing, and not as a general purpose emulator.
> ```

s/the Storage /the Google Cloud Storage (GCS) / and then you can simply say "GCS" in the rest of this document.
___
*[google/cloud/storage/emulator/README.md, line 3 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-MMGrPhm97FqYF4WWRE7:-MMGrPhm97FqYF4WWRE8:baxknu1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ac8c9ac1e0b8b3c9b98be6b419529342c199ef25/google/cloud/storage/emulator/README.md#L3)):*
> ```Markdown
> # Storage Emulator for Python 3
> 
> This is a emulator for the Storage gRPC API, JSON API, and a limited support for the XML API. While it emulates most of the behaviors of Google Cloud Storage, it was developed mostly as an emulator for the client library, the emulator, for example, performs far fewer error checks and a little permission checks (ACL/IAM). Generally, the error codes are similar to the ones generated by GCS, but the error messages are not. In short, this is intended for testing, and not as a general purpose emulator.
> ```

s/gRPC API, JSON API/JSON API (both over REST and gRPC)/ we (Google) think of both as the same APIs, with different protocols, but the same APIs.
___
*[google/cloud/storage/emulator/README.md, line 66 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-MMGrs10Bdd7SoXMYoJL:-MMGrs10Bdd7SoXMYoJM:bmua4sp) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ac8c9ac1e0b8b3c9b98be6b419529342c199ef25/google/cloud/storage/emulator/README.md#L66)):*
> ```Markdown
> Set request headers with `x-goog-testbench-instructions: return-503-after-256K/retry-1` up to `x-goog-testbench-instructions: return-503-after-256K/retry-N`.
> 
> For N==1 and N==2 behave like `return-305-after-256K`, for `N>=3` ignore the failure instruction and return successfully. This is used to test failures during retry, the client cooperates by sending the retry counter in the failure instructions.
> ```

justify to 80 columns.

**Comment by vnvo2409** [comment]
Before fixing `README.md`, I think it is a good idea to implement the idea of #5462 . However, I find that `sha256` is a little bit slow. 

I am thinking of something like `git diff current-commit master-branch-commit google/cloud/storage/emulator` and if the diff isn't empty, we could use `--cache_test_results=no`. 

It will also ensure that everytime we kick off a CI in a PR with the change in emulator, the tests caches will be invalidated ( with `sha256`, they will be invalidated only once ). But I can not find a way to get the `master-branch-commit` ( or `current-destination-branch-commit` ). WDYT ?

**Comment by coryan** [comment]
> Before fixing `README.md`, I think it is a good idea to implement the idea of #5462 . However, I find that `sha256` is a little bit slow.

How slow is slow?  Seconds, minutes?

> 
> I am thinking of something like `git diff current-commit master-branch-commit google/cloud/storage/emulator` and if the diff isn't empty, we could use `--cache_test_results=no`.

Where would you do that?  In `storage/ci/run*`?  Just confirming we would not be affecting any other cached result (say the Pub/Sub or Spanner integration tests).  Having said that, it seems like this would have some downsides:

- It does not work if the target branch is not `master`
- consider a PR that has changes in `storage/emulator` and outside it, the first build should get an uncached build, after a review, if the changes to do not affect the emulator, maybe we should not?

> 
> It will also ensure that everytime we kick off a CI in a PR with the change in emulator, the tests caches will be invalidated ( with `sha256`, they will be invalidated only once ).

That is a win for the sha256 approach in my book.  Do you see it as a downside?  Can you explain why?

> But I can not find a way to get the `master-branch-commit` ( or `current-destination-branch-commit` ).

There is some code in `ci/kokoro/docker/build-in-docker-cmake.sh` that figures out what files changed in a PR.

> WDYT ?

The code to figure PR changes is less robust than sha256 and has some downsides too.

**Comment by vnvo2409** [comment]
> The code to figure PR changes is less robust than sha256 and has some downsides too.

I am overthinking it. Let's go with the sha256.

> s/gRPC API, JSON API/JSON API (both over REST and gRPC)/ we (Google) think of both as the same APIs, with different protocols, but the same APIs.

It is a little weird to me, because `gRPC` uses `Protobuf`. There 's nothing to do with `JSON` in `gRPC`. Maybe Protobuf API ?

**Review by coryan — CHANGES_REQUESTED** [review]
> It is a little weird to me, because gRPC uses Protobuf. There 's nothing to do with JSON in gRPC. Maybe Protobuf API ?

I agree it is weird. The intention is (I believe) to make it clear that we want both gRPC and REST to offer the same functionality (they don't right now, as gRPC is not GA, but that is where we want things to go). I just trust my colleagues in product management, and follow their guidance here.

+kokoro:run 

a small nit, I am starting the builds regardless so you can get feedback.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-:-MMM9jbo6xh0cssBLvZH:b-rdl87f)* status: all files reviewed, 1 unresolved discussion (waiting on @vnvo2409)

___
*[google/cloud/storage/emulator/README.md, line 6 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-MMMACTJ3O5yvlvvlFNb:-MMMACTJ3O5yvlvvlFNc:bdaugl1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7766f993b0f85edf7af0de2fb48208a3afc5bb39/google/cloud/storage/emulator/README.md#L6)):*
> ```Markdown
> REST and gRPC), and a limited support for the XML API. While it emulates most of
> the behaviors of GCS, it was developed mostly as an emulator for the client
> library. The emulator, for example, performs far fewer error checks and a little
> ```

s/a little/no/

**Review by coryan — COMMENTED** [review]
:lgtm: +kokoro:run 

Not approving as I want a second run without changes to verify the cache is used.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-:-MMMJ54zDHh-ovRk0BBL:b-19wi6z)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — COMMENTED** [review]
+kokoro:force-run to verify 

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-:-MMMRR6W5Ibz5VTZPPAd:b-av0uuw)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — APPROVED** [review]
Yay! The second run used the cached results. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5507#-:-MMMVNRd32aFZmGo-s9G:b-gunmm9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
