### PR TITLE
cleanup(storage): remove unused code in emulator

### PR DESCRIPTION
**Pull request by coryan**
Since we are no longer sending gRPC requests for Bucket metadata
operations, we do not need to emulate them either. This is needed
because the v2/ protos do not expose these RPCs (yet).

Part of the work for #6982

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048)

### CODE REVIEW

**Review by dbolduc — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/storage/emulator/gcs/bucket.py, line 466 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048#-MfJF-AaChGfiwdIa8-f:-MfJF-AbChlkV9tYF47Z:btn7zwq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4ae8f5300cde4b696c29e1f14f5aa1da959db707/google/cloud/storage/emulator/gcs/bucket.py#L466)):*
> ```Python
>             "kind": "storage#notification",
>             "id": "notification-%d" % random.getrandbits(16),
>             "payload_format": "JSON_API_V1",
> ```

I'm sure you know, but I do not know why `"JSON_API_V1" is the default value
___
*[google/cloud/storage/emulator/tests/test_bucket.py, line 302 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048#-MfJEolWBvL8-m3ylWUv:-MfJEolWBvL8-m3ylWUw:bmb2ssc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4ae8f5300cde4b696c29e1f14f5aa1da959db707/google/cloud/storage/emulator/tests/test_bucket.py#L302)):*
> ```Python
>         bucket, _ = gcs.bucket.Bucket.init(request, None)
> 
>         for topic in ["test-topic-1", "test-topic-2"]:
> ```

why do we need the loop?
___
*[google/cloud/storage/emulator/tests/test_bucket.py, line 311 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048#-MfJEXWvAfchaT4ZLX7M:-MfJEXWwEGhPUUtyGUsH:b-hzj2y7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4ae8f5300cde4b696c29e1f14f5aa1da959db707/google/cloud/storage/emulator/tests/test_bucket.py#L311)):*
> ```Python
> 
>             get = bucket.get_notification(notification["id"], None)
>             self.assertEqual(notification, get)
> ```

`get` is a strange variable name

**Review by coryan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @dbolduc)

___
*[google/cloud/storage/emulator/gcs/bucket.py, line 466 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048#-MfJF-AaChGfiwdIa8-f:-MfJSHmn2uGS83Yl0hjy:bi44lk7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4ae8f5300cde4b696c29e1f14f5aa1da959db707/google/cloud/storage/emulator/gcs/bucket.py#L466)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I'm sure you know, but I do not know why `"JSON_API_V1" is the default value
</blockquote></details>

It should not have been, thanks for pointing it out.
___
*[google/cloud/storage/emulator/tests/test_bucket.py, line 302 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048#-MfJEolWBvL8-m3ylWUv:-MfJSMQb3Os8StixwUDQ:bws5ml6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4ae8f5300cde4b696c29e1f14f5aa1da959db707/google/cloud/storage/emulator/tests/test_bucket.py#L302)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

why do we need the loop?
</blockquote></details>

Because I was going to test listing, and then I forgot.  Fixed.
___
*[google/cloud/storage/emulator/tests/test_bucket.py, line 311 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048#-MfJEXWvAfchaT4ZLX7M:-MfJSRW55i-HYPsJS28e:bt2vr1b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4ae8f5300cde4b696c29e1f14f5aa1da959db707/google/cloud/storage/emulator/tests/test_bucket.py#L311)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

`get` is a strange variable name
</blockquote></details>

Fixed.

**Review by coryan — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048#-:-MfJT1a72HRPqQa-xD56:bb71pro)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @dbolduc)

**Review by dbolduc — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @coryan and @dbolduc)

___
*[google/cloud/storage/emulator/tests/test_bucket.py, line 319 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048#-MfJW9k3-cgK85lyvDQa:-MfJW9k3-cgK85lyvDQb:b-ayduuk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f8a45ee50bdc2850092099530549f950eded2d2a/google/cloud/storage/emulator/tests/test_bucket.py#L319)):*
> ```
>         for id in [n["id"] for n in expected]:
>             bucket.delete_notification(id, None)
> ```

I think this would be easier on the eyes:
```
for n in expected:
  bucket.delete_notification(n["id"], None)
```

**Review by coryan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @dbolduc)

___
*[google/cloud/storage/emulator/tests/test_bucket.py, line 319 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7048#-MfJW9k3-cgK85lyvDQa:-MfJXSCF-dMhFq-PjbCA:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f8a45ee50bdc2850092099530549f950eded2d2a/google/cloud/storage/emulator/tests/test_bucket.py#L319)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

> ```
>         for id in [n["id"] for n in expected]:
>             bucket.delete_notification(id, None)
> ```

I think this would be easier on the eyes:
```
for n in expected:
  bucket.delete_notifications(n["id"], None)
```
</blockquote></details>

Done.

**Review by dbolduc — APPROVED** [review]

**Pull request merged**
