### PR TITLE
doc: ADR for versioned clients

### PR DESCRIPTION
**Pull request by dbolduc**
Per the discussion in our latest team meeting.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177)

### CODE REVIEW

**Review by scotthart — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dbolduc)

___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 15 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NG2L-OEBZMARmH6jH5D:-NG2L-OEBZMARmH6jH5E:bfu6kws) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L15)):*
> ```Markdown
> 
> vN and vN+1 of a GCP service might exist at the same time. They might share
> names (although not package names), but have different feature sets. Customers
> ```

What is meant by "package" in C++?
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 36 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NG2LLte4m1ePqYxxdKR:-NG2LLte4m1ePqYxxdKS:bof5g4u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L36)):*
> ```Markdown
> 
> We will continue to group nested services in one library, under
> `google/cloud/<library>`. The subdirectory structure of a library will now match
> ```

Can you elaborate here? I think you mean that our google/cloud/library will now have version subdirectories that match the versions specified in googleapis/googleapis. But other than that, we won't be matching other aspects of the googleapis/googleapis directory hierarchy.



_Code quote:_
```Markdown
`google/cloud/<library>`. The subdirectory structure of a library will now match
that of the subdirectory structure within `googleapis/googleapis`.
```

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177)* status: all files reviewed, 9 unresolved discussions (waiting on @dbolduc and @scotthart)

___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 4 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHgcjc-r9BBjGO_wGk:-NGHgcjc-r9BBjGO_wGl:b9xvnxo) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L4)):*
> ```Markdown
> library.
> 
> **Status**: proposed
> ```

Remember to fix this status before merging.
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 7 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHfmLS21M-BylHZPHq:-NGHfmLT7qW9248gLQtm:b-irh0j7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L7)):*
> ```Markdown
> 
> **Context**:
> We need our libraries to be resilient against new versions of existing GCP
> ```

Consider:

```
Some services already have more than one version. We anticipate that existing services may add new versions over time.  Our libraries should be able to support more than one version of a service at the same time.
```
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 12 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHgRnEDFNLBtxmaNNK:-NGHgRnEDFNLBtxmaNNL:b-8g9ytv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L12)):*
> ```Markdown
> Note that we are talking about different versions of a GCP service. That is, the
> version that would appear in that service's API reference docs. We are not
> talking about versions of the google-cloud-cpp client library.
> ```

nit: Should we style `google-cloud-cpp` as code?
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 15 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NG2L-OEBZMARmH6jH5D:-NGHfj33CmJvpzJf6IBs:b-ntyzp3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L15)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

What is meant by "package" in C++?
</blockquote></details>

Consider "protobuf package names"
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 20 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHgsM-1LWJxh-TIvRG:-NGHgsM-1LWJxh-TIvRH:busk2zw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L20)):*
> ```Markdown
> Historically, we have defined a client library in `google/cloud/<library>`,
> regardless of the directory structure in `googleapis/googleapis`. We have
> included all nested services in that library. We have defined clients for these
> ```

"nested services" is confusing cause and effect.  Maybe "Historically, we have grouped related services into a single library.  The code for such a library, including all the `*Client` classes for these services are placed in a flat hierarchy under `google/cloud/<library>`." ?
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 26 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHhWpJ1OCITuU4o0Kt:-NGHhWpJ1OCITuU4o0Ku:bhccv5x) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L26)):*
> ```Markdown
> For example, at the moment of writing this, `google::cloud::bigquery` contains
> multiple nested services. These services have independent versions (some are v1,
> some are v2). If a new version of one of these services was released, we could
> ```

s/could not necessarily/ ?  Maybe "we would not be able to place the types and functions for this service in the `google::cloud::bigquery` namespace, as the new symbols ..."?

I would move this to be the first paragraph of the "context" section.  Maybe something like:

"The current directory and namespace structure does not support the addition of new versions of a service. We need to change the libraries to fix this."
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 32 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHiHr9BscplzXEfB96:-NGHiHr9BscplzXEfB97:b-x37y2g) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L32)):*
> ```Markdown
> 
> **Decision**:
> We recognize that it is necessary to capture the version of individual GCP
> ```

I would skip this paragraph.
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHmBcC7ERYGjxgpQTP:-NGHmBcC7ERYGjxgpQTQ:b-wbru38) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L56)):*
> ```Markdown
> existing GCP services (because we now have a protocol).
> 
> Service namespaces will become more verbose, as they will necessarily
> ```

I would move this up above the previous paragraph.

**Review by dbolduc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @coryan and @scotthart)

___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 4 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHgcjc-r9BBjGO_wGk:-NGZAV1G1v0N_blZbuYz:b-doszji) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L4)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Remember to fix this status before merging.
</blockquote></details>

noted. I expect at least another round of changes.
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 7 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHfmLS21M-BylHZPHq:-NGZA6th6PqeO4bsnSFC:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L7)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Consider:

```
Some services already have more than one version. We anticipate that existing services may add new versions over time.  Our libraries should be able to support more than one version of a service at the same time.
```

</blockquote></details>

Done.
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 12 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHgRnEDFNLBtxmaNNK:-NGZA7hiAXLHSVKo7JUT:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L12)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: Should we style `google-cloud-cpp` as code?
</blockquote></details>

Done.
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 15 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NG2L-OEBZMARmH6jH5D:-NGZ9LqN8JiwEJe820rI:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L15)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Consider "protobuf package names"
</blockquote></details>

Done.
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 20 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHgsM-1LWJxh-TIvRG:-NGZAiIO186Zx6WGOfAl:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L20)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

"nested services" is confusing cause and effect.  Maybe "Historically, we have grouped related services into a single library.  The code for such a library, including all the `*Client` classes for these services are placed in a flat hierarchy under `google/cloud/<library>`." ?
</blockquote></details>

Done.
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 26 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHhWpJ1OCITuU4o0Kt:-NGZAjC7BAo0w4dqlOh8:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L26)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

s/could not necessarily/ ?  Maybe "we would not be able to place the types and functions for this service in the `google::cloud::bigquery` namespace, as the new symbols ..."?

I would move this to be the first paragraph of the "context" section.  Maybe something like:

"The current directory and namespace structure does not support the addition of new versions of a service. We need to change the libraries to fix this."

</blockquote></details>

Done.
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 32 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHiHr9BscplzXEfB96:-NGZAkF98JMkID-tcCi6:bss4a2b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L32)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I would skip this paragraph.
</blockquote></details>

Removed.
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 36 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NG2LLte4m1ePqYxxdKR:-NGZ9_a96YDrSt5IxfW-:bjawwbl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L36)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Can you elaborate here? I think you mean that our google/cloud/library will now have version subdirectories that match the versions specified in googleapis/googleapis. But other than that, we won't be matching other aspects of the googleapis/googleapis directory hierarchy.
</blockquote></details>

I hope it's clearer now, but it could probably use another round of edits.

I tried to lay out that we map from googleapis/A -> google-cloud-cpp/B

And then within A and B, the subdirectory structure matches.

(I think this comment is clearer than the words I wrote in the ADR..... maybe I should just use it instead....)
___
*[`doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md` line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGHmBcC7ERYGjxgpQTP:-NGZAlWS72gc7uKOgmWg:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4e53ee2397167a5afc1e9094c15aef32952ebc8a/doc/adr/2022-11-03-multiple-versions-of-GCP-service-in-one-library.md#L56)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I would move this up above the previous paragraph.
</blockquote></details>

Done.

**Review by coryan — CHANGES_REQUESTED** [review]
A couple of small nits, others :lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-:-NGb7eQ9EkfFwRe2J6FY:b-515aet)* status: all files reviewed, 3 unresolved discussions (waiting on @dbolduc and @scotthart)

___
*[`doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md` line 21 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGb6Tpv45T0GGY4hXoD:-NGb6Tpv45T0GGY4hXoE:b-j3wfdg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ae88c1ea092043fef1da34419839ba727b49d127/doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md#L21)):*
> ```Markdown
> 
> vN and vN+1 of a GCP service might exist at the same time. They might share
> names (although not protobuf package names), but have different feature sets.
> ```

consider s/, but/, and/
___
*[`doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md` line 23 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGb6bsWCS5FNeYwofwe:-NGb6bsWCS5FNeYwofwf:b-acngh0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ae88c1ea092043fef1da34419839ba727b49d127/doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md#L23)):*
> ```Markdown
> names (although not protobuf package names), but have different feature sets.
> Customers must be able to use these different versions of the same GCP service,
> together.
> ```

Maybe "same GCP service in a single C++ program."?

**Review by dbolduc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @coryan and @scotthart)

___
*[`doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md` line 21 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGb6Tpv45T0GGY4hXoD:-NGbXP0c9twOOvqtrGyJ:bd0a7ly) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ae88c1ea092043fef1da34419839ba727b49d127/doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md#L21)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

consider s/, but/, and/
</blockquote></details>

I prefer "but". I hope I am conveying why we cannot just generate vN+1 over vN (because the features are different, and thus the API will break).

Maybe this was already obvious, as a service team would never create a vN+1 which is identical to vN.
___
*[`doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md` line 23 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGb6bsWCS5FNeYwofwe:-NGbXOmpEaJbcrQGSFWL:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ae88c1ea092043fef1da34419839ba727b49d127/doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md#L23)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Maybe "same GCP service in a single C++ program."?
</blockquote></details>

Done.

**Review by devbww — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177)* status: all files reviewed, 3 unresolved discussions (waiting on @coryan and @scotthart)

___
*[`doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md` line 21 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGb6Tpv45T0GGY4hXoD:-NGbbMx8ARJ5eKX4D_e6:bnt7q47) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ae88c1ea092043fef1da34419839ba727b49d127/doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md#L21)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I prefer "but". I hope I am conveying why we cannot just generate vN+1 over vN (because the features are different, and thus the API will break).

Maybe this was already obvious, as a service team would never create a vN+1 which is identical to vN.
</blockquote></details>

Yeah, "but".
___
*[`doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md` line 23 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGb6bsWCS5FNeYwofwe:-NGbbVfr9_G-TLDBF9Aw:b-7kid11) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ae88c1ea092043fef1da34419839ba727b49d127/doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md#L23)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

s/,//

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-:-NGbnu160iomLBWnWbVq:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @scotthart)

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177)* status: all files reviewed, 3 unresolved discussions (waiting on @dbolduc)

___
*[`doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md` line 43 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177#-NGbxDsk6JugTty7ai0c:-NGbxDsk6JugTty7ai0d:b-svq3qi) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/0ea2d7a0ab1701b123abf6a5b5e174c097fd6fe7/doc/adr/2022-11-10-multiple-versions-of-GCP-service-in-one-library.md#L43)):*
> ```Markdown
> Namespaces of services will match the subdirectory structure of the
> `google-cloud-cpp` library, but with `_` instead of `/`s. We cannot just nest
> the namespace, because that may conflict with the gRPC types. For example,
> ```

Technically these are the emitted protoc types. They are defined in the pb.h files, not the grpc.pb.h files.



_Code quote:_
```Markdown
gRPC
```

**Review by scotthart — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10177)* status: all files reviewed, 3 unresolved discussions (waiting on @dbolduc)

**Pull request merged**
