### PR TITLE
ci: upgrade `cxx20` to Fedora:40

### PR DESCRIPTION
**Pull request by alevenberg**
https://github.com/googleapis/google-cloud-cpp/issues/14076

This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14145)

### CODE REVIEW

**Comment by alevenberg** [comment]
Need to change to zlib-ng

**Comment by alevenberg** [comment]
I added
```
    dnf install -y zlib-ng-devel
```

and

```
        -DgRPC_ZLIB_PROVIDER=module \
```

Based on https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/BUILDING.md

But that is now failing to build gRPC. I think we might want to build zlib locally.

**Comment by coryan** [comment]
I think you want:

```
        -DgRPC_ZLIB_PROVIDER=package \
```

Using `module` is telling gRPC to build zlib from source, and we don't want that: the dependency tree gets terribly messy.

The errors look unrelated:

```
/usr/bin/ld: external/googleapis/libgoogle_cloud_cpp_rpc_status_protos.a(status.pb.cc.o): in function `absl::lts_20240116::log_internal::LogMessage::operator<<(unsigned long)':
status.pb.cc:(.text._ZN4absl12lts_2024011612log_internal10LogMessagelsEm[_ZN4absl12lts_2024011612log_internal10LogMessagelsEm]+0x19): undefined reference to `_ZN4absl12lts_2024011612log_internal10LogMessagelsImTnNSt9enable_ifIXntsr4absl16HasAbslStringifyIT_EE5valueEiE4typeELi0EEERS2_RKS5_'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

That is a missing symbol in Abseil. I wonder if they have some C++20 #ifdefs or something that causes trouble downstream?

**Comment by alevenberg** [comment]
Rebased & applied the following patch

```
diff --git a/ci/cloudbuild/builds/clang-cxx20.sh b/ci/cloudbuild/builds/clang-cxx20.sh
index 8cb8764e2c..9616d1dfb7 100755
--- a/ci/cloudbuild/builds/clang-cxx20.sh
+++ b/ci/cloudbuild/builds/clang-cxx20.sh
@@ -34,6 +34,7 @@ readonly ENABLED_FEATURES
 
 io::run cmake "${cmake_args[@]}" \
   -DCMAKE_CXX_STANDARD=20 \
+  -DGOOGLE_CLOUD_CPP_COMPILER_SUPPORTS_CLANG_ABI_COMPAT_17=ON \
   -DGOOGLE_CLOUD_CPP_ENABLE="${ENABLED_FEATURES}"
 io::run cmake --build cmake-out
 mapfile -t ctest_args < <(ctest::common_args)
```

**Review by coryan — APPROVED** [review]

**Pull request merged**
