### PR TITLE
fix: enable spanner slow integration tests 

### PR DESCRIPTION
**Pull request by devjgm**
These "slow" integration tests are only enabled for certain builds at
this point. For now, only the "integration" build (both CI and
presubmit), and builds that use the Spanner emulator.

In the previous repo, google-cloud-cpp-spanner, these tests were
controlled by the variable `RUN_SLOW_INTEGRATION_TESTS`, but in this
monorepo, that variable was too generic, so it was renamed to be
Spanner specific.

If these builds aren't too slow or cause too much contention, we can
enable them in more builds. Possibly even include them in all
builds that run integration tests. We'll see.

Fixes: #4228

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4295)

### CODE REVIEW

**Comment by devjgm** [comment]
The timing for the newly enabled tests in this from the "integration" build is:

```
//google/cloud/spanner/integration_tests:spanner_client_backup_integration_test PASSED in 742.8s
...
//google/cloud/spanner/integration_tests:spanner_client_instance_admin_integration_test PASSED in 25.7s
```

The overall time for the build was 20 min, 24 sec: https://source.cloud.google.com/results/invocations/6fa52828-e9d1-49e5-8e2d-6a4071e3616e/targets

**Comment by coryan** [comment]
I just realized: spanner now runs against the emulator, are these tests/examples disabled when running against the emulator?  I recall that backups are, maybe?

**Comment by devjgm** [comment]
> I just realized: spanner now runs against the emulator, are these tests/examples disabled when running against the emulator? I recall that backups are, maybe?

I don't think Spanner uses the emulator in the "integration" build that uses bazel. I filed an issue to track that (https://github.com/googleapis/google-cloud-cpp/issues/4297).

There are the Spanner+emulator+cmake tests (https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh), and in this PR I added "instance,backup".... though I'm not totally sure which of our builds hits this code path.

**Comment by devjgm** [comment]
> Ah, so the code is running in the `integration` build, but not in the `coverage` build. I missed that. LGTM then. We are slightly blind as to coverage, but otherwise Okay.
> 
> > Reviewed 7 of 7 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4295#-:-M8Rw8fO78g0-AUqat1_:bw16ysc)_ status: all files reviewed, 1 unresolved discussion (waiting on @devjgm)
> 
> _[google/cloud/spanner/integration_tests/instance_admin_integration_test.cc, line 58 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4295#-M8RvpTV0IgK8bnQQKcX:-M8RvpTV0IgK8bnQQKcY:b-ilfco4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/178d428816309e3e532f03683f2e24e4bbd92e92/google/cloud/spanner/integration_tests/instance_admin_integration_test.cc#L58)):_
> 
> > ```c++
> >             .value_or("");
> >     auto const run_slow_integration_tests =
> >         google::cloud::internal::GetEnv("ENABLE_SPANNER_SLOW_INTEGRATION_TESTS")
> > ```
> 
> nit: we have both `GOOGLE_CLOUD_CPP_SPANNER_TEST_*` and `ENABLE_SPANNER_*` variables... not sure if we want that.

True. I added it next to [`ENABLE_BIGTABLE_ADMIN_INTEGRATION_TESTS`](https://github.com/googleapis/google-cloud-cpp/blob/e01df8e3eb7e7d3c61c71dd7c59c1b713f8ff3e1/ci/kokoro/docker/build.sh#L444) and copied that naming style. But I think you're right that the GOOGLE_CLOUD_CPP prefix is more common and probably what we should following going forward.

Fixed.

**Pull request merged**
