### PR TITLE
cleanup(spanner): Use absl::FixedArray instead of vector

### PR DESCRIPTION
**Pull request by remyabel**
Fixes TODO (issue no longer exists).

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271)

### CODE REVIEW

**Comment by coryan** [comment]
@mr-salty can you take a look?  The code looks right, but you understand the advantages / rationale for `absl::FixedArray`.

**Comment by coryan** [comment]
___
*[google/cloud/spanner/BUILD, line 31 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271#-MK-zPXh6Qb_0mUyN31Z:-MK-zPXh6Qb_0mUyN31_:bwbwdk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/99f5a672d98216e9de6592e72964127ecd926d2e/google/cloud/spanner/BUILD#L31)):*
> ```Starlark
>         "//google/cloud:google_cloud_cpp_common",
>         "//google/cloud:google_cloud_cpp_grpc_utils",
>         "@com_google_absl//absl/container:fixed_array",
> ```

Can you do the analogous thing in the CMake file?  We use the CMake deps to generate pkg-config files, including indirect dependencies.

**Comment by coryan** [comment]
___
*[google/cloud/spanner/CMakeLists.txt, line 151 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271#-MK03TbI-DBtiNpddut6:-MK03TbI-DBtiNpddut7:bpb2i8n) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a88b36625c12dae50270a84a3f24757d08af332e/google/cloud/spanner/CMakeLists.txt#L151)):*
> ```CMake
> target_link_libraries(
>     spanner_client
>     PUBLIC absl::container
> ```

Just curious, why that instead of `absl::fixed_array`?  It seems to exist, at least based on browsing the generated `absl*.cmake` files.

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @coryan and @mr-salty)

___
*[google/cloud/spanner/BUILD, line 31 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271#-MK-zPXh6Qb_0mUyN31Z:-MK05g9a7VxAwjCWfBOp:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/99f5a672d98216e9de6592e72964127ecd926d2e/google/cloud/spanner/BUILD#L31)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Can you do the analogous thing in the CMake file?  We use the CMake deps to generate pkg-config files, including indirect dependencies.
</blockquote></details>

Done.
___
*[google/cloud/spanner/CMakeLists.txt, line 151 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271#-MK03TbI-DBtiNpddut6:-MK05ggY5p-h-55m3UJT:bqo0dv1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a88b36625c12dae50270a84a3f24757d08af332e/google/cloud/spanner/CMakeLists.txt#L151)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Just curious, why that instead of `absl::fixed_array`?  It seems to exist, at least based on browsing the generated `absl*.cmake` files.
</blockquote></details>

No particular reason other than I did not notice. Fixed.

**Review by mr-salty — APPROVED** [review]
:lgtm:

sorry, I missed Carlos' comment... exactly what I had in mind, thanks for the cleanup

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271#-:-MKIJtDb63wYv2DfZ71V:bhim7cy)* status: all files reviewed, 3 unresolved discussions (waiting on @coryan and @remyabel)

___
*[google/cloud/spanner/internal/session_pool.h, line 188 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271#-MKIKyHy1HEQ1i58BMta:-MKIKyHy1HEQ1i58BMtb:bo6s572) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fcce64505e8f2b1ade550323257f39fd61987515/google/cloud/spanner/internal/session_pool.h#L188)):*
> ```
>   // `channels_` is guaranteed to be non-empty and will not be resized after
>   // the constructor runs (so the iterators are guaranteed to always be valid).
> ```

I might change this to something like:

```
  // `channels_` is guaranteed to be non-empty.
  //  n.b.: `FixedArray` iterators are never invalidated.
```

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @coryan and @mr-salty)

___
*[google/cloud/spanner/internal/session_pool.h, line 188 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271#-MKIKyHy1HEQ1i58BMta:-MKIPenk0pzHwgheuXzU:b-q7f0ar) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fcce64505e8f2b1ade550323257f39fd61987515/google/cloud/spanner/internal/session_pool.h#L188)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

> ```
>   // `channels_` is guaranteed to be non-empty and will not be resized after
>   // the constructor runs (so the iterators are guaranteed to always be valid).
> ```

I might change this to something like:

```
  // `channels_` is guaranteed to be non-empty.
  //  n.b.: `FixedArray` iterators are never invalidated.
```
</blockquote></details>

Thanks for the feedback. Done.

**Review by mr-salty — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan)

**Review by coryan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5271)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
