### PR TITLE
refactor: dedicated grpc subdirectory

### PR DESCRIPTION
**Pull request by dbolduc**
Move the internal gRPC classes into their own subdirectory in `google/cloud/internal/grpc`. We did a similar thing in storage.

To make this PR, I run the following:

```sh
files=(...) # List taken from google_cloud_cpp_grpc_utils.cmake

mkdir google/cloud/internal/grpc

for f in "${files[@]}"; do
  # I am impatient and demand progress updates.
  echo "file: ${f}"

  # Find and replace in build files.
  sed -i "s;internal/${f};internal/grpc/${f};g" google/cloud/google_cloud_cpp_grpc_utils*

  # If file is a header...
  if $(echo "${f}" | grep -q "\.h" ); then
    # Find and replace over whole repo. ("" because these are always strings)
    #
    # This is slow and we could be more fine grained. But if we do this, and
    # generate-libraries builds clean, we are fairly confident the changes are
    # correct. Note that if there are conflicting file basenames, the builds
    # would fail.
    sed -i "s;google/cloud/internal/${f}\";google/cloud/internal/grpc/${f}\";g" $(git ls-files)

    # Fix header guards (non-idempotent)
    sed -i "s;GOOGLE_CLOUD_INTERNAL_;GOOGLE_CLOUD_INTERNAL_GRPC_;g" google/cloud/internal/${f}
  fi
done

for f in "${files[@]}"; do
  # Move the file in a separate loop (so I don't have to think about whether
  # git is tracking these files or not).
  mv google/cloud/internal/${f} google/cloud/internal/grpc/
done

ci/cloudbuild/build.sh -t checkers-pr

git add google/cloud/internal/grpc google/cloud/google_cloud_cpp_grpc_utils*
git commit -m "refactor: dedicated grpc subdirectory"
git commit -m "update includes" .

ci/cloudbuild/build.sh -t generate-libraries-pr
git commit -m "golden fixes" .
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13227)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 2376 of 2376 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13227)* status: all files reviewed, 4 unresolved discussions (waiting on @dbolduc)

___
*[`ci/cloudbuild/builds/lib/integration.sh` line 159 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13227#-NkuXRZZ8T6EqhIKMSvn:-NkuXRZZ8T6EqhIKMSvo:bif5rsj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2702291d1b903861fde7311d26da337d732946be/ci/cloudbuild/builds/lib/integration.sh#L159)):*
> ```Shell
>   production_integration_tests=(
>     # gRPC Utils integration tests
>     "google/cloud:internal_grpc_grpc_impersonate_service_account_integration_test"
> ```

This suggests the file should have lost its `grpc_` prefix.
___
*[`google/cloud/internal/grpc/grpc_access_token_authentication.h` line 0 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13227#-NkuYJvw306WnIPrHdeK:-NkuYJvw306WnIPrHdeL:bhafhtv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2702291d1b903861fde7311d26da337d732946be/google/cloud/internal/grpc/grpc_access_token_authentication.h#L0)):*
I think all these  `grpc/grpc_${name}` files should become `grpc/${name}`. Thoughts?
___
*[`google/cloud/internal/grpc/populate_grpc_options.h` line 15 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13227#-NkuZ0Wk3QBnJtK5wdhA:-NkuZ0Wk3QBnJtK5wdhB:b-sg11ce) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2702291d1b903861fde7311d26da337d732946be/google/cloud/internal/grpc/populate_grpc_options.h#L15)):*
> ```objc
> // limitations under the License.
> 
> #ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_INTERNAL_GRPC_POPULATE_GRPC_OPTIONS_H
> ```

the `_grpc_` in the middle of this filename is also kind of redundant.
___
*[`google/cloud/internal/grpc/time_utils.h` line 0 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13227#-Nku_6_d58SSOyN7zJ01:-Nku_6_d58SSOyN7zJ02:b-p88xj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2702291d1b903861fde7311d26da337d732946be/google/cloud/internal/grpc/time_utils.h#L0)):*
nit: there is nothing particularly "gRPC" about this file.  It is more of a Protobuf thing.  Now that we use Protobuf with REST-only libraries (sql, compute) it may be worthwhile to keep these things in `rest_protobuf_internal`.

**Review by dbolduc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13227)* status: all files reviewed, 4 unresolved discussions (waiting on @coryan)

___
*[`google/cloud/internal/grpc/time_utils.h` line  at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13227#-Nku_6_d58SSOyN7zJ01:-Nl-_1tJC7aY9NGBsix0:b-ks33z6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2702291d1b903861fde7311d26da337d732946be/google/cloud/internal/grpc/time_utils.h#L)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: there is nothing particularly "gRPC" about this file.  It is more of a Protobuf thing.  Now that we use Protobuf with REST-only libraries (sql, compute) it may be worthwhile to keep these things in `rest_protobuf_internal`.
</blockquote></details>

These APIs are used by gRPC-only libraries. They cannot depend on anything `rest_`.

https://github.com/googleapis/google-cloud-cpp/blob/803c09a7cf7d4e59b711eb31a7103bfa91f200a7/google/cloud/pubsub/message.cc#L72

**Review by coryan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13227)* status: all files reviewed, 3 unresolved discussions (waiting on @dbolduc)

___
*[`google/cloud/internal/grpc/time_utils.h` line  at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13227#-Nku_6_d58SSOyN7zJ01:-Nl-ayWNAT7T64cxEfIm:b6i0s2p) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2702291d1b903861fde7311d26da337d732946be/google/cloud/internal/grpc/time_utils.h#L)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

These APIs are used by gRPC-only libraries. They cannot depend on anything `rest_`.

https://github.com/googleapis/google-cloud-cpp/blob/803c09a7cf7d4e59b711eb31a7103bfa91f200a7/google/cloud/pubsub/message.cc#L72
</blockquote></details>

Ack.  Seems like we need a `google-cloud-cpp::protobuf_internal` library (with a better name).

**Comment by dbolduc** [comment]
I'll try again later.

**Pull request closed without merging**
