### PR TITLE
cleanup(storage): revise error message in emulator handle_retry_test_instruction

### LINKED ISSUE #6783: Storage(emulator): Revise error message in handle_retry_test_instruction()
When the storage emulator handles retry test instructions, instructions are dequeued and a Retry Test error message is sent along with the forced failure response. 

Revise error message from `str` to `dict` to match the json content-type. This avoids running into an `AttributeError` when creating a `GoogleAPICallError` from a `requests.Response` within [api-core/exceptions](https://github.com/googleapis/python-api-core/blob/8d8bc5150ee5543b4aeb2c271da034a5305d1436/google/api_core/exceptions.py#L399)

### PR DESCRIPTION
**Pull request by cojenco**
Revise error message in emulator handle_retry_test_instruction() from str to dict to match the json content-type. This avoids running into an `AttributeError` when creating a `GoogleAPICallError` from a `requests.Response` within [api-core/exceptions](https://github.com/googleapis/python-api-core/blob/8d8bc5150ee5543b4aeb2c271da034a5305d1436/google/api_core/exceptions.py#L399)

Fixes #6783

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6788)

### CODE REVIEW

**Comment by coryan** [comment]
The logs for the failed build are here:

https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/6788/08de3144ee95044cafb4a48c397db0469f2c41df/checkers-checkers/log-586625fa-2e2f-4275-af18-46b9d9b3e1ec.txt

```
Step #3: diff --git a/google/cloud/storage/emulator/utils/common.py b/google/cloud/storage/emulator/utils/common.py
Step #3: index 3d0d7f1..fa9719b 100644
Step #3: --- a/google/cloud/storage/emulator/utils/common.py
Step #3: +++ b/google/cloud/storage/emulator/utils/common.py
Step #3: @@ -388,15 +388,10 @@ def handle_retry_test_instruction(database, request, method):
Step #3:          items = list(error_code_matches.groups())
Step #3:          error_code = items[0]
Step #3:          error_message = {
Step #3: -            "error": {
Step #3: -                "message": "Retry Test: Caused a {}".format(error_code)
Step #3: -            }
Step #3: +            "error": {"message": "Retry Test: Caused a {}".format(error_code)}
Step #3:          }
Step #3:          utils.error.generic(
Step #3: -            msg=error_message,
Step #3: -            rest_code=error_code,
Step #3: -            grpc_code=None,
Step #3: -            context=None,
Step #3: +            msg=error_message, rest_code=error_code, grpc_code=None, context=None
Step #3:          )
Step #3:      retry_connection_matches = utils.common.retry_return_error_connection.match(
Step #3:          next_instruction
```

For future reference: there is a [link](https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/6788/08de3144ee95044cafb4a48c397db0469f2c41df/index.html) to them in an earlier [comment](https://github.com/googleapis/google-cloud-cpp/pull/6788#issuecomment-861670907).

nit: please create PRs from your fork, in general we do not create development or patch branches in this repository.  We want the branch list to be "clean".

**Comment by coryan** [comment]
Off-topic: I do not understand why the error messages need to be formatted in a particular way.  There is no guarantee that they would be, GCS may send errors as JSON objects, but the load balancers would not.  Your client library should be ready to receive errors that are not JSON payloads.

**Comment by cojenco** [comment]
In the emulator, `handle_retry_test_instruction()` raises a `RestException` and makes a response with [`flask.make_response(flask.jsonify(self.msg), self.code)`](https://github.com/googleapis/google-cloud-cpp/blob/1c30be46a0a5245e38cf4b4f76299ff6ab74dd1c/google/cloud/storage/emulator/utils/error.py#L32). 

[`flask.jsonify()`](https://flask.palletsprojects.com/en/2.0.x/api/?highlight=jsonify#flask.json.jsonify) returns a Response with the application/json mimetype. IIUC, this is confusing [python-api-core](https://github.com/googleapis/python-api-core/blob/8d8bc5150ee5543b4aeb2c271da034a5305d1436/google/api_core/exceptions.py#L411) to view the response as application/json mimetype while it is actually text/html. So this change is specifically to align with how the emulator makes flask responses.

**Review by coryan — COMMENTED** [review]
The code looks fine (thanks for explaining the intent), please fix the formatting to make the builds pass.

**Comment by cojenco** [comment]
Thanks @coryan for the comments and pointing me to the build logs. I will create PRs from my fork now on. Meanwhile, I still have one outstanding branch. Sorry for spamming the repo.

**Review by coryan — APPROVED** [review]
LGTM. The running test is about to flake, see #441. I will restart it in a minute and then merge.

**Pull request merged**
