### PR TITLE
feature(generator): support single repeated string field in pagination

### PR DESCRIPTION
**Pull request by scotthart**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715)* status: all files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[generator/internal/codegen_utils.cc, line 77 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715#-MRV9QKo51-Ts4Yh7xbe:-MRV9QKpBwmTYLxZwofz:b-i6racz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5b17a720391939070c55961d3b2cf2f1728b8d59/generator/internal/codegen_utils.cc#L77)):*
> ```cpp
> 
> std::string ProtoNameToCppName(absl::string_view proto_name) {
>   if (proto_name == "string") return "std::string";
> ```

What about `proto_name == bytes` ?  And why not support all the types here: https://developers.google.com/protocol-buffers/docs/proto3#scalar ?

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715)* status: all files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[generator/internal/codegen_utils.cc, line 77 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715#-MRV9QKo51-Ts4Yh7xbe:-MRVia1H4PEuNyskmocT:bj4mv1h) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5b17a720391939070c55961d3b2cf2f1728b8d59/generator/internal/codegen_utils.cc#L77)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

What about `proto_name == bytes` ?  And why not support all the types here: https://developers.google.com/protocol-buffers/docs/proto3#scalar ?
</blockquote></details>

Your comment prompted me to re-examine where I was putting the exception logic for this string case. ProtoNameToCppName was not the correct place to add this as its purpose is to format message types into C++ types. I have relocated the exception logic to where the dictionary value is assigned and added a comment to explain why.

Handling scalar types is done in CppTypeToString where we rely on protoc to determine the correct C++ type and the generator merely provides the character sequence for the C++ type.

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715)* status: all files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[generator/internal/descriptor_utils.cc, line 523 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715#-MRVqSsL-CL5V0kUiL6X:-MRVqSsL-CL5V0kUiL6Y:butf6jy) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2bd46daed32a0832c8e0ffb023a17679ca4905e9/generator/internal/descriptor_utils.cc#L523)):*
> ```cpp
>       // repeated field that is of primitive type string.
>       method_vars["range_output_type"] =
>           pagination_info->second == "string"
> ```

Glad to hear this is a better place for the exception, but you did not answer my question. If `string` deserves this treatment, why not `bytes`?  Why not all the other types too?

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715)* status: all files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[generator/internal/descriptor_utils.cc, line 523 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715#-MRVqSsL-CL5V0kUiL6X:-MRVxDpZ0PmTvqVN1xEY:be4rtb9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2bd46daed32a0832c8e0ffb023a17679ca4905e9/generator/internal/descriptor_utils.cc#L523)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Glad to hear this is a better place for the exception, but you did not answer my question. If `string` deserves this treatment, why not `bytes`?  Why not all the other types too?
</blockquote></details>

Per AIP-4233, only non-primitive (i.e. Message) types are allowed to be paginated. In generating the logging library, I ran across this special case of string, which appears to have been grandfathered in. Until we encounter other special cases for paginated types, I don't want to add support for them.

**Review by coryan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5715#-:-MRVynCa0tqZ2if61U4i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
