### PR TITLE
refactor(spanner): improve Option discoverability by having a single spanner/options.h

### PR DESCRIPTION
**Pull request by devjgm**
Part of https://github.com/googleapis/google-cloud-cpp/issues/5738

This PR improves Option discoverability for users by putting all spanner-specific user-tweakable options in a single file: `spanner/options.h`. This gives users a single place to find all the options. This file also includes a file-level comment
explaining how users should use options.

All options in `spanner/options.h` will become public, user-facing options in the `spanner::` namespace soon (as soon as we make `google::cloud::internal::Options` public too).

Each function that accepts `Options` should still document which sets of options it expects.

Renamed `internal/options*` to `internal/defaults*` to more clearly indicate that it's only for computing *default* values for options, not defining options themselves.

**There's no semantic change in this PR**

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6037)

### CODE REVIEW

**Comment by devjgm** [comment]
Hmm. There's a strange seems-to-be-unrelated clang-tidy error: https://source.cloud.google.com/results/invocations/915e4790-b19a-41de-b95f-111dc444d857/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fclang-tidy-presubmit/log

**Review by coryan — COMMENTED** [review]
I think you are hitting one of those cases where running `clang-tidy` over a header file produces incorrect results.

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6037#-:-MVgg6ml16CMXpFyuekD:bq87kar)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @devjgm)

**Comment by devjgm** [comment]
Any idea how to get around this issue? All I can think of is make clang-tidy not a required build, submit, then re-enable it.

**Comment by devjgm** [comment]
I think I fixed the clang-tidy issue by adding an empty `google/cloud/spanner/options.cc` file. For some reason, that was causing `clang-tidy '-p=cmake-out/ci-fedora-install-33-clang-tidy' '--checks=-misc-unused-using-decls,-readability-redundant-declaration' google/cloud/spanner/options.h` to complain about non-sense.

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6037#-:-MVlE2CXBrxt9uYL7wjr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @devjgm)

___
*[google/cloud/spanner/options.cc, line 22 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6037#-MVlDgSe9Zooi4w46-G4:-MVlDgSe9Zooi4w46-G5:b-9n37i8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bd1fa5e669b40261dfae5a3cd9bdf2196e965d52/google/cloud/spanner/options.cc#L22)):*
> ```cpp
> inline namespace SPANNER_CLIENT_NS {
> 
> // Nothing for now.
> ```

nit: maybe mention why: `// This empty `.cc` file eliminates false positive errors from clang-tidy in our CI builds` or something.

**Pull request merged**
