### PR TITLE
fix(Dockerfile): Some debian package manager tweaks

### PR DESCRIPTION
**Pull request by Rajpratik71**
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

results in smaller image size.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3417)

### CODE REVIEW

**Comment by coryan** [comment]
Thanks for the PR, it looks good so far. I have kicked off the CI builds.  Meanwhile, is there a reason why you recommend using `apt-get` vs. `apt`?

**Comment by Rajpratik71** [comment]
As "--no-install-recommends" option is provided by "apt-get" i.e why i changed "apt" to "apt-get".

**Comment by coryan** [comment]
I think the `ci/docker/install/Dockerfile.*` files might be missing some dependencies now? Maybe whatever provides `ldconfig`?

**Comment by Rajpratik71** [comment]
@coryan , can you please trigger a kokoro:run

**Pull request merged**
