### PR TITLE
feat(generator): add some support for deprecated RPCs

### PR DESCRIPTION
**Pull request by devbww**
Do not generate APIs for deprecated RPCs unless their names appear in
an `emitted_rpcs` list, the reverse of the existing `omitted_rpcs`.

Furthermore, require that deprecated RPCs are listed in either of
`emitted_rpcs` or `omitted_rpcs`.  Use `emitted_rpcs` when the RPC
code has previously been generated (probably from before it was
deprecated), and so is needed for backwards compatibility.  Otherwise
use `omitted_rpcs`, typically for a new-generated service with
existing deprecated RPCs (which should be rare).

This will allow us to reliably omit generating APIs for deprecated
RPCs that we have never supported.

Part of #8486.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10573)

### CODE REVIEW

**Review by coryan — APPROVED** [review]
Very cool idea, I like it.

**Review by dbolduc — COMMENTED** [review]
Thanks, I did not even realize we were generating deprecated methods as is. Something to think about, that shouldn't block this PR....

There is another piece to the puzzle, which is deprecated fields in a method signature: https://github.com/googleapis/google-cloud-cpp/blob/677c800829c1b39efe6a018c0b61e898c9960185/generator/internal/descriptor_utils.cc#L209-L213

I think we are still liable to lose a public client method if a field is newly deprecated, but the overall RPC is not. Can this be addressed with `emitted_rpcs`? I think at worst, we could do:

```
# generate the method signature for `GetFoo` at index 5.
emitted_rpcs: ["GetFoo.5"]
```

**Comment by devbww** [comment]
> Something to think about, that shouldn't block this PR....
> 
> I think we are still liable to lose a public client method if a field is newly deprecated, but the overall RPC is not.

Yes, I agree that's an issue.  Perhaps we should expand #8486 to cover signature-method field deprecations in addition to RPC deprecations.  If you agree, I'll happily do that (if you don't first).

**Comment by dbolduc** [comment]
> If you agree

I agree.

> (if you don't first)

I won't.

**Comment by devbww** [comment]
> > (if you don't first)
> 
> I won't.

Done.

**Pull request merged**
