### PR TITLE
impl(bigquery): performance benchmark shared classes

### PR DESCRIPTION
**Pull request by jsrinnn**
This PR includes the following changes for performance benchmark tests for v1/minimal apis

1) Additional parameter configs for each resource, and corresponding test changes

2) A shared benchmark class/library that all benchmark programs would use. I modeled it after bigtable benchmark tests.

3) Initial shell or empty files for each benchmark program based on the resource being tested. Subsequent PRs would implement these files.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600)* status: all files reviewed, 7 unresolved discussions (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3X1852yeNKEXLxqQn:-Ne3X1852yeNKEXLxqQo:b-l7oz3n) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h#L1)):*
> ```objc
> // Copyright 2023 Google Inc.
> ```

s/Inc./LLC/ there is no need to change old files, but new files should be Copyright "Google LLC"
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h` line 34 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3XFaXEr-IBZtLTIu7:-Ne3XFaXEr-IBZtLTIu8:b-jk64ok) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h#L34)):*
> ```objc
> GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN
> 
> using ::google::cloud::bigquery_v2_minimal_internal::Dataset;
> ```

We generally frown on using directives in header files.  
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3XvxjB7zoOtIjYk2P:-Ne3XvxjB7zoOtIjYk2Q:b-q64pkt) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L1)):*
> ```cpp
> // Copyright 2023 Google Inc.
> ```

See above.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 25 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3Xzjv2d0tg_XQlVhj:-Ne3Xzjv2d0tg_XQlVhk:byswbk1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L25)):*
> ```cpp
> #include <sstream>
> 
> namespace {
> ```

Normally we put these inside the namespace
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3Y5tg4Q8-jgNyfCab:-Ne3Y5tg4Q8-jgNyfCac:b-vh2ic0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L73)):*
> ```cpp
> using ::google::cloud::internal::MakeStreamRange;
> 
> auto invalid_argument = [](std::string msg) {
> ```

Why a lambda vs. a function?  And why not use `google::cloud::internal::InvalidArgumentError()`?
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 403 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3YOmB27P7ngtxYqHj:-Ne3YOmB27P7ngtxYqHk:bntsp2u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L403)):*
> ```cpp
> }
> 
> std::ostream& operator<<(std::ostream& os, FormatDuration duration) {
> ```

Abseil has helper functions to do this:

https://github.com/abseil/abseil-cpp/blob/317085adc4e4e474eb4546fa9d37f74c61d95f7f/absl/time/time.h#L683

You could do:

```cc
std::ostream& operator<<(ostream& os, FormatDuration d) {
  return os << absl::FormatDuration(absl::FromChrono(d.ns));
}
```
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config_test.cc` line 24 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3Z9F2BEDDKo_6hSVW:-Ne3Z9F2BEDDKo_6hSVX:b-kxtsxq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2d0061141177f8f412bc0fd377a739808e34570d/google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config_test.cc#L24)):*
> ```cpp
> namespace bigquery_v2_minimal_benchmarks {
> GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN
> namespace {
> ```

Why remove this?

**Review by jsrinnn — COMMENTED** [review]
Addressed all feedback. PTAL.

Thank you, Carlos!

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-:-Ne4-YzhAdQ6vnofHnXY:b-f6nfdt)* status: all files reviewed, 7 unresolved discussions (waiting on @coryan)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3X1852yeNKEXLxqQn:-Ne3hWfa-bcThdIE3VSf:b-njc722) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

s/Inc./LLC/ there is no need to change old files, but new files should be Copyright "Google LLC"
</blockquote></details>

Done.

Fixed here and other files in this PR.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h` line 34 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3XFaXEr-IBZtLTIu7:-Ne3q2jo5DY1tmlwI0aj:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.h#L34)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

We generally frown on using directives in header files.
</blockquote></details>

Done.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3XvxjB7zoOtIjYk2P:-Ne3q6G1A7WOyFnAccTF:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 25 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3Xzjv2d0tg_XQlVhj:-Ne3r3Ol8g4VlUmjvLly:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L25)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Normally we put these inside the namespace
</blockquote></details>

Done.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3Y5tg4Q8-jgNyfCab:-Ne3wHym5O4I6w-iNJaF:blrt3fx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L73)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Why a lambda vs. a function?  And why not use `google::cloud::internal::InvalidArgumentError()`?
</blockquote></details>

Done.

Ah...thanks. One of the other benchmark tests was using the lambda so I did the same.

I have modified the code to use `google::cloud::internal::InvalidArgumentError()` instead of redeclaring the function.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 403 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3YOmB27P7ngtxYqHj:-Ne3xO8n-7y97ViM7gyK:b7zqmn4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L403)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Abseil has helper functions to do this:

https://github.com/abseil/abseil-cpp/blob/317085adc4e4e474eb4546fa9d37f74c61d95f7f/absl/time/time.h#L683

You could do:

```cc
std::ostream& operator<<(ostream& os, FormatDuration d) {
  return os << absl::FormatDuration(absl::FromChrono(d.ns));
}
```
</blockquote></details>

Done.

Ah...nice. Thank you! This reduces the code length.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config_test.cc` line 24 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3Z9F2BEDDKo_6hSVW:-Ne3z-rJ8TxwSnQgA-Uz:bptflzh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2d0061141177f8f412bc0fd377a739808e34570d/google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config_test.cc#L24)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Why remove this?
</blockquote></details>

If you mean this directive `using ::google::cloud::testing_util::StatusIs;`, it wasn't being used and clang-tidy was complaining about it.

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600)* status: all files reviewed, 2 unresolved discussions (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne59amK8MMfoUSd5DYh:-Ne59amK8MMfoUSd5DYi:b6bfp3r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L1)):*
> ```cpp
> // Copyright 2023 Google Inc.
> ```

nit: I think the go/ospo guidelines call for no period in this line.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config_test.cc` line 24 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3Z9F2BEDDKo_6hSVW:-Ne59MWJ5G9u6XQsMXFZ:b27spfh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2d0061141177f8f412bc0fd377a739808e34570d/google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config_test.cc#L24)):*
<details><summary><i>Previously, jsrinnn wrote…</i></summary><blockquote>

If you mean this directive `using ::google::cloud::testing_util::StatusIs;`, it wasn't being used and clang-tidy was complaining about it.
</blockquote></details>

No, I was looking at the anonymous namespace.

**Review by coryan — APPROVED** [review]
Argh, my comments are minor.  approved.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-:-Ne5A1sdE7DfNaK0BLsk:b-9h6241)* status: all files reviewed, 2 unresolved discussions (waiting on @jsrinnn)

**Review by jsrinnn — COMMENTED** [review]
Addressed remaining feedback. Thanks Carlos!

I went ahead and enabled auto merge. If there are additional items to address do let me know and I can address it in the follow-up PR.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-:-Ne5BPFxEsmj7R8oMsyq:b-azpjdy)* status: 12 of 15 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne59amK8MMfoUSd5DYh:-Ne5AbCn2XZxhO-hJlvn:b8az0bl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fa2401dd2b080269cef9b1887931184c37646a06/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: I think the go/ospo guidelines call for no period in this line.
</blockquote></details>

Done.

Fixed here and other files in the PR.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config_test.cc` line 24 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12600#-Ne3Z9F2BEDDKo_6hSVW:-Ne5AtI86eyQjlZeSfUZ:bywcswt) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2d0061141177f8f412bc0fd377a739808e34570d/google/cloud/bigquery/v2/minimal/benchmarks/benchmarks_config_test.cc#L24)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

No, I was looking at the anonymous namespace.
</blockquote></details>

Ah..okay. I usually put any common declarations or functions in an anonymous namespace and not all the test cases. 

Is the latter the recommended way? Let me know and I can add that in a follow up PR.

**Pull request merged**
