### PR TITLE
refactor: auth strategy outside of stub factory

### PR DESCRIPTION
**Pull request by dbolduc**
Related to #13115 

Remove the logic around defaulting endpoints from the stub factory. This is handled when we default the options.

While we're here, take the opportunity to pull out the authentication strategy from the stub factory interface. While this change is not strictly necessary, I think the interfaces are clearer this way.

If we need to create an authentication strategy that will always error, the stub factory is not the place. e.g. we could say:
```cc
if (options.get<UniverseDomainOption>().empty()
auto auth = [&options, &cq] {
  // or better yet, incorporate this logic into `CreateAuthenticationStrategy`
  if (options.has<UniverseDomainOption>() && options.get<UniverseDomainOption>().empty()) {
    return std::make_shared<GrpcErrorCredentialsAuthentication>(...);
  }
  return internal::CreateAuthenticationStrategy(cq, options);
}();
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13336)

### CODE REVIEW

**Comment by dbolduc** [comment]
I am going to rewrite the history with my next push to make this easier to review.

**Review by coryan — COMMENTED** [review]
Can you say why `bigtable`, `spanner`, and `pubsub` needed an ABI baseline update?

**Comment by coryan** [comment]
> Can you say why `bigtable`, `spanner`, and `pubsub` needed an ABI baseline update?

Or a link to the errors, I cannot find then.

**Comment by dbolduc** [comment]
> A link to the errors

CONSOLE_LOG_URL
https://console.cloud.google.com/cloud-build/builds;region=us-east1/1a6f1274-e6e1-42dd-b718-76f807c4affb;tab=detail?project=cloud-cpp-testing-resources
RAW_LOG_URL
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/13336/4a06e962f8eaf0d9c666732b42a35ff55f7ccd8d/fedora-latest-cmake-check-api/log-1a6f1274-e6e1-42dd-b718-76f807c4affb.txt

> Can you say why `bigtable`, `spanner`, and `pubsub` needed an ABI baseline update?

It is some way related to `Options{}.set<UnifiedCredentialsOption>()`. The errors all look like this:

```
Removed Symbols  6 

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
options.h
namespace google::cloud::v2_20
Options::Data<UnifiedCredentialsOption>::clone ( ) const
_ZNK6google5cloud5v2_207Options4DataINS1_24UnifiedCredentialsOptionEE5cloneEv

Options::Data<UnifiedCredentialsOption>::data_address ( )
_ZN6google5cloud5v2_207Options4DataINS1_24UnifiedCredentialsOptionEE12data_addressEv


Options::Data<UnifiedCredentialsOption>::data_address ( ) const
_ZNK6google5cloud5v2_207Options4DataINS1_24UnifiedCredentialsOptionEE12data_addressEv


Options::Data<UnifiedCredentialsOption>::~Data [D0] ( )
_ZN6google5cloud5v2_207Options4DataINS1_24UnifiedCredentialsOptionEED0Ev

Options::Data<UnifiedCredentialsOption>::~Data [D1] ( )
_ZN6google5cloud5v2_207Options4DataINS1_24UnifiedCredentialsOptionEED1Ev

Options::Data<UnifiedCredentialsOption>::~Data [D2] ( )
_ZN6google5cloud5v2_207Options4DataINS1_24UnifiedCredentialsOptionEED2Ev
```

Those services all have at least one generated stub factory which was changed in #13176, which landed before the latest release.

I cannot explain why the other services do not need updates. Maybe we exercise more of the code paths in these services? /idk

**Review by coryan — APPROVED** [review]

**Pull request merged**
