### PR TITLE
feature(generator): add PrintMethod and its helpers

### PR DESCRIPTION
**Pull request by scotthart**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5018)

### CODE REVIEW

**Comment by coryan** [comment]
___
*[generator/CMakeLists.txt, line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5018#-MGKfMMsEwC-1E7YczLd:-MGKfMMsEwC-1E7YczLe:bf9f6yj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/93c84c498b867fb6c394df1b8757e7cd85b9dac2/generator/CMakeLists.txt#L73)):*
> ```CMake
> 
>     add_library(google_cloud_cpp_generator_testing # cmake-format: sort
>                 testing/printer_mocks.h)
> ```

a head-only library needs to be an `INTERFACE` library, look at what we do for `spanner*mocks` and `pubsub*mocks`.

**Review by coryan — COMMENTED** [review]
Seems fine, but I have no idea why we want to have one of these.  Can you give me some context?  What are these intended for?

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5018#-:-MGKhQHJCoM32KyHvAB4:b-rpkg4v)* status: all files reviewed, 1 unresolved discussion (waiting on @scotthart)

**Review by scotthart — COMMENTED** [review]
When we iterate though the various rpc methods on a service, for each generated class, we may need to vary the implementation and/or declaration depending on if the method is longrunning, paginated, etc. So we will need several "patterns" to choose from for each method. Furthermore, each method should match exactly one pattern otherwise we have either a) an error in the generator code or b) we're attempting to generate a method that the generator doesn't currently support.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5018#-:-MGKwSM9BP5dUK2322_w:b4abb3f)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[generator/CMakeLists.txt, line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5018#-MGKfMMsEwC-1E7YczLd:-MGKwQnb2M1n1cXMbgzW:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/93c84c498b867fb6c394df1b8757e7cd85b9dac2/generator/CMakeLists.txt#L73)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

a head-only library needs to be an `INTERFACE` library, look at what we do for `spanner*mocks` and `pubsub*mocks`.
</blockquote></details>

Done.

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5018#-:-MGLIJao8OBG6fOCrjqF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
