### PR TITLE
cleanup: use absl::StrSplit where appropriate

### PR DESCRIPTION
**Pull request by remyabel**
Part of the work for: #4458

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5255)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
The `clang-tidy` build says:

```
/v/google/cloud/storage/oauth2/service_account_credentials_test.cc:374:19: error: the variable 'encoded_header' is copy-constructed from a const reference but is only used as const reference; consider making it a const reference [performance-unnecessary-copy-initialization,-warnings-as-errors]
      std::string encoded_header = std::move(tokens[0]);
                  ^
      const      &
/v/google/cloud/storage/oauth2/service_account_credentials_test.cc:375:19: error: the variable 'encoded_payload' is copy-constructed from a const reference but is only used as const reference; consider making it a const reference [performance-unnecessary-copy-initialization,-warnings-as-errors]
      std::string encoded_payload = std::move(tokens[1]);
                  ^
      const      &
```

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5255#-:-MJgFaIUDsRKkcSWJqda:b-9ny88a)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5255)* status: all files reviewed, 1 unresolved discussion (waiting on @remyabel)

___
*[google/cloud/storage/oauth2/service_account_credentials_test.cc, line 374 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5255#-MJgaH9qEWVTz9zfkIks:-MJgaH9qEWVTz9zfkIkt:bujxf8w) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a5d1b19da6e8d4c3216bbc9f320b1f8e9c91e48c/google/cloud/storage/oauth2/service_account_credentials_test.cc#L374)):*
> ```cpp
> 
>       std::vector<std::string> const tokens = absl::StrSplit(assertion, '.');
>       std::string const& encoded_header = std::move(tokens[0]);
> ```

the `std::move` here and below becomes redundant, right?

**Review by remyabel — COMMENTED** [review]
Done.

Sigh. Even though I'm pretty sure I have the same version of Clang as the CI, I get a completely different set of errors preventing me from using it:

```
/home/tom/second_drive/google-cloud-cpp-1/google/cloud/storage/internal/complex_option.h:56:21: error: use default member initializer for 'value_' [modernize-use-default-member-init,-warnings-as-errors]
  absl::optional<T> value_;
                    ^
                          {}
/home/tom/second_drive/google-cloud-cpp-1/google/cloud/storage/well_known_headers.h:55:21: error: use default member initializer for 'value_' [modernize-use-default-member-init,-warnings-as-errors]
  absl::optional<T> value_;
                    ^
                          {}
/home/tom/second_drive/google-cloud-cpp-1/google/cloud/storage/well_known_parameters.h:53:21: error: use default member initializer for 'value_' [modernize-use-default-member-init,-warnings-as-errors]
  absl::optional<T> value_;
                    ^
                          {}
```

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5255#-:-MJgaMN89xsGpLn4N8M8:b-3i3s1u)* status: all files reviewed, 1 unresolved discussion (waiting on @remyabel)

**Review by remyabel — COMMENTED** [review]
Yeah I don't know why I thought I had the same version. Disregard that comment. I have Clang 10. It seems my various problems can be attributed to that, I will install Clang 9 later.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5255#-:-MJgcY4uA4d3YvSssBTD:b-tjufpt)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — COMMENTED** [review]
Looking good, one more run +kokoro:run 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5255#-:-MJghCujASZQTp1C9len:b-99zhm6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5255#-:-MJgqB4cBimJ6KOwO6MD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
