### PR TITLE
fix(storage): use FQDN

### PR DESCRIPTION
**Pull request by dbolduc**
Sorta related to #13345 

Didn't run any integration tests. YOLO.

---

This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13357)

### CODE REVIEW

**Comment by alevenberg** [comment]
FQDN?

**Comment by dbolduc** [comment]
> FQDN?

https://letmegooglethat.com/?q=fqdn

**Comment by dbolduc** [comment]
`integration-production-pr`
```
[ RUN      ] ThreadIntegrationTest.ReuseConnections
google/cloud/storage/tests/thread_integration_test.cc:224: Failure
Expected: (max_expected_connections) >= (connected.size()), actual: 10 vs 201
...
~CurlHandle recv_count=0 (0 with no data), send_count=0 (0 with no data).
~CurlHandle == curl(Info): Connection cache is full, closing the oldest one.
== curl(Info): Closing connection 0
== curl(Info): TLSv1.3 (OUT), TLS alert, close notify (256):
== curl(Info): Connection #4 to host storage.googleapis.com left intact
```

`demo-centos-7-pr`
```
-----------------------------------
|   Running quickstart: storage   |
-----------------------------------
2023-12-21T23:17:44Z (+1582s): [ CMake ]
Error creating object: UNKNOWN: Permanent error, with a last message of PerformWork() - CURL error [51]=SSL peer certificate or SSH remote key was not OK error_info={reason=, domain=, metadata={gcloud-cpp.retry.function=CreateResumableUpload, gcloud-cpp.retry.reason=permanent-error, gcloud-cpp.retry.original-message=PerformWork() - CURL error [51]=SSL peer certificate or SSH remote key was not OK}}
```

**Comment by dbolduc** [comment]
Closing, because I don't really want to debug `libcurl`. Sorry.

**Pull request closed without merging**
