### PR TITLE
impl(oauth2): add authorized user credentials

### PR DESCRIPTION
**Pull request by scotthart**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
I think you can simplify the constructor (and consequently the tests) a little bit.  There is also a nit in the comments.

You also need to rebase to pick the latest build definition files, sorry about that race condition.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340#-:-Mv_vXEk1it1_-c8OoKu:bcxa29q)* status: all files reviewed, 2 unresolved discussions (waiting on @scotthart)

___
*[google/cloud/internal/oauth2_authorized_user_credentials.h, line 61 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340#-Mv_uUq18WZoqq_ksj09:-Mv_uUq18WZoqq_ksj0A:by9ht6u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c98c7ba37716a9dc6583c46be1c54294505a2c9c/google/cloud/internal/oauth2_authorized_user_credentials.h#L61)):*
> ```objc
>  * Google Authorization Service as needed. Instances of this class should
>  * usually be created via the convenience methods declared in
>  * google_credentials.h.
> ```

nit: we are not planning to have a `google_credentials.h` remember?
___
*[google/cloud/internal/oauth2_authorized_user_credentials.h, line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340#-Mv_um695BXUJc2dVIq8:-Mv_um695BXUJc2dVIq9:bw1e00e) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c98c7ba37716a9dc6583c46be1c54294505a2c9c/google/cloud/internal/oauth2_authorized_user_credentials.h#L73)):*
> ```objc
> class AuthorizedUserCredentials : public Credentials {
>  public:
>   using RestClientFn = std::function<std::unique_ptr<rest_internal::RestClient>(
> ```

I think we can do the same simplifications about how `RestClient` is constructed?  That is, there is no need for a factory function, just pass the constructed `RestClient` to the `AuthorizedUserCredentials()`?

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/internal/oauth2_authorized_user_credentials.h, line 61 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340#-Mv_uUq18WZoqq_ksj09:-Mv_xyhTBapGJYbXYOYd:byiie8u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c98c7ba37716a9dc6583c46be1c54294505a2c9c/google/cloud/internal/oauth2_authorized_user_credentials.h#L61)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: we are not planning to have a `google_credentials.h` remember?
</blockquote></details>

Corrected comments.
___
*[google/cloud/internal/oauth2_authorized_user_credentials.h, line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340#-Mv_um695BXUJc2dVIq8:-Mv_y-Fm9CbuOxOnkL-n:bki6p0m) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c98c7ba37716a9dc6583c46be1c54294505a2c9c/google/cloud/internal/oauth2_authorized_user_credentials.h#L73)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think we can do the same simplifications about how `RestClient` is constructed?  That is, there is no need for a factory function, just pass the constructed `RestClient` to the `AuthorizedUserCredentials()`?
</blockquote></details>

I had mage those changes to the constructor, just forgot to remove the using declaration.

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/internal/oauth2_authorized_user_credentials.h, line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340#-Mv_um695BXUJc2dVIq8:-Mv_yFJd3N-fq_Rmo68q:b-5yyasv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c98c7ba37716a9dc6583c46be1c54294505a2c9c/google/cloud/internal/oauth2_authorized_user_credentials.h#L73)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

I had mage those changes to the constructor, just forgot to remove the using declaration.
</blockquote></details>

s/mage/made

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340#-:-Mva0mMA4_PZZZbm5ng5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scotthart)

___
*[google/cloud/internal/oauth2_authorized_user_credentials.h, line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8340#-Mv_um695BXUJc2dVIq8:-Mva0iYe3GzoO4pGxilR:b5g2dm9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c98c7ba37716a9dc6583c46be1c54294505a2c9c/google/cloud/internal/oauth2_authorized_user_credentials.h#L73)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

s/mage/made
</blockquote></details>

I missed that.  Looks good now.

**Pull request merged**
