### PR TITLE
fix: create service account credentials from json contents

### PR DESCRIPTION
**Pull request by amitchauhan1007**
Added code for validating private key before making cloud operations.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404)

### CODE REVIEW

**Comment by coryan** [comment]
Why don't you start by reproducing the problem?  Start with this test:

https://github.com/googleapis/google-cloud-cpp/blob/82ce9d1b41b5d8ba9fa535922ceca8aa95507a2d/google/cloud/storage/oauth2/service_account_credentials_test.cc#L775-L799

Create a copy that uses an invalid key and see how it behaves?  Does the `MakeJWTAssertion()` raises an exception with an invalid key? If it does, then we already have enough validation, we just need to perform this validation as part of `ParseServiceAccountCredentials()`.  If it does not, then maybe we should add code like the one in this PR.

**Comment by amitchauhan1007** [comment]
Yes, you are correct! 
`MakeJWTAssertion()` already handles an invalid key. I have refactored  code to handle invalid key in CreateServiceAccountCredentailsFromJsonContents as reported in #5315. kindly review.

**Review by coryan — CHANGES_REQUESTED** [review]
Please write a unit test to verify the new behavior. That is, feed `CreateServiceAccountCredentialsFromJsonContents()` something that triggers the new behavior and verify the returned error status.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-:-MLSvmxX5YkAu4pvj3b-:b-qxgv05)* status: all files reviewed, 2 unresolved discussions (waiting on @amitchauhan1007)

___
*[google/cloud/storage/oauth2/google_credentials.cc, line 305 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLSv4Xf4sthybawofPp:-MLSv4Xf4sthybawofPq:btu2sbj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c462d5909c96a200b18505e2bb45897437821e0f/google/cloud/storage/oauth2/google_credentials.cc#L305)):*
> ```cpp
>   std::chrono::system_clock::time_point now;
>   auto assertion_components = AssertionComponentsFromInfo(info, now);
>   return MakeJWTAssertion(assertion_components.first,
> ```

Good start.  I think this will throw when there is an error, and we want to return `StatusOr<>` instead.  You need to refactor the implementation of `MakeJWTAssertion` rename the function, have it return a `StatusOr<>` and then wrap it with something that throws on an error.
___
*[google/cloud/storage/oauth2/google_credentials.cc, line 319 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLSvR_F-wALIrOu6utt:-MLSvR_F-wALIrOu6utu:b9ahp6x) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c462d5909c96a200b18505e2bb45897437821e0f/google/cloud/storage/oauth2/google_credentials.cc#L319)):*
> ```cpp
>   auto jwt_assertion = MakeJWTAssertionChecked(info.value());
>   if (!jwt_assertion) {
>     return StatusOr<std::shared_ptr<Credentials>>(jwt_assertion.status());
> ```

here you want `std::move(jwt_assertion).status()` to avoid copying.  Also, I think the `return StatusOr<...>` is redundant, the compiler knows how to convert a `Status` to a `StatusOr<>`.  We made the same mistake a couple of lines above, please fix them too.

**Comment by amitchauhan1007** [comment]
Please review code changes.

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404)* status: all files reviewed, 12 unresolved discussions (waiting on @amitchauhan1007)

___
*[google/cloud/storage/internal/openssl_util.cc, line 184 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwoL3H-OUqBsUubeY1:-MLwoL3I1Tq5rMzAu2eB:b4focm2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/internal/openssl_util.cc#L184)):*
> ```cpp
>   if (!digest_ctx) {
>     return Status(StatusCode::kInvalidArgument,
>                   "Invalid ServiceAccountCredentials,"
> ```

these will render as `"Invalid ServiceAccountCredentials,Could not create .."` they would be hard to read (never mind punctuation and capitalization), consider instead:

```cc
return Status(StatusCode::kInvalidArgument,
                        "Invalid service account credentials: "
                         "could not find specified digest in OpenSSL.");
```

note the extra space and the lowercase "could".
___
*[google/cloud/storage/internal/openssl_util.cc, line 196 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwoy7I4SmejTN37gAn:-MLwoy7I4SmejTN37gAo:b1jet0p) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/internal/openssl_util.cc#L196)):*
> ```cpp
>   if (digest_type == nullptr) {
>     return Status(StatusCode::kInvalidArgument,
>                   "Invalid ServiceAccountCredentials,"
> ```

same comment as above.
___
*[google/cloud/storage/internal/openssl_util.cc, line 206 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwp-0g5YwPQuibBqwT:-MLwp-0g5YwPQuibBqwU:b-rqxvo7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/internal/openssl_util.cc#L206)):*
> ```cpp
>   if (!pem_buffer) {
>     return Status(StatusCode::kInvalidArgument,
>                   "Invalid ServiceAccountCredentials,"
> ```

ditto.
___
*[google/cloud/storage/internal/openssl_util.cc, line 221 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwp0K3A7k2V55yCzTT:-MLwp0K3A7k2V55yCzTU:b-7ropln) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/internal/openssl_util.cc#L221)):*
> ```cpp
>       &EVP_PKEY_free);
>   if (!private_key) {
>     return Status(StatusCode::kInvalidArgument,
> ```

ditto
___
*[google/cloud/storage/internal/openssl_util.cc, line 233 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwp1S94Iq0aqqJXkYk:-MLwp1S94Iq0aqqJXkYl:b-7ropln) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/internal/openssl_util.cc#L233)):*
> ```cpp
>                          nullptr,  // `ENGINE *e`
>                          private_key.get())) {
>     return Status(StatusCode::kInvalidArgument,
> ```

ditto
___
*[google/cloud/storage/internal/openssl_util.cc, line 241 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwp2PN6pPRbVwsS1_i:-MLwp2PN6pPRbVwsS1_j:b-7ropln) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/internal/openssl_util.cc#L241)):*
> ```cpp
>       EVP_DigestSignUpdate(digest_ctx.get(), str.data(), str.length())) {
>     return Status(StatusCode::kInvalidArgument,
>                   "Invalid ServiceAccountCredentials,"
> ```

ditto
___
*[google/cloud/storage/oauth2/service_account_credentials.h, line 89 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwpyV7443glDSGW5cp:-MLwpyV7443glDSGW5cq:b-e90fqd) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/oauth2/service_account_credentials.h#L89)):*
> ```objc
>     std::chrono::system_clock::time_point now);
> 
> // Does not through exception rather returns Status.
> ```

s/through/throw/ ?  And you can omit the comment altogether, all functions returning `StatusOr<>` should not be throwing exceptions.
___
*[google/cloud/storage/oauth2/service_account_credentials.h, line 91 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwpr4j25yrz_S9gs9w:-MLwpr4kEralouDTOB-k:b-lh2nhy) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/oauth2/service_account_credentials.h#L91)):*
> ```objc
> // Does not through exception rather returns Status.
> // Given a key and a JSON header and payload, creates a JWT assertion string
> StatusOr<std::string> MakeJWTAssertionNoThrow(std::string const& header,
> ```

This function should be in the `internal` namespace. we do not want to create more APIs.
___
*[google/cloud/storage/oauth2/service_account_credentials.h, line 99 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwpwnf9Mgn-rfpNH89:-MLwpwnf9Mgn-rfpNH8A:b-ey9pzd) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/oauth2/service_account_credentials.h#L99)):*
> ```objc
>  * @see https://tools.ietf.org/html/rfc7519
>  */
> // std::string MakeJWTAssertion(ServiceAccountCredentialsInfo const& info);
> ```

remove comment?
___
*[google/cloud/storage/oauth2/service_account_credentials.cc, line 228 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwqSvh0TrhCu6UTccc:-MLwqSvh0TrhCu6UTccd:btigig0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/oauth2/service_account_credentials.cc#L228)):*
> ```cpp
> }
> 
> StatusOr<std::string> MakeJWTAssertionNoThrow(std::string const& header,
> ```

Please move this to the `internal` namespace.
___
*[google/cloud/storage/oauth2/service_account_credentials.cc, line 249 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MLwqB5ZA5FRCKjzgPsU:-MLwqB5ZA5FRCKjzgPsV:b-n8vj3p) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4eec258cba6f67bd04ae867218667d67684d5ea/google/cloud/storage/oauth2/service_account_credentials.cc#L249)):*
> ```cpp
>                              std::string const& payload,
>                              std::string const& pem_contents) {
>   auto result = MakeJWTAssertionNoThrow(header, payload, pem_contents);
> ```

You can just do:

```cc
return MakeJWTAssertionNoThrow(..).value();
```

that will throw an exception if the `StatusOr<T>` contains an error.

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @amitchauhan1007 and @coryan)

___
*[google/cloud/storage/oauth2/google_credentials.cc, line 165 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MM0a2C60kJPbU08EOAa:-MM0a2C797cMOIC0a5QN:b-kfmrou) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/3564ce5dd98a4fe2013ff420773be45e1fd93754/google/cloud/storage/oauth2/google_credentials.cc#L165)):*
> ```cpp
>   auto gce_creds = std::make_shared<ComputeEngineCredentials<>>();
>   auto override_val = google::cloud::internal::GetEnv(
>       google::cloud::storage::v1::internal::GceCheckOverrideEnvVar());
> ```

We never add the inline namespace (`v1`) in the name.  I wonder why do you need to quality the name more than before?
___
*[google/cloud/storage/oauth2/service_account_credentials.h, line 89 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MM0aIiiB37x6hXHMnDY:-MM0aIiiB37x6hXHMnDZ:b-3z2zrz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/3564ce5dd98a4fe2013ff420773be45e1fd93754/google/cloud/storage/oauth2/service_account_credentials.h#L89)):*
> ```objc
>     std::chrono::system_clock::time_point now);
> 
> namespace internal {
> ```

When I said "the internal namespace" I meant `google::cloud::storage::internal` (or `google::cloud::storage::v1::internal` if we want the full name including inlined namespaces), you are introducing `google::cloud::storage::oauth2::internal` You can still declare this in the same header, just move the declaration to the right spot.
___
*[google/cloud/storage/oauth2/service_account_credentials.cc, line 31 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MM0aokj8urEicUPO2TL:-MM0aokj8urEicUPO2TM:b-6hu40s) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/3564ce5dd98a4fe2013ff420773be45e1fd93754/google/cloud/storage/oauth2/service_account_credentials.cc#L31)):*
> ```cpp
> namespace oauth2 {
> 
> namespace internal {
> ```

As above, this should be outside `oauth2`.
___
*[google/cloud/storage/oauth2/service_account_credentials_test.cc, line 383 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MM0awWu-V3HpwXKClKj:-MM0awWu-V3HpwXKClKk:b-rm4kpt) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/3564ce5dd98a4fe2013ff420773be45e1fd93754/google/cloud/storage/oauth2/service_account_credentials_test.cc#L383)):*
> ```cpp
> 
>       auto header_bytes =
>           google::cloud::storage::v1::internal::UrlsafeBase64Decode(
> ```

I think you needed these changes just because you created that new `oauth2::internal` namespace.

**Review by coryan — CHANGES_REQUESTED** [review]
clang-tidy is asking you to reformat the code. Some changes look unnecessary to me, but maybe I am missing something.

> Reviewed 1 of 7 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-:-MM1ya0h-taSmEk9Sdsm:bk8mbbj)* status: all files reviewed, 1 unresolved discussion (waiting on @amitchauhan1007)

___
*[google/cloud/storage/oauth2/service_account_credentials_test.cc, line 383 at r7](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MM1yLi19VOPzO1pT7Bb:-MM1yLi19VOPzO1pT7Bc:b-wls9q1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ec210484cf452c93e0ff04cd6ebdc0d09948608c/google/cloud/storage/oauth2/service_account_credentials_test.cc#L383)):*
> ```cpp
> 
>       auto header_bytes =
>           storage::internal::UrlsafeBase64Decode(encoded_header);
> ```

are these changes still needed?

**Comment by amitchauhan1007** [comment]
> clang-tidy is asking you to reformat the code. Some changes look unnecessary to me, but maybe I am missing something.
> 
> > Reviewed 1 of 7 files at r6, 4 of 4 files at r7.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-:-MM1ya0h-taSmEk9Sdsm:bk8mbbj)_ status: all files reviewed, 1 unresolved discussion (waiting on @amitchauhan1007)
> 
> _[google/cloud/storage/oauth2/service_account_credentials_test.cc, line 383 at r7](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-MM1yLi19VOPzO1pT7Bb:-MM1yLi19VOPzO1pT7Bc:b-wls9q1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ec210484cf452c93e0ff04cd6ebdc0d09948608c/google/cloud/storage/oauth2/service_account_credentials_test.cc#L383)):_
> 
> > ```c++
> >       auto header_bytes =
> >           storage::internal::UrlsafeBase64Decode(encoded_header);
> > ```
> 
> are these changes still needed?

These changes not required anymore. Updated code by removing "storage::" namespace prefixes.

**Review by coryan — APPROVED** [review]
:lgtm: just waiting for the builds at this point.

> Reviewed 7 of 7 files at r9.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5404#-:-MMLc3cA058F0YNXI8AP:b-n3fekm)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
