### PR TITLE
Fix openSUSE misspelling and inconsistencies in documentation 

### LINKED ISSUE #3167: openSUSE is misspelled in the TOC of the readme file
While openSUSE is written correctly later on in the readme file, it is misspelled as "OpenSuSE" in the table of contents.

### PR DESCRIPTION
**Pull request by m-rey**
Fix #3167 
The correct spelling of openSUSE can be checked on https://en.opensuse.org/Portal:Distribution

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3168)

### CODE REVIEW

**Comment by m-rey** [comment]
@googlebot I signed it!

**Comment by m-rey** [comment]
No problem! I'll look into it.

**Comment by m-rey** [comment]
That should be all, as far as I can see.

**Comment by coryan** [comment]
Looks good, thank you so much for these fixes.  I started the builds because even comments can break things (I do not expect any breakage).  I will merge this once the builds pass or let you know if any other changes might be needed.

**Pull request merged**
