### PR TITLE
feat(spanner): use spanner_cmek_and_pitr_lite protos

### PR DESCRIPTION
**Pull request by devbww**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5443)

### CODE REVIEW

**Comment by coryan** [comment]
I just sent cl/341279892 for review, you will need to close and reopen this PR after that is submitted.  And probably wait about 1/2 hour afterwards because my experience is that it takes time for some Kokoro configs to propagate.

**Comment by coryan** [comment]
The gcc-10 build failed because the target branch does not have that configuration (or support for it in the `build.sh` script).  Best guess would be to rebase the target branch.  Next guess would be to cherry-pick the changes to support the `gcc-10` build into the target branch.

**Comment by devbww** [comment]
I changed the branch spec, given that it is base on v1.20, back to include `gcc-9` and exclude `gcc-10`.  I'll wait to see if everything else passes before trying to close/reopen to clear the failure (if that is the right tactic).

**Comment by devbww** [comment]
There is the chance that we may have to cherry-pick into the branch, but I'd prefer to avoid that if we can.

**Review by mr-salty — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5443#-:-MLjSqUa3VX604RAg0Ql:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @devbww)

___
*[bazel/google_cloud_cpp_deps.bzl, line 81 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5443#-MLjSdN2D4EZVJwUYNMX:-MLjSdN2D4EZVJwUYNMY:bl6ktj0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ecf16b4e0a2dc04a9e112bbfb5b279e02e6c4838/bazel/google_cloud_cpp_deps.bzl#L81)):*
> ```Starlark
>             ],
>             strip_prefix = "googleapis-spanner_cmek_and_pitr_lite",
>             sha256 = "ef6f78f8823812a92c714eda2379177c72f154c9143119bca67e724bf98321c5",
> ```

fwiw, I omitted this in my repo, which disables the check... my thinking was, if they change this repo in a way that doesn't break my code, I don't really care.

**Review by devbww — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5443)* status: all files reviewed, 1 unresolved discussion (waiting on @mr-salty)

___
*[bazel/google_cloud_cpp_deps.bzl, line 81 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5443#-MLjSdN2D4EZVJwUYNMX:-MLjW2O-7JfSCP7yhVHX:b-cvcwd3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ecf16b4e0a2dc04a9e112bbfb5b279e02e6c4838/bazel/google_cloud_cpp_deps.bzl#L81)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

fwiw, I omitted this in my repo, which disables the check... my thinking was, if they change this repo in a way that doesn't break my code, I don't really care.
</blockquote></details>

Ack.  As I mentioned in the other PR, I think I'll keep it, but I hope I don't end up eating my words.

**Pull request merged**
