### PR TITLE
feat: add configuration options to set the SSL root of trust

### PR DESCRIPTION
**Pull request by mcharsley**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3455)

### CODE REVIEW

**Comment by coryan** [comment]
If you have access to a Linux workstation with Docker installed, consider running:

```
./ci/kokoro/docker/build.sh clang-tidy
```

to fix the formatting issues.  It will be slow the first time as it builds a Docker image with the development tools and compiles all the dependencies.

**Comment by coryan** [comment]
Sigh, sorry, you need to rebase and push the new `.abi.dump.gz` files.

**Comment by mcharsley** [comment]
Done. I think: that was pushing the limits of my git-fu :-(

**Comment by coryan** [comment]
Thanks, assuming it all goes well I will merge your changes before some other changes that would conflict with these.

**Pull request merged**
