### PR TITLE
test(storage): add utils for new gcs emulator

### PR DESCRIPTION
**Pull request by vnvo2409**
This PR adds some utils for the new emulator ( I prefer emulator over testbench ):
- `acl.py`: utils related to access control list
- `error.py`: a common interface to return error code for both REST and gRPC
- `common.py`: common utils used by both gRPC and REST.

The generated protos will be installed via `pip` from https://github.com/googleapis/python-storage/pull/270

This PR is a part of https://github.com/googleapis/google-cloud-cpp/issues/4751

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
A few nits below.  Do you think we should be writing unit tests for this new code?  It is complex enough that maybe we should.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-:-MHGglHeETkx2ppVUO0V:bwo2c3q)* status: all files reviewed, 11 unresolved discussions (waiting on @vnvo2409)

___
*[google/cloud/storage/emulator/requirements.txt, line 5 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGfH_LBBvMU82ZNYt9:-MHGfH_MAqJwyPVYKQY3:b-dfd1o6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/requirements.txt#L5)):*
> ```vimhelp
> flask==1.1.2
> grpc-google-iam-v1==0.12.3
> pysimdjson==3.0.0
> ```

missing newlines at the end of the file?
___
*[google/cloud/storage/emulator/utils/__init__.py, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGfV8A6Pc9pIHNf-jb:-MHGfV8A6Pc9pIHNf-jc:b349owg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/__init__.py#L1)):*
> ```Python
> # Copyright 2020 Google Inc.
> ```

s/Google Inc./Google LLC/ here and below.
___
*[google/cloud/storage/emulator/utils/acl.py, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGfRtxA5YIqnqatlZ9:-MHGfRtxA5YIqnqatlZA:bmx84vu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/acl.py#L1)):*
> ```Python
> # Copyright 2020 Google Inc.
> ```

s/Google Inc./Google LLC/
___
*[google/cloud/storage/emulator/utils/acl.py, line 14 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGfMyO4L5FgddNH98r:-MHGfMyO4L5FgddNH98s:b-2d62af) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/acl.py#L14)):*
> ```Python
> # See the License for the specific language governing permissions and
> # limitations under the License.
> """Utils related to access control"""
> ```

nit: blank line after copyright boiler plate?
___
*[google/cloud/storage/emulator/utils/acl.py, line 22 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGf_8T9Vx9-g2ltxMp:-MHGf_8T9Vx9-g2ltxMq:b-4ydadh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/acl.py#L22)):*
> ```Python
> from google.cloud.storage_v1.proto import storage_resources_pb2 as resources_pb2
> 
> PROJECT_NUMBER = os.getenv("GCS_EMULATOR_PROJECT_NUMBER", "123456789")
> ```

We are trying to prefix all environment variables with `GOOGLE_CLOUD_CPP_<SERVICE>`, please use `GOOGLE_CLOUD_CPP_STORAGE_EMULATOR_PROJECT_NUMBER`
___
*[google/cloud/storage/emulator/utils/acl.py, line 24 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGfr9t5CXC6MfToFGv:-MHGfr9t5CXC6MfToFGw:b-wy0tr5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/acl.py#L24)):*
> ```Python
> PROJECT_NUMBER = os.getenv("GCS_EMULATOR_PROJECT_NUMBER", "123456789")
> OBJECT_OWNER_ENTITY = os.getenv(
>     "GCS_EMULATOR_OBJECT_OWNER_ENTITY", "user-object.owners@gmail.com"
> ```

can we use `user-object.owners@example.com` to avoid emailing some real person?  same comments about environment variables.
___
*[google/cloud/storage/emulator/utils/acl.py, line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGfzkR7-P1OjavbpTz:-MHGfzkR7-P1OjavbpU-:bs4q9op) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/acl.py#L27)):*
> ```Python
> )
> OBJECT_READER_ENTITY = os.getenv(
>     "GCS_EMULATOR_OBJECT_READER_ENTITY", "user-object.viewers@gmail.com"
> ```

Ditto.
___
*[google/cloud/storage/emulator/utils/common.py, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGgLYa6hvtExU83dYG:-MHGgLYa6hvtExU83dYH:bmx84vu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/common.py#L1)):*
> ```Python
> # Copyright 2020 Google Inc.
> ```

s/Google Inc./Google LLC/
___
*[google/cloud/storage/emulator/utils/common.py, line 14 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGgU6G5l6rxEj_TG0G:-MHGgU6G5l6rxEj_TG0H:b-absd4c) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/common.py#L14)):*
> ```Python
> # See the License for the specific language governing permissions and
> # limitations under the License.
> """Common utils"""
> ```

nit: blank line.
___
*[google/cloud/storage/emulator/utils/error.py, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGgSvPDUqmAmMF4WXm:-MHGgSvQ06NIlJlvFEFB:bmx84vu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/error.py#L1)):*
> ```Python
> # Copyright 2020 Google Inc.
> ```

s/Google Inc./Google LLC/
___
*[google/cloud/storage/emulator/utils/error.py, line 14 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGgX0G4Ll11d-K22r-:-MHGgX0G4Ll11d-K22r0:b-absd3v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/error.py#L14)):*
> ```Python
> # See the License for the specific language governing permissions and
> # limitations under the License.
> """Utils to raise error code and abort the server"""
> ```

nit: blank line?

**Comment by vnvo2409** [comment]
I will add tests in the next PR

**Comment by coryan** [comment]
___
*[google/cloud/storage/emulator/utils/__init__.py, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-MHGfV8A6Pc9pIHNf-jb:-MHHBdtp3mT9lO0QA9w0:b-18fh8a) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/39e4d594c004ccc34057b2a52ac0319cca8405ee/google/cloud/storage/emulator/utils/__init__.py#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

s/Google Inc./Google LLC/ here and below.
</blockquote></details>

nit: next time you go through these files, no `.` after `LLC`.

**Comment by vnvo2409** [comment]
I copied the style of `google/cloud/storage/testbench/` but it seems that that style is outdated. I will fix these lines in this PR or later PR ?

**Comment by coryan** [comment]
Later is fine.

**Review by coryan — APPROVED** [review]
:lgtm:

Thanks. Yes, the copyright notice format changed, and we are not supposed to change the old ones :man_shrugging: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5057#-:-MHHEH6mBpTgvTo6Xrro:b-iha0o)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
