### PR TITLE
impl(rest): add unified credential support

### LINKED ISSUE #8130: Add support for Authorization via UnifiedCredentialsOption
`CurlRestClient` should interrogate the `UnifiedCredentialsOption` and set the `Authorization` header to the appropriate value before making a request.

### PR DESCRIPTION
**Pull request by scotthart**
fixes #8130

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409)

### CODE REVIEW

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409)* status: all files reviewed, 4 unresolved discussions (waiting on @coryan)

___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 40 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwBvf5V9UveBzp_SPWl:-MwJ-fxgCnBAc97aTUTR:bvlejee) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/43034814aa61ec5d89ffcf93c46a7809d258eacf/google/cloud/internal/unified_rest_credentials_integration_test.cc#L40)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

If you assert this, why bother making `key_file_` an `absl::optional<>`?
</blockquote></details>

GetEnv returns an unset optional<std::string> if the env var isn't found.
___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 41 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwBv6f6AvM1ikSaQz6y:-MwJ00W72GDraU2j0luf:bt2vr1b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/43034814aa61ec5d89ffcf93c46a7809d258eacf/google/cloud/internal/unified_rest_credentials_integration_test.cc#L41)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This means you never test with GCE credentials.  I would think you want to?  Maybe just set this variable in the tests that need it and use the GCE credentials for the other tests?
</blockquote></details>

Fixed.
___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 110 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwBx-mOA3TOo91LttT5:-MwJ04nnB_q1W-D0CKDL:bl3audw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/43034814aa61ec5d89ffcf93c46a7809d258eacf/google/cloud/internal/unified_rest_credentials_integration_test.cc#L110)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

And the magic `6` comes from?  `Bearer `?  Shouldn't that be `7` then?  Could you call the existing API to get these access tokens instead?
</blockquote></details>

Not sure what existing API you're referring to. Refactored the magic number subtr to StrSplit with a comment.
___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 132 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwBw8PxDL2cWdm_6TEG:-MwJ0GyO5jTLagrDSoOJ:b3tc5vm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/43034814aa61ec5d89ffcf93c46a7809d258eacf/google/cloud/internal/unified_rest_credentials_integration_test.cc#L132)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: this is a code smell... setting a member variable and then calling a function that uses the member variable as an input is using the member variables as a global in disguise. 

I think the data flow would be easier to follow if you just passed `Options` as a parameter to `MakeRestRpcCall()`

</blockquote></details>

Removed lambda.

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409)* status: all files reviewed, 3 unresolved discussions (waiting on @scotthart)

___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 40 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwBvf5V9UveBzp_SPWl:-MwNQKUc-Zfchi4QrSgv:b-jqwh0g) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/43034814aa61ec5d89ffcf93c46a7809d258eacf/google/cloud/internal/unified_rest_credentials_integration_test.cc#L40)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

GetEnv returns an unset optional<std::string> if the env var isn't found.
</blockquote></details>

You could write:

```
auto env = internal::GetEnv("GOOGLE_CLOUD_CPP_REST_TEST_KEY_FILE_JSON");
ASSERT_TRUE(env.has_value());
key_file_ = std::move(*env);
```
___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 110 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwBx-mOA3TOo91LttT5:-MwNSnhz72X9rqHNTIpc:buwq6fk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/43034814aa61ec5d89ffcf93c46a7809d258eacf/google/cloud/internal/unified_rest_credentials_integration_test.cc#L110)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Not sure what existing API you're referring to. Refactored the magic number subtr to StrSplit with a comment.
</blockquote></details>

You could call this directly:

https://github.com/googleapis/google-cloud-cpp/blob/033fcd3890fff97b4c8605c58a8b593e880c63f6/google/cloud/internal/oauth2_minimal_iam_credentials_rest.h#L69-L70
___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 132 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwBw8PxDL2cWdm_6TEG:-MwNT39_3o0mSTE4fHN-:b-bi4ig5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/43034814aa61ec5d89ffcf93c46a7809d258eacf/google/cloud/internal/unified_rest_credentials_integration_test.cc#L132)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Removed lambda.
</blockquote></details>

I wasn't saying anything about the lambda.  I was suggesting you change `MakeRestRpcCall()` to be:

```
static void MakeRestRpcCall(StatusCode expected_status, Options options = {}) {
 ...
```

and then this code becomes:

```
MakeRestRpcCall(StatusCode::kOk, Options{}.set<UnifiedCredentialsOption>(...));
```

And I think after that change using a fixture for this test becomes unattractive.
___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 44 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwNQjuNBTJUQk9C__9i:-MwNQjuNBTJUQk9C__9j:b-z7k8xu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/cc35c1e619267bf4f0679c108070fee0f144744d/google/cloud/internal/unified_rest_credentials_integration_test.cc#L44)):*
> ```cpp
> 
>   void TearDown() override {
>     internal::UnsetEnv("GOOGLE_APPLICATION_CREDENTIALS");
> ```

Note that this does not restore to the original state if `GOOGLE_APPLICATION_CREDENTIALS` had a value.  Probably better to use `testing_util::ScopedEnvironment` in the tests that set the environment variable.

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409)* status: all files reviewed, 3 unresolved discussions (waiting on @coryan)

___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 40 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwBvf5V9UveBzp_SPWl:-MwPBzh84chKYWYLrr0z:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/43034814aa61ec5d89ffcf93c46a7809d258eacf/google/cloud/internal/unified_rest_credentials_integration_test.cc#L40)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

You could write:

```
auto env = internal::GetEnv("GOOGLE_CLOUD_CPP_REST_TEST_KEY_FILE_JSON");
ASSERT_TRUE(env.has_value());
key_file_ = std::move(*env);
```

</blockquote></details>

Done.
___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 110 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwBx-mOA3TOo91LttT5:-MwPC8NMErPh53ehB-ud:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/43034814aa61ec5d89ffcf93c46a7809d258eacf/google/cloud/internal/unified_rest_credentials_integration_test.cc#L110)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

You could call this directly:

https://github.com/googleapis/google-cloud-cpp/blob/033fcd3890fff97b4c8605c58a8b593e880c63f6/google/cloud/internal/oauth2_minimal_iam_credentials_rest.h#L69-L70

</blockquote></details>

Done.
___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 132 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwBw8PxDL2cWdm_6TEG:-MwPCIsR9pQxPdX0buzb:b-lx58u8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/43034814aa61ec5d89ffcf93c46a7809d258eacf/google/cloud/internal/unified_rest_credentials_integration_test.cc#L132)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I wasn't saying anything about the lambda.  I was suggesting you change `MakeRestRpcCall()` to be:

```
static void MakeRestRpcCall(StatusCode expected_status, Options options = {}) {
 ...
```

and then this code becomes:

```
MakeRestRpcCall(StatusCode::kOk, Options{}.set<UnifiedCredentialsOption>(...));
```

And I think after that change using a fixture for this test becomes unattractive.

</blockquote></details>

Proposed changes incorporated; fixture removed.
___
*[google/cloud/internal/unified_rest_credentials_integration_test.cc, line 44 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-MwNQjuNBTJUQk9C__9i:-MwPC0GL65RK0y9VhFOy:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/cc35c1e619267bf4f0679c108070fee0f144744d/google/cloud/internal/unified_rest_credentials_integration_test.cc#L44)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Note that this does not restore to the original state if `GOOGLE_APPLICATION_CREDENTIALS` had a value.  Probably better to use `testing_util::ScopedEnvironment` in the tests that set the environment variable.
</blockquote></details>

Done.

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8409#-:-MwRyB4dDgNhfQ9RfUER:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scotthart)

**Pull request merged**
