### PR TITLE
feat: overload SetCell() for bigtable::Cell

### LINKED ISSUE #3689: Provide bigtable::SetCell() overload that takes a bigtable::Cell
Some of our customers need to copy cell values, it would be nice to provide an overload of `SetCell()` that copies the values from an existing `Cell()`.

### PR DESCRIPTION
**Pull request by dopiera**
This fixes #3689.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4086)

### CODE REVIEW

**Comment by dopiera** [comment]
Clang-tidy is picking on me for parts of the file, which I haven't touched. I don't think I should be fixing them in an unrelated PR.

**Comment by coryan** [comment]
No, but can you add `grep -v bigtable/*.h` and `grep -v `storage/*.h` to: 

https://github.com/googleapis/google-cloud-cpp/blob/d9d61ea0bdbb6ddc2fbe278467e2f0496ea47716/ci/kokoro/docker/build-in-docker-cmake.sh#L129-L131

Probably in a previous PR.

Also, did you consider `SetCell(Cell)` as the function prototype, and then `std::move(..)` all the values?

**Comment by dopiera** [comment]
> No, but can you add `grep -v bigtable/*.h` and `grep -v `storage/*.h` to:
> [...]
> Probably in a previous PR.
Done in #4101 .

> Also, did you consider `SetCell(Cell)` as the function prototype, and then `std::move(..)` all the values?

I did, but I'd first have to make `bigtable::Cell` movable from - the way it is right now, it would add an additional copy.

**Comment by dopiera** [comment]
> No, but can you add `grep -v bigtable/*.h` and `grep -v `storage/*.h` to:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/d9d61ea0bdbb6ddc2fbe278467e2f0496ea47716/ci/kokoro/docker/build-in-docker-cmake.sh#L129-L131

I just reread it and realized I misunderstood it initially. Is your intention to enable it only for BQ and Spanner?

**Comment by coryan** [comment]
Can you rebase?  The clang-tidy failures should not happen anymore.

**Comment by dopiera** [comment]
> Can you rebase? The clang-tidy failures should not happen anymore.

Done

**Pull request merged**
