### PR TITLE
doc: update CHANGELOG for 2020-08 release

### PR DESCRIPTION
**Pull request by mr-salty**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4768)

### CODE REVIEW

**Comment by coryan** [comment]
___
*[CHANGELOG.md, line 41 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4768#-MDqOR04-_-LiunZE7y3:-MDqOR04-_-LiunZE7y4:b-sfdpb8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c3aea98b6efb7b0a93279e7bcf9834da7f2e9976/CHANGELOG.md#L41)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> * fix: begin a `has_begin` transaction in Rollback() (#4731)
> * fix: handle `ExecuteBatchDml` returning OK with no results (#4724)
> * fix: use the updated transaction id in `ReadImpl` (#4722)
> * fix: explicitly begin failed implicit begin transactions (#4706)
> ```
</details>


I suspect a lot of these could be summarized better, something like `* fix: if the first operation of a transaction fails, do not attempt further operations in that transaction` or something.

**Comment by mr-salty** [comment]
___
*[CHANGELOG.md, line 23 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4768#-MDqKHCt1xOJTrqQep9x:-MDqSHBZA_6KFuccQ-kU:bq00rms) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c3aea98b6efb7b0a93279e7bcf9834da7f2e9976/CHANGELOG.md#L23)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

When we have breaking changes we have (so far) (a) created a section with all the breaking changes (search for `**BREAKING` in this file), and (b) included a longer description of the breaking change, typically something based on the full commit message.
</blockquote></details>

I (mistakenly, apparently) thought we had stopped that based on recent history... have we really had zero breaking changes in the past 2 releases?

**Comment by coryan** [comment]
___
*[CHANGELOG.md, line 23 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4768#-MDqKHCt1xOJTrqQep9x:-MDqUXWy3iZRRooajhFX:b41cjlh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c3aea98b6efb7b0a93279e7bcf9834da7f2e9976/CHANGELOG.md#L23)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

I (mistakenly, apparently) thought we had stopped that based on recent history... have we really had zero breaking changes in the past 2 releases?
</blockquote></details>

At least we thought none of the changes were breaking.  None of them has a `!`, but you can verify that yourself.  So I assume you are just double checking, and yes, I think we should continue the practice of describing breaking changes at length.

This file is us talking to our customers and describing (to the best of our abilities), what changes have taken place, and which of those may be tricky / difficult / annoying for them.

**Comment by mr-salty** [comment]
___
*[CHANGELOG.md, line 23 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4768#-MDqKHCt1xOJTrqQep9x:-MDq_aFS1EqX7EvQcWr4:b2nhysk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c3aea98b6efb7b0a93279e7bcf9834da7f2e9976/CHANGELOG.md#L23)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

At least we thought none of the changes were breaking.  None of them has a `!`, but you can verify that yourself.  So I assume you are just double checking, and yes, I think we should continue the practice of describing breaking changes at length.

This file is us talking to our customers and describing (to the best of our abilities), what changes have taken place, and which of those may be tricky / difficult / annoying for them.

</blockquote></details>

ack

**Pull request merged**
