### PR TITLE
chore: update googleapis SHA circa 2023-10-23

### PR DESCRIPTION
**Pull request by scotthart**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12956)

### CODE REVIEW

**Review by dbolduc — APPROVED** [review]

**Review by alevenberg — APPROVED** [review]

**Comment by devbww** [comment]
If this didn't change anything but those two files, it probably isn't worth merging.

**Comment by dbolduc** [comment]
> If this didn't change anything but those two files, it probably isn't worth merging.

It probably unblocks generating a new library

**Review by scotthart — COMMENTED** [review]
Correct.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12956#-:-NhT1OBw9vB8lOBWaaar:btqqu5l)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by devbww** [comment]
> > If this didn't change anything but those two files, it probably isn't worth merging.
> 
> It probably unblocks generating a new library

I see.  Thanks.

**Pull request merged**
