### PR TITLE
impl(GCS+gRPC): partial upload coroutine

### PR DESCRIPTION
**Pull request by coryan**
Implement a "coroutine" to upload part of an object. This will be needed when the application provides more than 2 MiB of data for a single "write" call.

Part of the work for #9134

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12962)

### CODE REVIEW

**Comment by coryan** [comment]
This may need some additional work.

**Review by scotthart — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12962)* status: all files reviewed, 1 unresolved discussion (waiting on @coryan)

**Comment by coryan** [comment]
*[`google/cloud/storage/internal/async/partial_upload.h` line 91 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12962#-NhbR9sv3GPqG7JEUUrx:-NhcevuJ2l4wYn1P-y9X:bwsl07v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2b036347bcb1e14cff7d65cf23eeae82362c28f5/google/cloud/storage/internal/async/partial_upload.h#L91)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

why not an `enum class`?
</blockquote></details>

Because then I would have to write `PartialUpload::LaskMessageAction::kNone` to use them, and `PartialUpload::kNone` seems like enough scope.

**Review by coryan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12962)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @dbolduc and @scotthart)

*[a discussion](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12962#gh-1369644474:-NhcfZHX0vFrTbCERs_T:bss4a2b) (no related file):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/googleapis/google-cloud-cpp/pull/12962#discussion_r1369644474) to the right spot — sorry!)*

`StringOption` is never used.
</blockquote></details>

Removed.

___
___
*[`google/cloud/storage/internal/async/partial_upload.h` line 67 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12962#gh-1371155276:-Nhcf7jiAc4V2fLVlljb:b-mr8v98) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2b036347bcb1e14cff7d65cf23eeae82362c28f5/google/cloud/storage/internal/async/partial_upload.h#L67)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

It doesn't quite match the implementation
</blockquote></details>

Fixed I think.

**Pull request merged**
