### PR TITLE
impl(bigquery): Rest stubs for dataset apis

### PR DESCRIPTION
**Pull request by jsrinnn**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324)* status: all files reviewed, 1 unresolved discussion (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324#-NTQelF0EF0ohTF9G6Dk:-NTQelF0EF0ohTF9G6Dl:bswy1mx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/02f561910ac0d00def0324cc730d99fa47a80972/google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h#L1)):*
> ```objc
> // Copyright 2023 Google LLC
> ```

FYI, I would have sent this as a separate PR. No action required.  Your ears will burn when the archeologists go through this code though :grinning: 
___
*[`google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h` line 19 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324#-NTQEmF-A8XwNVA5CpsN:-NTQEmF08pPgVHqtK5bM:b13noyb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/02f561910ac0d00def0324cc730d99fa47a80972/google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h#L19)):*
> ```objc
> 
> #include "google/cloud/bigquery/v2/minimal/internal/bigquery_http_response.h"
> #include "google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h"
> ```

self-include?

**Review by jsrinnn — COMMENTED** [review]
Addressed feedback. Thanks Carlos.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324#-:-NTVEffC5oMY9nJzHWgL:b-jw06qk)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[`google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324#-NTQelF0EF0ohTF9G6Dk:-NTVD7ZFCQQ6aFi2ckeI:b-ofnrut) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/02f561910ac0d00def0324cc730d99fa47a80972/google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

FYI, I would have sent this as a separate PR. No action required.  Your ears will burn when the archeologists go through this code though :grinning: 
</blockquote></details>

Ack.

Just checking, I put the template functions in a separate header file as they were being called from multiple different places If not this way then, I would have had to duplicate the calls  as self-include in all the stub cc files. Is this preferred?

I also noticed, for template functions, they had to be inlined in the header. It did not work when I had a separate cc file for them. I guess that makes sense since the type is not defined.
___
*[`google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h` line 19 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324#-NTQEmF-A8XwNVA5CpsN:-NTVDhTc7W9UMcekgIgB:b-sivtx8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/02f561910ac0d00def0324cc730d99fa47a80972/google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h#L19)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

self-include?
</blockquote></details>

As mentioned in the previous comment, The template functions will needed to be duplicated in the stubb cc files when preparing the request and parsing the response.  Is the duplication preferred over defining it in single header file and including that header everywhere?

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324)* status: all files reviewed, 1 unresolved discussion (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324#-NTQelF0EF0ohTF9G6Dk:-NTVGT0z2sMlrBSVSFxv:b-ccr82p) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/02f561910ac0d00def0324cc730d99fa47a80972/google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h#L1)):*
> Is this preferred?

We prefer to refactor them to a header, as you have done here.

> I also noticed, for template functions, they had to be inlined in the header. It did not work when I had a separate cc file for them. I guess that makes sense since the type is not defined.

C++ requires the definition of template functions and classes must be visible at the point of instantiation (think "where it is used").  In practice this means you need to inline them as you have done here. 
___
*[`google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h` line 19 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324#-NTQEmF-A8XwNVA5CpsN:-NTVGl1w8CbFRrIlYuik:b35d2s0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/02f561910ac0d00def0324cc730d99fa47a80972/google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h#L19)):*
<details><summary><i>Previously, jsrinnn wrote…</i></summary><blockquote>

As mentioned in the previous comment, The template functions will needed to be duplicated in the stubb cc files when preparing the request and parsing the response.  Is the duplication preferred over defining it in single header file and including that header everywhere?
</blockquote></details>

Yes, but this is in the `rest_stubs_utils.h` file and it is including itself...   That either serves no purpose or will break something.

**Review by jsrinnn — COMMENTED** [review]
Addressed feedback and fixed the compile error from the rebase. PTAL.

Thanks Carlos!

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324#-:-NTVIk4q41np3ROrM3VB:bkf77b8)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[`google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324#-NTQelF0EF0ohTF9G6Dk:-NTVIAGD7If3qvF-Hfy2:b6ks9lq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/02f561910ac0d00def0324cc730d99fa47a80972/google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

> Is this preferred?

We prefer to refactor them to a header, as you have done here.

> I also noticed, for template functions, they had to be inlined in the header. It did not work when I had a separate cc file for them. I guess that makes sense since the type is not defined.

C++ requires the definition of template functions and classes must be visible at the point of instantiation (think "where it is used").  In practice this means you need to inline them as you have done here. 

</blockquote></details>

Ack. Thanks for the detailed explanation.
___
*[`google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h` line 19 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324#-NTQEmF-A8XwNVA5CpsN:-NTVIJutEnRNS_ihGPzq:bbdbqrb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/02f561910ac0d00def0324cc730d99fa47a80972/google/cloud/bigquery/v2/minimal/internal/rest_stub_utils.h#L19)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Yes, but this is in the `rest_stubs_utils.h` file and it is including itself...   That either serves no purpose or will break something.
</blockquote></details>

Done

whoops...Sorry didn't realize it was the same header file!

**Review by coryan — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsrinnn)

**Pull request merged**
