### PR TITLE
doc: fix cmake instructions in top-level README

### PR DESCRIPTION
**Pull request by VPeruS**
Reordered command line options, "-C" option is part of the git's general options.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7057)

### CODE REVIEW

**Comment by coryan** [comment]
Thanks for the pull request.  Do you mind also the file that generates this README?

https://github.com/googleapis/google-cloud-cpp/blob/727bc4f4676a75a97cec91247bcdd78741cf7204/ci/generate-markdown/generate-readme.sh#L107

The CI builds will not pass until that is fixed.  If this is too annoying we would be happy to make the changes ourselves.

**Comment by VPeruS** [comment]
Updated bash script

**Review by coryan — APPROVED** [review]

**Comment by coryan** [comment]
Thanks again for the PR.

**Pull request merged**
