### PR TITLE
feat(spanner): merge CMEK changes into preview branch

### PR DESCRIPTION
**Pull request by devbww**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469)

### CODE REVIEW

**Review by coryan — COMMENTED** [review]
I am not sure if this drive-by review is useful.  I think there is a lesson here somewhere about sticking to protos for admin APIs.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469#-:-MLoim6tBHNOfI5YCDrV:b-4dmafy)* status: all files reviewed, 2 unresolved discussions (waiting on @devbww)

___
*[ci/test-abi/bigtable_client.expected.abi.dump.gz, line 0 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469#-MLogr_b4-eDup2kG_kW:-MLogr_b4-eDup2kG_kX:b-8ap6az) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3c74f7ddc101906be83ce2b2e633b8aae58e92d/ci/test-abi/bigtable_client.expected.abi.dump.gz#L0)):*
You may not want to commit the (most likely trivial or empty) changes to the Bigtable, Pub/Sub, Storage, and common library baselines. If they are changed in the mainline that is a guaranteed conflict you could otherwise avoid.  Up to you.
___
*[google/cloud/spanner/database_admin_client.h, line 152 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469#-MLoh83r2F_JfQosfa6v:-MLoh83r2F_JfQosfa6w:bdjqsy8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3c74f7ddc101906be83ce2b2e633b8aae58e92d/google/cloud/spanner/database_admin_client.h#L152)):*
> ```objc
>   future<StatusOr<google::spanner::admin::database::v1::Database>>
>   CreateDatabase(Database db, std::vector<std::string> extra_statements = {},
>                  absl::optional<KmsKeyName> encryption_key = absl::nullopt);
> ```

It may be time to byte the bullet and introduce a builder.  With a second optional parameter we may want to set the second but not the first. Consider instead:

```cc
future<StatusOr<...Database>>
CreateDatabase(DatabaseSpec);

future<StatusOr<...Database>>
CreateDatabase(Database db, std::vector<std::string> extra_statements = {}) {
  return CreateDatabase(DatabaseSpecBuilder(db).AddStatemements(std::move(extra_statements)).Build());
}
```

**Review by mr-salty — COMMENTED** [review]
Sorry, I saw that "Veerify" issue in my branch, but got distracted by the line wrapping issue with the tags and forgot about it. I fixed it in my branch, LG otherwise.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469#-:-MLomZaI3zfUbbHFKwIr:b2nwqh0)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan and @devbww)

___
*[google/cloud/spanner/database_admin_client.h, line 152 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469#-MLoh83r2F_JfQosfa6v:-MLolMoW3Dvg4gfjrRKo:b-h7y7tx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3c74f7ddc101906be83ce2b2e633b8aae58e92d/google/cloud/spanner/database_admin_client.h#L152)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

It may be time to byte the bullet and introduce a builder.  With a second optional parameter we may want to set the second but not the first. Consider instead:

```cc
future<StatusOr<...Database>>
CreateDatabase(DatabaseSpec);

future<StatusOr<...Database>>
CreateDatabase(Database db, std::vector<std::string> extra_statements = {}) {
  return CreateDatabase(DatabaseSpecBuilder(db).AddStatemements(std::move(extra_statements)).Build());
}
```
</blockquote></details>

I'd consider this out of scope for this PR - Brad is just pulling my branch verbatim into his.

But, we can discuss it elsewhere; I agree `CreateDatabase(foo, {}, key)` is awkward.

**Review by coryan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469)* status: all files reviewed, 1 unresolved discussion (waiting on @devbww)

___
*[google/cloud/spanner/database_admin_client.h, line 152 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469#-MLoh83r2F_JfQosfa6v:-MLopg5aDRO6yxwpDqis:b-81nlyc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3c74f7ddc101906be83ce2b2e633b8aae58e92d/google/cloud/spanner/database_admin_client.h#L152)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

I'd consider this out of scope for this PR - Brad is just pulling my branch verbatim into his.

But, we can discuss it elsewhere; I agree `CreateDatabase(foo, {}, key)` is awkward.
</blockquote></details>

SGTM.

**Review by devbww — COMMENTED** [review]
Fixed the "Verrify".

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469#-:-MLpW9Xh0L2ImvVYb58F:bim0pqv)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[ci/test-abi/bigtable_client.expected.abi.dump.gz, line  at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469#-MLogr_b4-eDup2kG_kW:-MLpVr5nEdG004ZtwCEz:bhfoxn5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3c74f7ddc101906be83ce2b2e633b8aae58e92d/ci/test-abi/bigtable_client.expected.abi.dump.gz#L)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

You may not want to commit the (most likely trivial or empty) changes to the Bigtable, Pub/Sub, Storage, and common library baselines. If they are changed in the mainline that is a guaranteed conflict you could otherwise avoid.  Up to you.
</blockquote></details>

Reverted the others.  Thanks.  I understand things are complicated, but it would be nice if `update-abi` didn't change things it didn't have to.

**Review by devbww — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mr-salty — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469#-:-MLpfK3ACH64OR5JU-uf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by coryan** [comment]
___
*[ci/test-abi/bigtable_client.expected.abi.dump.gz, line  at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5469#-MLogr_b4-eDup2kG_kW:-MLpgIt63NUOH6JLMyVH:bb2geki) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3c74f7ddc101906be83ce2b2e633b8aae58e92d/ci/test-abi/bigtable_client.expected.abi.dump.gz#L)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Reverted the others.  Thanks.  I understand things are complicated, but it would be nice if `update-abi` didn't change things it didn't have to.
</blockquote></details>

Created #5470

**Pull request merged**
