### PR TITLE
ci(gcb): add title for public logs index.html page

### PR DESCRIPTION
**Pull request by vnvo2409**
A small improvement for #6397.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6405)

### CODE REVIEW

**Review by devjgm — APPROVED** [review]
Thanks!

**Comment by devjgm** [comment]
I deployed this change. It should show up on the next PR from someone. Thanks again!

**Comment by vnvo2409** [comment]
Thank you !

**Pull request merged**
