### PR TITLE
refactor: relocate polling_loop.h from spanner to common

### PR DESCRIPTION
**Pull request by scotthart**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185)

### CODE REVIEW

**Comment by scotthart** [comment]
Moving the generic portions of the polling_loop code to common for use by generated code.

**Review by mr-salty — APPROVED** [review]
:lgtm:

> Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-:-MIvQwY85SrI4Q6sC21L:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @scotthart)

___
*[google/cloud/spanner/CMakeLists.txt, line 98 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-MIvNVHV7Y9CynzcIZRC:-MIvNVHW1WDSugvDHoHB:b-9unw6p) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/965b8858bf94db4afd368849046d8c2b3a1e6c13/google/cloud/spanner/CMakeLists.txt#L98)):*
> ```CMake
>     internal/partial_result_set_source.cc
>     internal/partial_result_set_source.h
>     # internal/polling_loop.h
> ```

delete?
___
*[google/cloud/spanner/CMakeLists.txt, line 272 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-MIvNX-M46An0mCZ5K0Y:-MIvNX-M46An0mCZ5K0Z:b-9unw6p) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/965b8858bf94db4afd368849046d8c2b3a1e6c13/google/cloud/spanner/CMakeLists.txt#L272)):*
> ```CMake
>         internal/partial_result_set_resume_test.cc
>         internal/partial_result_set_source_test.cc
>         # internal/polling_loop_test.cc
> ```

delete?
___
*[google/cloud/internal/polling_loop_test.cc, line 49 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-MIvQ9hw7kFiYvM-mmoP:-MIvQ9hx8UbzO8u6FG0v:b54debp) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/668db18a4e07469791631fd9fd81ff2d134d1282/google/cloud/internal/polling_loop_test.cc#L49)):*
> ```cpp
>           "Received unexpected EOS on DATA frame from server",
>           "Connection closed with unknown cause",
>           "HTTP/2 error code: INTERNAL_ERROR", "RST_STREAM"};
> ```

I'd just use the simpler pre-#5087 version of this method:

```
    return status.code() == StatusCode::kUnavailable ||
           status.code() == StatusCode::kResourceExhausted;
```

Although, it brings up an interesting question of whether the "real" policies should be checking for those error messages for all clients, rather than just Spanner.

**Review by coryan — CHANGES_REQUESTED** [review]
Please split this so we can keep the spanner specific strings checks in spanner, even if the generic polling loop moves.

Also discuss with @devbww because he is changing the polling functions to use asynchronous RPCs. 

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-:-MIvYWyE0oPjXU7DKS1o:b-k658za)* status: all files reviewed, 3 unresolved discussions (waiting on @mr-salty and @scotthart)

___
*[google/cloud/internal/polling_loop_test.cc, line 49 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-MIvQ9hw7kFiYvM-mmoP:-MIvYCib-6hbLY2Sbe7H:bq0dp54) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/668db18a4e07469791631fd9fd81ff2d134d1282/google/cloud/internal/polling_loop_test.cc#L49)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

I'd just use the simpler pre-#5087 version of this method:

```
    return status.code() == StatusCode::kUnavailable ||
           status.code() == StatusCode::kResourceExhausted;
```

Although, it brings up an interesting question of whether the "real" policies should be checking for those error messages for all clients, rather than just Spanner.
</blockquote></details>

They should not.  These are spanner-specific workarounds.  In general, there is not "One True" set of error codes that are retryable in all services. And certainly not strings.

**Review by mr-salty — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185)* status: all files reviewed, 3 unresolved discussions (waiting on @coryan and @scotthart)

___
*[google/cloud/internal/polling_loop_test.cc, line 49 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-MIvQ9hw7kFiYvM-mmoP:-MIv_gtJEhuOKHwajwUk:b-wj6wid) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/668db18a4e07469791631fd9fd81ff2d134d1282/google/cloud/internal/polling_loop_test.cc#L49)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

They should not.  These are spanner-specific workarounds.  In general, there is not "One True" set of error codes that are retryable in all services. And certainly not strings.
</blockquote></details>

We should discuss that elsewhere, but I don't think it matters for purposes of this PR, we can just remove them as I suggested rather than splitting the PR.

**Review by coryan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185)* status: all files reviewed, 3 unresolved discussions (waiting on @mr-salty and @scotthart)

___
*[google/cloud/internal/polling_loop_test.cc, line 49 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-MIvQ9hw7kFiYvM-mmoP:-MIvwNA-CEW9hhGE4Efi:bcptoc4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/668db18a4e07469791631fd9fd81ff2d134d1282/google/cloud/internal/polling_loop_test.cc#L49)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

We should discuss that elsewhere, but I don't think it matters for purposes of this PR, we can just remove them as I suggested rather than splitting the PR.
</blockquote></details>

Okay, I probably misunderstand what is going on then.

**Comment by devbww** [comment]
> Also discuss with @devbww because he is changing the polling functions to use asynchronous RPCs.

Don't worry about me.  When I finally figure out what I'm doing I'll adapt to any changes made here.  Thanks.

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185)* status: all files reviewed, 3 unresolved discussions (waiting on @mr-salty)

___
*[google/cloud/spanner/CMakeLists.txt, line 98 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-MIvNVHV7Y9CynzcIZRC:-MIypdMmB7S2N-CFKbwA:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/965b8858bf94db4afd368849046d8c2b3a1e6c13/google/cloud/spanner/CMakeLists.txt#L98)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

delete?
</blockquote></details>

Done.
___
*[google/cloud/spanner/CMakeLists.txt, line 272 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-MIvNX-M46An0mCZ5K0Y:-MIypeFW8qTpV9QTucw3:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/965b8858bf94db4afd368849046d8c2b3a1e6c13/google/cloud/spanner/CMakeLists.txt#L272)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

delete?
</blockquote></details>

Done.
___
*[google/cloud/internal/polling_loop_test.cc, line 49 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5185#-MIvQ9hw7kFiYvM-mmoP:-MIypcFZ34tSGMDFqr9b:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/668db18a4e07469791631fd9fd81ff2d134d1282/google/cloud/internal/polling_loop_test.cc#L49)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Okay, I probably misunderstand what is going on then.
</blockquote></details>

Done.

**Pull request merged**
