### PR TITLE
ci: use bazel for the coverage build

### PR DESCRIPTION
**Pull request by devjgm**
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/5067

This changes our "coverage" build to use bazel rather than cmake. The idea is that since bazel can use a remote cache that's updated from the pre- and post-merge builds, the cache hits may be higher. Bazel also knows how to run coverage tests in parallel, which solves https://github.com/googleapis/google-cloud-cpp/issues/3530.

This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5070)

### CODE REVIEW

**Comment by coryan** [comment]
This is really cool.  Note that the CMake builds use the emulator for the spanner tests.  That is faster than production, so this could go even faster if we changed the Bazel builds (or at least this build) to use the emulator too.

I think that explains some of the coverage differences for `google/cloud/spanner/testing/...` too.

**Comment by coryan** [comment]
Also, it seems this excludes all the coverage results from tests (that seems fine), and examples.

Examples are important (to me), I look at them to see how much of our sample code actually is tested.

**Comment by devjgm** [comment]
> This is really cool. Note that the CMake builds use the emulator for the spanner tests. That is faster than production, so this could go even faster if we changed the Bazel builds (or at least this build) to use the emulator too.

Good point. I added a note to https://github.com/googleapis/google-cloud-cpp/issues/4297

> Also, it seems this excludes all the coverage results from tests (that seems fine), and examples.
> Examples are important (to me), I look at them to see how much of our sample code actually is tested.

I added the `--instrument_test_targets` flag, which I think should address this. A new build is running now.

**Review by coryan — COMMENTED** [review]
### Things we MUST fix in this PR

For Bigtable, I think we did not activate all the tests we could when we moved the Bazel builds to the emulator:

https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5070/changes#L43

That seems like easy to fix and would recover most of the lost coverage.

We lost all coverage for the `gcs2cbt.cc` example.

### This we SHOULD fix in a future PR

Running against production for spanner changed things:

https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5070/tree/google/cloud/spanner

We gained some coverage:

https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5070/src/google/cloud/spanner/samples/samples.cc#L3200

And lost some:

https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5070/src/google/cloud/spanner/samples/samples.cc#L3129

We should really split the tests / samples and run against both production and the emulator to cover both.

On the storage side, we lost all the code for `getrusage()` (it is `#ifdef`-out in Bazel):

https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5070/changes#L164

We should fix that in a future PR that enables this code for Bazel.

### Things we can ignore

I think we also lost the weird tests to trigger failures on `read()` calls:

https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5070/changes#L197

We are testing with a different SSL library:

https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5070/changes#L87

Do you want to remove the code from CMake to support code coverage now or in a future PR?

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5070#-:-MHN_NLx5s_PJGgEvr2t:b-qz2r9u)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @coryan)

___
*[ci/kokoro/docker/Dockerfile.fedora-install, line 136 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5070#-MHNZx8U8HRPBNt7nQeT:-MHNZx8U8HRPBNt7nQeU:blf2gn) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/20a1bd8b08c4b2989f67646a73a48044d294e971/ci/kokoro/docker/Dockerfile.fedora-install#L136)):*
> ```
> # The Cloud Pub/Sub emulator needs Java, and so does `bazel coverage` :shrug:
> # Bazel needs the '-devel' version with javac.
> RUN dnf makecache && dnf install -y java-latest-openjdk-devel
> ```

FYI, this means the builds will be even faster, because this is rebuilding at least part of the development docker image.

**Comment by coryan** [comment]
I am happy with the changes. As your probably noticed, `codecov.io` does not seem to be. The last 3 builds failed to upload.  Any thoughts?

**Comment by devjgm** [comment]
> I am happy with the changes. As your probably noticed, `codecov.io` does not seem to be. The last 3 builds failed to upload. Any thoughts?

Thanks. I did see the issues on `codecov.io`. So far, I've found no way to debug codecov.io issues. It says there was an error, but doesn't say what the error was nor provide any way for me to debug it. I'll keep looking and googling.

**Comment by devjgm** [comment]
I've no idea why codecov is failing to process these files sometimes, and I see no way to debug it. I asked on the codecov support forum, so we'll see: https://community.codecov.io/t/help-debugging-there-was-an-error-processing-coverage-reports/1984

**Comment by coryan** [comment]
The only thing that comes to mind is comparing the size of the pre-Bazel and post-Bazel uploads.

**Comment by devjgm** [comment]
Due to a mistaken `rebase -i`, I cannot reopen this PR. The new PR is https://github.com/googleapis/google-cloud-cpp/pull/5075

**Pull request closed without merging**
