### PR TITLE
impl(oauth2): relocate base oauth credentials

### PR DESCRIPTION
**Pull request by scotthart**
part of the work for #8219

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220)* status: all files reviewed, 2 unresolved discussions (waiting on @scotthart)

___
*[google/cloud/internal/oauth2_credentials.h, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220#-Mv-eCSFBfDO8RGF-IwG:-Mv-eCSGA1UtjLx_gERE:b-oft5xb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6c75158bc24aee8ce177924bea85eb37253638f0/google/cloud/internal/oauth2_credentials.h#L1)):*
> ```objc
> // Copyright 2018 Google LLC
> ```

You will need to remind me again about what we decided about these files and copyright years?
___
*[google/cloud/internal/oauth2_credentials.h, line 31 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220#-Mv-hJgS4_gSThZDCVN_:-Mv-hJgS4_gSThZDCVNa:bk4q2vk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6c75158bc24aee8ce177924bea85eb37253638f0/google/cloud/internal/oauth2_credentials.h#L31)):*
> ```objc
>  * Interface for OAuth 2.0 credentials used to access Google Cloud services.
>  *
>  * Instantiating a specific kind of `Credentials` should usually be done via the
> ```

I think this not how we will use these credentials, we are planning to use the unified credentials?
___
*[google/cloud/internal/oauth2_credentials.h, line 61 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220#-Mv0ziFPAJocb1iE5w6H:-Mv0ziFPAJocb1iE5w6I:b-upqg0v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6c75158bc24aee8ce177924bea85eb37253638f0/google/cloud/internal/oauth2_credentials.h#L61)):*
> ```objc
>    * mismatch.
>    */
>   virtual StatusOr<std::vector<std::uint8_t>> SignBlob(
> ```

FYI, this can be used for both self-signed JWTs (https://google.aip.dev/auth/4111) and signed URLs.  It could be handy to implement all the GUAC stuff.

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/internal/oauth2_credentials.h, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220#-Mv-eCSFBfDO8RGF-IwG:-Mv16A_u7uvJqEVjejWn:b-qdyt6o) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6c75158bc24aee8ce177924bea85eb37253638f0/google/cloud/internal/oauth2_credentials.h#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

You will need to remind me again about what we decided about these files and copyright years?
</blockquote></details>

We decided to be conservative and as the majority of the contents of the files remains unchanged from the original, I kept the original Copyright years.
___
*[google/cloud/internal/oauth2_credentials.h, line 31 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220#-Mv-hJgS4_gSThZDCVN_:-Mv16Of50NKFSgmbgFPM:b-7klsy9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6c75158bc24aee8ce177924bea85eb37253638f0/google/cloud/internal/oauth2_credentials.h#L31)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think this not how we will use these credentials, we are planning to use the unified credentials?
</blockquote></details>

I was planning on porting/copying all the various credentials from storage/oauth2 for the time being to ensure that I can refactor GCS to use the REST library. Yes I am planning to use unified credentials.
___
*[google/cloud/internal/oauth2_credentials.h, line 61 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220#-Mv0ziFPAJocb1iE5w6H:-Mv174HfE4_V_W9FCt3b:boksy0o) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6c75158bc24aee8ce177924bea85eb37253638f0/google/cloud/internal/oauth2_credentials.h#L61)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

FYI, this can be used for both self-signed JWTs (https://google.aip.dev/auth/4111) and signed URLs.  It could be handy to implement all the GUAC stuff.
</blockquote></details>

Agreed. If additional code/functionality is needed, I would prefer to add that later.

**Review by coryan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220)* status: all files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[google/cloud/internal/oauth2_credentials.h, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220#-Mv-eCSFBfDO8RGF-IwG:-Mv3sZqLEFS2iVxkQXcT:b-3ttu0d) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6c75158bc24aee8ce177924bea85eb37253638f0/google/cloud/internal/oauth2_credentials.h#L1)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

We decided to be conservative and as the majority of the contents of the files remains unchanged from the original, I kept the original Copyright years.
</blockquote></details>

Thanks.  I candidly completely forgot about it, glad you did not.
___
*[google/cloud/internal/oauth2_credentials.h, line 31 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220#-Mv-hJgS4_gSThZDCVN_:-Mv3sfAR3KtgHzjnOFsh:brd9yaj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6c75158bc24aee8ce177924bea85eb37253638f0/google/cloud/internal/oauth2_credentials.h#L31)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

I was planning on porting/copying all the various credentials from storage/oauth2 for the time being to ensure that I can refactor GCS to use the REST library. Yes I am planning to use unified credentials.
</blockquote></details>

I agree with your plan, but the comments says otherwise?  Maybe change it to say that we expect application developers to use the unified credentials framework?

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[google/cloud/internal/oauth2_credentials.h, line 31 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220#-Mv-hJgS4_gSThZDCVN_:-Mv5H0hb0UMbyZI0_FEL:b-3kig9r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6c75158bc24aee8ce177924bea85eb37253638f0/google/cloud/internal/oauth2_credentials.h#L31)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I agree with your plan, but the comments says otherwise?  Maybe change it to say that we expect application developers to use the unified credentials framework?
</blockquote></details>

Updated the comments.

**Review by coryan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8220)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scotthart)

**Pull request merged**
