### PR TITLE
docs: create a few code snippets as examples for using Spanner Graph using cpp

### LINKED ISSUE #14659: Create samples for Cloud Spanner Graph
google/cloud/spanner

There are currently several examples for how to use Cloud Spanner with CPP.
With the recent announcement of the introduction of Spanner Graph, some examples of how to use graph features in Spanner are useful to have.
The goal here is to create some simple samples.

### PR DESCRIPTION
**Pull request by bharadwajvr**
Add a few code snippets to illustrate how to use Spanner Graph functionality in Java. These examples resemble other snippets for how various other Spanner features can be used.

Fixes #14659

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660)

### CODE REVIEW

**Review by scotthart — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @bharadwajvr)

___
*[`google/cloud/spanner/samples/graph_samples.cc` line 43 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660#-O5Eyi3nDNMDir18h_BJ:-O5Eyi3nDNMDir18h_BK:bkvc1fr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45fbb48590bfa24d8490dadfa0334a6ff1c3d0b/google/cloud/spanner/samples/graph_samples.cc#L43)):*
> ```cpp
> //! [START spanner_create_database_with_property_graph]
> void CreateDatabaseWithPropertyGraph(
> 		google::cloud::spanner_admin::DatabaseAdminClient client,
> ```

Looks like there's some formatting that needs be applied. Running `ci/cloudbuild/build.sh -t checkers-pr` locally should take care of it.
___
*[`google/cloud/spanner/samples/graph_samples.cc` line 419 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660#-O5Ezoka0Li7QfZrEqHM:-O5EzokbEpNAOgzrVggR:bsl3eq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45fbb48590bfa24d8490dadfa0334a6ff1c3d0b/google/cloud/spanner/samples/graph_samples.cc#L419)):*
> ```cpp
>   using CommandMap = std::map<std::string, CommandType>;
> 
>   using SampleFunction = void (*)(google::cloud::spanner::Client);
> ```

Prefer using `std::function` instead of C style function pointers, here and elsewhere:
```
using SampleFunction = std::function<void(google::cloud::spanner::Client)>;
```
___
*[`google/cloud/spanner/samples/spanner_client_integration_samples.bzl` line 15 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660#-O5EyBmw2Gkxz3NQ1a-4:-O5EyBmx9jLEV-EMpqRy:b-b0fky6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45fbb48590bfa24d8490dadfa0334a6ff1c3d0b/google/cloud/spanner/samples/spanner_client_integration_samples.bzl#L15)):*
> ```Starlark
> # limitations under the License.
> #
> # DO NOT EDIT -- GENERATED BY CMake -- Change the CMakeLists.txt file if needed
> ```

You'll want to edit `spanner/samples/CMakeLists.txt` to add `graph_samples.cc`

**Review by bharadwajvr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @scotthart)

___
*[`google/cloud/spanner/samples/graph_samples.cc` line 43 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660#-O5Eyi3nDNMDir18h_BJ:-O5seK1LE8shOwbC8W-a:b-6keqjd) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45fbb48590bfa24d8490dadfa0334a6ff1c3d0b/google/cloud/spanner/samples/graph_samples.cc#L43)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Looks like there's some formatting that needs be applied. Running `ci/cloudbuild/build.sh -t checkers-pr` locally should take care of it.
</blockquote></details>

I tried this and I run into compilation errors in typos-cli v1.16.1 - errors E0277, E0308.
Googling didn't help me find a fix. Is this something you recognize and can help me fix?
___
*[`google/cloud/spanner/samples/graph_samples.cc` line 419 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660#-O5Ezoka0Li7QfZrEqHM:-O5shnd_9Vyw1xre4X_K:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45fbb48590bfa24d8490dadfa0334a6ff1c3d0b/google/cloud/spanner/samples/graph_samples.cc#L419)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Prefer using `std::function` instead of C style function pointers, here and elsewhere:
```
using SampleFunction = std::function<void(google::cloud::spanner::Client)>;
```
</blockquote></details>

Done.
___
*[`google/cloud/spanner/samples/spanner_client_integration_samples.bzl` line 15 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660#-O5EyBmw2Gkxz3NQ1a-4:-O5sfUjX2Gx5bkdNYaeZ:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45fbb48590bfa24d8490dadfa0334a6ff1c3d0b/google/cloud/spanner/samples/spanner_client_integration_samples.bzl#L15)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

You'll want to edit `spanner/samples/CMakeLists.txt` to add `graph_samples.cc`
</blockquote></details>

Done.

**Review by bharadwajvr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @scotthart)

___
*[`google/cloud/spanner/samples/graph_samples.cc` line 43 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660#-O5Eyi3nDNMDir18h_BJ:-O5xmnZUEUcSS41MoPGq:b1hvod3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45fbb48590bfa24d8490dadfa0334a6ff1c3d0b/google/cloud/spanner/samples/graph_samples.cc#L43)):*
<details><summary><i>Previously, bharadwajvr wrote…</i></summary><blockquote>

I tried this and I run into compilation errors in typos-cli v1.16.1 - errors E0277, E0308.
Googling didn't help me find a fix. Is this something you recognize and can help me fix?
</blockquote></details>

Rebased to updated main and that fixed the problem. Formatting changes are applied now.

**Comment by bharadwajvr** [comment]
Gentle reminder: @scotthart

**Review by scotthart — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660)* status: 0 of 3 files reviewed, 2 unresolved discussions

**Review by bharadwajvr — COMMENTED** [review]
Ignoring the code-coverage data here since this is sample code.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14660#-:-O6c2v_fBMdQztrI5sO-:bh2q4wi)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @scotthart)

**Pull request merged**
