### PR TITLE
fix: retry PartitionedDml if the gRPC connection is terminated

### PR DESCRIPTION
**Pull request by mr-salty**
part of #4714

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080)

### CODE REVIEW

**Comment by mr-salty** [comment]
___
*[google/cloud/spanner/internal/connection_impl.cc, line 849 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080#-MHVAajf-lMGO0iT-4GN:-MHVAajf-lMGO0iT-4GO:b-21a0k5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/05ab09a027c4b978679b319139f54afdc8bd83d7/google/cloud/spanner/internal/connection_impl.cc#L849)):*
> ```
>    // TODO(salty) this is an ugly hack; we need to make sure the original
>     // policy does not treat a "retryable" internal error as permanent.
> ```

This whole PR, while it does resolve the issue, is kind of ugly, and this is the ugliest part of it. However, I don't know that we can do any better without restructuring the base classes. I sent this PR as a draft as a point for discussion - ideas are welcome... maybe better to chat/meet about it later.

**Review by coryan — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080)* status: all files reviewed, 2 unresolved discussions (waiting on @mr-salty)

___
*[google/cloud/spanner/internal/connection_impl.cc, line 847 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080#-MHWP-af4FVz3pFFw_BW:-MHWP-af4FVz3pFFw_BX:badffb9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/05ab09a027c4b978679b319139f54afdc8bd83d7/google/cloud/spanner/internal/connection_impl.cc#L847)):*
> ```cpp
>       return false;
>     }
>     // TODO(salty) this is an ugly hack; we need to make sure the original
> ```

TODOs should point to a bug number, not a person.
___
*[google/cloud/spanner/internal/connection_impl.cc, line 849 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080#-MHVAajf-lMGO0iT-4GN:-MHWP9-q-mSFPh3X3hUD:b-pmtr1f) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/05ab09a027c4b978679b319139f54afdc8bd83d7/google/cloud/spanner/internal/connection_impl.cc#L849)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

> ```
>    // TODO(salty) this is an ugly hack; we need to make sure the original
>     // policy does not treat a "retryable" internal error as permanent.
> ```

This whole PR, while it does resolve the issue, is kind of ugly, and this is the ugliest part of it. However, I don't know that we can do any better without restructuring the base classes. I sent this PR as a draft as a point for discussion - ideas are welcome... maybe better to chat/meet about it later.
</blockquote></details>

Maybe this is easier to follow:

```cc
bool OnFailure(Status const& status) override {
  bool treat_as_transient = IsInternalTreatedAsTransient(status);
  return original_retry_policy->OnFailure(treat_as_transient ? FakeTransient(status) : status);
}

bool IsPermanentFailure(Status const& status) const override {
  bool treat_as_transient = IsInternalTreatedAsTransient(status);
  return original_retry_policy->OnFailure(treat_as_transient ? FakeTransient(status) : status);
}

Status FakeTransient(Status const& status) const {
  return Status(StatusCode::kUnavailable, "kInternal treated as transient: " + status.message());
}

bool IsInternalAndTransient(Status const& status) {
  if (status.code() != StatusCode::kInternal) return false;
  auto constexpr kRetryableMessages[] = {
          "Received unexpected EOS on DATA frame from server",
          "Connection closed with unknown cause",
          "HTTP/2 error code: INTERNAL_ERROR", "RST_STREAM"};
  for (auto const& message : kRetryableMessages) {
      if (absl::StrContains(status.message(), message)) return true;
   }
  return false;
}
```

**Review by mr-salty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/spanner/internal/connection_impl.cc, line 847 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080#-MHWP-af4FVz3pFFw_BW:-MHWo5qTB_DmSVjGjoki:bxl7aav) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/05ab09a027c4b978679b319139f54afdc8bd83d7/google/cloud/spanner/internal/connection_impl.cc#L847)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

TODOs should point to a bug number, not a person.
</blockquote></details>

My intent was to resolve the TODO (and remove it) before submitting... so i guess a DO NOT SUBMIT would have been appropriate.
___
*[google/cloud/spanner/internal/connection_impl.cc, line 849 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080#-MHVAajf-lMGO0iT-4GN:-MHWpQxs76_gq3INdw4P:b-gy3q81) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/05ab09a027c4b978679b319139f54afdc8bd83d7/google/cloud/spanner/internal/connection_impl.cc#L849)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Maybe this is easier to follow:

```cc
bool OnFailure(Status const& status) override {
  bool treat_as_transient = IsInternalTreatedAsTransient(status);
  return original_retry_policy->OnFailure(treat_as_transient ? FakeTransient(status) : status);
}

bool IsPermanentFailure(Status const& status) const override {
  bool treat_as_transient = IsInternalTreatedAsTransient(status);
  return original_retry_policy->OnFailure(treat_as_transient ? FakeTransient(status) : status);
}

Status FakeTransient(Status const& status) const {
  return Status(StatusCode::kUnavailable, "kInternal treated as transient: " + status.message());
}

bool IsInternalAndTransient(Status const& status) {
  if (status.code() != StatusCode::kInternal) return false;
  auto constexpr kRetryableMessages[] = {
          "Received unexpected EOS on DATA frame from server",
          "Connection closed with unknown cause",
          "HTTP/2 error code: INTERNAL_ERROR", "RST_STREAM"};
  for (auto const& message : kRetryableMessages) {
      if (absl::StrContains(status.message(), message)) return true;
   }
  return false;
}
```

</blockquote></details>

I think that is clearer, although it still bugs me that really all we're trying to do is change `IsPermanentFailure()` but we need a bunch of extra code around it.

BTW, I think [this line](https://github.com/googleapis/google-cloud-cpp/blob/228472c3719a015b434c49d230dd01042cc49d8b/google/cloud/internal/retry_policy.h#L100) should call the `IsPermanentFailure()` method on `this` rather than the traits. I initially thought changing that might help me here.  Unfortunately I don't think it really does, but it still feels more "correct" to me - WDYT?

**Review by coryan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080)* status: all files reviewed, 2 unresolved discussions (waiting on @devbww and @mr-salty)

___
*[google/cloud/spanner/internal/connection_impl.cc, line 847 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080#-MHWP-af4FVz3pFFw_BW:-MHWswrOET2l5plTj3Wq:bon4god) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/05ab09a027c4b978679b319139f54afdc8bd83d7/google/cloud/spanner/internal/connection_impl.cc#L847)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

My intent was to resolve the TODO (and remove it) before submitting... so i guess a DO NOT SUBMIT would have been appropriate.
</blockquote></details>

Sorry, I thought so, but I wanted a comment to block the review on.
___
*[google/cloud/spanner/internal/connection_impl.cc, line 849 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080#-MHVAajf-lMGO0iT-4GN:-MHWt6X71u0LKTady13r:b-7bamad) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/05ab09a027c4b978679b319139f54afdc8bd83d7/google/cloud/spanner/internal/connection_impl.cc#L849)):*
> BTW, I think this line should call the IsPermanentFailure() method on this rather than the traits. I initially thought changing that might help me here. Unfortunately I don't think it really does, but it still feels more "correct" to me - WDYT?

I agree, is just that the virtual `IsPermanentFailure()` is new-ish.... maybe create a PR to fix that first?  I think @devbww was working on fixing all the retry stuff, he may have additional thoughts.

**Review by devbww — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080)* status: all files reviewed, 2 unresolved discussions (waiting on @mr-salty)

___
*[google/cloud/spanner/internal/connection_impl.cc, line 849 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080#-MHVAajf-lMGO0iT-4GN:-MHWyhSb8XSWAV7JDpG3:bwqa5fi) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/05ab09a027c4b978679b319139f54afdc8bd83d7/google/cloud/spanner/internal/connection_impl.cc#L849)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

> BTW, I think this line should call the IsPermanentFailure() method on this rather than the traits. I initially thought changing that might help me here. Unfortunately I don't think it really does, but it still feels more "correct" to me - WDYT?

I agree, is just that the virtual `IsPermanentFailure()` is new-ish.... maybe create a PR to fix that first?  I think @devbww was working on fixing all the retry stuff, he may have additional thoughts.

</blockquote></details>

I haven't done anything on that front yet.

**Comment by mr-salty** [comment]
___
*[google/cloud/spanner/internal/connection_impl.cc, line 849 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5080#-MHVAajf-lMGO0iT-4GN:-MHXCtxABOIxmgm6Vh-b:bkgspym) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/05ab09a027c4b978679b319139f54afdc8bd83d7/google/cloud/spanner/internal/connection_impl.cc#L849)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I haven't done anything on that front yet.
</blockquote></details>

So, WDYT about just baking this into `SafeGrpcRetry`?  As I noted in chat, this  should apply to all streaming calls, not just PDML. For non-streaming calls, maybe these errors never happen, but if they do it seems like we'd still want to retry.

**Comment by mr-salty** [comment]
dropping this in favor of #5087

**Pull request closed without merging**
