### PR TITLE
test(storage): add more utils for gcs emulator

### PR DESCRIPTION
**Pull request by vnvo2409**
This PR adds:
- Init for `Database`
- Entry point for `emulator` and `REST`
- `generation` to deal with precondition and generation in request.
- Unit tests
- `FakeRequest` to mimic the structure of a `Flask` request. It will be added more feature in later PRs.

Related to #4751

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5124)

### CODE REVIEW

**Comment by coryan** [comment]
The changes look good, we need to fix the CI system before starting the builds (too many broken things right now).

We should start thinking about how to connect these python tests to the CI system, we would want them to run on each build.

**Comment by coryan** [comment]
Can you please rebase to pick up all the CI fixes?

**Review by coryan — COMMENTED** [review]
Looks good, let's see what the builds say +kokoro:run 

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5124#-:-MI0BKSk8j0LtmlI37iL:bxk64q4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by vnvo2409** [comment]
> Can you please rebase to pick up all the CI fixes?

Done

> We should start thinking about how to connect these python tests to the CI system, we would want them to run on each build.

I think that adding tests to the CI system isn't necessary right now because I am the only one who working on the emulator at the moment. I think connect these python tests to the CI system after the emulator is finished is more reasonable.

**Comment by coryan** [comment]
There are some formatting changes needed:

```patch
diff --git a/google/cloud/storage/emulator/rest_server.py b/google/cloud/storage/emulator/rest_server.py
index 91ef35697..1ab2a5efc 100644
--- a/google/cloud/storage/emulator/rest_server.py
+++ b/google/cloud/storage/emulator/rest_server.py
@@ -32,21 +32,12 @@ def index():
 # === SERVER === #
 
 
-server = DispatcherMiddleware(
-    root,
-    {
-        "/httpbin": httpbin.app,
-    },
-)
+server = DispatcherMiddleware(root, {"/httpbin": httpbin.app})
 
 
 def run(port, database):
     global db
     db = database
     serving.run_simple(
-        "localhost",
-        int(port),
-        server,
-        use_reloader=False,
-        threaded=True,
+        "localhost", int(port), server, use_reloader=False, threaded=True
     )
```

**Comment by vnvo2409** [comment]
> There are some formatting changes needed

Done

**Review by coryan — APPROVED** [review]
Thanks, +kokoro:run 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5124#-:-MI4Z7t53WQuLBaWeAUr:b-wkqi73)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
