### PR TITLE
feat(bigtable): create logging layer for Cloud Bigtable

### PR DESCRIPTION
**Pull request by manish-qlogic**
This Pull Request completes a sub task ` logging client for admin_client.`  of #4320

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5556)

### CODE REVIEW

**Review by coryan — COMMENTED** [review]
Can you add a test case for each function that prints something?  You can check:

https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/pubsub/internal/subscriber_logging_test.cc

for an example.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5556#-:-MNOYM10B6iBhAp37tGf:bpftakk)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by manish-qlogic — COMMENTED** [review]
I need more inputs here.

`SubscriberLogging` has a way to pass mocked stubs

https://github.com/googleapis/google-cloud-cpp/blob/1c586e12483c8b03e5e9d51e12dabd6cc679a7d4/google/cloud/pubsub/internal/subscriber_logging_test.cc#L60


where as in case of `bigtable::AdminClient` it is taken care by `CommonClient`

https://github.com/googleapis/google-cloud-cpp/blob/1c586e12483c8b03e5e9d51e12dabd6cc679a7d4/google/cloud/bigtable/internal/common_client.h#L91

Now, one way to write test cases is
- write mock common client that will generate mockstub
- figure out a way to pass this mock common client to `bigtable::AdminClient`.

Should i try this or am i missing something here?

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5556#-:-MNW-ydH2tOF2VfCYKav:buwv43r)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — COMMENTED** [review]
Oh, I did not pay enough attention to the implementation.  I think we should consider making `LoggingAdminClient` a decorator around any other `google::cloud::bigtable::AdminClient`


```cc
class LoggingAdminClient : public google::cloud::bigtable::AdminClient {
public:
  LoggingAdminClient(std::shared_ptr<google::cloud::bigtable::AdminClient> child, TracingOptions options)
    : child_(std::move(child)), options_(std::move(options)) {}
```

Then the implementation of most functions becomes:

```cc
  grpc::Status LoggingAdminClient::GetBackup(grpc::ClientContext* context,
                         btadmin::GetBackupRequest const& request,
                         btadmin::Backup* response) override {
    return LogWrapper(
        [this](grpc::ClientContext* context,
               btadmin::GetBackupRequest const& request,
               btadmin::Backup* response) {
          return child_->GetBackup(context, request, response);
        },
        context, request, response, __func__,
        tracing_options_);
  }
```

That makes it possible to accept mocks at the logging layer.  In addition, the initialization changes:

```cc
std::shared_ptr<AdminClient> CreateDefaultAdminClient(std::string project,
                                                      ClientOptions options) {
  std::shared_ptr<AdminClient> client = std::make_shared<DefaultAdminClient>(std::move(project),
                                              options);
  if (options.tracing_enabled("rpc")) {
    GCP_LOG(INFO) << "Enabled logging for gRPC calls";
    client = std::make_shared<LoggingAdminClient>(std::move(client),
                                                       options.tracing_options());
  }
 return client;
}
```

WDYT?

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5556#-:-MNYhjya-WmPEO2XqqiS:b-321woy)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5556#-:-MOcb16Q1G8RTQwTxSUl:b-g2a5fb)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
