### PR TITLE
feat(pubsub): implement a throughput benchmark

### LINKED ISSUE #4565: Implement a throughput benchmark
We want a test to measure throughput for both publishing and receiving messages.
We also want to measure the "overhead" of either operation when compared to "raw" gRPC.

### PR DESCRIPTION
**Pull request by coryan**
Implement a benchmark to measure publisher and/or subscriber throughput.

Fixes #4565

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368)

### CODE REVIEW

**Comment by mr-salty** [comment]
___
*[google/cloud/pubsub/benchmarks/README.md, line 41 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKq4Zi53rmCbTPYsCu4:-MKq4Zi61oUNiJG6iClY:b-tv2k0f) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/README.md#L41)):*
> ```
> the the
> ```
typo: "the the"

**Review by mr-salty — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @coryan)

___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 55 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKq7HVc1UQBAEDWKOeu:-MKq7HVc1UQBAEDWKOev:bngmcqa) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L55)):*
> ```cpp
>   std::chrono::seconds iteration_duration = std::chrono::seconds(5);
> 
>   bool publisher = false;
> ```

completely up to you, but maybe `struct Publisher` and `struct Subscriber` and make them optionals?  i.e. `config.publisher->thread_count`etc.
___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 80 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKq8qwdEeI1fwAqJgZY:-MKq8qwdEeI1fwAqJgZZ:bpwwqj8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L80)):*
> ```cpp
> StatusOr<Config> ParseArgs(std::vector<std::string> args);
> 
> class Cleanup {
> ```

you don't actually use this (see comment below)
___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 124 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKq8GaaAy5jgvdpRGoT:-MKq8GaaAy5jgvdpRGoU:b-dtkjhc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L124)):*
> ```cpp
>     delete_topic = [topic_admin, topic]() mutable {
>       (void)topic_admin.DeleteTopic(topic);
>     };
> ```

don't you need to call `cleanup.Defer(delete_topic)`?

I think you can do it here and eliminate the `std::function` outside the `if`. actually, you don't need a local variable at all, just `Defer([...]...`
___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 141 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKq90Z46x8Da-SQaTSS:-MKq90Z46x8Da-SQaTST:bnj7hl0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L141)):*
> ```cpp
>       return 1;
>     }
>     delete_subscription = [subscription_admin, subscription]() mutable {
> ```

same as above

**Review by mr-salty — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @coryan and @mr-salty)

___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 223 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKqC9q45yWp9dJDZ8sG:-MKqC9q45yWp9dJDZ8sH:b-nmhz7r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L223)):*
> ```cpp
>       absl::StrFormat("%.02f", static_cast<double>(bytes) /
>                                    static_cast<double>(elapsed_us.count()));
>   std::lock_guard<std::mutex> lk(mu);
> ```

IIUC `mu` is only used to avoid interleaving output? If so, I think a global/static is actually preferable in this case, since it's important for all the uses to use the same lock, and passing it around obscures that IMO (and  naming it`cout_mu` or similar would also make it clearer)
___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 361 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKqDXQi4L_y0kEQ0tyE:-MKqDXQi4L_y0kEQ0tyF:b-sl4ggv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L361)):*
> ```cpp
>   for (auto& s : sessions) {
>     auto status = s.get();
>     std::lock_guard<std::mutex> lk(mu);
> ```

I don't think taking the lock here (as opposed to right before `cout`) changes anything.

If you're trying to ensure the `if` on the next line and the `last_received_count` assignment see the same value you should do `int64_t current_received_count = received_count.load()` once here and use it in both places below, rather than calling `load` twice.
___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 362 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKqD3hcBWd1563A3TU0:-MKqD3hcBWd1563A3TU1:b-x8xtg2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L362)):*
> ```
> received_count == received_count.load()
> ```

should be`last_received_count == received_count.load()` (or `== current_received_count` per my suggestion above)?

**Review by coryan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @mr-salty)

___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 55 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKq7HVc1UQBAEDWKOeu:-MKqRnf3Cys1jbd4t_G1:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L55)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think I will pass, it would make the command-line parsing harder, logging more complicated.
</blockquote></details>

Done.
___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 80 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKq8qwdEeI1fwAqJgZY:-MKqRo393NLD_1UVkB0G:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L80)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Doh! Fixed.
</blockquote></details>

Done.
___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 223 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKqC9q45yWp9dJDZ8sG:-MKqMr0r4NoJCFSHJUpa:bs7wumb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L223)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

IIUC `mu` is only used to avoid interleaving output? If so, I think a global/static is actually preferable in this case, since it's important for all the uses to use the same lock, and passing it around obscures that IMO (and  naming it`cout_mu` or similar would also make it clearer)
</blockquote></details>

Done.
___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 361 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKqDXQi4L_y0kEQ0tyE:-MKqMsW91RrRtZ3aIm9G:bo3vl6y) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L361)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

I don't think taking the lock here (as opposed to right before `cout`) changes anything.

If you're trying to ensure the `if` on the next line and the `last_received_count` assignment see the same value you should do `int64_t current_received_count = received_count.load()` once here and use it in both places below, rather than calling `load` twice.
</blockquote></details>

Thanks, done.
___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 362 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKqD3hcBWd1563A3TU0:-MKqNVulEmuKc6loktD3:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1dfc49ae05ce07e9a191a740ae0f059b3cc76b35/google/cloud/pubsub/benchmarks/throughput.cc#L362)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

> ```
> received_count == received_count.load()
> ```

should be`last_received_count == received_count.load()` (or `== current_received_count` per my suggestion above)?
</blockquote></details>

Done.

**Review by mr-salty — APPROVED** [review]
:lgtm: (one small change remaining)

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-:-MKrXAOs-tKmHdlvSAqp:bklxx1z)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan and @mr-salty)

___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 360 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKrWhw526psscvnlBC-:-MKrWhw526psscvnlBC0:bndzaox) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2d03ac41e7c46586777863d0887187a89341a7af/google/cloud/pubsub/benchmarks/throughput.cc#L360)):*
> ```
> received_count
> ```

This still needs to be **`last_received_count`**`== current`,  I believe

**Review by coryan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @mr-salty)

___
*[google/cloud/pubsub/benchmarks/throughput.cc, line 360 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5368#-MKrWhw526psscvnlBC-:-MKtR7bQ4mJj66p-7b5k:b-wp0etj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2d03ac41e7c46586777863d0887187a89341a7af/google/cloud/pubsub/benchmarks/throughput.cc#L360)):*
<details><summary><i>Previously, mr-salty (Todd Derr) wrote…</i></summary><blockquote>

> ```
> received_count
> ```

This still needs to be **`last_received_count`**`== current`,  I believe
</blockquote></details>

Doh! Fixed.

**Pull request merged**
