### PR TITLE
cleanup: use versioned clients in quickstart

### PR DESCRIPTION
**Pull request by dbolduc**
Most of the remaining work for #10170

Any remotely interesting decisions were separated into different commits.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11314)

### CODE REVIEW

**Review by coryan — APPROVED** [review]
I noted how some protos needed fully qualified name.  A non-blocking question below and a small note.

> Reviewed 177 of 177 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11314#-:-NTKOXKq8Xh4GJHbQDme:b-hupo7n)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dbolduc)

___
*[`google/cloud/webrisk/quickstart/quickstart.cc` line 31 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11314#-NTKOhZd-ua-HZvEDbYL:-NTKOhZd-ua-HZvEDbYM:b-382rc1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/97e9186fae60d353a45fff75112e519f27183b45/google/cloud/webrisk/quickstart/quickstart.cc#L31)):*
> ```cpp
> 
>   auto const uri = std::string{argc == 2 ? argv[1] : "https://www.google.com/"};
>   auto const threat_types = {google::cloud::webrisk::v1::MALWARE,
> ```

FYI, this changes the type to `std::initializer_list<T>`, seems Okay.

**Review by coryan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dbolduc)

**Comment by coryan** [comment]
*[`google/cloud/iam/quickstart/quickstart.cc` line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11314#-NTKPDbD1P-NnwgsGR6R:-NTKPDbD1P-NnwgsGR6S:b-7d3zxc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/97e9186fae60d353a45fff75112e519f27183b45/google/cloud/iam/quickstart/quickstart.cc#L27)):*
> ```cpp
> 
>   // Create a namespace alias to make the code easier to read.
>   namespace iam_admin = ::google::cloud::iam_admin_v1;
> ```

??? Why is this changing to `iam_admin`?

**Review by dbolduc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11314)* status: all files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[`google/cloud/iam/quickstart/quickstart.cc` line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11314#-NTKPDbD1P-NnwgsGR6R:-NTKwCrc2dRGb5kU6HmA:b-a0ot1a) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/97e9186fae60d353a45fff75112e519f27183b45/google/cloud/iam/quickstart/quickstart.cc#L27)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

??? Why is this changing to `iam_admin`?
</blockquote></details>

Reverted.

I think my logic was to reserve `namespace iam` for `::google::cloud::iam_v1` or something.
___
*[`google/cloud/webrisk/quickstart/quickstart.cc` line 31 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11314#-NTKOhZd-ua-HZvEDbYL:-NTKzHgkEs_skdgmtFro:bb6sh2i) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/97e9186fae60d353a45fff75112e519f27183b45/google/cloud/webrisk/quickstart/quickstart.cc#L31)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

FYI, this changes the type to `std::initializer_list<T>`, seems Okay.
</blockquote></details>

Ack.

**Pull request merged**
