### PR TITLE
ci(macos): change os to macos-13-xlarge

### PR DESCRIPTION
**Pull request by alevenberg**
Closes https://github.com/googleapis/google-cloud-cpp/issues/12808

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12826)

### CODE REVIEW

**Comment by alevenberg** [comment]
Will delete branches on the upstream repo after merged.

**Comment by coryan** [comment]
Were you able to compare the running build time on the new machines?  The last builds look slow:

https://github.com/googleapis/google-cloud-cpp/actions/runs/6422090014/job/17440893524

But that may be because the cache was cold.  How does it look with a warm cache?  Can we run something close to a head-to-head test?

**Comment by alevenberg** [comment]
> Were you able to compare the running build time on the new machines? 
Yes, but I was lazy so I only did it on one.

With caching
[macOS-CMake / cmake + macos-12 + Core](https://github.com/googleapis/google-cloud-cpp/actions/runs/6411466850/job/17433775135#logs)
succeeded yesterday in 13m 59s
$0.12/minute for large -> =~1.68

[macOS-CMake / cmake + macos-13 + Core](https://github.com/googleapis/google-cloud-cpp/actions/runs/6422090014/job/17440891540#logs)
succeeded now in 8m 47s
$0.16/minute for XL = ~1.44

(no caching)
[macOS-CMake / cmake + macos-13 + Core](https://github.com/googleapis/google-cloud-cpp/actions/runs/6422090014/job/17437926130#logs)
succeeded 1 hour ago in 33m 44s. [View latest attempt](https://github.com/googleapis/google-cloud-cpp/actions/runs/6422090014).

> The last builds look slow:
>
> [googleapis/google-cloud-cpp/actions/runs/6422090014/job/17440893524](https://github.com/googleapis/google-cloud-cpp/actions/runs/6422090014/job/17440893524)
> 
> But that may be because the cache was cold. How does it look with a warm cache? Can we run something close to a head-to-head test?

I can re-run all the tests and they should be cached now.

**Comment by alevenberg** [comment]
[macOS-CMake / cmake + macos-13 + Other](https://github.com/googleapis/google-cloud-cpp/actions/runs/6422090014/job/17441668655#logs)
succeeded 22 minutes ago in 12m 3s

**Review by coryan — APPROVED** [review]

**Pull request merged**
