### PR TITLE
feat(bigquery): add validation of input parameters

### PR DESCRIPTION
**Pull request by MeilakhSiarhei**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13429)

### CODE REVIEW

**Comment by coryan** [comment]
In general this applies:

https://github.com/googleapis/google-cloud-cpp/blob/main/doc/adr/2018-06-19-do-not-duplicate-server-side-validation.md

Why should we make an exception in this case?

**Comment by MeilakhSiarhei** [comment]
> In general this applies:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/main/doc/adr/2018-06-19-do-not-duplicate-server-side-validation.md
> 
> Why should we make an exception in this case?

I added it for consistency with JobRequest validations
https://github.com/googleapis/google-cloud-cpp/blob/e6282c3cbe1462cb997f8925d87131f4cf4e2249/google/cloud/bigquery/v2/minimal/internal/job_request.cc#L447

If we don't validate parameters, maybe we should delete existing ones.
CC @jsrinnn, what do you think?

**Review by jsrinnn — APPROVED** [review]
Please look at my feedback as well.

**Comment by coryan** [comment]
> 
> If we don't validate parameters, maybe we should delete existing ones. 

Yes please.  I missed the checks in the PR for `job_request.cc`.

**Comment by jsrinnn** [comment]
Siarhei and I chatted offline. Yes, let's not add it for job_request as well. Thanks!

**Pull request closed without merging**
