### PR TITLE
test(storage): add rest handle for object

### PR DESCRIPTION
**Pull request by vnvo2409**
This PR adds some basic operations and rest handle for object.

Part of #4751

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5289)

### CODE REVIEW

**Review by coryan — COMMENTED** [review]
A few questions below, let's start the builds just in case +kokoro:run 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5289#-:-MK6OsMj643BXo8Ztl03:b-rh4vfr)* status: all files reviewed, 2 unresolved discussions (waiting on @vnvo2409)

___
*[google/cloud/storage/emulator/gcs/object.py, line 105 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5289#-MK6OKxQCkkLlDoqq8xx:-MK6OKxR5lg4Q714FRLY:b-vlgtq9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/793ea6011d674e275ce95d4ec2292d91ae494d57/google/cloud/storage/emulator/gcs/object.py#L105)):*
> ```Python
>         bucket.iam_configuration.uniform_bucket_level_access.enabled = False
>         if len(metadata.acl) != 0:
>             default_projection = 2
> ```

I just noticed this numeric literals here, what do they mean?  Can we add a constant to make their meaning more obvious?
___
*[google/cloud/storage/emulator/gcs/object.py, line 111 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5289#-MK6OW5W1FthzxnB8rEu:-MK6OW5W1FthzxnB8rEv:b-cccpos) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/793ea6011d674e275ce95d4ec2292d91ae494d57/google/cloud/storage/emulator/gcs/object.py#L111)):*
> ```Python
>             )
>             if predefined_acl == 0:
>                 predefined_acl = 5
> ```

Here is another numeric literal

**Comment by vnvo2409** [comment]
I will add some comments to make it clear. In fact, these literals comes from the protobuf definition of storage service ( `storage.proto` and `resources.proto` ). For a fully understanding, we have to read the proto file.

Projection has 3 enum value ( 0 unset, 1 noAcl , 2 full ). Predefined acl has 6 enum value and so on.

**Comment by coryan** [comment]
Ugh... I assume these things have symbolic names in the proto-generated files?  Can we use those?

**Comment by vnvo2409** [comment]
> Ugh... I assume these things have symbolic names in the proto-generated files?  Can we use those?
> 

Of course we can. It's strange that I have never thought of that. :/

**Review by coryan — COMMENTED** [review]
Much easier to follow, I am happy with the PR as-is, but I have one more thought for you. Meanwhile, let's start the builds +kokoro:run 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5289#-:-MKG3A9L5uLhV3evnMIV:bwtu4fu)* status: all files reviewed, 1 unresolved discussion (waiting on @vnvo2409)

___
*[google/cloud/storage/emulator/rest_server.py, line 22 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5289#-MKG20Ie30LvMJ6YyE5J:-MKG20Ie30LvMJ6YyE5K:b-vt5o11) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8db50bd6edaab566dfcee7f2b211c876c033099c/google/cloud/storage/emulator/rest_server.py#L22)):*
> ```Python
> from werkzeug import serving
> from werkzeug.middleware.dispatcher import DispatcherMiddleware
> from google.cloud.storage_v1.proto import storage_resources_pb2 as resources_pb2
> ```

Maybe for a future PR, consider instead:

```py
from google.cloud.storage_v1.proto import storage_resources_pb2.CommonEnums as CommonEnums
```

or even (though I have no clue what is the right way to format these):

```py
from google.cloud.storage_v1.proto import 
    storage_resources_pb2.CommonEnums.Projection as Projection,
    storage_resources_pb2.CommonEnums.PredefinedBucketAcl as PredefinedBucketAcl,
    storage_resources_pb2.CommonEnums.PredefinedBucketAcl as PredefinedObjectAcl
```

What do you think?

**Comment by vnvo2409** [comment]
> What do you think?

Sound good to me

**Comment by coryan** [comment]
> > What do you think?
> 
> Sound good to me

Should we do that on this PR of a future one?  Totally your call.

**Comment by vnvo2409** [comment]
> Should we do that on this PR of a future one? Totally your call.

I think this PR is better

**Comment by vnvo2409** [comment]
`CommonEnums` is the deepest layer that we can import

**Review by coryan — COMMENTED** [review]
Sounds good. +kokoro:run 

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5289#-:-MKGMANK3wAJmKhWmpN-:b-xy075n)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5289#-:-MKGMNzkCvvCIWJEk5Kw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
