### PR TITLE
Implement Table::AsyncReadRows.

### LINKED ISSUE #1487: Implement bigtable::Table::AsyncReadRows
This function will implement an asynchronous version of `Table::ReadRows`. The function will have the following signature:

```C++
class google::cloud::bigtable::Table { public:
template <typename ReadRowFunctor, ...>
future<void> AsyncReadRows(
    RowSet row_set, Filter filter, CompletionQueue& cq, ReadRowFunctor&&);
template <typename ReadRowFunctor, ...>
future<void> AsyncReadRows(
    RowSet row_set, std::int64_t rows_limit, Filter filter, CompletionQueue& cq, ReadRowFunctor&&);
};
```

The `ReadRowFunctor` parameter will be called for each row received. The future becomes satisfied when all the rows have been read.

As part of this work we need to:

- [ ] Implement the function.
- [ ] Implement an integration test for this function.
- [ ] Implement an example for this function.
- [ ] Execute the example as part of the CI build.

The main difference between the example and the integration test is that the latter uses pre-defined values and checks the resulting state against expected outputs, while the former takes (most) of its parameters from the command-line and simply prints out any state.

### PR DESCRIPTION
**Pull request by dopiera**
This fixes #1487.

This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2579)

### CODE REVIEW

**Comment by coryan** [comment]
I think we should implement this will callbacks for now. This is too easy to use wrong, and too many layers of type wrapping.

**Comment by coryan** [comment]
Thanks, I will review when I get back to work tomorrow.

To be clear: I think we will want something *like* futures for asynchronous streaming reads, it is just that we are not ready for them yet.  What I am thinking about is something like RxCpp (which I believe you introduced me to), so application would be able to say things like:

```C++
Stream<Row> rows = table.AsyncReadRows(...);
// Call the lambda for each result and return a new stream, note that this is done asynchronously ...
Stream<Bar> bars = rows | transform([](Row r) -> Bar { ... });
// Aggregate the Bars into some kind of total
future<Total> final = bars | accumulate(Total{}, [](Total acc, Bar b) -> Total { ... });
final.then([](Total t) { std::cout << t << std::endl; });
```

But I do not think we have the time or the enough understanding of this stuff to design it correctly, so I am going with callbacks for now.

Somewhat unrelated, are you sure about that parallel version? "[Read] ..  should not be called concurrently with other streaming APIs on the same stream. It is not meaningful to call it concurrently with another AsyncReaderInterface::Read on the same stream since reads on the same stream are delivered in order."

https://grpc.github.io/grpc/cpp/classgrpc_1_1internal_1_1_async_reader_interface.html#adf87c602036d69158950b7299d0aae70

**Comment by dopiera** [comment]
> Somewhat unrelated, are you sure about that parallel version? "[Read] .. should not be called concurrently with other streaming APIs on the same stream. It is not meaningful to call it concurrently with another AsyncReaderInterface::Read on the same stream since reads on the same stream are delivered in order."
> 
This is only parallel row processing - not reading. The first two examples instruct gRPC to read more data only after the `future<>` returned by `Process()` is satisfied. The parallel example allows for `N` simultaneous `Process()` to run, but gRPC still gets only one `AsyncReaderInterface::Read()` at a time - this is implemented in `AsyncRowReader`.

**Comment by coryan** [comment]
Should we close this PR?

**Comment by coryan** [comment]
Closing in favor of #2701.

**Pull request closed without merging**
