### PR TITLE
feat: asynchronous waiting for connections

### PR DESCRIPTION
**Pull request by dopiera**
This PR implements support for using
`grpc::Channel::NotifyOnStateChange`. This is a prerequisite to avoiding
periodic latency spikes when channels are automatically closed (#5550).

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569)* status: all files reviewed, 8 unresolved discussions (waiting on @dopiera)

___
*[google/cloud/completion_queue.h, line 250 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNViVttBR0zHIg0wGeU:-MNViVttBR0zHIg0wGeV:bqk40bb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/completion_queue.h#L250)):*
> ```objc
>    *     -  otherwise with `false`
>    */
>   future<bool> AsyncWaitForConnectionStateChange(
> ```

Should this be `future<Status>` and then you can return `kDeadlineExceeded` for deadlines, and `kCancelled` when the completion queue is already shutdown (in which case `Notify(false)` is called).
___
*[google/cloud/completion_queue.h, line 253 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVgi4t1BHYV3KKA05z:-MNVgi4t1BHYV3KKA06-:b-4a7ffe) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/completion_queue.h#L253)):*
> ```objc
>       std::shared_ptr<grpc::Channel> channel,
>       std::chrono::system_clock::time_point deadline,
>       grpc_connectivity_state last_observed) {
> ```

Introducing a `gRPC` type here seems odd, doubly so as this is a type from the `"C"` API, not even the C++ API.

Can we simplify this to `AsyncWaitForConnected()` and only (a) go to sleep if the current state is *not* connected already, and (b) return a future that is satisfied when the connection succeeds?
___
*[google/cloud/completion_queue_test.cc, line 893 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNViycU2Yd_rfU4VXcL:-MNViycU2Yd_rfU4VXcM:b-dothfz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/completion_queue_test.cc#L893)):*
> ```cpp
>                           grpc::InsecureChannelCredentials());
> 
>   EXPECT_EQ(GRPC_CHANNEL_IDLE, channel->GetState(false));
> ```

That seems flaky?
___
*[google/cloud/completion_queue_test.cc, line 894 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVj7zV9A87fbVtrAyr:-MNVj7zV9A87fbVtrAys:b-v12xr2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/completion_queue_test.cc#L894)):*
> ```cpp
> 
>   EXPECT_EQ(GRPC_CHANNEL_IDLE, channel->GetState(false));
>   for (auto state = channel->GetState(true); state != GRPC_CHANNEL_READY;
> ```

Feels like every application will need to run this loop (asynchronously!) maybe it would be better to implement it as part of `Await()`?  I guess it could be an external helper too.
___
*[google/cloud/internal/completion_queue_impl.h, line 69 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVh7JhBVBpBlDtTHna:-MNVh7JhBVBpBlDtTHnb:blh4kc2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/internal/completion_queue_impl.h#L69)):*
> ```objc
>   virtual void RunAsync(std::unique_ptr<RunAsyncBase> function) = 0;
> 
>   /// Asynchronously wait for connection state change.
> ```

I am not sure this is needed.  You can create a `AsyncGrpcOperation` and then call `StartOperation()`, all from `google::cloud::CompletionQueue` without having to introduce a new virtual function to this class.
___
*[google/cloud/internal/default_completion_queue_impl.h, line 130 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVnWfG1tZ0G8zid21b:-MNVnWfG1tZ0G8zid21c:bsiiafi) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/internal/default_completion_queue_impl.h#L130)):*
> ```objc
>  * `FakeCompletionQueueImpl`.
>  */
> class AsyncConnectionStateChangeFuture : public internal::AsyncGrpcOperation {
> ```

Would it make sense to move this to its own header file?
___
*[google/cloud/internal/default_completion_queue_impl.cc, line 244 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVhdLl31vO-HUygX_a:-MNVhdLl31vO-HUygX_b:beqz5mg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/internal/default_completion_queue_impl.cc#L244)):*
> ```cpp
>     std::chrono::system_clock::time_point deadline,
>     grpc_connectivity_state last_observed) {
>   auto op = std::make_shared<AsyncConnectionStateChangeFuture>(
> ```

Note that all this code can live in `google::cloud::CompletionQueue::AsyncAwaitFor*()`. And because the `Start()` function is called through a `absl::FunctionRef` it should be fast too (not that we care that much).
___
*[google/cloud/testing_util/fake_completion_queue_impl.cc, line 129 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVi1nj7RwoyqpaV5IS:-MNVi1nj7RwoyqpaV5IT:b3xc3k1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/testing_util/fake_completion_queue_impl.cc#L129)):*
> ```cpp
>     grpc_connectivity_state last_observed) {
>   // There's nothing fake in this implementation, currently.
>   auto op = std::make_shared<internal::AsyncConnectionStateChangeFuture>(
> ```

Ditto, this function can be removed I think.

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @coryan)

___
*[google/cloud/completion_queue.h, line 250 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNViVttBR0zHIg0wGeU:-MNYUYC8-b4zWgZeFnkz:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/completion_queue.h#L250)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Should this be `future<Status>` and then you can return `kDeadlineExceeded` for deadlines, and `kCancelled` when the completion queue is already shutdown (in which case `Notify(false)` is called).
</blockquote></details>

Done.
___
*[google/cloud/completion_queue.h, line 253 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVgi4t1BHYV3KKA05z:-MNYU_5V8G75aKTmsIG4:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/completion_queue.h#L253)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Introducing a `gRPC` type here seems odd, doubly so as this is a type from the `"C"` API, not even the C++ API.

Can we simplify this to `AsyncWaitForConnected()` and only (a) go to sleep if the current state is *not* connected already, and (b) return a future that is satisfied when the connection succeeds?
</blockquote></details>

Done.
___
*[google/cloud/completion_queue_test.cc, line 893 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNViycU2Yd_rfU4VXcL:-MNYUa6X14SLkWemi7Hl:bds11l1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/completion_queue_test.cc#L893)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

That seems flaky?
</blockquote></details>

The connection on its own won't try to connect. Only `GetState(true)` or a method call will trigger an attempt.
___
*[google/cloud/completion_queue_test.cc, line 894 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVj7zV9A87fbVtrAyr:-MNYUkr39ffKcz6x4LRk:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/completion_queue_test.cc#L894)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Feels like every application will need to run this loop (asynchronously!) maybe it would be better to implement it as part of `Await()`?  I guess it could be an external helper too.
</blockquote></details>

Done.
___
*[google/cloud/internal/completion_queue_impl.h, line 69 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVh7JhBVBpBlDtTHna:-MNYUleP518uamMEJrBL:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/internal/completion_queue_impl.h#L69)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I am not sure this is needed.  You can create a `AsyncGrpcOperation` and then call `StartOperation()`, all from `google::cloud::CompletionQueue` without having to introduce a new virtual function to this class.
</blockquote></details>

Done.
___
*[google/cloud/internal/default_completion_queue_impl.h, line 130 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVnWfG1tZ0G8zid21b:-MNYUmP7001aJeiv3lvJ:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/internal/default_completion_queue_impl.h#L130)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Would it make sense to move this to its own header file?
</blockquote></details>

Done.
___
*[google/cloud/internal/default_completion_queue_impl.cc, line 244 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVhdLl31vO-HUygX_a:-MNYUqi68k7rhRXaSW-d:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/internal/default_completion_queue_impl.cc#L244)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Note that all this code can live in `google::cloud::CompletionQueue::AsyncAwaitFor*()`. And because the `Start()` function is called through a `absl::FunctionRef` it should be fast too (not that we care that much).
</blockquote></details>

Done.
___
*[google/cloud/testing_util/fake_completion_queue_impl.cc, line 129 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNVi1nj7RwoyqpaV5IS:-MNYUreNCRl60Dd5qq9-:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/testing_util/fake_completion_queue_impl.cc#L129)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Ditto, this function can be removed I think.
</blockquote></details>

Done.

**Review by coryan — CHANGES_REQUESTED** [review]
a couple of small nits below, but it is looking really good, thanks.

> Reviewed 12 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-:-MNYfhCVC3bVdz4zKkIF:b-rx6w7r)* status: all files reviewed, 2 unresolved discussions (waiting on @dopiera)

___
*[google/cloud/completion_queue.h, line 254 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNYeYl85SC8d8pigFhZ:-MNYeYl85SC8d8pigFh_:b-l9u1es) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/d790e7be6a6b897d2e111dacc8bbed457588e6da/google/cloud/completion_queue.h#L254)):*
> ```objc
>     impl_->StartOperation(op, [&](void* tag) { op->Start(impl_->cq(), tag); });
>     return op->GetFuture();
>     ;
> ```

extra semi?
___
*[google/cloud/completion_queue_test.cc, line 893 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNViycU2Yd_rfU4VXcL:-MNYeewtDAgxo3ypPPlw:be17u8d) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c73ebc7bfe9a2259ddb24f9820dc1ddb31569c82/google/cloud/completion_queue_test.cc#L893)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

The connection on its own won't try to connect. Only `GetState(true)` or a method call will trigger an attempt.
</blockquote></details>

Ack, thanks.
___
*[google/cloud/internal/async_connection_ready_test.cc, line 69 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNYeslWB1q9jQnZ3Ovc:-MNYeslWB1q9jQnZ3Ovd:bucdq63) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/d790e7be6a6b897d2e111dacc8bbed457588e6da/google/cloud/internal/async_connection_ready_test.cc#L69)):*
> ```cpp
>                           grpc::InsecureChannelCredentials());
> 
>   EXPECT_EQ(GRPC_CHANNEL_IDLE, channel->GetState(false));
> ```

Maybe add a comment, I now know that this is not flaky, future me (and others) may not know that.

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/completion_queue.h, line 254 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNYeYl85SC8d8pigFhZ:-MNYkPn8-bfYfDZRcZim:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/d790e7be6a6b897d2e111dacc8bbed457588e6da/google/cloud/completion_queue.h#L254)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

extra semi?
</blockquote></details>

Done.
___
*[google/cloud/internal/async_connection_ready_test.cc, line 69 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569#-MNYeslWB1q9jQnZ3Ovc:-MNYkWOdB9DGUhPG_DVn:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/d790e7be6a6b897d2e111dacc8bbed457588e6da/google/cloud/internal/async_connection_ready_test.cc#L69)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Maybe add a comment, I now know that this is not flaky, future me (and others) may not know that.
</blockquote></details>

Done.

**Review by coryan — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5569)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
