### PR TITLE
ci: cache vcpkg binary

### PR DESCRIPTION
**Pull request by devjgm**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816)

### CODE REVIEW

**Review by coryan — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816)* status: all files reviewed, 1 unresolved discussion (waiting on @devjgm)

___
*[ci/kokoro/docker/build-in-docker-quickstart-cmake.sh, line 51 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816#-MSnJUDDE6mDdbAOSoVT:-MSnJUDE1BXnMVb0rV1x:b67of95) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/429f0214519adbb5a614ade1125e021342705120/ci/kokoro/docker/build-in-docker-quickstart-cmake.sh#L51)):*
> ```Shell
>   | tar -C "${vcpkg_dir}" --strip-components=1 -zxf -
> 
> ${vcpkg_dir}/bootstrap-vcpkg.sh
> ```

FYI (no action needed), this takes like a minute or so to run, and since the vcpkg version is pinned to a SHA, we may want to consider caching the `vcpkg` binary too.
___
*[ci/kokoro/macos/build-quickstart-cmake.sh, line 31 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816#-MSnJvYr5Ba4Sqch188h:-MSnJvYr5Ba4Sqch188i:bef9n05) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/429f0214519adbb5a614ade1125e021342705120/ci/kokoro/macos/build-quickstart-cmake.sh#L31)):*
> ```Shell
> echo "Downloading vcpkg@${vcpkg_sha} into ${vcpkg_dir}..."
> mkdir -p "${vcpkg_dir}"
> curl -sSL "https://github.com/microsoft/vcpkg/archive/${vcpkg_sha}.tar.gz" \
> ```

We should make the analogous changes to the windows builds too?  If you want to wait for a future PR that is cool too.

**Comment by devjgm** [comment]
> > Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816)_ status: all files reviewed, 1 unresolved discussion (waiting on @devjgm)
> 
> _[ci/kokoro/docker/build-in-docker-quickstart-cmake.sh, line 51 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816#-MSnJUDDE6mDdbAOSoVT:-MSnJUDE1BXnMVb0rV1x:b67of95) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/429f0214519adbb5a614ade1125e021342705120/ci/kokoro/docker/build-in-docker-quickstart-cmake.sh#L51)):_
> 
> > ```shell
> >   | tar -C "${vcpkg_dir}" --strip-components=1 -zxf -
> > 
> > ${vcpkg_dir}/bootstrap-vcpkg.sh
> > ```
> 
> FYI (no action needed), this takes like a minute or so to run, and since the vcpkg version is pinned to a SHA, we may want to consider caching the `vcpkg` binary too.

Done.

> 
> _[ci/kokoro/macos/build-quickstart-cmake.sh, line 31 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816#-MSnJvYr5Ba4Sqch188h:-MSnJvYr5Ba4Sqch188i:bef9n05) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/429f0214519adbb5a614ade1125e021342705120/ci/kokoro/macos/build-quickstart-cmake.sh#L31)):_
> 
> > ```shell
> > echo "Downloading vcpkg@${vcpkg_sha} into ${vcpkg_dir}..."
> > mkdir -p "${vcpkg_dir}"
> > curl -sSL "https://github.com/microsoft/vcpkg/archive/${vcpkg_sha}.tar.gz" \
> > ```
> 
> We should make the analogous changes to the windows builds too? If you want to wait for a future PR that is cool too.

We should. Filed https://github.com/googleapis/google-cloud-cpp/issues/5818 so we don't forget.

**Comment by coryan** [comment]
___
*[ci/kokoro/macos/upload-cache.sh, line 47 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816#-MSnpOKi5rysZ9R_egid:-MSnpOKi5rysZ9R_egie:bm26ksf) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/403a71fb60a94efa5a75521a31cf0ac97a49f642/ci/kokoro/macos/upload-cache.sh#L47)):*
> ```Shell
> 
>   # This is where vcpkg caches its output.
>   "${HOME}/.cache"
> ```

FYI, I think  Bazel also stores stuff there, lots of stuff, I do not remember if it worked (or not) to cache it. It may make things slower?

**Review by coryan — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @devjgm)

**Comment by devjgm** [comment]
> _[ci/kokoro/macos/upload-cache.sh, line 47 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816#-MSnpOKi5rysZ9R_egid:-MSnpOKi5rysZ9R_egie:bm26ksf) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/403a71fb60a94efa5a75521a31cf0ac97a49f642/ci/kokoro/macos/upload-cache.sh#L47)):_
> 
> > ```shell
> >   # This is where vcpkg caches its output.
> >   "${HOME}/.cache"
> > ```
> 
> FYI, I think Bazel also stores stuff there, lots of stuff, I do not remember if it worked (or not) to cache it. It may make things slower?

Per our chats offline:

* We weren't sure originally, but we discovered that bazel does not cache in `~/.cache`. 
* I did not test these macos "quickstart-cmake" scripts, and our CI+presubmit builds are disabled for this.
* I updated these files to match the Linux builds (which I did test) only because they visually looked to be doing the same thing. But I could revert these macos changes.

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5816#-:-MSoBCO68PnzMdcAp6fm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
