### PR TITLE
feat(bigtable): Bind CompletionQueue with Table

### PR DESCRIPTION
**Pull request by dopiera**
This is a part of #2567 and a continuation of #5967 and #6004.

This change is a part of the removal of the `CompletionQueue` argument
from all `Table::Async*` calls. Instead, `CompletionQueue` will have to
be bound with the `Table` object. Current `Table::Async*` member
functions have been deprecated and overrides without the
`CompletionQueue` have been added.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012)

### CODE REVIEW

**Comment by coryan** [comment]
Hey, thanks for sending these changes.  We are getting a lot more careful about breaking changes, even about experimental APIs like this.  I think we should make this in two steps:

**Step 1:**

- First add all the new member functions (i.e., without the `cq` parameter), moving the examples and tests to use them.
- These functions should just call the existing functions (or maybe some `Async*Impl()` functions if we need to avoid warnings.
- Mark the existing member functions as deprecated, using something like this (but the date should be `2021-07-01`):

https://github.com/googleapis/google-cloud-cpp/blob/a68f32d679b560dccbfec49ec8243daeac31a27d/google/cloud/bigtable/version.h#L23-L26

- Note that using these functions in our code (as described above) might trigger warnings. If it does, we need to refactor the body to a `Async*Impl` private member function.

**Step 2:**

- Remove the deprecated functions.

**Comment by dopiera** [comment]
> Hey, thanks for sending these changes. We are getting a lot more careful about breaking changes, even about experimental APIs like this. I think we should make this in two steps:

Done

**Review by coryan — CHANGES_REQUESTED** [review]
Generally looking really good.  There seems to be some debugging code leftover (see below).

> Reviewed 34 of 34 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012#-:-MVOYURH6cuXTe5GLtqt:bymiuu5)* status: all files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc, line 192 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012#-MVOUf6c2OmR3SOe3Ayo:-MVOUf6c2OmR3SOe3Ayp:byc34df) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b6ab56280d8e04254c3fc0df50d097021d7c5c07/google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc#L192)):*
> ```cpp
>       async_benchmark.Run(setup->test_duration(),
>                           setup->thread_count() * setup->parallel_requests());
>   std::cout << "ASYNC COMPLETE" << std::endl << std::flush;
> ```

This seems like debugging remnants? Also, `std::endl` flushes.
___
*[google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc, line 211 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012#-MVOUmyu9zT1otwER5z1:-MVOUmyu9zT1otwER5z2:bs4q9op) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b6ab56280d8e04254c3fc0df50d097021d7c5c07/google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc#L211)):*
> ```cpp
>     ++count;
>   }
>   std::cout << "SYNC COMPLETE" << std::endl << std::flush;
> ```

Ditto.
___
*[google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc, line 232 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012#-MVOUo7M32YM8HDbc8ez:-MVOUo7M32YM8HDbc8f-:brhumzt) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b6ab56280d8e04254c3fc0df50d097021d7c5c07/google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc#L232)):*
> ```cpp
>   benchmark.DeleteTable();
> 
>   std::cout << "EXITING" << std::endl << std::flush;
> ```

Same here.
___
*[google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc, line 266 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012#-MVOUvy8DKegaPAhyVva:-MVOUvy8DKegaPAhyVvb:bb7hf91) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b6ab56280d8e04254c3fc0df50d097021d7c5c07/google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc#L266)):*
> ```cpp
> 
>   auto request_start = std::chrono::steady_clock::now();
>   std::cout << "RUN" << std::endl << std::flush;
> ```

here
___
*[google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc, line 285 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012#-MVOUwoY6pVAyPIeHi-_:-MVOUwoY6pVAyPIeHi-a:bji28bi) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b6ab56280d8e04254c3fc0df50d097021d7c5c07/google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc#L285)):*
> ```cpp
>   std::unique_lock<std::mutex> lk(mu_);
>   outstanding_requests_--;
>   std::cout << "COMPLETED, LEFT=" << outstanding_requests_ << std::endl
> ```

and here

**Review by coryan — CHANGES_REQUESTED** [review]
Looking good, one question (which I think I know the answer to),  and the builds passing and we are good to go.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012#-:-MVOr_6u9NOHVa87O4Vq:bf45jnj)* status: all files reviewed, 1 unresolved discussion (waiting on @dopiera)

___
*[ci/test-abi/google_cloud_cpp_bigtable.expected.abi.dump.gz, line 0 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012#-MVOrKTa7aahmnm5XSxd:-MVOrKTa7aahmnm5XSxe:bz05s5u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/3335020c18a647a1b0e070e2202d4a18688a0b13/ci/test-abi/google_cloud_cpp_bigtable.expected.abi.dump.gz#L0)):*
This is just because the `AsyncBulkApplyImpl()` correct?  I would not expect any other changes needed.

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012)* status: all files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[ci/test-abi/google_cloud_cpp_bigtable.expected.abi.dump.gz, line  at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012#-MVOrKTa7aahmnm5XSxd:-MVQgo649jyn89zIBvfW:b-l7hazn) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/3335020c18a647a1b0e070e2202d4a18688a0b13/ci/test-abi/google_cloud_cpp_bigtable.expected.abi.dump.gz#L)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is just because the `AsyncBulkApplyImpl()` correct?  I would not expect any other changes needed.
</blockquote></details>

Precisely.
Here are `check-abi` logs, which show it (from a run where the ABI dump was not updated):
https://source.cloud.google.com/results/invocations/a7c6d91e-3e4c-4b2d-bb47-1e4356a35ce3/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fcheck-abi-presubmit/log

**Review by coryan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6012#-:-MVQvrpo8dbO0EJDvdJy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dopiera)

**Comment by coryan** [comment]
Thanks again, this is really cool.

**Pull request merged**
