### PR TITLE
Create an example listing objects with a prefix.

### LINKED ISSUE #2178: Create an example listing objects with a prefix.
We want an example that lists all the objects with a given prefix.  This is probably similar to:

https://github.com/googleapis/google-cloud-cpp/blob/52b8e180b617452e088bd1ecfd162041a2391465/google/cloud/storage/examples/storage_object_samples.cc#L50

The region tags should be `storage_list_files_with_prefix`.

### PR DESCRIPTION
**Pull request by remyabel**
Fixes #2178

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2183)

### CODE REVIEW

**Comment by remyabel** [comment]
`delete-object` doesn't seem to properly handle prefixes:

```
127.0.0.1 - - [09/Mar/2019:02:09:40 +0000] "POST /upload/storage/v1/b/fake-bucket-1552097379-742/o?uploadType=multipart&name=prefix-1552097380-4014%2Fobject-1.txt HTTP/1.1" 200 2314 "-" "gcs-c++/v0.6.0+076964cc ex Clang 6.0.0 libcurl/7.60.0 OpenSSL/1.1.0g zlib/1.2.11 c-ares/1.14.0"
127.0.0.1 - - [09/Mar/2019:02:09:40 +0000] "GET /storage/v1/b/fake-bucket-1552097379-742/o?prefix=prefix-1552097380-4014&pageToken= HTTP/1.1" 200 4558 "-" "gcs-c++/v0.6.0+076964cc ex Clang 6.0.0 libcurl/7.60.0 OpenSSL/1.1.0g zlib/1.2.11 c-ares/1.14.0"
```

No problem here. Then:

```
127.0.0.1 - - [09/Mar/2019:02:09:40 +0000] "DELETE /storage/v1/b/fake-bucket-1552097379-742/o/prefix-1552097380-4014%2Fobject-1.txt HTTP/1.1" 404 233 "-" "gcs-c++/v0.6.0+076964cc ex Clang 6.0.0 libcurl/7.60.0 OpenSSL/1.1.0g zlib/1.2.11 c-ares/1.14.0"
```

Returns a 404.

**Comment by coryan** [comment]
`delete-object` can only delete specific objects. There is no API in GCS to delete all the objects that match a prefix.

**Comment by coryan** [comment]
Oh, I see now... my bad.
Probably the testbench is not handling URL-escaped names properly. Let me take a look.

**Comment by remyabel** [comment]
> Probably the testbench is not handling URL-escaped names properly. Let me take a look.

This looks like a Flask/werkzeug issue: https://github.com/pallets/flask/issues/900

**Pull request merged**
