### PR TITLE
fix(common): use 64-bit API on Windows to get file sizes

### PR DESCRIPTION
**Pull request by HoraceBianchon**
For files with a size bigger than 2GB (32bit unsigned integer's max value) calculation based on the "::stat" function doesn't work correctly on the Windows operation systems. 
I replaced the "::stat" function with "::stat64". For more details on the "::stat", please see link below

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=msvc-170

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11906)

### CODE REVIEW

**Comment by coryan** [comment]
Thanks for the PR!  I made some changes to fit our coding style, I hope you don't mind.

**Comment by coryan** [comment]
The changes look good, but we do need you to sign the CLA when you have a chance.

**Comment by coryan** [comment]
@HoraceBianchon at this point we are waiting for you to sign the CLA, once you do I will enable the builds again.  There is no need to rebase or merge the changes from `main`.

**Comment by HoraceBianchon** [comment]
> The changes look good, but we do need you to sign the CLA when you have a chance.

I, mistakenly, committed with my corporate email. 
And, now, I can't pass that signing.

**Comment by coryan** [comment]
I requested an override and it was granted. Yay! 🎉   Now we wait for the builds to finish.

Thanks again for your contribution.

**Comment by HoraceBianchon** [comment]
Thanks

**Review by coryan — APPROVED** [review]

**Pull request merged**
