### PR TITLE
impl(bigquery): Job benchmark program

### PR DESCRIPTION
**Pull request by jsrinnn**
This PR includes the following changes

1) A Job benchmark program that runs the ListJobs and GetJob apis end to end based on input parameters 
and prints latency and throughput results. See the Project benchmark program output here: https://paste.googleplex.com/4967864862769152

2) Modified benchmark loops for all benchmarks to not flush every line. This was a feedback requested in the previous PR.

2) I have divided the job benchmarks as read-only and mutating as these are different apis and testing them all as one benchmark makes them super complicated. I may further divide the mutating benchmarks depending on the complexity.

3) Fixed the following issues related to parsing of json Job response, as exposed by benchmark tests:
   a) Modified inputStages field to be string as it can be alphanumeric
   b) Fixed enum parsing for Job objects
   c) Fixed 64-bit integer parsing in the json response
   
4) Fixed enum parsing for other resources (dataset, Table) as well based on how they are being returned from the server.

5) Modified all unit tests related to the fixes above.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12709)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12709)* status: all files reviewed, 2 unresolved discussions (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 132 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12709#-Nf1HVyI5eMhPffUd1yI:-Nf1HVyI5eMhPffUd1yJ:b-6g9isp) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/315cc8bc9eae172edb00667382bfc0e13a1f84a4/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L132)):*
> ```cpp
>                 << "\nNumber of ListDatasets operations performed thus far= "
>                 << result.list_results.operations.size() << "\n...\n"
>                 << std::flush;
> ```

nit:  `"\n" << std::flush` is the same as `<< std::endl`.  With that said, whatever is clearer for you and @devbww  is fine with me.

I think the objection wasn't that the code used `std::endl`, but that the code used `std::endl` in quick succession.  Something like `<< std::endl .... << std::endl; std::cout ... << std::endl;` which flushes multiple times.
___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc` line 106 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12709#-Nf1Iisl2qbjuZB3FM6j:-Nf1Iisl2qbjuZB3FM6k:bp7ylcj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/315cc8bc9eae172edb00667382bfc0e13a1f84a4/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc#L106)):*
> ```cpp
> 
>     void operator()(absl::monostate const&) {
>       j = nlohmann::json{{"typeKind", std::move(type_kind.value)}};
> ```

I find it confusing to fix bugs in the code and update the benchmarks in the same PR.  I appreciate that the benchmarks are showing you what needs fixing, but we should be more disciplined about keeping PRs focused.

It should be easy to separate these changes, something like:

```
git checkout $current_branch
git checkout -b library-only
git checkout origin/main -- google/cloud/bigquery/v2/minimal/benchmarks/
git commit --amend -m"fix(bigquery): fix expected data types" # change the message as needed
git rebase -i origin/main # If you want to merge all the changes into a single commit
```

That should leave you with a branch that only has the library changes.  Then you can rebase the existing branch to remove the other changes:

```
git checkout $current_branch
git rebase -i library-only
```

**Review by devbww — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12709)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan and @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 132 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12709#-Nf1HVyI5eMhPffUd1yI:-Nf8TUug-i_sC3iFUoQg:bea4aq0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/315cc8bc9eae172edb00667382bfc0e13a1f84a4/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L132)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit:  `"\n" << std::flush` is the same as `<< std::endl`.  With that said, whatever is clearer for you and @devbww  is fine with me.

I think the objection wasn't that the code used `std::endl`, but that the code used `std::endl` in quick succession.  Something like `<< std::endl .... << std::endl; std::cout ... << std::endl;` which flushes multiple times.
</blockquote></details>

For what it's worth, I'd say that I prefer this clear separation of `\n` and `std::flush` (i.e., that `std::endl` isn't worth the confusion it seems to carry).

**Review by jsrinnn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12709)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan and @devbww)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 132 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12709#-Nf1HVyI5eMhPffUd1yI:-NfBZvp7BDg8TseV4ccK:b-2jcal7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/315cc8bc9eae172edb00667382bfc0e13a1f84a4/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L132)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

For what it's worth, I'd say that I prefer this clear separation of `\n` and `std::flush` (i.e., that `std::endl` isn't worth the confusion it seems to carry).
</blockquote></details>

ah...got it. I was initially under the same understanding as well but thought maybe I misunderstood.

Thank you for the clarification. 
___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc` line 106 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12709#-Nf1Iisl2qbjuZB3FM6j:-NfB_L_k93P2uaLh0vlK:b-r10wi8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/315cc8bc9eae172edb00667382bfc0e13a1f84a4/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc#L106)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I find it confusing to fix bugs in the code and update the benchmarks in the same PR.  I appreciate that the benchmarks are showing you what needs fixing, but we should be more disciplined about keeping PRs focused.

It should be easy to separate these changes, something like:

```
git checkout $current_branch
git checkout -b library-only
git checkout origin/main -- google/cloud/bigquery/v2/minimal/benchmarks/
git commit --amend -m"fix(bigquery): fix expected data types" # change the message as needed
git rebase -i origin/main # If you want to merge all the changes into a single commit
```

That should leave you with a branch that only has the library changes.  Then you can rebase the existing branch to remove the other changes:

```
git checkout $current_branch
git rebase -i library-only
```
</blockquote></details>

The problem is the benchmark won't work without the library fixes which is why I had included them both but I also understand the review becomes difficult. 

Let me try to make the changes so the the current pr is library only fixes and then send a separate PR for the benchmarks.

**Review by jsrinnn — COMMENTED** [review]
This PR has been modified to only contain the library fixes. I need to submit this first so I can re-test the benchmark programs with these fixes.

Carlos, can you PTAL please? Thank You!

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12709#-:-NfBq1dnDrKtiMgji6tv:b-20zm8n)* status: 16 of 24 files reviewed, 2 unresolved discussions (waiting on @coryan and @devbww)

**Pull request merged**
