### PR TITLE
doc(api-support): document API support guarantees

### PR DESCRIPTION
**Pull request by devjgm**
Fixes: #3847

Preview: https://github.com/devjgm/google-cloud-cpp/blob/api-support/README.md

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
Thanks for taking the initiative to write this. Sorry for the (unavoidable?) nit picking.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-:-MNV3EAS0uUIRofVUOsd:b-y8mmed)* status: all files reviewed, 6 unresolved discussions (waiting on @devjgm)

___
*[ci/generate-markdown/generate-readme.sh, line 138 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNUyaXm1QKlkZCLn1lv:-MNUyaXm1QKlkZCLn1lw:bcilsm1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L138)):*
> ```Shell
> By "API" we mean the C++ API exposed by public header files in this repo. We
> are not talking about the gRPC or REST APIs exposed by Google Cloud servers. We
> are also talking only about A**P**I stability -- We make NO PROMISES about
> ```

s/We make/we make/ ?

More explicitly: "-- the A**B**I is subject to change without notice.  You should not assume that binary artifacts (e.g. static libraries, shared objects, dynamically loaded libraries, object files) created with one version of the library are usable with newer and/or older versions of the library.  The ABI may, and does, change on "minor revisions". The ABI may even change with a patch release".
___
*[ci/generate-markdown/generate-readme.sh, line 143 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNUzSv41FAeJ9YOBGs_:-MNUzSv41FAeJ9YOBGsa:bc9dcm1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L143)):*
> ```Shell
> 
> In order for us to provide this level of API support, we ask that our customers
> understand some basic points.
> ```

That sounds slightly like talking down to our customers.  Maybe something like:

```
We request that our customers adhere to the following guidelines to avoid accidentally depending on parts of the library we do not consider to be part of the public APIs:

- You should only include headers matching the `google/cloud/${library}/*.h`, `google/cloud/${library}/mock/*.h` or `google/cloud/*.h` patterns.
- You should **NOT** directly include headers in any subdirectories, such as `google/cloud/${library}/internal`
"

Note that I added `${library}/mock/*.h` to that list, I think that was our intention.
```

___
*[ci/generate-markdown/generate-readme.sh, line 148 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV-nzXAdZSX1pKSYpR:-MNV-nzYBQgmNNK_-X0g:b7z942p) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L148)):*
> ```Shell
>   `google/cloud/${library}/*.h`.
> * There are also some public API "common" headers at `google/cloud/*.h`.
> * The files *included from* our public headers are **not part of our public
> ```

This is tricky... How are customers supposed to know where all the different symbols are defined?  It is virtually impossible for them to adhere to this rule.  Maybe just describe the problem:

```
* For any symbol that you use, you should directly include the headers that define this symbol (this is sometimes known as include-what-you-use [link here].)  Depending on indirect includes may break your build in the future, as we may change a header "foo.h" to stop including "bar.h" if "foo.h" no longer needs the symbols in "bar.h", but we cannot fix your code at the same time.
```
___
*[ci/generate-markdown/generate-readme.sh, line 153 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV0Cgt6TKYEka1QTxZ:-MNV0Cgt6TKYEka1QTx_:b-yjmetm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L153)):*
> ```Shell
> * Any file or symbol that lives within a directory or namespace named
>   "internal", "test(s)", "testing", "detail", "benchmark(s)", "sample(s)",
>   "example(s)", are **not part of our public API**.
> ```

maybe "are **not part of our public API**. They are subject to change (including removal) without notice."  I am getting repetitive, so maybe refactor that "subject to change blah blah" to the top?
___
*[ci/generate-markdown/generate-readme.sh, line 154 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV0PqEDG_MF7Fvy76A:-MNV0PqEDG_MF7Fvy76B:b-73e19l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L154)):*
> ```Shell
>   "internal", "test(s)", "testing", "detail", "benchmark(s)", "sample(s)",
>   "example(s)", are **not part of our public API**.
> * Any file or symbol with "Impl" or "impl" in name is **not part of our
> ```

I had not thought about these, sounds fine.
___
*[ci/generate-markdown/generate-readme.sh, line 157 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV0VZN7eClQd6HegaF:-MNV0VZN7eClQd6HegaG:brhqeo6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L157)):*
> ```Shell
>   public API**.
> 
> Note that this document has no bearing on the Google Cloud Platform deprecation
> ```

Maybe add something about how the previous versions of the library remain available from GitHub?

**Review by scotthart — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564)* status: all files reviewed, 7 unresolved discussions (waiting on @devjgm)

___
*[ci/generate-markdown/generate-readme.sh, line 130 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV8NyyBaiMS4uUt2P1:-MNV8Nyz1ph0E_srbhXu:botanpz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L130)):*
> ```
> and/or more consistent APIs across services. When these benefits warrant it, we
> will announce these changes prominently in our `CHANGELOG.md` file and in the
> affected release's notes. Nevertheless, though we take commercially reasonable
> ```
Do we want to also uprev the major release number? 
Also, will we provide bug fixes for the old API for some N period of time?

**Review by devjgm — COMMENTED** [review]
No problem. Nitpicking on something like this is highly desired! :-) 

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-:-MNZ1KtN9JV3CmWMOobu:b-a8p6jb)* status: all files reviewed, 7 unresolved discussions (waiting on @coryan and @scotthart)

___
*[ci/generate-markdown/generate-readme.sh, line 130 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV8NyyBaiMS4uUt2P1:-MNZ7Et1ArqSyXkHHGC4:b3j216) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L130)):*
Good questions.

I can imagine major API changes where we bump the major version, but I'm not sure we want to bump it on "small" API breaks. We explicitly [do not follow semantic versioning](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/spanner/README.md#google-cloud-spanner-c-client-library)... but it looks like we sorta do. 

So I'm not sure if/what to say about major version bumps. Suggested wording?

> Also, will we provide bug fixes for the old API for some N period of time?

Hmm. We probably should say something about that. We may want to check w/ other client library teams and see what the standard policy is. I may split this out to a separate issue, if you agree.
___
*[ci/generate-markdown/generate-readme.sh, line 138 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNUyaXm1QKlkZCLn1lv:-MNZ1QXq8ySGZMWPlzb7:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L138)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

s/We make/we make/ ?

More explicitly: "-- the A**B**I is subject to change without notice.  You should not assume that binary artifacts (e.g. static libraries, shared objects, dynamically loaded libraries, object files) created with one version of the library are usable with newer and/or older versions of the library.  The ABI may, and does, change on "minor revisions". The ABI may even change with a patch release".

</blockquote></details>

Done.
___
*[ci/generate-markdown/generate-readme.sh, line 143 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNUzSv41FAeJ9YOBGs_:-MNZ1RLh66UDQ3avTWFf:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L143)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

That sounds slightly like talking down to our customers.  Maybe something like:

```
We request that our customers adhere to the following guidelines to avoid accidentally depending on parts of the library we do not consider to be part of the public APIs:

- You should only include headers matching the `google/cloud/${library}/*.h`, `google/cloud/${library}/mock/*.h` or `google/cloud/*.h` patterns.
- You should **NOT** directly include headers in any subdirectories, such as `google/cloud/${library}/internal`
"

Note that I added `${library}/mock/*.h` to that list, I think that was our intention.
</blockquote></details>

Done.
___
*[ci/generate-markdown/generate-readme.sh, line 148 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV-nzXAdZSX1pKSYpR:-MNZ4Uzz1BUjcWm__cT4:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L148)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is tricky... How are customers supposed to know where all the different symbols are defined?  It is virtually impossible for them to adhere to this rule.  Maybe just describe the problem:

```
* For any symbol that you use, you should directly include the headers that define this symbol (this is sometimes known as include-what-you-use [link here].)  Depending on indirect includes may break your build in the future, as we may change a header "foo.h" to stop including "bar.h" if "foo.h" no longer needs the symbols in "bar.h", but we cannot fix your code at the same time.
```

</blockquote></details>

Done.
___
*[ci/generate-markdown/generate-readme.sh, line 153 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV0Cgt6TKYEka1QTxZ:-MNZ5SQZ5vE1JBxEDKKC:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L153)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

maybe "are **not part of our public API**. They are subject to change (including removal) without notice."  I am getting repetitive, so maybe refactor that "subject to change blah blah" to the top?
</blockquote></details>

Done.
___
*[ci/generate-markdown/generate-readme.sh, line 154 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV0PqEDG_MF7Fvy76A:-MNZ5TVT7aBLGCljkluk:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L154)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I had not thought about these, sounds fine.
</blockquote></details>

Done.
___
*[ci/generate-markdown/generate-readme.sh, line 157 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV0VZN7eClQd6HegaF:-MNZ61Uw3KOY8Bv6CYLd:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L157)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Maybe add something about how the previous versions of the library remain available from GitHub?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-:-MNZDKQ861b6ZmaqJhzw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[ci/generate-markdown/generate-readme.sh, line 130 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV8NyyBaiMS4uUt2P1:-MNZANTA8WpsbYYNCNx5:b-5g1krw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L130)):*
>> Also, will we provide bug fixes for the old API for some N period of time?
> 
> Hmm. We probably should say something about that. We may want to check w/ other client library teams and see what the standard policy is.

AFAIK, none of the other libraries apply bug fixes or feature changes to previous versions, not even when they manage to follow semver.

**Review by devjgm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564)* status: all files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[ci/generate-markdown/generate-readme.sh, line 130 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564#-MNV8NyyBaiMS4uUt2P1:-MNZXgp43o4emUTKn1a2:b-13v5bw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76e91c4fabf428db2c66cc1ccf26cab78592c2e5/ci/generate-markdown/generate-readme.sh#L130)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

>> Also, will we provide bug fixes for the old API for some N period of time?
> 
> Hmm. We probably should say something about that. We may want to check w/ other client library teams and see what the standard policy is.

AFAIK, none of the other libraries apply bug fixes or feature changes to previous versions, not even when they manage to follow semver.

</blockquote></details>

Justin just confirmed that they only support the latest release. They've looked into it and the cost of supporting previous releases is astronomical and they just can't justify it.

**Review by scotthart — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5564)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
