### PR TITLE
feat: prepare for breaking change in Protobuf C++ API.

### PR DESCRIPTION
**Pull request by evalon32**
Protobuf 6.30.0 will change the return types of Descriptor::name() and other methods to absl::string_view. This makes the code work both before and after such a change.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14828)

### CODE REVIEW

**Review by scotthart — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14828)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @evalon32)

___
*[`google/cloud/spanner/internal/status_utils.cc` line 19 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14828#-OB6ONY99lT217sQwdK8:-OB6ONY99lT217sQwdK9:be0nmin) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/388dddb2be28e62d33181b8e610312b047b9f619/google/cloud/spanner/internal/status_utils.cc#L19)):*
> ```cpp
> #include "google/cloud/internal/status_payload_keys.h"
> #include "absl/strings/match.h"
> #include "absl/strings/str_cat.h"
> ```

Please use our wrapper for this header "google/cloud/internal/absl_str_cat_quiet.h"
___
*[`google/cloud/spanner/testing/status_utils.cc` line 17 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14828#-OB6O_B5BPwiohB5XpZw:-OB6O_B65MCfaEUb9mns:be0nmin) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/388dddb2be28e62d33181b8e610312b047b9f619/google/cloud/spanner/testing/status_utils.cc#L17)):*
> ```cpp
> #include "google/cloud/spanner/testing/status_utils.h"
> #include "google/cloud/grpc_error_delegate.h"
> #include "absl/strings/str_cat.h"
> ```

Please use our wrapper for this header "google/cloud/internal/absl_str_cat_quiet.h"

**Review by evalon32 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14828)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @scotthart)

___
*[`google/cloud/spanner/internal/status_utils.cc` line 19 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14828#-OB6ONY99lT217sQwdK8:-OB6Y7HUCbVoc1M8f_1E:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/388dddb2be28e62d33181b8e610312b047b9f619/google/cloud/spanner/internal/status_utils.cc#L19)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Please use our wrapper for this header "google/cloud/internal/absl_str_cat_quiet.h"
</blockquote></details>

Done.
___
*[`google/cloud/spanner/testing/status_utils.cc` line 17 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14828#-OB6O_B5BPwiohB5XpZw:-OB6Y8MEBCq7-CFHzyWL:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/388dddb2be28e62d33181b8e610312b047b9f619/google/cloud/spanner/testing/status_utils.cc#L17)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Please use our wrapper for this header "google/cloud/internal/absl_str_cat_quiet.h"
</blockquote></details>

Done.

**Comment by scotthart** [comment]
We're going to wait on merging these changed until we are closer to updating our dependencies to include protobuf v30.

**Review by scotthart — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14828)* status: all files reviewed, 2 unresolved discussions (waiting on @evalon32)

**Pull request merged**
