### PR TITLE
cleanup(storage): Factor out test constants into common location

### PR DESCRIPTION
**Pull request by remyabel**
Fixes: #3022

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5459)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
Thanks for the changes. A bunch of nit picky things below, and then a request to not move the functions if they are not shared across tests? +kokoro:run 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5459#-:-MLmKz9eDyys-N6dR4hY:b2kjn08)* status: all files reviewed, 2 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/storage/testing/constants.h, line 30 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5459#-MLmKHbG-_ExcsD1rpq4:-MLmKHbH4jmbBj7O70jT:blnhszg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1280700e09acc331fe8fb59f228574cab0baa3e8/google/cloud/storage/testing/constants.h#L30)):*
> ```objc
>  */
> 
> constexpr char kAltScopeForTest[] =
> ```

I know you are just moving code, but the project is "East Const", these should be:

```cc
char constexpr kAltScopeForTest[] = ...
```

or nowadays we write

```cc
auto constexpr kAltScopeForTest = ...
```
___
*[google/cloud/storage/testing/constants.h, line 199 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5459#-MLmK_VO2gfJq05cq8UA:-MLmK_VO2gfJq05cq8UB:bt6fmnp) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1280700e09acc331fe8fb59f228574cab0baa3e8/google/cloud/storage/testing/constants.h#L199)):*
> ```objc
> //@}
> 
> //@{
> ```

Can we move the functions to the top?  They seem more important.  They also seem slightly out of place in a `constants.h` file?  Are these functions used in more than one file?  If not, maybe they can stay where they were?

**Comment by remyabel** [comment]
> Can we move the functions to the top? They seem more important. They also seem slightly out of place in a constants.h file? Are these functions used in more than one file? If not, maybe they can stay where they were?

I'll put `Dec64` back but `WriteBase64AsBinary` is used in multiple tests. Where you recommend I put it instead of `constants.h`?

**Comment by coryan** [comment]
Sorry, I have been a bit distracted today.

> > Can we move the functions to the top? They seem more important. They also seem slightly out of place in a constants.h file? Are these functions used in more than one file? If not, maybe they can stay where they were?
> 
> I'll put `Dec64` back

Thanks.

> but `WriteBase64AsBinary` is used in multiple tests. Where you recommend I put it instead of `constants.h`?

The first answer I can think of is its own file, e.g., `storage/testing/write_base64.{h,cc}`. Another possibility is `storage/testing/storage_integration_test.{h,cc}`.

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5459)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/storage/testing/constants.h, line 30 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5459#-MLmKHbG-_ExcsD1rpq4:-MLos0WYCTRO_ztB_S3n:b-4q72dy) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1280700e09acc331fe8fb59f228574cab0baa3e8/google/cloud/storage/testing/constants.h#L30)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I know you are just moving code, but the project is "East Const", these should be:

```cc
char constexpr kAltScopeForTest[] = ...
```

or nowadays we write

```cc
auto constexpr kAltScopeForTest = ...
```

</blockquote></details>

Done. I redid the PR to make the changes more minimal. Sorry for the force push.
___
*[google/cloud/storage/testing/constants.h, line 199 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5459#-MLmK_VO2gfJq05cq8UA:-MLorxZR00rR6CLuib7N:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1280700e09acc331fe8fb59f228574cab0baa3e8/google/cloud/storage/testing/constants.h#L199)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Can we move the functions to the top?  They seem more important.  They also seem slightly out of place in a `constants.h` file?  Are these functions used in more than one file?  If not, maybe they can stay where they were?
</blockquote></details>

Done.

**Review by coryan — COMMENTED** [review]
Looking good, I will probably make another pass tomorrow, but let's get the builds going +kokoro:run 

> Reviewed 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5459#-:-MLoyMKUCeem1g0VfwGN:bzagb3x)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — APPROVED** [review]
:lgtm: thanks!

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5459#-:-MLraC31A_kmhZr99UJr:brfqlux)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
