### PR TITLE
cleanup(generator): parse api version from url pattern

### PR DESCRIPTION
**Pull request by cuiy0006**
Parse api version from url pattern instead of package name.

In some cases, api version doesn't exist in the package name.

This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14595)

### CODE REVIEW

**Review by scotthart — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14595)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @cuiy0006)

___
*[`generator/internal/http_option_utils.cc` line 402 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14595#-O394D_pC3Nzi_tMhzrV:-O394D_pC3Nzi_tMhzrW:b-31uszu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/0ccc9a5d41e8c208fb578e8df9d939332213df98/generator/internal/http_option_utils.cc#L402)):*
> ```cpp
>                                            std::string const& file_name) {
>   std::vector<std::string> parts = absl::StrSplit(url_pattern, '/');
>   std::regex re{R"(v\d+)"};
> ```

use `static std::regex const`

So that the regex only gets built once.



_Code quote:_
```cpp
std::regex
```

**Review by cuiy0006 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14595)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[`generator/internal/http_option_utils.cc` line 402 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14595#-O394D_pC3Nzi_tMhzrV:-O39WCI42xIy60AiY-_7:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/0ccc9a5d41e8c208fb578e8df9d939332213df98/generator/internal/http_option_utils.cc#L402)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

use `static std::regex const`

So that the regex only gets built once.
</blockquote></details>

Done.

**Review by scotthart — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14595)* status: all files reviewed, 1 unresolved discussion (waiting on @cuiy0006)

**Review by dbolduc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14595)* status: all files reviewed, 1 unresolved discussion

___
*[`generator/internal/http_option_utils.cc` line 402 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14595#-O394D_pC3Nzi_tMhzrV:-O39ZNTT3X7G6hVm16ze:bfc1oq0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/0ccc9a5d41e8c208fb578e8df9d939332213df98/generator/internal/http_option_utils.cc#L402)):*
<details><summary><i>Previously, cuiy0006 (Yao Cui) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`std::is_trivially_destructible_v<std::regex> == false`, and Google style guide says anything used for static storage must be trivially destructible, so technically we should say:

```cc
 static auto const* const kVersion = new std::regex{R"(v\d+)"};
```

**Comment by cuiy0006** [comment]
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14595)_ status: all files reviewed, 1 unresolved discussion
> 
> _[`generator/internal/http_option_utils.cc` line 402 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14595#-O394D_pC3Nzi_tMhzrV:-O39ZNTT3X7G6hVm16ze:bfc1oq0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/0ccc9a5d41e8c208fb578e8df9d939332213df98/generator/internal/http_option_utils.cc#L402)):_
> 
> Previously, cuiy0006 (Yao Cui) wrote…
> > Done.
> 
> `std::is_trivially_destructible_v<std::regex> == false`, and Google style guide says anything used for static storage must be trivially destructible, so technically we should say:
> 
> ```c++
>  static auto const* const kVersion = new std::regex{R"(v\d+)"};
> ```

I made a followup pr to fix. https://github.com/googleapis/google-cloud-cpp/pull/14599

**Pull request merged**
