### PR TITLE
refactor(rest): separate reusable log functions

### PR DESCRIPTION
**Pull request by scotthart**
Part of the work for #10037 

While using REST transport requires proto support, it does not need grpc support. This PR separates the proto specific pieces that the REST logging decorators will require. `rest_log_wrapper.h` will be added in a later PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10040)

### CODE REVIEW

**Comment by coryan** [comment]
> While using REST transport requires proto support, it does not need grpc support. This PR separates the proto specific pieces that the REST logging decorators will require. `rest_log_wrapper.h` will be added in a later PR.

That might be true, but separating this library will not stop customers from needing to link gRPC:

- The generated `*.pb.cc` and `*.grpc.pb.cc` files go into the same CMake library
- The client libraries will always link the gRPC dependencies (for both CMake and Bazel)

If you are trying to help customers not link gRPC, then this is not enough, and I am not sure we can achieve that.

**Review by scotthart — COMMENTED** [review]
Per our conversation, I'm not adding an additional library and leaving the files in grpc_utils.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10040#-:-NEbTRnB3oIYh4XoOXDf:bjsfa7d)* status: 0 of 8 files reviewed, all discussions resolved

**Review by coryan — APPROVED** [review]
A few nits but otherwise Okay.

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10040)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @coryan)

___
*[`google/cloud/internal/log_wrapper_helpers.h` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10040#-NEDUmML5vB11yv_-rqo-r1-1:-NEbf0WG1lnoQiXxGioQ:b-886gsx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/184f0a4c7b28bae432ed67b969dca6d10bd0888e/google/cloud/internal/log_wrapper_helpers.h#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: copyright year.  This is a new file.
</blockquote></details>

Fixed
___
*[`google/cloud/internal/log_wrapper_helpers.h` line 18 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10040#-NEDUmML5vB11yv_-rqo-r1-18:-NEbf1V-18bEgermKbDX:b-hfpv0l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/184f0a4c7b28bae432ed67b969dca6d10bd0888e/google/cloud/internal/log_wrapper_helpers.h#L18)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

removed
___
*[`google/cloud/internal/log_wrapper_helpers.h` line 19 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10040#-NEDUmML5vB11yv_-rqo-r1-19:-NEbf2X29jHrHpPbmkPy:b499q7j) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/184f0a4c7b28bae432ed67b969dca6d10bd0888e/google/cloud/internal/log_wrapper_helpers.h#L19)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

unused?  I think you wanted `google/cloud/status.h`.
</blockquote></details>

Changed
___
*[`google/cloud/internal/log_wrapper_helpers.h` line 23 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10040#-NEDUmML5vB11yv_-rqo-r1-23:-NEbf4Hi4aM--AiwCbW5:b-hfpv0l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/184f0a4c7b28bae432ed67b969dca6d10bd0888e/google/cloud/internal/log_wrapper_helpers.h#L23)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

removed
___
*[`google/cloud/internal/log_wrapper_helpers_test.cc` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10040#-NEDUmML5vB11yv_-rqp-r1-1:-NEbf5Qo8avUtpY0Ex6s:bvnrpcm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/184f0a4c7b28bae432ed67b969dca6d10bd0888e/google/cloud/internal/log_wrapper_helpers_test.cc#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

copyright year, this is a new file.
</blockquote></details>

updated

**Pull request merged**
