### PR TITLE
impl(oauth2): add GUAC to OAuth2 credential mapping

### PR DESCRIPTION
**Pull request by scotthart**
Integration tests are in progress to increase test coverage.

This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @coryan and @scotthart)

___
*[google/cloud/internal/unified_rest_credentials.cc, line 42 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400#-Mw3r0tO-VjPfy-PSu__:-Mw3r0tO-VjPfy-PSu_a:b-jxyd4y) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a6187e793010451039f683f49dc9eb76b82b30e3/google/cloud/internal/unified_rest_credentials.cc#L42)):*
> ```cpp
>       oauth2_internal::ParseServiceAccountCredentials(contents, "memory");
>   if (!info) {
>     return StatusOr<std::shared_ptr<oauth2_internal::Credentials>>(
> ```

Why not return `oauth2_internal::ErrorCredentials` from here, and save yourself the `StatusOr<>` wrapper .  For that matter, why not return that directly from `ParseServiceAccountCredentials()` (and all the other helps functions)? 
___
*[google/cloud/internal/unified_rest_credentials.cc, line 87 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400#-Mw3s7aiAIN7pQ7pwi-j:-Mw3s7aiAIN7pQ7pwi-k:bhz015t) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a6187e793010451039f683f49dc9eb76b82b30e3/google/cloud/internal/unified_rest_credentials.cc#L87)):*
> ```cpp
> 
>     void visit(ServiceAccountConfig& cfg) override {
>       auto credentials =
> ```

FYI, no action required in this PR (maybe file a bug).  For all services except storage you can use self-signed JWTs:


https://google.aip.dev/auth/4111


https://github.com/googleapis/google-cloud-cpp/blob/541eb09c32c91c09ea84a55fc0861e916ebec56a/google/cloud/storage/internal/self_signing_service_account_credentials.h#L41

and I am told that even storage can use self-signed JWTs if you use the right scope.  Self-signed JWTs are simpler, more tolerate to IAM service failures, and faster.  We should be trying to use them, specially in this library that is not (yet) targeting GCS.

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[google/cloud/internal/unified_rest_credentials.cc, line 42 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400#-Mw3r0tO-VjPfy-PSu__:-Mw4ceN_50uNNh2izjrW:bwxektg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a6187e793010451039f683f49dc9eb76b82b30e3/google/cloud/internal/unified_rest_credentials.cc#L42)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Why not return `oauth2_internal::ErrorCredentials` from here, and save yourself the `StatusOr<>` wrapper .  For that matter, why not return that directly from `ParseServiceAccountCredentials()` (and all the other helps functions)? 
</blockquote></details>

I made this change. it was straightforward. Changing all the other helper functions was not and I'll create an issue (#8401) to track improving that later.
___
*[google/cloud/internal/unified_rest_credentials.cc, line 87 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400#-Mw3s7aiAIN7pQ7pwi-j:-Mw4eNLLE5AG0KtYanSi:besro9v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a6187e793010451039f683f49dc9eb76b82b30e3/google/cloud/internal/unified_rest_credentials.cc#L87)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

FYI, no action required in this PR (maybe file a bug).  For all services except storage you can use self-signed JWTs:


https://google.aip.dev/auth/4111


https://github.com/googleapis/google-cloud-cpp/blob/541eb09c32c91c09ea84a55fc0861e916ebec56a/google/cloud/storage/internal/self_signing_service_account_credentials.h#L41

and I am told that even storage can use self-signed JWTs if you use the right scope.  Self-signed JWTs are simpler, more tolerate to IAM service failures, and faster.  We should be trying to use them, specially in this library that is not (yet) targeting GCS.



</blockquote></details>

Created issue #8402

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400)* status: all files reviewed, 2 unresolved discussions (waiting on @scotthart)

___
*[google/cloud/internal/unified_rest_credentials.cc, line 41 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400#-Mw6q6Yv2nnKUSU7Lkjz:-Mw6q6YwETk4tcdXmd_O:b-qv2a3o) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c2e402d35832a5fbe87b5fbe416c3f24e3a60c4f/google/cloud/internal/unified_rest_credentials.cc#L41)):*
> ```cpp
>   auto info =
>       oauth2_internal::ParseServiceAccountCredentials(contents, "memory");
>   if (!info)
> ```

nit: this does not fit in a single line, we allow

```cc
if (foo) bar();
```

but not

```cc
if (foo)
  very_long_bar();
```
___
*[google/cloud/internal/unified_rest_credentials.cc, line 48 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400#-Mw6qKgc4KfDawW4fvDk:-Mw6qKgc4KfDawW4fvDl:b-7p5xaj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c2e402d35832a5fbe87b5fbe416c3f24e3a60c4f/google/cloud/internal/unified_rest_credentials.cc#L48)):*
> ```cpp
>   auto jwt_assertion = internal::MakeJWTAssertionNoThrow(
>       components.first, components.second, info->private_key);
>   if (!jwt_assertion)
> ```

Same formatting problem.

**Review by coryan — APPROVED** [review]
:lgtm: Please fix the formatting nits and merge.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8400#-:-Mw6qST305BlRU46c5H0:bbqy56z)* status: all files reviewed, 2 unresolved discussions (waiting on @scotthart)

**Pull request merged**
