### PR TITLE
ci: clear previously generated files

### LINKED ISSUE #12587: enhance generated code auditing
The `generate-libraries` build currently detects changes in existing files or adding of new files, but it doesn't account for extraneous files that should not exist.

One possible solution would to have the `generate-libraries` build git rm all the .h files in the directories of generated code to make sure they are replaced by running the generator. We would want to exclude any build, documentation, or streaming.cc files from being removed as the generator may not replace them exactly.

### PR DESCRIPTION
**Pull request by dbolduc**
Fixes #12587 

Make the `generate-libraries` build a bit more hermetic by removing previously generated files. This is how I found #14519 

@scotthart - my read is that the `compute` stuff is the old way of doing things and `UPDATED_DISCOVERY_DOCUMENT=compute` is the new way. You would know better.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14524)

### CODE REVIEW

**Review by coryan — APPROVED** [review]

**Comment by coryan** [comment]
Do you think this is a fix for https://github.com/googleapis/google-cloud-cpp/issues/12587 ?

**Comment by dbolduc** [comment]
> Do you think this is a fix for #12587 ?

Yes, it is. I remember us discussing it, but I couldn't find the issue when I searched for it.

**Review by scotthart — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14524)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dbolduc)

___
*[`ci/cloudbuild/builds/generate-libraries.sh` line 29 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14524#-O2QIRpO3aGd98UwVuFt:-O2QIRpO3aGd98UwVuFu:b6ey3tw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3f5b93ee561e9696e3f470f7eca65e5470dc0b0/ci/cloudbuild/builds/generate-libraries.sh#L29)):*
> ```Shell
> if [ -z "${GENERATE_GOLDEN_ONLY}" ]; then
>   io::log_h2 "Removing all other previously generated files"
>   git grep -l "Generated by the Codegen C++ plugin" google | xargs rm
> ```

This probably needs to also delete any generated files under the protos/ dir as well.

**Comment by dbolduc** [comment]
> This probably needs to also delete any generated files under the protos/ dir as well.

Thanks, I did not think about this.

(You know more about this, but) I think the discovery to proto process depends on the existing protos to make sure we do not break backwards compatibility. If I remove the protos before regenerating them, some of the field indices change.

So I restored the code that removes obsolete compute protos.

**Review by scotthart — COMMENTED** [review]
That is correct. We do need the previous generation to compare message field id numbers.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14524#-:-O2QxBJ_BU0T--NO3S6A:bx5ambp)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dbolduc)

**Review by scotthart — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14524)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dbolduc)

___
*[`ci/cloudbuild/builds/generate-libraries.sh` line 54 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14524#-O2QxvoLEsnML9yKneM3:-O2QxvoLEsnML9yKneM4:b-qikwt2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b55de814d275ff5538dae26fa3aba5f776fe71e0/ci/cloudbuild/builds/generate-libraries.sh#L54)):*
> ```Shell
>   rm "${newer_tmp_file}"
> 
>   io::log_h2 "Formatting and adding any new google/cloud/compute/v1/internal/common_*.proto"
> ```

IIRC, we need to format the new protos before we generate code from them because that could change line numbers in the proto files that we put in documentation links.

**Comment by dbolduc** [comment]
> IIRC, we need to format the new protos before we generate code from them because that could change line numbers in the proto files that we put in documentation links.

We already format the protos a few lines down, before running the generator on `generator_config.textproto`, so it was redundant.

https://github.com/googleapis/google-cloud-cpp/blob/06f65cfa3db781570b91e747e13df97f62f0cf69/ci/cloudbuild/builds/generate-libraries.sh#L68-L69

**Review by scotthart — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14524)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dbolduc)

**Pull request merged**
