### PR TITLE
feat(bigtable): limit default connection pool size

### PR DESCRIPTION
**Pull request by remyabel**
Fixes: #5877

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5881)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
This is really cool, thanks.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5881#-:-MTzNlA-CCIh8oN3o59O:b-hkk9h0)* status: all files reviewed, 1 unresolved discussion (waiting on @remyabel)

___
*[google/cloud/bigtable/client_options.cc, line 102 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5881#-MTzNrZrCXjTgASuQqL1:-MTzNrZs347As_sqhFt-:b9tk37f) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2400081fefad5cb4b62eff0bd7fc7e5b7fc7eb82/google/cloud/bigtable/client_options.cc#L102)):*
> ```cpp
>   // capped so that servers with many cores do not create too many channels.
>   std::size_t cpu_count = std::thread::hardware_concurrency();
>   return (cpu_count > 0)
> ```

I think we may have reached the limits of this ternary expression... and I am still paranoid about `min()` on Windows. Maybe:

```
if (cpu_count == 0) return BIGTGABLE_CLIENT_DEFAULT_CONNECTION_POOL_SIZE;
return (std::min<std::size_t>)(BIGTABLE_CLIENT_DEFAULT_CONNECTION_POOL_SIZE_MAX,
    cpu_count * BIGTABLE_CLIENT_DEFAULT_CHANNELS_PER_CPU);
```

WDYT?

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5881)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[google/cloud/bigtable/client_options.cc, line 102 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5881#-MTzNrZrCXjTgASuQqL1:-MTzSLou8-VYer1kaRmQ:brm1oey) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2400081fefad5cb4b62eff0bd7fc7e5b7fc7eb82/google/cloud/bigtable/client_options.cc#L102)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think we may have reached the limits of this ternary expression... and I am still paranoid about `min()` on Windows. Maybe:

```
if (cpu_count == 0) return BIGTGABLE_CLIENT_DEFAULT_CONNECTION_POOL_SIZE;
return (std::min<std::size_t>)(BIGTABLE_CLIENT_DEFAULT_CONNECTION_POOL_SIZE_MAX,
    cpu_count * BIGTABLE_CLIENT_DEFAULT_CHANNELS_PER_CPU);
```

WDYT?
</blockquote></details>

Done. For future reference, what's the problem with `std::min` on Windows?

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5881#-:-MTzTyar8Qte2bAA3y_z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[google/cloud/bigtable/client_options.cc, line 102 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5881#-MTzNrZrCXjTgASuQqL1:-MTzSnRu7oVR5XQVJj_V:bp62xei) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2400081fefad5cb4b62eff0bd7fc7e5b7fc7eb82/google/cloud/bigtable/client_options.cc#L102)):*
<details><summary><i>Previously, remyabel wrote…</i></summary><blockquote>

Done. For future reference, what's the problem with `std::min` on Windows?
</blockquote></details>

Depending on what headers you include, and what `-D` flags you use, `min()` may be a macro.  Because the preprocessor does not know about scoping, it expands `std::min(a, b)` to `std::SOME_EXPRESSION_FROM_THE_MACRO` and things break.  `(std::min)` prevents the pre-processor from thinking that `min` means the macro.  I guess `std::min<std::size_t>` also does, but I rather not find out I was wrong the hard way :-)

**Review by coryan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5881)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @remyabel)

**Comment by coryan** [comment]
Thanks for the quick turnaround on this PR.

**Pull request merged**
