### PR TITLE
feat: moves in bigquery code, preserving history

### PR DESCRIPTION
**Pull request by devjgm**
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/3560

This PR moves the the `-bigquery` code in `google/cloud/bigquery` into this `-cpp` repo. It preserves all the commit history from the original repo.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3762)

### CODE REVIEW

**Comment by devbww** [comment]
Q. No history?

**Comment by devjgm** [comment]
> Q. No history?

I'm not sending this for review. Just seeing what builds work. No need for history for that.

**Comment by coryan** [comment]
FYI: consider a rebase, I am about to change the configuration for the builds in ways that will break PRs based on older (circa 1 week ago) baselines for `master`.

**Comment by devjgm** [comment]
Moved the real PR to a new, clean one: https://github.com/googleapis/google-cloud-cpp/pull/3808

**Pull request closed without merging**
