### PR TITLE
Replace TEST_CASE with TEST_SUITE

### LINKED ISSUE #1861: Upgrade to googletest and replace TEST_CASE with TEST_SUITE.
The newer versions of googletest, including the internal version use `TEST_SUITE` instead of `TEST_CASE`, which is more standard naming. As there is no release of googletest, we need to update to a commit, currently google/googletest@b6cd405286ed8635ece71c72f118e659f4ade3fb was recommended by @gennadiycivil.

### PR DESCRIPTION
**Pull request by ghost**
Per https://github.com/google/googletest/blob/master/googletest/docs/primer.md#beware-of-the-nomenclature TEST_CASE is deprecated in favor of TEST_SUITE.

Fixes #1861

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1894)

### CODE REVIEW

**Comment by remyabel** [comment]
Kokoro builds will need to be restarted, which I can't do myself.

**Comment by remyabel** [comment]
Nope, I don't have permission to view the builds. Can you post the errors for me?

**Comment by coryan** [comment]
Doh!  If you could send me (my email address is all over the commit log) your email address I can grant you access.  I do not know of a way to grant you read access without an email, sorry, not even a way to make it public.  Meanwhile:


```
[205/580] Building CXX object google\cloud\storage\CMakeFiles\internal_curl_client_test.dir\internal\curl_client_test.cc.obj
FAILED: google/cloud/storage/CMakeFiles/internal_curl_client_test.dir/internal/curl_client_test.cc.obj
C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe  /nologo /TP  -I..\ -I. -Iexternal\nlohmann_json\include -IT:\src\github\vcpkg\installed\x64-windows-static\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MTd /Zi /Ob0 /Od /RTC1   /std:c++latest /showIncludes /Fogoogle\cloud\storage\CMakeFiles\internal_curl_client_test.dir\internal\curl_client_test.cc.obj /Fdgoogle\cloud\storage\CMakeFiles\internal_curl_client_test.dir\ /FS -c ..\google\cloud\storage\internal\curl_client_test.cc
..\google\cloud\storage\internal\curl_client_test.cc(404): error C2065: 'CredentialsFailure': undeclared identifier
..\google\cloud\storage\internal\curl_client_test.cc(404): error C2275: 'google::cloud::storage::v0::internal::`anonymous-namespace'::CurlClientTest': illegal use of this type as an expression
..\google\cloud\storage\internal\curl_client_test.cc(52): note: see declaration of 'google::cloud::storage::v0::internal::`anonymous-namespace'::CurlClientTest'
..\google\cloud\storage\internal\curl_client_test.cc(405): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
..\google\cloud\storage\internal\curl_client_test.cc(405): error C2440: 'initializing': cannot convert from 'initializer list' to 'int'
..\google\cloud\storage\internal\curl_client_test.cc(405): note: The initializer contains too many elements
..\google\cloud\storage\internal\curl_client_test.cc(407): error C2065: 'LibCurlFailure': undeclared identifier
..\google\cloud\storage\internal\curl_client_test.cc(407): error C2275: 'google::cloud::storage::v0::internal::`anonymous-namespace'::CurlClientTest': illegal use of this type as an expression
..\google\cloud\storage\internal\curl_client_test.cc(52): note: see declaration of 'google::cloud::storage::v0::internal::`anonymous-namespace'::CurlClientTest'
..\google\cloud\storage\internal\curl_client_test.cc(408): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
..\google\cloud\storage\internal\curl_client_test.cc(407): error C2374: 'google::cloud::storage::v0::internal::`anonymous-namespace'::INSTANTIATE_TEST_SUITE_P': redefinition; multiple initialization
..\google\cloud\storage\internal\curl_client_test.cc(404): note: see declaration of 'google::cloud::storage::v0::internal::`anonymous-namespace'::INSTANTIATE_TEST_SUITE_P'
..\google\cloud\storage\internal\curl_client_test.cc(408): error C2440: 'initializing': cannot convert from 'initializer list' to 'int'
..\google\cloud\storage\internal\curl_client_test.cc(408): note: The initializer contains too many elements
```

**Comment by remyabel** [comment]
Got'cha. The issue probably is having to pull in a newer gtest since the Kokoro build uses vcpkg. I'll attempt to work on it.

**Pull request closed without merging**
