### PR TITLE
cleanup(storage): Remove references of BucketPolicyOnly

### PR DESCRIPTION
**Pull request by remyabel**
Fixes: #3194
Fixes: #5613

**BREAKING CHANGE**

* `UniformBucketLevelAccess` was known as `BucketPolicyOnly` during the beta.
  For compatibility the C++ Cloud Storage library supported both, however
  `BucketPolicyOnly` is now completely removed.

Making a new one because of force push.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5720)

### CODE REVIEW

**Review by coryan — COMMENTED** [review]
Thanks, this is really useful.  Do you mind updating the `CHANGELOG.md`and move the description of this change to the next release changes?

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5720#-:-MRWTiCU4GO2O_o-mMOx:b-iqcop5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — COMMENTED** [review]
+kokoro:run 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5720#-:-MRWW0l47lc2WGifG7l9:bcgx490)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by remyabel** [comment]
I am running into unexplainable protobuf errors and I'm too sick to debug right now. Feel free to close this and take over the PR if you wish.

**Comment by coryan** [comment]
Ack, I will take a look.

**Comment by remyabel** [comment]
I fixed my development environment and the build error was eluding me because I forgot to enable storage GRPC again. Should be good to go now.

**Comment by coryan** [comment]
When you have some time, please run `./ci/kokoro/docker/build.sh update-abi` and commit the files it changes to update the API baseline.

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5720#-:-MRfPMi_CHklzx1ufe9f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by coryan** [comment]
Thanks!

**Pull request merged**
