### PR TITLE
feat(mixin): add mixin utils

### PR DESCRIPTION
**Pull request by cuiy0006**
Add mixin utils used for extracting mixin info from YAML and proto files.

For testing, change the logic of inserting proto to FakeSourceTree, newly inserted proto replaces the old one.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691)

### CODE REVIEW

**Review by scotthart — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @cuiy0006)

___
*[`generator/internal/mixin_utils.h` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RZP5U4aLTF2VAwmnR:-O6RZP5VBgUYp-a3GR8d:bpub5b7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.h#L1)):*
> ```objc
> // Copyright 2020 Google LLC
> ```

Update the year to 2024
___
*[`generator/internal/mixin_utils.cc` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RZrseEYShocpe0DrZ:-O6RZrsf2wxfWZIIJ75q:bhhbhyh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.cc#L1)):*
> ```cpp
> #include "generator/internal/mixin_utils.h"
> ```

Add the copyright and license boilerplate.
___
*[`generator/internal/mixin_utils.cc` line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6Rda-g-E5DWrlLO1lq:-O6Rda-h1NzeeKJKgIjd:b-9a063u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.cc#L27)):*
> ```cpp
> std::unordered_map<std::string, std::string> const kMixinProtoPathMap = {
>     {"google.cloud.location.Locations",
>      "google/cloud/location/locations.proto"},
> ```

Per the style guide, constants are required to have a type that is trivially destructible. You'll want to refactor these lookup tables to look something like:

```
std::unordered_map<std::string, std::string> const& Foo() {
  static auto const* kFoo = [](){
      auto* foo = new std::unordered_map<std::string, std::string>();
      // add values here
      return foo;
  }();
  return *kFoo;
}
```
___
*[`generator/internal/mixin_utils.cc` line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RaqdHCyY2IU2qpPy2:-O6RaqdI8JzGUKoPXTAa:b-ghsvl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.cc#L56)):*
> ```cpp
>     auto const& selector = rule["selector"];
>     if (selector.Type() != YAML::NodeType::Scalar) continue;
>     std::string const& method_full_name = selector.as<std::string>();
> ```

When using `as` it's going to be safer to assign the result to a plain `std::string` instead of a `std::string cont&` so that we're not relying on how the yaml library manages the lifetime of the `std::string` it's creating when we call `as`.
___
*[`generator/internal/mixin_utils.cc` line 66 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RcX6J6GzHvnYNhv1x:-O6RcX6J6GzHvnYNhv1y:botjvs) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.cc#L66)):*
> ```cpp
>           absl::AsciiStrToLower(kv.first.as<std::string>());
>       if (kHttpVerbs.find(http_verb_lower) == kHttpVerbs.end()) continue;
>       std::string const& http_verb = kHttpVerbs.at(http_verb_lower);
> ```

Avoid using `at` to look things up in a map because there's not a good way to return a meaningful error message.



_Code quote:_
```cpp
at
```
___
*[`generator/internal/mixin_utils_test.cc` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RhyiP2sEmXhJANTCq:-O6RhyiP2sEmXhJANTCr:bhhbhyh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils_test.cc#L1)):*
> ```cpp
> #include "generator/internal/mixin_utils.h"
> ```

Add the copyright and license boilerplate.
___
*[`generator/testing/fake_source_tree.cc` line 25 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6Rh0bu4j4Q8YfoskpM:-O6Rh0bv1dbxcqmCV2cE:b1clr1s) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/testing/fake_source_tree.cc#L25)):*
> ```cpp
> 
> void FakeSourceTree::Insert(std::string const& filename, std::string contents) {
>   files_[filename] = std::move(contents);
> ```

Why did this need to change?

**Review by cuiy0006 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @scotthart)

___
*[`generator/internal/mixin_utils.h` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RZP5U4aLTF2VAwmnR:-O6XutDc3_lNyj-eM0EY:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.h#L1)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Update the year to 2024
</blockquote></details>

Done.
___
*[`generator/internal/mixin_utils.cc` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RZrseEYShocpe0DrZ:-O6Xuu9k3dA_6BH2Ix3u:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.cc#L1)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Add the copyright and license boilerplate.
</blockquote></details>

Done.
___
*[`generator/internal/mixin_utils.cc` line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6Rda-g-E5DWrlLO1lq:-O6XuuqKACIAxWJ8DjqG:b-1hy645) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.cc#L27)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Per the style guide, constants are required to have a type that is trivially destructible. You'll want to refactor these lookup tables to look something like:

```
std::unordered_map<std::string, std::string> const& Foo() {
  static auto const* kFoo = [](){
      auto* foo = new std::unordered_map<std::string, std::string>();
      // add values here
      return foo;
  }();
  return *kFoo;
}
```
</blockquote></details>

Done with modifiying it following totw#110.
___
*[`generator/internal/mixin_utils.cc` line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RaqdHCyY2IU2qpPy2:-O6XvDG06k-7EGvZCM6D:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.cc#L56)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

When using `as` it's going to be safer to assign the result to a plain `std::string` instead of a `std::string cont&` so that we're not relying on how the yaml library manages the lifetime of the `std::string` it's creating when we call `as`.
</blockquote></details>

Done.
___
*[`generator/internal/mixin_utils.cc` line 66 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RcX6J6GzHvnYNhv1x:-O6XvECl5Ohcsqa_1QMZ:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.cc#L66)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Avoid using `at` to look things up in a map because there's not a good way to return a meaningful error message.
</blockquote></details>

Done.
___
*[`generator/internal/mixin_utils_test.cc` line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RhyiP2sEmXhJANTCq:-O6XvEy46vXmRK7w-CoV:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils_test.cc#L1)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Add the copyright and license boilerplate.
</blockquote></details>

Done.
___
*[`generator/testing/fake_source_tree.cc` line 25 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6Rh0bu4j4Q8YfoskpM:-O6XvFcRA8LsTxjD4kKe:b-80fzdb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/testing/fake_source_tree.cc#L25)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Why did this need to change?
</blockquote></details>

Yes, there are some [proto](https://github.com/googleapis/google-cloud-cpp/blob/41b11529ed8fbf308ebab2208c56d7a9782342f4/generator/testing/descriptor_pool_fixture.cc#L55) files added by the test fixture by default. If the file is added again in the test cases, people will expect it to be overriden, instead of implicitly ignore the new added proto files.

If you want to keep the `insert` method, I can add a `insert_or_assign` method to update if the key exists.

**Review by scotthart — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @cuiy0006)

___
*[`generator/internal/mixin_utils.cc` line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RaqdHCyY2IU2qpPy2:-O6bfNEf6wBoSQAxquyt:b-fg5rpw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.cc#L56)):*
<details><summary><i>Previously, cuiy0006 (Yao Cui) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like there are multiple places where we're assigning the result of `as` to a `std::string const&`. Let's go ahead and change all of them like this one.

**Review by cuiy0006 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[`generator/internal/mixin_utils.cc` line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691#-O6RaqdHCyY2IU2qpPy2:-O6bjSRV8EhRLY6eRDCq:b-xeigax) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e53cbbc69e8ca263540a094092b7433227c2a3b4/generator/internal/mixin_utils.cc#L56)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Looks like there are multiple places where we're assigning the result of `as` to a `std::string const&`. Let's go ahead and change all of them like this one.
</blockquote></details>

Done. Thanks for pointing that out, I missed these.

**Review by scotthart — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14691)* status: 6 of 7 files reviewed, all discussions resolved

**Pull request merged**
