### PR TITLE
docs(managedkafka): change old title to new title

### PR DESCRIPTION
**Pull request by noahdietz**
Changes all instances of the "old" product title to the "new" one. Internal bug http://b/379316147

This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14846)

### CODE REVIEW

**Review by dbolduc — APPROVED** [review]

**Comment by dbolduc** [comment]
Thanks! To pass the formatting build, can you run the following and commit the changes:

```
ci/cloudbuild/build.sh -t checkers-pr
```

And if you are wondering why this naming stuff is maintained by hand, there is some discussion in #10237

**Comment by noahdietz** [comment]
> Thanks! To pass the formatting build, can you run the following and commit the changes:
> 
> ```
> ci/cloudbuild/build.sh -t checkers-pr
> ```

Done!

**Pull request merged**
