### PR TITLE
feat(pubsub): only empty order keys for non-ordered publishers

### PR DESCRIPTION
**Pull request by remyabel**
…ot enabled

Fixes: #4802

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
Thanks for the PR!  Please see some suggestions below.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-:-MIxnmHGA0jBX1oOo53z:b-b3w1xw)* status: all files reviewed, 2 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/pubsub/publisher_connection.cc, line 40 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MIxm-UU0FmyLkJHUrbd:-MIxm-UU0FmyLkJHUrbe:bz4shut) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/903b8b180e9f240a2490d72efb5a4ce3ab1909e7/google/cloud/pubsub/publisher_connection.cc#L40)):*
> ```cpp
> 
>   future<StatusOr<std::string>> Publish(PublishParams p) override {
>     if (!p.message.ordering_key().empty()) {
> ```

I think this code is used for both ordering and non-ordering publishers.  Maybe we should not have this here?
___
*[google/cloud/pubsub/publisher_connection.cc, line 118 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MIxmSGCAl4sSzKvOdTi:-MIxmSGCAl4sSzKvOdTj:b-g4uld) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/903b8b180e9f240a2490d72efb5a4ce3ab1909e7/google/cloud/pubsub/publisher_connection.cc#L118)):*
> ```cpp
>       return OrderingKeyPublisherConnection::Create(std::move(factory));
>     }
>     return BatchingPublisherConnection::Create(
> ```

FYI, note how both the ordering and non-ordering cases use `BatchingPublisherConnection`.  And both use the `ContainingPublisherConnection` too.

I think what we need is a new decorator injected here:

```
if (options.message_ordering()) {
    // as before
    return ...;
}
return RejectsWithOrderingKey::Create(BatchingPublisherConnection::Create(
   ... /* as before */)));
```

This new decorator would do the check and reject the messages.
___
*[google/cloud/pubsub/internal/batching_publisher_connection.cc, line 71 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MIxnI9l8f9PIQoe8o4A:-MIxnI9l8f9PIQoe8o4B:b2gtv4p) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/903b8b180e9f240a2490d72efb5a4ce3ab1909e7/google/cloud/pubsub/internal/batching_publisher_connection.cc#L71)):*
> ```cpp
>   if (!p.message.ordering_key().empty()) {
>     return google::cloud::make_ready_future(StatusOr<std::string>(
>         Status(StatusCode::kPermissionDenied,
> ```

Also, I think `kPermissionDenied` is not the right error code, there are descriptions for the analogous error codes in gRPC:

https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

`kInvalidArgument` seems like a better (the best?)  match here.

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/pubsub/publisher_connection.cc, line 40 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MIxm-UU0FmyLkJHUrbd:-MJ-9RFV0IZ-91BkhD7i:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/903b8b180e9f240a2490d72efb5a4ce3ab1909e7/google/cloud/pubsub/publisher_connection.cc#L40)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think this code is used for both ordering and non-ordering publishers.  Maybe we should not have this here?
</blockquote></details>

Done.
___
*[google/cloud/pubsub/publisher_connection.cc, line 118 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MIxmSGCAl4sSzKvOdTi:-MJ-9TM92WhXcDkfgknf:b-vhwjfr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/903b8b180e9f240a2490d72efb5a4ce3ab1909e7/google/cloud/pubsub/publisher_connection.cc#L118)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

FYI, note how both the ordering and non-ordering cases use `BatchingPublisherConnection`.  And both use the `ContainingPublisherConnection` too.

I think what we need is a new decorator injected here:

```
if (options.message_ordering()) {
    // as before
    return ...;
}
return RejectsWithOrderingKey::Create(BatchingPublisherConnection::Create(
   ... /* as before */)));
```

This new decorator would do the check and reject the messages.
</blockquote></details>

Done. However, `PublisherConnectionTest.Basic` is now crashing so I've converted the PR to a draft.
___
*[google/cloud/pubsub/internal/batching_publisher_connection.cc, line 71 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MIxnI9l8f9PIQoe8o4A:-MJ-9e5263nOgFrlOXCH:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/903b8b180e9f240a2490d72efb5a4ce3ab1909e7/google/cloud/pubsub/internal/batching_publisher_connection.cc#L71)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Also, I think `kPermissionDenied` is not the right error code, there are descriptions for the analogous error codes in gRPC:

https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

`kInvalidArgument` seems like a better (the best?)  match here.

</blockquote></details>

Done.

**Review by coryan — COMMENTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187)* status: all files reviewed, 2 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/pubsub/publisher_connection.cc, line 118 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MIxmSGCAl4sSzKvOdTi:-MJ-B0wT43G6H3GXImAM:byxc38n) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/903b8b180e9f240a2490d72efb5a4ce3ab1909e7/google/cloud/pubsub/publisher_connection.cc#L118)):*
<details><summary><i>Previously, remyabel wrote…</i></summary><blockquote>

Done. However, `PublisherConnectionTest.Basic` is now crashing so I've converted the PR to a draft.
</blockquote></details>

See the comments below to explain the crash. I believe my code snippet was ~not clear enough~ just wrong, what we want is something like this:

```cc
std::shared_ptr<pubsub::PublisherConnection> MakePublisherConnection(
    pubsub::Topic topic, pubsub::PublisherOptions options,
    pubsub::ConnectionOptions connection_options,
    std::shared_ptr<PublisherStub> stub,
    std::unique_ptr<pubsub::RetryPolicy const> retry_policy,
    std::unique_ptr<pubsub::BackoffPolicy const> backoff_policy) {
  if (!retry_policy) retry_policy = DefaultRetryPolicy();
  if (!backoff_policy) backoff_policy = DefaultBackoffPolicy();
  stub = std::make_shared<pubsub_internal::PublisherMetadata>(std::move(stub));
  if (connection_options.tracing_enabled("rpc")) {
    GCP_LOG(INFO) << "Enabled logging for gRPC calls";
    stub = std::make_shared<pubsub_internal::PublisherLogging>(
        std::move(stub), connection_options.tracing_options());
  }

  auto default_thread_pool_size = []() -> std::size_t {
    auto constexpr kDefaultThreadPoolSize = 4;
    auto const n = std::thread::hardware_concurrency();
    return n == 0 ? kDefaultThreadPoolSize : n;
  };
  if (connection_options.background_thread_pool_size() == 0) {
    connection_options.set_background_thread_pool_size(
        default_thread_pool_size());
  }

  auto background = connection_options.background_threads_factory()();
  auto make_connection = [&]() -> std::shared_ptr<pubsub::PublisherConnection> {
    auto cq = background->cq();
    if (options.message_ordering()) {
      // We need to copy these values because we will call `clone()` on them
      // multiple times.
      std::shared_ptr<pubsub::RetryPolicy const> retry =
          std::move(retry_policy);
      std::shared_ptr<pubsub::BackoffPolicy const> backoff =
          std::move(backoff_policy);
      auto factory = [topic, options, stub, cq, retry,
                      backoff](std::string const&) {
        return BatchingPublisherConnection::Create(
            topic, options, stub, cq, retry->clone(), backoff->clone());
      };
      return OrderingKeyPublisherConnection::Create(std::move(factory));
    }
    return RejectsWithOrderingKey::Create(BatchingPublisherConnection::Create(
        std::move(topic), std::move(options), std::move(stub), std::move(cq),
        std::move(retry_policy), std::move(backoff_policy)));
  };
  return std::make_shared<pubsub::ContainingPublisherConnection>(
      std::move(background), make_connection());
}
```
___
*[google/cloud/pubsub/internal/batching_publisher_connection_test.cc, line 420 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MJ-ARN83pKNVMD4R-X0:-MJ-ARN97DoGA0EtnZWa:b-16rup6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4fd141a42b8932dcb6eded9d18bd390a44c75090/google/cloud/pubsub/internal/batching_publisher_connection_test.cc#L420)):*
> ```cpp
>   };
> 
>   auto publisher = RejectsWithOrderingKey::Create(std::move(factory));
> ```

This is moving this test a tiny bit away from a pure unit test for `BatchingPublisherConnection` and more into integration test territory.  I think we should leave this test as it was, and create a new unit test for `RejectsWithOrderingKey`.
___
*[google/cloud/pubsub/internal/rejects_with_ordering_key.h, line 48 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MJ-9g5-8wNB9LzaidW0:-MJ-9g50Aa91d8bveGoM:byrc5a7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4fd141a42b8932dcb6eded9d18bd390a44c75090/google/cloud/pubsub/internal/rejects_with_ordering_key.h#L48)):*
> ```objc
> 
>   ConnectionFactory factory_;
>   std::shared_ptr<PublisherConnection> connection_;
> ```

The crashes you are seeing are because `connection_` is never initialized.  Its default value will be `nullptr` and `Publish()` will crash, right?

I think this class should receive a `std::shared_ptr<pubsub::PublisherConnection>` as an argument in `Create()`, and the `factory` is just needed for `OrderingKeyPublisherConnection`.  Thoughts?

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/pubsub/publisher_connection.cc, line 118 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MIxmSGCAl4sSzKvOdTi:-MJ02X1_-shuolyuW5HD:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/903b8b180e9f240a2490d72efb5a4ce3ab1909e7/google/cloud/pubsub/publisher_connection.cc#L118)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

See the comments below to explain the crash. I believe my code snippet was ~not clear enough~ just wrong, what we want is something like this:

```cc
std::shared_ptr<pubsub::PublisherConnection> MakePublisherConnection(
    pubsub::Topic topic, pubsub::PublisherOptions options,
    pubsub::ConnectionOptions connection_options,
    std::shared_ptr<PublisherStub> stub,
    std::unique_ptr<pubsub::RetryPolicy const> retry_policy,
    std::unique_ptr<pubsub::BackoffPolicy const> backoff_policy) {
  if (!retry_policy) retry_policy = DefaultRetryPolicy();
  if (!backoff_policy) backoff_policy = DefaultBackoffPolicy();
  stub = std::make_shared<pubsub_internal::PublisherMetadata>(std::move(stub));
  if (connection_options.tracing_enabled("rpc")) {
    GCP_LOG(INFO) << "Enabled logging for gRPC calls";
    stub = std::make_shared<pubsub_internal::PublisherLogging>(
        std::move(stub), connection_options.tracing_options());
  }

  auto default_thread_pool_size = []() -> std::size_t {
    auto constexpr kDefaultThreadPoolSize = 4;
    auto const n = std::thread::hardware_concurrency();
    return n == 0 ? kDefaultThreadPoolSize : n;
  };
  if (connection_options.background_thread_pool_size() == 0) {
    connection_options.set_background_thread_pool_size(
        default_thread_pool_size());
  }

  auto background = connection_options.background_threads_factory()();
  auto make_connection = [&]() -> std::shared_ptr<pubsub::PublisherConnection> {
    auto cq = background->cq();
    if (options.message_ordering()) {
      // We need to copy these values because we will call `clone()` on them
      // multiple times.
      std::shared_ptr<pubsub::RetryPolicy const> retry =
          std::move(retry_policy);
      std::shared_ptr<pubsub::BackoffPolicy const> backoff =
          std::move(backoff_policy);
      auto factory = [topic, options, stub, cq, retry,
                      backoff](std::string const&) {
        return BatchingPublisherConnection::Create(
            topic, options, stub, cq, retry->clone(), backoff->clone());
      };
      return OrderingKeyPublisherConnection::Create(std::move(factory));
    }
    return RejectsWithOrderingKey::Create(BatchingPublisherConnection::Create(
        std::move(topic), std::move(options), std::move(stub), std::move(cq),
        std::move(retry_policy), std::move(backoff_policy)));
  };
  return std::make_shared<pubsub::ContainingPublisherConnection>(
      std::move(background), make_connection());
}
```
</blockquote></details>

Done.
___
*[google/cloud/pubsub/internal/batching_publisher_connection_test.cc, line 420 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MJ-ARN83pKNVMD4R-X0:-MJ02Yk2DfgF8D0-qZZh:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4fd141a42b8932dcb6eded9d18bd390a44c75090/google/cloud/pubsub/internal/batching_publisher_connection_test.cc#L420)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is moving this test a tiny bit away from a pure unit test for `BatchingPublisherConnection` and more into integration test territory.  I think we should leave this test as it was, and create a new unit test for `RejectsWithOrderingKey`.
</blockquote></details>

Done.
___
*[google/cloud/pubsub/internal/rejects_with_ordering_key.h, line 48 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-MJ-9g5-8wNB9LzaidW0:-MJ02bUWBdcESiJ2K7Vt:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4fd141a42b8932dcb6eded9d18bd390a44c75090/google/cloud/pubsub/internal/rejects_with_ordering_key.h#L48)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

The crashes you are seeing are because `connection_` is never initialized.  Its default value will be `nullptr` and `Publish()` will crash, right?

I think this class should receive a `std::shared_ptr<pubsub::PublisherConnection>` as an argument in `Create()`, and the `factory` is just needed for `OrderingKeyPublisherConnection`.  Thoughts?

</blockquote></details>

Done.

**Review by coryan — COMMENTED** [review]
:lgtm: let's see what the builds say +kokoro:run 

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-:-MJ1sjLM6eNIAgSkF8Bg:b-a5la7b)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5187#-:-MJ1xM2aCWuvJApg9Uyp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
