### PR TITLE
Adding move semantics to Row

### LINKED ISSUE #1746: Create non-const accessors for bigtable::Row to allow move semantics.
[bigtable::Row](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/608dd154cf3f028982ed46cf436c1de246990f2c/google/cloud/bigtable/row.h#L32) class currently have const& accessors. 
Due to this, copies are created and makes it less efficient. 

Non const accessors needs to be created for `bigtable::Row`. This will enable efficient move of `bigtable::Row`.

### PR DESCRIPTION
**Pull request by manish-qlogic**
This fixes #1746

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1873)

### CODE REVIEW

**Comment by devjgm** [comment]
I read #1746, but I don't fully understand the context in which the Row class is used and the members need to be moved out of it. My concern is that I'd worry if we started adding these 4 ref-qualified overloads to all/lots of getters. So, if there's a specific reason why these ref overloads are specifically needed in this Row class, then that's cool, but I missed that in issue #1746. However, if our thinking is that we want to add these 4 ref-qualified overloads all over the place, then I'd like to better understand the needs and tradeoffs... and discuss this more :-)

Sorry I'm late to this game.

**Comment by remyabel** [comment]
I agree with @devjgm. You gain nothing here because move semantics already works without explicit ref qualifiers (rule of zero) since `std::string` and `std::vector` are move aware already. As I understand it, the ref qualifiers would be useful if i.e `Row` owned a resource that needed to be managed.

**Comment by manish-qlogic** [comment]
AFAIK, these 4 overloads are only for `Row` and don't have plans for other objects. The main reason is to reduce the overhead of copy. With  many rows in `BigTable`, this overhead can be significant. So the idea is to avoid coping.

Here, in the following example `Noisy` makes extra copy but `LittleNoisy` wont.

```
#include <iostream>
#include <vector>

struct Noisy {
    Noisy() = default;
    Noisy(Noisy&&) {
        std::cout << "Noisy&&\n";
    }
    Noisy(const Noisy&) {
        std::cout << "const Noisy&\n";
    }
    Noisy& operator=(const Noisy&) = default;
    Noisy& operator=(Noisy&&) = default;
};

struct LittleNoisy {
    LittleNoisy() = default;
    LittleNoisy(LittleNoisy&&) {
        std::cout << "LittleNoisy&&\n";
    }
    LittleNoisy(const LittleNoisy&) {
        std::cout << "const LittleNoisy&\n";
    }
    LittleNoisy& operator=(const LittleNoisy&) = default;
    LittleNoisy& operator=(LittleNoisy&&) = default;
};

struct Foo {
public:
    Foo(Noisy a, LittleNoisy b)
        : a_(std::move(a)), b_(std::move(b)) { }
        
    Noisy a() const { return a_; }
    LittleNoisy && b() && { return std::move(b_);}
private:
    Noisy a_;
    LittleNoisy b_;
};

int main() {
    Noisy n;
    LittleNoisy ln;
    Foo f(n, ln);

    std::cout<<"------------Extra Copies for Noisy------------------------------\n";
    Foo f1(f.a(), std::move(f).b());

    std::cout<<"------------Extra Copies for Noisy Even with move-------------------------\n";
    Foo f2(std::move(f).a(), std::move(f).b());
    std::cout<<"------------------------------------------\n";
}
```

Hope this clarifies a bit.

**Comment by remyabel** [comment]
Thank you for the example. I've created a [benchmark](http://quick-bench.com/BkdTWJiwaPlT6-nNG_6cf3EsCe8) using quick-bench and the performance/disassembly seems to be identical between the three examples.

**Comment by remyabel** [comment]
Here is another [benchmark](http://quick-bench.com/ea7-hRKGHeyiYvMwyVZpf7j2Fag) using a more minimal example that more closely matches the original code. `Foo` has all the ref qualifiers, `Foo2` only has one. It seems that `Foo2` actually performs better than `Foo`. Please take a look at the benchmark and let me know if I'm missing something obvious.

**Comment by manish-qlogic** [comment]
IMHO, it is because string size is less. Copy is costly as and when we use heavy objects.
see this [benchmark](http://quick-bench.com/ToznPBltTyZB6sd8nI5YLKIf6uA) with little bigger string.

**Comment by remyabel** [comment]
Ah, yeah.  Short string optimization is definitely a factor here. You're right.

**Comment by devjgm** [comment]
I think I follow the example, but I'm not sure exactly how it relates to the code change in this PR. From looking at the example code, it looks like what you really want is a `Foo(Foo&&)` constructor. Is that right? is that what we really want in `Row` too?

I'm just wonder what is special about the `Row` class that makes it so its access need these ref qualifiers to be able to move each field out independently. #1746 mentions extra copies and implies a performance problem: Where is that performance problem? Is there code somewhere that's showing a problem?

**Comment by devjgm** [comment]
> std::cout<<"------------Extra Copy for Noisy------------------------------\n";
> Foo f1(f.a(), std::move(f).b())
> std::cout<<"------------Extra Copy for Noisy Even with move-------------------------\n";
> Foo f2(std::move(f).a(), std::move(f).b());


Note that the above example contains undefined behavior because the order of function argument evaluation isn't guaranteed, so `f` may be moved from before `f.a()` is invoked in the first call. And in the second call, one of the arguments is using a moved-from `f`.

... so maybe there's a clearer example of what use-case we're trying to enable with this PR? Thanks.

**Pull request closed without merging**
