### PR TITLE
feat(otel): promote `OpenTelemetryTracingOption` to GA

### PR DESCRIPTION
**Pull request by dbolduc**
Part of the work for #12726 

I plan to allow for the one, maybe two customers who have tried this feature to update the version of the library independently from their code.

This means we need to leave the experimental option around for one release of the library.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12728)

### CODE REVIEW

**Review by devbww — APPROVED** [review]
Something for README.md?

**Comment by dbolduc** [comment]
> Something for README.md?

Like what? And which README.MD?

**Comment by devbww** [comment]
> > Something for README.md?
> 
> Like what? And which README.md?

Sorry ... I meant CHANGELOG.md.  Something announcing the GA-ness?

**Comment by dbolduc** [comment]
> Sorry ... I meant CHANGELOG.md. Something announcing the GA-ness?

Ah. I haven't written it yet, but my plan was to have one PR for the CHANGELOG.md and google/cloud/opentelemetry/README.md documentation update.

**Pull request merged**
