### PR TITLE
doc(doxygen): fix typo in storage-mocking.dox: ueeful -> useful

### PR DESCRIPTION
**Pull request by Hex052**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7130)

### CODE REVIEW

**Comment by devjgm** [comment]
Hi. Thanks for the PR. Before we can accept any PR, you'll need to sign the Contributor License Agreement. Do you see the link to do that above?

**Comment by devjgm** [comment]
Also, the "conventionalcommits.org" bot is unhappy. Annoyingly, it needs you to change your commit message to match a certain pattern. You should be able to `git commit --amend` to change your commit message to, say, "doc(doxygen): fix typo in storage-mocking.dox: ueeful -> useful". Then you can re-push the commit to your fork with `git push --force-with-lease`. Let me know if you have questions.

**Comment by coryan** [comment]
We can also ignore conventional commits bot.  It is not a `required` build

**Comment by devjgm** [comment]
> We can also ignore conventional commits bot. It is not a `required` build

Good point. I forgot about that.

**Comment by Hex052** [comment]
@googlebot I signed it!

**Review by devjgm — APPROVED** [review]

**Comment by devjgm** [comment]
Thanks for the fix! Let's just ignore the conventional commits bot failure.

**Pull request merged**
