### PR TITLE
feat(spanner): add samples for MR CMEK

### PR DESCRIPTION
**Pull request by panerorenn9541**
Add samples for MR CMEK database creation, backup creation, copy backup, and backup restore.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674)

### CODE REVIEW

**Review by scotthart — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @panerorenn9541)

___
*[`google/cloud/spanner/samples/samples.cc` line 1304 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674#-O5tXsC42JZXZCLuydvn:-O5tXsC5DzlWc3p1TzWj:b-hf1ghe) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4b30fbe46c6a8900f530e5036d34fef085e3de3d/google/cloud/spanner/samples/samples.cc#L1304)):*
> ```cpp
>                 std::string const& src_project_id,
>                 std::string const& src_instance_id,
>                 std::string const& src_backup_id,
> ```

This is a lot of parameters for a function. Perhaps define a struct
```
struct BackupIdentifier {
  std::string project_id;
  std::string instance_id;
  std::string backup_id;
};

void CopyBackupWithMRCMEK(google::cloud::spanner_admin::DatabaseAdminClient client,
    BackupIdentifier const& src,
    BackupIdentifier const& dst,
...
```
___
*[`google/cloud/spanner/samples/samples.cc` line 1320 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674#-O5tYqoc-eYTXuFNaEUB:-O5tYqoc-eYTXuFNaEUC:b-vrb0gj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4b30fbe46c6a8900f530e5036d34fef085e3de3d/google/cloud/spanner/samples/samples.cc#L1320)):*
> ```cpp
>           .get();
>   if (!copy_backup) throw std::move(copy_backup).status();
>   std::cout << "Copy Backup " << copy_backup->name()  //
> ```

Are these comment sequences needed?
___
*[`google/cloud/spanner/samples/samples.cc` line 1355 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674#-O5tZOFBABtKHK8li1_G:-O5tZOFBABtKHK8li1_H:brl6nqc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4b30fbe46c6a8900f530e5036d34fef085e3de3d/google/cloud/spanner/samples/samples.cc#L1355)):*
> ```cpp
>   auto expire_time = TimestampAdd(
>       google::cloud::spanner::MakeTimestamp(backup->expire_time()).value(),
>       absl::Hours(7));
> ```

Can we use std::chrono instead of absl here?
___
*[`google/cloud/spanner/samples/samples.cc` line 1614 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674#-O5tZctkBPq7S5WAtExs:-O5tZctkBPq7S5WAtExt:bgwj97w) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4b30fbe46c6a8900f530e5036d34fef085e3de3d/google/cloud/spanner/samples/samples.cc#L1614)):*
> ```cpp
> void CreateBackupWithMRCMEK(
>     google::cloud::spanner_admin::DatabaseAdminClient client,
>     std::string const& project_id, std::string const& instance_id,
> ```

Same comment about excessive number of parameters.
___
*[`google/cloud/spanner/samples/samples.cc` line 1650 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674#-O5ta0Cr25T1XRJfwEa6:-O5ta0Cr25T1XRJfwEa7:b-k51ojo) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4b30fbe46c6a8900f530e5036d34fef085e3de3d/google/cloud/spanner/samples/samples.cc#L1650)):*
> ```cpp
>       std::cout << ", ";
>     }
>   }
> ```

We seem to do this several times. Perhaps factor this out into a function.



_Code quote:_
```cpp
      << " using encryption keys ";
  for (int i = 0; i < encryption_keys.size(); ++i) {
    std::cout << encryption_keys[i].FullName();
    if (i != encryption_keys.size() - 1) {
      std::cout << ", ";
    }
  }
```

**Review by panerorenn9541 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @scotthart)

___
*[`google/cloud/spanner/samples/samples.cc` line 1304 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674#-O5tXsC42JZXZCLuydvn:-O9HISwqA1fiQqpMO1rh:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/417d6a2efaedbab5a493152a1de28938b86b85cd/google/cloud/spanner/samples/samples.cc#L1304)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

This is a lot of parameters for a function. Perhaps define a struct
```
struct BackupIdentifier {
  std::string project_id;
  std::string instance_id;
  std::string backup_id;
};

void CopyBackupWithMRCMEK(google::cloud::spanner_admin::DatabaseAdminClient client,
    BackupIdentifier const& src,
    BackupIdentifier const& dst,
...
```
</blockquote></details>

Done.
___
*[`google/cloud/spanner/samples/samples.cc` line 1320 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674#-O5tYqoc-eYTXuFNaEUB:-O9HITJT8CKfpMMYb4Y6:bjeyqkk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/417d6a2efaedbab5a493152a1de28938b86b85cd/google/cloud/spanner/samples/samples.cc#L1320)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Are these comment sequences needed?
</blockquote></details>

The logs are there for other copy/create/restores.
___
*[`google/cloud/spanner/samples/samples.cc` line 1355 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674#-O5tZOFBABtKHK8li1_G:-O9HIeYNA90aCyVhHItF:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/417d6a2efaedbab5a493152a1de28938b86b85cd/google/cloud/spanner/samples/samples.cc#L1355)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Can we use std::chrono instead of absl here?
</blockquote></details>

Done.
___
*[`google/cloud/spanner/samples/samples.cc` line 1614 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674#-O5tZctkBPq7S5WAtExs:-O9HIfQh0eNBJ_Q3jidZ:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/417d6a2efaedbab5a493152a1de28938b86b85cd/google/cloud/spanner/samples/samples.cc#L1614)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Same comment about excessive number of parameters.
</blockquote></details>

Done.
___
*[`google/cloud/spanner/samples/samples.cc` line 1650 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14674#-O5ta0Cr25T1XRJfwEa6:-O9HIg8u91St4XaQ2IiO:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/417d6a2efaedbab5a493152a1de28938b86b85cd/google/cloud/spanner/samples/samples.cc#L1650)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

We seem to do this several times. Perhaps factor this out into a function.
</blockquote></details>

Done.

**Pull request merged**
