### PR TITLE
do not merge or review

### PR DESCRIPTION
**Pull request by alevenberg**
Related to https://github.com/googleapis/google-cloud-cpp/issues/12232

This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12560)

### CODE REVIEW

**Comment by alevenberg** [comment]
Some notes from debugging with bww@ locally:

- We tried adding `google-cloud-cpp::iam_credentials_v1_iamcredentials_protos` to link to the test target in `google_cloud_cpp_grpc_utils_add_test`
- We saw `google-cloud-cpp::grpc_utils` depends on `google-cloud-cpp::iam_credentials_v1_iamcredentials_protos`, 
- The fixture which is getting the error (validate_metadata) is built in `google_cloud_cpp_testing_grpc`
- So tried adding `google-cloud-cpp::iam_credentials_v1_iamcredentials_protos` to link to `google_cloud_cpp_testing_grpc`
- That one also already has the grpc_utils dependency
- The generated proto files do contain the message name for the request:  "google.iam.credentials.v1.GenerateAccessTokenResponse"; is in `.build/google/iam/v1/common.pb.h`
- I found the symbol, a function GenerateAccessToken, but no string corresponding to  "google.iam.credentials.v1.GenerateAccessToken" in the .build

**Comment by alevenberg** [comment]
Maybe it is the annotations:

```
const char descriptor_table_protodef_google_2fiam_2fcredentials_2fv1_2fiamcredentials_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
"google/iam/credentials/v1/co"
  "mmon.proto2\255\007\n\016IAMCredentials\022\354\001\n\023Genera"
  "teAccessToken\0225.google.iam.credentials.v"
  "1.GenerateAccessTokenRequest\0326.google.ia"
  "m.credentials.v1.GenerateAccessTokenResp"
  "onse\"f\202\323\344\223\002@\";/v1/{name=projects/*/servi"
  "ceAccounts/*}:generateAccessToken:\001*\332A\035n"
  "ame,delegates,scope,lifetime"

```

**Comment by alevenberg** [comment]
There is ```class IAMCredentials final {
 public:
  static constexpr char const* service_full_name() {
    return "google.iam.credentials.v1.IAMCredentials";
  }``` 
in `/.build/external/googleapis/google/iam/credentials/v1/iamcredentials.grpc.pb.h`

**Comment by coryan** [comment]
I was able to get this to work with these changes:

```diff
diff --git a/google/cloud/internal/minimal_iam_credentials_stub_test.cc b/google/cloud/internal/minimal_iam_credentials_stub_test.cc
index f1b4044f27..fec203d376 100644
--- a/google/cloud/internal/minimal_iam_credentials_stub_test.cc
+++ b/google/cloud/internal/minimal_iam_credentials_stub_test.cc
@@ -160,8 +160,9 @@ TEST_F(MinimalIamCredentialsStubTest, Invalid) {
 }
 
 // For some reasons the method name is not found in IsContextMDValid()
-TEST_F(MinimalIamCredentialsStubTest,
-       DISABLED_AsyncGenerateAccessTokenMetadata) {
+TEST_F(MinimalIamCredentialsStubTest, AsyncGenerateAccessTokenMetadata) {
+  EXPECT_THAT(descriptor_table_google_2fiam_2fcredentials_2fv1_2fiamcredentials_2eproto.descriptor,
+  ::testing::NotNull());
   auto mock = std::make_shared<MockMinimalIamCredentialsStub>();
   EXPECT_CALL(*mock, AsyncGenerateAccessToken)
       .WillOnce([this](CompletionQueue&, auto context,
```

It seems that `iamcredentials.proto` defines only a `service` and no protos:

https://github.com/googleapis/googleapis/blob/master/google/iam/credentials/v1/iamcredentials.proto

Consequently, the `iamcredentials.pb.h` and `iamcredentials.pb.cc` files are basically empty.  All they have is some data structures to support Protobuf reflection and some global constructors:


```cc

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_google_2fiam_2fcredentials_2fv1_2fiamcredentials_2eproto(&descriptor_table_google_2fiam_2fcredentials_2fv1_2fiamcredentials_2eproto);

```

But none of our code (or gRPC's generated code) uses these symbols directly.  So the C++ linker decides there is no need to include `iamcredentials.pb.o` in our program, the global constructor does not exist in our program, it never gets to run (as it does not exist) and when we try to discover the contents dynamically the Protobuf reflection data structures cannot find it.

Before adding the code forcibly include this `.o` file in our program you can see that the necessary symbols are not linked in:

```
nm .build/google/cloud/internal_minimal_iam_credentials_stub_test  | c++filt | grep descriptor_table_google_2fiam_2f
0000000001682f00 D descriptor_table_google_2fiam_2fcredentials_2fv1_2fcommon_2eproto
00000000008203fc W descriptor_table_google_2fiam_2fcredentials_2fv1_2fcommon_2eproto_getter()
0000000001658e60 d descriptor_table_google_2fiam_2fcredentials_2fv1_2fcommon_2eproto_deps
0000000001694c00 b descriptor_table_google_2fiam_2fcredentials_2fv1_2fcommon_2eproto_once
```

Afterwards there are more symbols:

```
nm .build/google/cloud/internal_minimal_iam_credentials_stub_test  | c++filt | grep descriptor_table_google_2fiam_2f
00000000016b0f60 D descriptor_table_google_2fiam_2fcredentials_2fv1_2fcommon_2eproto
00000000016b0ce0 D descriptor_table_google_2fiam_2fcredentials_2fv1_2fiamcredentials_2eproto
0000000000825af6 W descriptor_table_google_2fiam_2fcredentials_2fv1_2fcommon_2eproto_getter()
00000000008172d3 W descriptor_table_google_2fiam_2fcredentials_2fv1_2fiamcredentials_2eproto_getter()
0000000001685cc0 d descriptor_table_google_2fiam_2fcredentials_2fv1_2fcommon_2eproto_deps
00000000016c3280 b descriptor_table_google_2fiam_2fcredentials_2fv1_2fcommon_2eproto_once
00000000016855c0 d descriptor_table_google_2fiam_2fcredentials_2fv1_2fiamcredentials_2eproto_deps
00000000016c31d4 b descriptor_table_google_2fiam_2fcredentials_2fv1_2fiamcredentials_2eproto_once
```

As to why this works with Bazel. CMake compiles the tests using static libraries.  That is what we told it to do:

```
ldd .build/google/cloud/internal_minimal_iam_credentials_stub_test  
        linux-vdso.so.1 (0x00007ffc4abf4000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd909c00000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd909f21000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd90b71e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd909a1e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd90b756000)
```

In contrast, Bazel uses shared libraries for the test:

```
ldd $(bazel info bazel-bin)/google/cloud/internal_minimal_iam_credentials_stub_test
        linux-vdso.so.1 (0x00007ffd68fcb000)
        libgoogle_Scloud_Stesting_Uutil_Slibgoogle_Ucloud_Ucpp_Utesting_Ugrpc_Uprivate.so => /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/a105f86a6de6212c5d475bb1d14d58b2/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/../../_solib_k8/libgoogle_Scloud_Stesting_Uutil_Slibgoogle_Ucloud_Ucpp_Utesting_Ugrpc_Uprivate.so (0x00007fdb99400000)

snip snip
        libexternal_Scom_Ugoogle_Ugoogleapis_Sgoogle_Siam_Scredentials_Sv1_Slibcredentials_Ucc_Ugrpc.so => /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/a105f86a6de6212c5d475bb1d14d58b2/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/../../_solib_k8/libexternal_Scom_Ugoogle_Ugoogleapis_Sgoogle_Siam_Scredentials_Sv1_Slibcredentials_Ucc_Ugrpc.so (0x00007f5942989000)
        libexternal_Scom_Ugoogle_Ugoogleapis_Sgoogle_Siam_Scredentials_Sv1_Slibcredentials_Uproto.so => /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/a105f86a6de6212c5d475bb1d14d58b2/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/../../_solib_k8/libexternal_Scom_Ugoogle_Ugoogleapis_Sgoogle_Siam_Scredentials_Sv1_Slibcredentials_Uproto.so (0x00007f5942959000)
        libexternal_Scom_Ugithub_Ugrpc_Ugrpc_Ssrc_Score_Slibgrpc_Uiam_Ucredentials.so => /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/a105f86a6de6212c5d475bb1d14d58b2/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/../../_solib_k8/libexternal_Scom_Ugithub_Ugrpc_Ugrpc_Ssrc_Score_Slibgrpc_Uiam_Ucredentials.so (0x00007f594133e000)
        libexternal_Scom_Ugoogle_Ugoogleapis_Sgoogle_Siam_Sv1_Slibiam_Upolicy_Uproto.so => /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/a105f86a6de6212c5d475bb1d14d58b2/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/../../_solib_k8/libexternal_Scom_Ugoogle_Ugoogleapis_Sgoogle_Siam_Sv1_Slibiam_Upolicy_Uproto.so (0x00007f593c1f1000)
        libexternal_Scom_Ugoogle_Ugoogleapis_Sgoogle_Siam_Sv1_Sliboptions_Uproto.so => /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/a105f86a6de6212c5d475bb1d14d58b2/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/../../_solib_k8/libexternal_Scom_Ugoogle_Ugoogleapis_Sgoogle_Siam_Sv1_Sliboptions_Uproto.so (0x00007f593cc47000)
        libexternal_Scom_Ugoogle_Ugoogleapis_Sgoogle_Siam_Sv1_Slibpolicy_Uproto.so => /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/a105f86a6de6212c5d475bb1d14d58b2/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/../../_solib_k8/libexternal_Scom_Ugoogle_Ugoogleapis_Sgoogle_Siam_Sv1_Slibpolicy_Uproto.so (0x00007f593c1bb000)
  
  
  snip snip


        libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest_Umain.so => /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/a105f86a6de6212c5d475bb1d14d58b2/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/../../_solib_k8/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest_Umain.so (0x00007fdb9140f000)
        libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so => /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/a105f86a6de6212c5d475bb1d14d58b2/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/../../_solib_k8/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so (0x00007fdb91299000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdb911a4000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdb90e00000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdb91182000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdb90c1e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdb998e2000)

**Comment by devbww** [comment]
I concur.  But while protobuf can document what code is generated, what actually ends up in the binary is outside their control.  So, it seems, in general, that it is invalid to assert that the method descriptor is available at runtime.

**Comment by coryan** [comment]
> So, it seems, in general, that it is invalid to assert that the method descriptor is available at runtime.

I think I agree that "in general" just referring to a symbol in this TU is not *guaranteed* to fix anything.  In *practice* I think it would (in fact, it does!).

Nevertheless, maybe Protobuf could provide a function returning all the descriptors in the file.  Or a function to initialize the global reflection data structures with all the descriptors in the file.  Those seem like more robust solutions.  I will comment in the bug that I opened with Protobuf.

**Pull request closed without merging**
