### PR TITLE
bug: Use write_basic_package_version_file to generate cmake configs

### PR DESCRIPTION
**Pull request by remyabel**
Fixes: #4267

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5374)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
Thanks, this really helps, one question that maybe simplifies the code. +kokoro:run 

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5374#-:-MKqY4BC3i9XYL9FOsuG:b-p6ubng)* status: all files reviewed, 1 unresolved discussion (waiting on @remyabel)

___
*[external/googleapis/CMakeLists.txt, line 458 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5374#-MKqYLM_1VW4Gd3eAx0y:-MKqYLMa2x4N1UDwBpoR:b-gt1o9y) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/3ac89a78daaf5ae7021d31608820a15b32d95fcd/external/googleapis/CMakeLists.txt#L458)):*
> ```CMake
>     "googleapis-config-version.cmake"
>     VERSION
>         ${GOOGLE_CLOUD_CPP_VERSION_MAJOR}.${GOOGLE_CLOUD_CPP_VERSION_MINOR}.${GOOGLE_CLOUD_CPP_VERSION_PATCH}
> ```

Here and below, can we use this:

https://github.com/googleapis/google-cloud-cpp/blob/4cbc8962a2cef8ef51729d65b4a5a171e46662c2/CMakeLists.txt#L26

?

**Comment by remyabel** [comment]
`SameMinorVersion` is not available in [CMake 3.5](https://cmake.org/cmake/help/v3.5/module/CMakePackageConfigHelpers.html). Thoughts?

**Comment by coryan** [comment]
> `SameMinorVersion` is not available in [CMake 3.5](https://cmake.org/cmake/help/v3.5/module/CMakePackageConfigHelpers.html).

Seems like it appears in 3.11:

https://cmake.org/cmake/help/v3.10/module/CMakePackageConfigHelpers.html
https://cmake.org/cmake/help/v3.10/module/CMakePackageConfigHelpers.html

> Thoughts?

Several, but I don't trust myself (I am a bit tired today):

- Leave the code as-is, how different is the behavior.
- Use `ExactSameVersion` for CMake <= 3.10. We rarely create patch releases, and even then, most applications would not specify a version in their `find_package()`.
- Always use `ExactSameVersion`.

I think I like the second option best... but maybe wait until I am more rested.

**Comment by coryan** [comment]
> > `SameMinorVersion` is not available in [CMake 3.5](https://cmake.org/cmake/help/v3.5/module/CMakePackageConfigHelpers.html).
> 
> Seems like it appears in 3.11:
> 
> https://cmake.org/cmake/help/v3.10/module/CMakePackageConfigHelpers.html
> https://cmake.org/cmake/help/v3.10/module/CMakePackageConfigHelpers.html
> 
> > Thoughts?
> 
> Several, but I don't trust myself (I am a bit tired today):
> 
> * Leave the code as-is, how different is the behavior.
> * Use `ExactSameVersion` for CMake <= 3.10. We rarely create patch releases, and even then, most applications would not specify a version in their `find_package()`.
> * Always use `ExactSameVersion`.
> 
> I think I like the second option best... but maybe wait until I am more rested.

Thanks for waiting.  I think we should go with "Always use `ExactSameVersion`", we can always change that to a more relaxed definition as we gain more experience and/or drop CMake-3.5 support.

**Comment by coryan** [comment]
___
*[external/googleapis/CMakeLists.txt, line 458 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5374#-MKqYLM_1VW4Gd3eAx0y:-MKvF7qI77XEhGkJxHy8:bmx2efh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/3ac89a78daaf5ae7021d31608820a15b32d95fcd/external/googleapis/CMakeLists.txt#L458)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Here and below, can we use this:

https://github.com/googleapis/google-cloud-cpp/blob/4cbc8962a2cef8ef51729d65b4a5a171e46662c2/CMakeLists.txt#L26

?
</blockquote></details>

Any thoughts on this?

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5374)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[external/googleapis/CMakeLists.txt, line 458 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5374#-MKqYLM_1VW4Gd3eAx0y:-MKvid6-6bykr4WrILdS:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/3ac89a78daaf5ae7021d31608820a15b32d95fcd/external/googleapis/CMakeLists.txt#L458)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Any thoughts on this?
</blockquote></details>

Done.

**Review by coryan — APPROVED** [review]
> Reviewed 8 of 8 files at r2, 1 of 1 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5374)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
