### PR TITLE
chore: update gcloud version

### PR DESCRIPTION
**Pull request by alevenberg**
Updating to get the pub/sub changes. You can find the SHA here https://cloud.google.com/sdk/docs/install-sdk#linux for future updates.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13764)

### CODE REVIEW

**Review by coryan — APPROVED** [review]

**Comment by devbww** [comment]
That emulator log output looks different to how it was before, making me think the output may not be being flushed in the same way, which means we never get to witness the "Server address" line before we time out.

**Comment by alevenberg** [comment]
Current output: 
```
I0000 00:00:1710352531.742451  242820 emulator_main.cc:40] Server address: localhost:8787
```
Old output:
```
Step #5:     17	2024-03-11 21:49:57  INFO  emulator_main.cc : 40 : Server address: localhost:8789
```

We believe the culprit is in google/cloud/spanner/ci/lib/spanner_emulator.sh
```
# Outputs the port number that the emulator chose to listen on.
function spanner_emulator::internal::read_emulator_port() {
  local -r logfile="$1"
  shift

  local emulator_port="0"
  local -r expected=" Server address: "
  for _ in $(seq 1 8); do
    if grep -q -s "${expected}" "${logfile}"; then
      # The port number is whatever is after the last ':'.
      emulator_port=$(grep "${expected}" "${logfile}" | awk -F: '{print $NF}')
      break
    fi
    sleep 1
  done
  echo "${emulator_port}"
}
```

**Comment by coryan** [comment]
I think it is specifically this line:

https://github.com/googleapis/google-cloud-cpp/blob/26b80a8c2650b7fca451406f54474da19618effa/google/cloud/spanner/ci/lib/spanner_emulator.sh#L36C23-L36C36

The ` : ` before `Server address:` is now gone.  I would try changing that line to:

```
  local -r expected=" Server address: "
```

**Comment by alevenberg** [comment]
Yes we agree @coryan. Running that now.

**Pull request merged**
