### PR TITLE
feat: Implement backup level IAM operations

### PR DESCRIPTION
**Pull request by amitchauhan1007**
Contains code for supporting backup level GetIAMPolicy , SetIAMPolicy and TestIAMPermissions.
Also contains corresponding unit tests.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
Consider these ideas:

1) Print the contents of `http` here:

https://github.com/googleapis/google-cloud-cpp/blob/6646c2aa4cea7df30b018b6907fa257b1e876a1c/google/cloud/testing_util/validate_metadata.cc#L173

It should be easy with `http.DebugString()` and see if the information we want is present.

2) Consider adding an overload to `IsContextMDValid()` which takes additional patterns as a parameter, and hard-code the patterns for the RPCs you need.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-:-MNPUrMd1NRv1ttSp79K:b-75z9qx)* status: all files reviewed, 3 unresolved discussions (waiting on @amitchauhan1007)

___
*[google/cloud/bigtable/table_admin.h, line 1394 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNPT3MqDGgxA4eFDI7v:-MNPT3MqDGgxA4eFDI7w:b-ju024e) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21aa273bc3eaffc6db58abebe25a065f3e4800bd/google/cloud/bigtable/table_admin.h#L1394)):*
> ```objc
> 
>   StatusOr<google::iam::v1::Policy> GetIamPolicy(std::string const& table_id);
>   /**
> ```

nit: insert blank line after the function declaration and remove the blank line before it.
___
*[google/cloud/bigtable/table_admin.h, line 1552 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNPTEZaBlcUykbu_Cx3:-MNPTEZaBlcUykbu_Cx4:bxxlhbv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21aa273bc3eaffc6db58abebe25a065f3e4800bd/google/cloud/bigtable/table_admin.h#L1552)):*
> ```objc
> 
>   /**
>    * Returns a permission set that the caller has on the specified table.
> ```

s/specified table/specified backup/

cut&paste?
___
*[google/cloud/bigtable/table_admin_test.cc, line 903 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNPUTSB-JYYbdfcZB4L:-MNPUTSB-JYYbdfcZB4M:b-rzelvu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21aa273bc3eaffc6db58abebe25a065f3e4800bd/google/cloud/bigtable/table_admin_test.cc#L903)):*
> ```cpp
>   TableAdmin tested(client_, "the-instance");
>   auto mock_policy = create_get_policy_mock();
>   EXPECT_CALL(*client_, GetIamPolicy(_, _, _)).WillOnce(mock_policy);
> ```

Here and elsewhere: you do not need `(_, _, _)`, simply say `EXPECT_CALL(*client_, GetIamPolicy)`

**Comment by amitchauhan1007** [comment]
Added code to handle additional_bindings and also unit test code for Get,Set and Test IAM policy. 
Please review

**Comment by amitchauhan1007** [comment]
> Consider these ideas:
> 
> 1. Print the contents of `http` here:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/6646c2aa4cea7df30b018b6907fa257b1e876a1c/google/cloud/testing_util/validate_metadata.cc#L173
> 
> It should be easy with `http.DebugString()` and see if the information we want is present.
> 
> 1. Consider adding an overload to `IsContextMDValid()` which takes additional patterns as a parameter, and hard-code the patterns for the RPCs you need.
> 
> > Reviewed 5 of 5 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-:-MNPUrMd1NRv1ttSp79K:b-75z9qx)_ status: all files reviewed, 3 unresolved discussions (waiting on @amitchauhan1007)
> 
> _[google/cloud/bigtable/table_admin.h, line 1394 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNPT3MqDGgxA4eFDI7v:-MNPT3MqDGgxA4eFDI7w:b-ju024e) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21aa273bc3eaffc6db58abebe25a065f3e4800bd/google/cloud/bigtable/table_admin.h#L1394)):_
> 
> > ```objc
> >   StatusOr<google::iam::v1::Policy> GetIamPolicy(std::string const& table_id);
> >   /**
> > ```
> 
> nit: insert blank line after the function declaration and remove the blank line before it.
>    Done
> _[google/cloud/bigtable/table_admin.h, line 1552 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNPTEZaBlcUykbu_Cx3:-MNPTEZaBlcUykbu_Cx4:bxxlhbv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21aa273bc3eaffc6db58abebe25a065f3e4800bd/google/cloud/bigtable/table_admin.h#L1552)):_
> 
> > ```objc
> >   /**
> >    * Returns a permission set that the caller has on the specified table.
> > ```
> 
> s/specified table/specified backup/
> 
> cut&paste?
>  Done
> _[google/cloud/bigtable/table_admin_test.cc, line 903 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNPUTSB-JYYbdfcZB4L:-MNPUTSB-JYYbdfcZB4M:b-rzelvu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21aa273bc3eaffc6db58abebe25a065f3e4800bd/google/cloud/bigtable/table_admin_test.cc#L903)):_
> 
> > ```c++
> >   TableAdmin tested(client_, "the-instance");
> >   auto mock_policy = create_get_policy_mock();
> >   EXPECT_CALL(*client_, GetIamPolicy(_, _, _)).WillOnce(mock_policy);
> > ```
> 
> Here and elsewhere: you do not need `(_, _, _)`, simply say `EXPECT_CALL(*client_, GetIamPolicy)`

Done

**Comment by amitchauhan1007** [comment]
> Consider these ideas:
> 
> 1. Print the contents of `http` here:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/6646c2aa4cea7df30b018b6907fa257b1e876a1c/google/cloud/testing_util/validate_metadata.cc#L173
> 
> It should be easy with `http.DebugString()` and see if the information we want is present.
> 
> 1. Consider adding an overload to `IsContextMDValid()` which takes additional patterns as a parameter, and hard-code the patterns for the RPCs you need.
> 
> > Reviewed 5 of 5 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-:-MNPUrMd1NRv1ttSp79K:b-75z9qx)_ status: all files reviewed, 3 unresolved discussions (waiting on @amitchauhan1007)
> 
> _[google/cloud/bigtable/table_admin.h, line 1394 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNPT3MqDGgxA4eFDI7v:-MNPT3MqDGgxA4eFDI7w:b-ju024e) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21aa273bc3eaffc6db58abebe25a065f3e4800bd/google/cloud/bigtable/table_admin.h#L1394)):_
> 
> > ```objc
> >   StatusOr<google::iam::v1::Policy> GetIamPolicy(std::string const& table_id);
> >   /**
> > ```
> 
> nit: insert blank line after the function declaration and remove the blank line before it.
> 
Done
> _[google/cloud/bigtable/table_admin.h, line 1552 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNPTEZaBlcUykbu_Cx3:-MNPTEZaBlcUykbu_Cx4:bxxlhbv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21aa273bc3eaffc6db58abebe25a065f3e4800bd/google/cloud/bigtable/table_admin.h#L1552)):_
> 
> > ```objc
> >   /**
> >    * Returns a permission set that the caller has on the specified table.
> > ```
> 
> s/specified table/specified backup/
> 
> cut&paste?
> 
Done
> _[google/cloud/bigtable/table_admin_test.cc, line 903 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNPUTSB-JYYbdfcZB4L:-MNPUTSB-JYYbdfcZB4M:b-rzelvu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21aa273bc3eaffc6db58abebe25a065f3e4800bd/google/cloud/bigtable/table_admin_test.cc#L903)):_
> 
> > ```c++
> >   TableAdmin tested(client_, "the-instance");
> >   auto mock_policy = create_get_policy_mock();
> >   EXPECT_CALL(*client_, GetIamPolicy(_, _, _)).WillOnce(mock_policy);
> > ```
> 
> Here and elsewhere: you do not need `(_, _, _)`, simply say `EXPECT_CALL(*client_, GetIamPolicy)`

Done

**Review by coryan — CHANGES_REQUESTED** [review]
+kokoro:run there are still some documentation problems.  I expect you will need to rebase this to pickup the latest changes from the `master` branch.

> Reviewed 5 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-:-MNjHomN4Q20x8X7CnWX:b-ckpi9z)* status: all files reviewed, 2 unresolved discussions (waiting on @amitchauhan1007)

___
*[tags, line 0 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNjGjNC8v8EXV-wWaSA:-MNjGjNC8v8EXV-wWaSB:bo0vfeg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4cd5a37b6748d9e99297830cb2c33281d4cd4ca5/tags#L0)):*
Please do not commit this...
___
*[google/cloud/bigtable/table_admin.h, line 1469 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5559#-MNjHAmZCvZ4q_-TWard:-MNjHAm_Dt2AQ3tQI7Qk:b-ijbd91) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4cd5a37b6748d9e99297830cb2c33281d4cd4ca5/google/cloud/bigtable/table_admin.h#L1469)):*
> ```objc
> 
>   /**
>    * Sets the IAM policy for a table.
> ```

s/table/backup/

**Pull request closed without merging**
