### PR TITLE
fix(spanner): add Options save/restore to PartialResultSetSource

### PR DESCRIPTION
**Pull request by devbww**
Save the options in force during `PartialResultSetSource` construction,
and then restore them over `PartialResultSetReader` calls.  This means
that `NextRow()`, `Finish()` and `TryCancel()` will have the right
options installed during any RPCs they execute.

Tighten up the test by installing a non-matching `OptionsSpan` before
any `NextRow()` calls are made, and by expecting no `TryCancel()`s in
cases that complete their enumeration.

This is the Spanner equivalent of #8256.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8355)

### CODE REVIEW

**Review by coryan — APPROVED** [review]
This got me thinking, should we make analogous changes to the resumable streaming RPC:

https://github.com/googleapis/google-cloud-cpp/blob/18082df93f4de5e52b97464eadc21f8e40a539a9/google/cloud/internal/resumable_streaming_read_rpc.h#L93-L99

**Comment by devbww** [comment]
> This got me thinking, should we make analogous changes to the resumable streaming RPC

I'll look into it.

**Review by coryan — APPROVED** [review]

**Comment by devbww** [comment]
> > This got me thinking, should we make analogous changes to the resumable streaming RPC
> 
> I'll look into it.

I had thought that the `StreamRange` changes would handle this, but it looks like there is a hole when the `StreamRange` destroys its `reader_`, as that might cause a cancellation RPC without the right options if the reader is not yet finished.  I'm investigating fixing that, and making the generated and Spanner cases look as similar as possible.

**Comment by devbww** [comment]
> > > This got me thinking, should we make analogous changes to the resumable streaming RPC
> > 
> > 
> > I'll look into it.
> 
> I had thought that the `StreamRange` changes would handle this, but it looks like there is a hole when the `StreamRange` destroys its `reader_`, as that might cause a cancellation RPC without the right options if the reader is not yet finished. I'm investigating fixing that, and making the generated and Spanner cases look as similar as possible.

I don't think there was really a hole, as destroying the unfinished streaming reader only calls directly into gRPC to try to cancel the stream.  That is, there is no cancellation RPC or other code that might look at our `Options`.  But, we should probably always restore the operation-start options whenever the user can call back into the library, no matter what code we think that executes.  So, I created #8403.

**Comment by coryan** [comment]
> 
> I don't think there was really a hole, as destroying the unfinished streaming reader only calls directly into gRPC to try to cancel the stream.

I was thinking about `google::cloud::internal::ResumableStreamingReadRpc<>`, I just created #8404, you can tell me there if the changes are not needed.

**Pull request merged**
