### PR TITLE
feat(pubsublite): pubsub to pubsublite translation layer

### PR DESCRIPTION
**Pull request by 18suresha**
This PR implements the translation layer to convert Pub/Sub messages to Pub/Sub Lite messages.

TODO: update CMake build configs with Pub/Sub Lite protos

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8612)

### CODE REVIEW

**Comment by coryan** [comment]
Is there a design document explaining why we need this?

**Review by dpcollins-google — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8612)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsub/options.h, line 275 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8612#-MzL38fM8s_N88hnQM4r:-MzL38fM8s_N88hnQM4s:bsabh3x) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8ba6d7ec89e28a3c203ad4b4bcb419d5255d884d/google/cloud/pubsub/options.h#L275)):*
> ```objc
>  * A function to convert a Pub/Sub message to a Pub/Sub Lite message.
>  */
> struct PublishMessageTransformer {
> ```

This should live in the google/cloud/pubsublite directory not the pubsub one



_Code quote:_
```objc
 */
struct PublishMessageTransformer {
  using Type =
      std::function<StatusOr<google::cloud::pubsublite::v1::SequencedMessage>(
          google::cloud::pubsub::Message)>;
};
```
___
*[google/cloud/pubsub/internal/defaults.h, line 41 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8612#-MzL3Dhj0DcwQfmwzx_K:-MzL3Dhj0DcwQfmwzx_L:b-7ropln) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8ba6d7ec89e28a3c203ad4b4bcb419d5255d884d/google/cloud/pubsub/internal/defaults.h#L41)):*
> ```objc
> Options DefaultSubscriberOptionsOnly(Options opts);
> 
> StatusOr<google::cloud::pubsublite::v1::SequencedMessage>
> ```

ditto



_Code quote:_
```objc
StatusOr<google::cloud::pubsublite::v1::SequencedMessage>
DefaultPublishMessageTransformer(const google::cloud::pubsub::Message&);
```
___
*[google/cloud/pubsub/internal/defaults.cc, line 71 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8612#-MzL3NWo5G7txyAdAUwQ:-MzL3NWo5G7txyAdAUwR:b-4ebsio) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8ba6d7ec89e28a3c203ad4b4bcb419d5255d884d/google/cloud/pubsub/internal/defaults.cc#L71)):*
> ```cpp
>   }
>   if (!opts.has<PublishMessageTransformer>()) {
>     opts.set<PublishMessageTransformer>(DefaultPublishMessageTransformer);
> ```

I should have clarified: The Pub/Sub Lite connection factory function will be a separate function from the Cloud Pub/Sub one. It will just have the same structure as the cloud Pub/Sub one. You should not modify any Cloud Pub/Sub files



_Code quote:_
```cpp
  if (!opts.has<PublishMessageTransformer>()) {
    opts.set<PublishMessageTransformer>(DefaultPublishMessageTransformer);
  }
```

**Comment by dpcollins-google** [comment]
___
*[google/cloud/pubsub/internal/defaults.cc, line 161 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8612#-MzL5VHDBMt9qdyVHnUa:-MzL5VHDBMt9qdyVHnUb:bw6fmyh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8ba6d7ec89e28a3c203ad4b4bcb419d5255d884d/google/cloud/pubsub/internal/defaults.cc#L161)):*
> ```cpp
> }
> 
> StatusOr<SequencedMessage> DefaultPublishMessageTransformer(
> ```

The return type is `PubsubMessage` not `SequencedMessage`

**Comment by 18suresha** [comment]
https://github.com/googleapis/google-cloud-cpp/pull/8736

**Pull request closed without merging**
