### PR TITLE
impl(bigquery): Job apis Response and request field name changes

### PR DESCRIPTION
**Pull request by jsrinnn**
This and subsequent PRs fix the json field names in request and responses for all V2 apis to be conformant with the API docs

Initially the field names were just taken from the proto. But I noticed that the api docs (e.g https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs) have different json request and response names. Most of the request field names are in accordance. Its mainly the json response field names that need changing

1) This specific PR makes the response and request json field names changes for all job apis. I will have few more PRs after this one which will changes it for the other resources (i.e Dataset, table and project)

2) Please note that no logic has been changed. Just the json field names and corresponding unit tests reflect those changes.

I am tracking each of the resource separately with Github issues. This specific PR fixes https://github.com/googleapis/google-cloud-cpp/issues/12107

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
The new C++ field names do not follow the C++ style guide.  I realized you need this for `NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT`, but it is not going to fly.


Could we rename the fields in JSON?  Something like:

```cc
auto body = Snakefy(to_json(Job{....}));
// body is a `nlohmann::json` class with `snakeCaseNames`
```

The `Snakefy` function would be something like:

```cc
std::string Snakefy(absl::string_view s) { ... we have one of these in the generator I think or Protobuf has one .... }

nlohman::json Snakefy(nlohman::json j) {
  auto r = nlohman::json{};
  for (auto& kv : j.items()) {
    r[Snakefy(kv.key())] = Snakefy(std::move(kv).value());
  }
  return r;
}
```

You would also need a `Desnake()` function, and maybe come up with better names :grin: 

> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-:-N_i6Vsy8GnUD39DTuWF:b-kdfg03)* status: all files reviewed, 4 unresolved discussions (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h` line 49 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i0HyLBckS6CvMIReK:-N_i0HyLBckS6CvMIReL:bthfbol) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h#L49)):*
> ```objc
> 
> struct TableReference {
>   std::string projectId;
> ```

I think we should to keep the fields in C++ style, even if they are not the JSON names.
___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h` line 70 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i1MNEASfekUj9P_x1:-N_i1MNEASfekUj9P_x2:b-9rvkgx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h#L70)):*
> ```objc
> };
> NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT(DatasetReference, projectId,
>                                                 datasetId);
> ```

Ugh, I see, `nlohmann` macros... is it possible to use different field names?
___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h` line 391 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i1bf-3jk9CNVof3-d:-N_i1bf-3jk9CNVof3-e:b-hhsep5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h#L391)):*
> ```objc
> bool operator==(QueryParameter const& lhs, QueryParameter const& rhs);
> 
> struct SessionInfo {
> ```

Why do we need to move this class to a different header?
___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc` line 137 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i0fYX2RwljyMhzwUt:-N_i0fYX2RwljyMhzwUu:byrtm9l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc#L137)):*
> ```cpp
> void from_json(nlohmann::json const& j, StandardSqlDataType& t) {
>   if (j.contains("typeKind")) j.at("typeKind").get_to(t.type_kind);
>   if (j.contains("sub_type_index")) {
> ```

This is more than a field name, intentional?

**Review by jsrinnn — COMMENTED** [review]
The tricky part here for the V2 apis  is not all json fields in the response is snakified. For instance, for the `Job` resource (https://cloud.google.com/bigquery/docs/reference/rest/v2/Job) not all fields are snakified. `user_email` and `principal_subject` are same as their protobuf versions. This is true for other resources as well. I would prefer not special case Snakefy with specific `if..then..else` for each of these fields

The simplest thing to do was modify the field names to be what is needed in the Json response. The other alternative which I mentioned in another comment below is to write `to_json()` and `from_json()` method for all structs/classes. A lot of work but that does achieve the desire to keep the field names the same.

Let me know what you think.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-:-N_iOqcC7fMHMBrm25UO:b-b476ta)* status: all files reviewed, 4 unresolved discussions (waiting on @coryan)

___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h` line 49 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i0HyLBckS6CvMIReK:-N_iNL9U3C2MOl4EMxe9:byrhw9e) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h#L49)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think we should to keep the fields in C++ style, even if they are not the JSON names.
</blockquote></details>

That would be tricky as the NLOHMANN macros uses the field names to also be JSON names. The alternative would be to remove the nlohmann macros and write manual `to_json()` and `from_json()` methods for all struct/classes. A lot of (redundant) work but does achieve the intent to keep the field names in C++ style and just change the json fields. 

If you notice, I have not changes the field names for structs/classes that have a manual `to_json()` and `from_json() ` methods.
___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h` line 70 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i1MNEASfekUj9P_x1:-N_iNJ3x3hxQPnR7AwPO:b-le5ht8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h#L70)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Ugh, I see, `nlohmann` macros... is it possible to use different field names?
</blockquote></details>

Not as far as I know. The struct field names are used as JSON field names as well.
___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h` line 391 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i1bf-3jk9CNVof3-d:-N_iNw6n5euZ92WszDiR:byb2fnx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h#L391)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Why do we need to move this class to a different header?
</blockquote></details>

Oh...only because it was used in multiple places so I put it in a common header. The `common_v2_resources` header is meant to be included in multiple files needing the same resource.
___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc` line 137 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i0fYX2RwljyMhzwUt:-N_iOBKl5ZKr_DYf5FXB:b-11afhp) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc#L137)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is more than a field name, intentional?
</blockquote></details>

The `typeKind` is the actual field in the json response. The `sub_type_index` is an additional metadata field added (not part of actual json response), to figure out the type of the field for fields of multiple types. This was there before and has not been changed.

**Review by jsrinnn — COMMENTED** [review]
Addressed all feedback. PTAL.

Thanks Carlos!

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-:-N_lkwEP3VeLf0M4QZZE:b-ke0hiz)* status: 35 of 36 files reviewed, 3 unresolved discussions (waiting on @coryan)

___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h` line 49 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i0HyLBckS6CvMIReK:-N_lko5v0ZJ14Q-V7Ukw:b-atdwgo) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h#L49)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I see, tedious work indeed... There are about invocations of the `NLOHMANN_*` macros.  While still tedious, the work can be reduced with things like:

```cc
void from_json(nlohmann::json const& j, TableReference& t) {
  internal::set_json_field(j, t.project_id, "projectId");
  internal::set_json_field(j, t.dataset_id, "datasetId");
  internal::set_json_field(j, t.table_id, "tableId");
}
```

and even a helper macro:

```cc
#define GCP_GET_JSON_FIELD(J, T, FIELD_NAME) internal::set_json_field((J), (T).FIELD_NAME, Snakefy(#FIELD_NAME))


void from_json(nlohmann::json const& j, TableReference& t) {
  GCP_GET_JSON_FIELD(j, t, project_id);
  GCP_GET_JSON_FIELD(j, t, dataset_id);
  GCP_GET_JSON_FIELD(j, t, table_id);
  // use internal::set_json_field() directly when there is no need to Snakefy things.
}
```

There is a run-time cost to the helper macro. We can evaluate which ones are important to optimize, if any, and call `internal::set_json_field` (or `internal::SetJsonField()` sigh) where needed.

Or (for extra credit), we could memoize these `Snakefy()` calls, or turn them into `constexpr` functions (that may be impossible until C++17 or C++20).  In any case, the run-time costs can be minimized where needed.


</blockquote></details>

Done.

Replaced default macros with manual to_json() and from_json() method where applicable
___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h` line 391 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i1bf-3jk9CNVof3-d:-N_lkkxo1AIXKzj0XpRW:b-kv3vv5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h#L391)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

That seems fine, but the PR description does not match what is happening.  Maybe split the PR?
</blockquote></details>

Done.

Fair enough. I have reverted this change.
___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc` line 137 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_i0fYX2RwljyMhzwUt:-N_kxHJdC_7SnTAPiMPb:bf2pmwd) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/781ae89ddc6032dd8e7333649fbfd838c1d7f2d6/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc#L137)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

But you had `j.contains("sub_type_index) && j.contains("sub_type")`, the second part of that conjunction went away.  I realize that now the `sub_type` goes by either `arrayElementType` or `struct` type, but the new code would throw an exception where the old code took no action.  Maybe we need some new `if()` statements in the switch statement?
</blockquote></details>

Done.

Gotcha. Thanks.

Added the if() statements.

**Review by coryan — APPROVED** [review]
> Reviewed 25 of 25 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149)* status: all files reviewed, 4 unresolved discussions (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc` line 551 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nJtVdDpQb_ZTr4DwC:-N_nJtVdDpQb_ZTr4DwD:bbblv3n) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bbea752b630e6e6d245c2c3959ba78413baa1611/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc#L551)):*
> ```cpp
> }
> void from_json(nlohmann::json const& j, TableReference& t) {
>   if (j.contains("projectId")) j.at("projectId").get_to(t.project_id);
> ```

TIL: `get_to()`.  

For a future PR (and only if there is evidence that it matters): `.contains()` performs a lookup, probably something O(log(N)) on the number of keys.  Then `.at()` performs another O(log(N)) lookup.  And each builds a `std::string` from the string literal.  You could do:

```cc
void SafeGetTo(std::string& value, nlohmann::json const& j, std::string const& key) {
  auto i = j.find(key);
  if (i != j.end()) i->get_to(value);
}
```

Then we can write:

```cc
void to_json(...) {
  SafeGetTo(t.project_id, j, "projectId");
}
```



PS: In C++17 we would just write:

```cc
void to_json(...) {
  if (auto i = j.find("projectId); i != j.end()) i->get_to(t.project_id);
}
```
___
*[`google/cloud/bigquery/v2/minimal/internal/job.cc` line 115 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nLkBVBZ50TV_X37gP:-N_nLkBW--40uJt2VyAG:bd1qpi) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bbea752b630e6e6d245c2c3959ba78413baa1611/google/cloud/bigquery/v2/minimal/internal/job.cc#L115)):*
> ```cpp
>   if (j.contains("jobReference")) j.at("jobReference").get_to(jb.job_reference);
>   if (j.contains("configuration"))
>     j.at("configuration").get_to(jb.configuration);
> ```

nit: too long for a single line.
___
*[`google/cloud/bigquery/v2/minimal/internal/job.cc` line 137 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nLrWtExKmLZclKYNU:-N_nLrWtExKmLZclKYNV:bdrcgc8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bbea752b630e6e6d245c2c3959ba78413baa1611/google/cloud/bigquery/v2/minimal/internal/job.cc#L137)):*
> ```cpp
>   if (j.contains("state")) j.at("state").get_to(l.state);
>   if (j.contains("principal_subject"))
>     j.at("principal_subject").get_to(l.principal_subject);
> ```

nit: too long for a single line
___
*[`google/cloud/bigquery/v2/minimal/internal/job_stats.h` line 140 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nMjrj65HcZdde2q1D:-N_nMjrj65HcZdde2q1E:b-uqdnjw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bbea752b630e6e6d245c2c3959ba78413baa1611/google/cloud/bigquery/v2/minimal/internal/job_stats.h#L140)):*
> ```objc
> 
>   std::string parent_job_id;
>   SessionInfo session_info;
> ```

This is also more than just a naming change.  I assume the fields need to be nested for some reason?  Please consider splitting changes like this, it will make your life easier in the future too.
___
*[`google/cloud/bigquery/v2/minimal/internal/job_stats.cc` line 192 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nMOJ_AYFrT3cKqVde:-N_nMOJ_AYFrT3cKqVdf:b-gjaicm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bbea752b630e6e6d245c2c3959ba78413baa1611/google/cloud/bigquery/v2/minimal/internal/job_stats.cc#L192)):*
> ```cpp
> void from_json(nlohmann::json const& j, TransactionInfo& t) {
>   if (j.contains("transactionId"))
>     j.at("transactionId").get_to(t.transaction_id);
> ```

nit: line too long
___
*[`google/cloud/bigquery/v2/minimal/internal/job_stats.cc` line 201 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nMQ5O5BcMn5g612sc:-N_nMQ5O5BcMn5g612sd:b-gjaicm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bbea752b630e6e6d245c2c3959ba78413baa1611/google/cloud/bigquery/v2/minimal/internal/job_stats.cc#L201)):*
> ```cpp
> void from_json(nlohmann::json const& j, ScriptStatistics& s) {
>   if (j.contains("evaluationKind"))
>     j.at("evaluationKind").get_to(s.evaluation_kind);
> ```

nit: line too long

**Review by jsrinnn — COMMENTED** [review]
Addressed latest around of feedback and enabling auto-merge.

Thanks!

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-:-N_pF1wt-vmsJg7Kiaji:b-67y3pf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc` line 551 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nJtVdDpQb_ZTr4DwC:-N_pCL-rBnyxxXUTxsAM:b-92merv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c85fe4b9e2d8879e4d4c9bf40f9b9e4f293efd98/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.cc#L551)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

TIL: `get_to()`.  

For a future PR (and only if there is evidence that it matters): `.contains()` performs a lookup, probably something O(log(N)) on the number of keys.  Then `.at()` performs another O(log(N)) lookup.  And each builds a `std::string` from the string literal.  You could do:

```cc
void SafeGetTo(std::string& value, nlohmann::json const& j, std::string const& key) {
  auto i = j.find(key);
  if (i != j.end()) i->get_to(value);
}
```

Then we can write:

```cc
void to_json(...) {
  SafeGetTo(t.project_id, j, "projectId");
}
```



PS: In C++17 we would just write:

```cc
void to_json(...) {
  if (auto i = j.find("projectId); i != j.end()) i->get_to(t.project_id);
}
```


</blockquote></details>

Ack.

Created a tracking bug for the above: https://github.com/googleapis/google-cloud-cpp/issues/12188 and added a TODO here.
___
*[`google/cloud/bigquery/v2/minimal/internal/job.cc` line 115 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nLkBVBZ50TV_X37gP:-N_pCzYUA1a85rzlDLuX:bb6un1j) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c85fe4b9e2d8879e4d4c9bf40f9b9e4f293efd98/google/cloud/bigquery/v2/minimal/internal/job.cc#L115)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: too long for a single line.
</blockquote></details>

Done
___
*[`google/cloud/bigquery/v2/minimal/internal/job.cc` line 137 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nLrWtExKmLZclKYNU:-N_pD8eX30nyjElPwukJ:b3jobh7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c85fe4b9e2d8879e4d4c9bf40f9b9e4f293efd98/google/cloud/bigquery/v2/minimal/internal/job.cc#L137)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: too long for a single line
</blockquote></details>

Done. 

Modified here and other places as well.
___
*[`google/cloud/bigquery/v2/minimal/internal/job_stats.h` line 140 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nMjrj65HcZdde2q1D:-N_pDP5U4HRGcsFpPrmM:b-y6ujjy) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c85fe4b9e2d8879e4d4c9bf40f9b9e4f293efd98/google/cloud/bigquery/v2/minimal/internal/job_stats.h#L140)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is also more than just a naming change.  I assume the fields need to be nested for some reason?  Please consider splitting changes like this, it will make your life easier in the future too.
</blockquote></details>

I just made them as they were listed in the json response.  Previously they were flattened to `session_id` , `transaction_id` etc. But in the proto and json response they are part of a `SessionInfo` and `TransactionInfo` objects. I just wanted to make sure the fields here reflects that.

So the change is the in accordance with the original intent  of the PR i.e making sure the custom class fields represents the proto/json response accurately. But you are correct that its slightly more than a name change.
___
*[`google/cloud/bigquery/v2/minimal/internal/job_stats.cc` line 192 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nMOJ_AYFrT3cKqVde:-N_pEYxXAYXKOnspMVSH:b-e5efch) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c85fe4b9e2d8879e4d4c9bf40f9b9e4f293efd98/google/cloud/bigquery/v2/minimal/internal/job_stats.cc#L192)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: line too long
</blockquote></details>

Done.

Made the same changes to other places in the file as well.
___
*[`google/cloud/bigquery/v2/minimal/internal/job_stats.cc` line 201 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12149#-N_nMQ5O5BcMn5g612sc:-N_pEhIoBsKESKCQ1Pgn:bb6un1j) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c85fe4b9e2d8879e4d4c9bf40f9b9e4f293efd98/google/cloud/bigquery/v2/minimal/internal/job_stats.cc#L201)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: line too long
</blockquote></details>

Done

**Pull request merged**
