### PR TITLE
fix: workaround curl_multi_poll returning an error on EINTR

### LINKED ISSUE #11647: curl_multi_wait might erroneously return CURLM_UNRECOVERABLE_POLL
In https://github.com/curl/curl/issues/11135 it was determined that `curl_multi_wait` could sometimes return `CURLM_UNRECOVERABLE_POLL` on EINTR, while in most cases it turns EINTR into a success.

It is a plausible cause for a sporadic error that a user [reported](https://github.com/apache/arrow/issues/35318) when using GCS from Arrow C++:
`google::cloud::Status(UNKNOWN: Permanent error ReadObjectNotWrapped: WaitForHandles(): unexpected error code in curl_multi_*, [12]=Unrecoverable error in select/poll)`

### PR DESCRIPTION
**Pull request by pitrou**
Fixes #11647.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11649)

### CODE REVIEW

**Comment by pitrou** [comment]
For now this implements a workaround in `CurlImpl::WaitForHandles`. Once we agree on that we have to port the workaround to `CurlDownloadRequest::WaitForHandles` (or factor out the logic into a shared helper routine).

@coryan

**Comment by pitrou** [comment]
I'll note that I can't test whether this actually fixes the underlying issue. At least it doesn't seem to break the test suite on my machine.

**Comment by pitrou** [comment]
By the way, this fix assumes we want to retry on EINTR, which seems to make sense but is not the case currently.
In any case, it seems `PerformWorkUntil` loops if `WaitForHandles` returns with success. Thoughts?

**Comment by coryan** [comment]
Thanks very much for the PR. 

> For now this implements a workaround in `CurlImpl::WaitForHandles`. Once we agree on that, I'll have to port the workaround to `CurlDownloadRequest::WaitForHandles` (or factor out the logic into a shared helper routine).

 In all likelihood we will remove that code in a couple of months.  It is there just as an emergency hatch in case the new code does not work for some people, and so far it looks like it is not needed.

The code looks good to me, though it is a bit sad to have so many `#if` branches.


Let's run the build so see if the robots have something to say.

**Comment by coryan** [comment]
The failure with `checkers-pr` is just formatting, you can see what the robots want at the end of:

https://github.com/googleapis/google-cloud-cpp/pull/11649/checks?check_run_id=13593517862

**Review by coryan — APPROVED** [review]

**Pull request merged**
