### PR TITLE
cleanup: use helper function to configure Bazel's toolchain

### PR DESCRIPTION
**Pull request by katre**
…nstead.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9466)

### CODE REVIEW

**Comment by coryan** [comment]
Thanks for the PR!  I have started the CI builds, let's see how they go.

**Comment by katre** [comment]
I can't see the failures. What version of Bazel does your project use? "use_cpp_toolchains" was added in a recent version.

**Comment by coryan** [comment]
> I can't see the failures.

There is a link to public logs in a previous comment:

https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/9466/da4c213d1cde2d68937fde1a09ac6718c46ea0f6/index.html


> What version of Bazel does your project use? "use_cpp_toolchains" was added in a recent version.

That would do it.  We test with Bazel 5.2.0 and Bazel 4.0.0

**Comment by katre** [comment]
Looks like the issue is actually rules_cc, which hasn't yet released the changes with `use_cpp_toolchain`. If I can get them to do a new release, will that be something that we can update in this PR?

**Comment by coryan** [comment]
> Looks like the issue is actually rules_cc, which hasn't yet released the changes with `use_cpp_toolchain`. If I can get them to do a new release, will that be something that we can update in this PR?

Sure, though I suspect the robots would pick such a change and send us a PR too.

**Comment by coryan** [comment]
@katre have you heard back?  If not, maybe we should close this PR until we have some clarity?

**Comment by katre** [comment]
They were cutting a release yesterday but ran into trouble. Can this stay open until early next week?

**Comment by coryan** [comment]
>  Can this stay open until early next week?

Sure, no problem.  I suspect you will need to rebase, we have changed the builds since you started the PR.

**Comment by katre** [comment]
That's fine, once the rules_cc release is done I'll handle that.

**Pull request closed without merging**
