### PR TITLE
refactor(compute): relocate proto_export.h files to protos dir

### PR DESCRIPTION
**Pull request by scotthart**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14646)

### CODE REVIEW

**Comment by dbolduc** [comment]
Moving public headers is a breaking change, no?

**Review by scotthart — COMMENTED** [review]
Added includes to the new files in the old files.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14646#-:-O4RNKfy4n-T77fhfTot:b-rm7c2b)* status: 0 of 211 files reviewed, all discussions resolved

**Review by dbolduc — DISMISSED** [review]
I still disagree that we should do this, but approved and unblocked.

- I don't think the extra granularity buys us anything.
- I don't think being nearer to the internal protos matters.
- We will have to do at least a bit of work to incorporate the new library in vcpkg, conan.

**Comment by dbolduc** [comment]
Can we close this? And #14654?

**Pull request closed without merging**
