### PR TITLE
feat(pubsub): Implement pubsub_dead_letter_create_subscription sample

### PR DESCRIPTION
**Pull request by remyabel**
Fixes: #4647

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101)* status: all files reviewed, 4 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/pubsub/samples/samples.cc, line 261 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfXd4l-FvPulVz7MB6:-MHfXd4l-FvPulVz7MB7:b-rwzwiz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L261)):*
> ```cpp
>             pubsub::SubscriptionMutationBuilder::MakeDeadLetterPolicy(
>                 pubsub::Topic(project_id, std::move(dead_letter_topic_name)),
>                 15)));
> ```

I think this `15` value should be a variable or an argument to the lambda to make its intent clearer, it seems too magical here.
___
*[google/cloud/pubsub/samples/samples.cc, line 1141 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfXsxJAK1q2Gb3dEYZ:-MHfXsxJAK1q2Gb3dEY_:brf94cn) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L1141)):*
> ```cpp
>   auto subscription_id = RandomSubscriptionId(generator);
>   auto push_subscription_id = RandomSubscriptionId(generator);
>   auto dead_letter_subscription_id = RandomSubscriptionId(generator);
> ```

At least in principle we should use a different topic for the dead letter id, which requires creating a new topic id and topic.
___
*[google/cloud/pubsub/samples/samples.cc, line 1199 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfXk-U1aquVHT1yi6U:-MHfXk-U1aquVHT1yi6V:b58qlev) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L1199)):*
> ```cpp
>   CreatePushSubscription(
>       subscription_admin_client,
>       {project_id, topic_id, push_subscription_id, endpoint2});
> ```

This change seems unrelated?
___
*[google/cloud/pubsub/samples/samples.cc, line 1203 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfXlmUC4ZnnOXhJ5i6:-MHfXlmUC4ZnnOXhJ5i7:bs4q9op) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L1203)):*
> ```cpp
>   std::cout << "\nRunning ModifyPushConfig() sample" << std::endl;
>   ModifyPushConfig(subscription_admin_client,
>                    {project_id, push_subscription_id, endpoint1});
> ```

Ditto.

**Review by coryan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101)* status: all files reviewed, 6 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/pubsub/samples/samples.cc, line 16 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfbG4EDgQM9dzacq0f:-MHfbG4EDgQM9dzacq0g:bfqrefl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L16)):*
> ```cpp
> 
> #include "google/cloud/pubsub/samples/pubsub_samples_common.h"
> #include "google/cloud/pubsub/snapshot_mutation_builder.h"
> ```

Is this used?
___
*[google/cloud/pubsub/samples/samples.cc, line 1141 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfXsxJAK1q2Gb3dEYZ:-MHfbOw78P8bxolBny8F:b-hes00s) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L1141)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

At least in principle we should use a different topic for the dead letter id, which requires creating a new topic id and topic.
</blockquote></details>

Oh, I see, the dead letter topic *id* below... we actually need to create the topic, by calling `CreateTopic`.
___
*[google/cloud/pubsub/samples/samples.cc, line 1142 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfbXHp8TzlToLuazLf:-MHfbXHp8TzlToLuazLg:bwnsvwk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L1142)):*
> ```cpp
>   auto push_subscription_id = RandomSubscriptionId(generator);
>   auto dead_letter_subscription_id = RandomSubscriptionId(generator);
>   auto dead_letter_topic_name = "dead-letter-" + RandomTopicId(generator);
> ```

this should be "dead_letter_topic_**id**"

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @coryan)

___
*[google/cloud/pubsub/samples/samples.cc, line 16 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfbG4EDgQM9dzacq0f:-MHffs9R6EIZVA4LcCX6:bqxtpq1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L16)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

I think that was automatically included by one of my tools and I did not notice. Removed in any case.
___
*[google/cloud/pubsub/samples/samples.cc, line 261 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfXd4l-FvPulVz7MB6:-MHfg-wA6u3IyTSbijy2:bt2vr1b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L261)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think this `15` value should be a variable or an argument to the lambda to make its intent clearer, it seems too magical here.
</blockquote></details>

Fixed.
___
*[google/cloud/pubsub/samples/samples.cc, line 1141 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfXsxJAK1q2Gb3dEYZ:-MHfg1GSB7p5sCIvsi_V:bt2vr1b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L1141)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Oh, I see, the dead letter topic *id* below... we actually need to create the topic, by calling `CreateTopic`.
</blockquote></details>

Fixed.
___
*[google/cloud/pubsub/samples/samples.cc, line 1142 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfbXHp8TzlToLuazLf:-MHfhMPd7n74sROePKFy:bt2vr1b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L1142)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

this should be "dead_letter_topic_**id**"
</blockquote></details>

Fixed.
___
*[google/cloud/pubsub/samples/samples.cc, line 1199 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfXk-U1aquVHT1yi6U:-MHfhOGy18vtCoGZYAIo:b8dpr6g) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L1199)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This change seems unrelated?
</blockquote></details>

That was an accident, already reverted.
___
*[google/cloud/pubsub/samples/samples.cc, line 1203 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfXlmUC4ZnnOXhJ5i6:-MHfhRKw0Ac7ZaknpxbQ:bs4q9op) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5f2714b29b849f1cc0f6ba6d371ad30e1110e83c/google/cloud/pubsub/samples/samples.cc#L1203)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Ditto.

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @coryan and @remyabel)

___
*[google/cloud/pubsub/samples/samples.cc, line 253 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfgt-11cuTja0xZtLV:-MHfgt-20s1z__Fzuxu9:b62btly) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L253)):*
> ```cpp
>   [](pubsub::SubscriptionAdminClient client, std::string const& project_id,
>      std::string const& topic_id, std::string const& subscription_id,
>      std::string const& dead_letter_topic_name,
> ```

This is a `dead_letter_topic_id`.  Typically a topic name is a string with this format `"projects/${PROJECT_ID}/topics/${PROJECT_ID}"`, commonly created using `pubsub::Topic(project_id, topic_id).FullName()`. We should try to be consistent on what we call these different strings.
___
*[google/cloud/pubsub/samples/samples.cc, line 254 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfgWcPDOcqDZhoie3b:-MHfgWcPDOcqDZhoie3c:bvc232o) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L254)):*
> ```cpp
>      std::string const& topic_id, std::string const& subscription_id,
>      std::string const& dead_letter_topic_name,
>      int const& dead_letter_delivery_attempts) {
> ```

nit: we would use just `int` in this case.
___
*[google/cloud/pubsub/samples/samples.cc, line 260 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfgwtb6530D6f3sDdg:-MHfgwtc1jt6qq_GDC9F:b7424if) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L260)):*
> ```cpp
>         pubsub::SubscriptionMutationBuilder{}.set_dead_letter_policy(
>             pubsub::SubscriptionMutationBuilder::MakeDeadLetterPolicy(
>                 pubsub::Topic(project_id, std::move(dead_letter_topic_name)),
> ```

should be `topic_id`, for consistency, we should not `std::move` the topic id either.
___
*[google/cloud/pubsub/samples/samples.cc, line 261 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfgZk59DdKQwMSy2QG:-MHfgZk59DdKQwMSy2QH:bxp0s7r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L261)):*
> ```cpp
>             pubsub::SubscriptionMutationBuilder::MakeDeadLetterPolicy(
>                 pubsub::Topic(project_id, std::move(dead_letter_topic_name)),
>                 std::move(dead_letter_delivery_attempts))));
> ```

no need to move `int`.
___
*[google/cloud/pubsub/samples/samples.cc, line 1217 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfior_CFjtmYXEa9a9:-MHfior_CFjtmYXEa9aA:b-eobtvc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L1217)):*
> ```cpp
>   // Hardcode this number as it does not really matter. The other samples pick
>   // something between 10 and 15.
>   auto dead_letter_delivery_attempts = 15;
> ```

consider:

```cc
auto constexpr kDeadLetterDeliveryAttemps = "15";
```
___
*[google/cloud/pubsub/samples/samples.cc, line 1222 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfiadUEKa1OPfEgOWa:-MHfiadUEKa1OPfEgOWb:b7epdw6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L1222)):*
> ```cpp
>   CreateDeadLetterSubscription(
>       subscription_admin_client,
>       {project_id, dead_letter_topic_id, dead_letter_subscription_id,
> ```

I think what we want here is `{project_id, topic_id, dead_letter_subscription_id, dead_letter_topic_id, kDeadLetterDeliveryAttempts}`.

The dead letter topic should be an existing topic, different from the source topic, where undelivered messages get sent to.  Think of it as a "last resort" or "error log" destination for messages.

As written the sample is configuring a subscription for an otherwise unused topic and sends them to a non-existent destination, none of this is visible in the extracted example, but seems wrong to write an example that does not work.

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @coryan)

___
*[google/cloud/pubsub/samples/samples.cc, line 253 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfgt-11cuTja0xZtLV:-MHfqnGx-tnC-XuHdpLI:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L253)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is a `dead_letter_topic_id`.  Typically a topic name is a string with this format `"projects/${PROJECT_ID}/topics/${PROJECT_ID}"`, commonly created using `pubsub::Topic(project_id, topic_id).FullName()`. We should try to be consistent on what we call these different strings.
</blockquote></details>

Done.
___
*[google/cloud/pubsub/samples/samples.cc, line 260 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfgwtb6530D6f3sDdg:-MHfr3sTDj44oobKsYe-:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L260)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

should be `topic_id`, for consistency, we should not `std::move` the topic id either.
</blockquote></details>

Done.
___
*[google/cloud/pubsub/samples/samples.cc, line 261 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfgZk59DdKQwMSy2QG:-MHfr4izCb1a4dEOikGA:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L261)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

no need to move `int`.
</blockquote></details>

Done.
___
*[google/cloud/pubsub/samples/samples.cc, line 1217 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfior_CFjtmYXEa9a9:-MHfr5UvBsfB0obTcOQ9:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L1217)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

consider:

```cc
auto constexpr kDeadLetterDeliveryAttemps = "15";
```
</blockquote></details>

Done.
___
*[google/cloud/pubsub/samples/samples.cc, line 1222 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-MHfiadUEKa1OPfEgOWa:-MHfr7H6AyC1sBP4QYGA:b-1zpgsf) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9655c35aa3b9d6fdc7ec483172fb386b6ef6fdf1/google/cloud/pubsub/samples/samples.cc#L1222)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think what we want here is `{project_id, topic_id, dead_letter_subscription_id, dead_letter_topic_id, kDeadLetterDeliveryAttempts}`.

The dead letter topic should be an existing topic, different from the source topic, where undelivered messages get sent to.  Think of it as a "last resort" or "error log" destination for messages.

As written the sample is configuring a subscription for an otherwise unused topic and sends them to a non-existent destination, none of this is visible in the extracted example, but seems wrong to write an example that does not work.

</blockquote></details>

Indeed, that was a typo. Fixed.

**Review by coryan — APPROVED** [review]
:lgtm:

Thank you for these changes, they really help.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101#-:-MHfwohw0JKrBdlKCXsU:b4wpt4l)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @coryan)

**Review by coryan — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5101)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
