### PR TITLE
test: use protobufs, not json in conformance tests

### PR DESCRIPTION
**Pull request by dopiera**
The file was imported from:
https://github.com/googleapis/conformance-tests/blob/d505e92d98f4f319ba774606ac95f693da2145c8/storage/v1/proto/google/cloud/conformance/storage/v1/tests.proto

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294)

### CODE REVIEW

**Comment by coryan** [comment]
I think the errors on Windows are caused by:

https://github.com/googleapis/google-cloud-cpp/blob/93589518733aed6d7147074d014500dc09e26451/ci/kokoro/windows/build-bazel.ps1#L69-L75

We turn on the equivalent of `-Wall -Werrror` for all the targets in `//google/cloud` including your new `.pb.cc` file.  Maybe you can change the `.ps1` script to set different flags for that new target, or compile the protos in `//external/conformance`?

**Comment by dopiera** [comment]
> I think the errors on Windows are caused by:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/93589518733aed6d7147074d014500dc09e26451/ci/kokoro/windows/build-bazel.ps1#L69-L75
> 
> We turn on the equivalent of `-Wall -Werrror` for all the targets in `//google/cloud` including your new `.pb.cc` file. Maybe you can change the `.ps1` script to set different flags for that new target, or compile the protos in `//external/conformance`?

:facepalm: 
Thanks! I kept changing cmake...

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294)* status: all files reviewed, 2 unresolved discussions (waiting on @dopiera)

___
*[google/cloud/storage/tests/CMakeLists.txt, line 53 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294#-MK9mP7eEGNsNK8L268j:-MK9mP7f0aIU3ivHO7Pl:brwm8yw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8cbc7067cff48b2a2acaf8b157b7af733ec3e7fd/google/cloud/storage/tests/CMakeLists.txt#L53)):*
> ```CMake
> 
> # Signed URL conformance tests are parsed using protos. In order to simplify the
> # build files, only build thes conformance tests if gRPC in GCS is compiled.
> ```

s/thes/these/ ??
___
*[google/cloud/storage/tests/CMakeLists.txt, line 62 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294#-MK9tpQO3YDKAZfe1dba:-MK9tpQPDpvaT43k2n0q:bjvk4an) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/42633b94349183989d1a6b44199779ff50f0ac43/google/cloud/storage/tests/CMakeLists.txt#L62)):*
> ```CMake
>         google_cloud_cpp_storage_tests_conformance_protos
>         conformance_tests.proto PROTO_PATH_DIRECTORIES
>         ${CMAKE_CURRENT_SOURCE_DIR} LOCAL_INCLUDE)
> ```

You may be able to just say:

```cmake
target_set_properties(google_cloud_cpp_storage_tests_conformance_protos
    PROPERTIES
    CXX_CLANG_TIDY "")
```

instead of saving and restoring the variable.  Possibly that needs an `if()` around it:

```cmake
if (CMAKE_VERSION VERSION_GREATER 3.6)
  target_set_properties(google_cloud_cpp_storage_tests_conformance_protos
      PROPERTIES
      CXX_CLANG_TIDY "")
endif ()
```

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/storage/tests/CMakeLists.txt, line 53 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294#-MK9mP7eEGNsNK8L268j:-MKAQLGVBCoI5HzNJ5YD:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8cbc7067cff48b2a2acaf8b157b7af733ec3e7fd/google/cloud/storage/tests/CMakeLists.txt#L53)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

s/thes/these/ ??
</blockquote></details>

Done.
___
*[google/cloud/storage/tests/CMakeLists.txt, line 62 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294#-MK9tpQO3YDKAZfe1dba:-MKAQZujB3Pf8IgXlo2s:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/42633b94349183989d1a6b44199779ff50f0ac43/google/cloud/storage/tests/CMakeLists.txt#L62)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

You may be able to just say:

```cmake
target_set_properties(google_cloud_cpp_storage_tests_conformance_protos
    PROPERTIES
    CXX_CLANG_TIDY "")
```

instead of saving and restoring the variable.  Possibly that needs an `if()` around it:

```cmake
if (CMAKE_VERSION VERSION_GREATER 3.6)
  target_set_properties(google_cloud_cpp_storage_tests_conformance_protos
      PROPERTIES
      CXX_CLANG_TIDY "")
endif ()
```

</blockquote></details>

Done.

**Review by coryan — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[google/cloud/storage/tests/CMakeLists.txt, line 62 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294#-MK9tpQO3YDKAZfe1dba:-MKAUB0d1FrmXPCc-SPN:b-k0ulgc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/42633b94349183989d1a6b44199779ff50f0ac43/google/cloud/storage/tests/CMakeLists.txt#L62)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ooops, `set_target_properties()`

https://cmake.org/cmake/help/v3.6/command/set_target_properties.html

**Comment by coryan** [comment]
___
*[google/cloud/storage/tests/CMakeLists.txt, line 62 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294#-MKAhC73AqxcNFBorNcT:-MKAhC73AqxcNFBorNcU:b-ux6vwe) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f141ecab68d4e994775f21c9fd8b8da985b0fedb/google/cloud/storage/tests/CMakeLists.txt#L62)):*
> ```CMake
>         ${CMAKE_CURRENT_SOURCE_DIR} LOCAL_INCLUDE)
>     if (CMAKE_VERSION VERSION_GREATER 3.6)
>         # Thsi works because we're not using clang-tidy with older cmake
> ```

nit: s/Thsi/This/

**Comment by coryan** [comment]
Your Bazel builds on Windows still have problems.  Have you tried using `/WDblah` instead of `-WDblah`?

**Review by coryan — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5294#-:-MKBut9U97pdFLQQY-rv:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
