### PR TITLE
fix: retry unexpected curl errors

### PR DESCRIPTION
**Pull request by devjgm**
We were sometimes seeing `CURLE_HTTP2` "Error in the HTTP2 framing
layer" errors when downloading large (20G) files using HTTP2. Details
captured in b/171350177.

Retying these errors works around the problem. Changed the default
behavior to retry all curl errors that aren't explicitly handled
separately in the switch statement.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5312)

### CODE REVIEW

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5312#-:-MKHJZ3UBpq8qrMGTBL2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @devjgm)

___
*[google/cloud/storage/internal/curl_handle_test.cc, line 50 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5312#-MKHJ7ms8VSGmH6kpoEj:-MKHJ7ms8VSGmH6kpoEk:b-lt60bu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/949815c94c76d40722c023e0020293f667e70529/google/cloud/storage/internal/curl_handle_test.cc#L50)):*
> ```cpp
>       {CURLE_GOT_NOTHING, StatusCode::kUnavailable},
>       {CURLE_AGAIN, StatusCode::kUnknown},
>       {CURLE_HTTP2, StatusCode::kUnavailable},
> ```

nit: if this compiles everywhere then the comment saying it is not defined in some versions of libcurl is no longer applicable, remove the comment?

**Comment by devjgm** [comment]
> _[google/cloud/storage/internal/curl_handle_test.cc, line 50 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5312#-MKHJ7ms8VSGmH6kpoEj:-MKHJ7ms8VSGmH6kpoEk:b-lt60bu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/949815c94c76d40722c023e0020293f667e70529/google/cloud/storage/internal/curl_handle_test.cc#L50)):_
> 
> > ```c++
> >       {CURLE_GOT_NOTHING, StatusCode::kUnavailable},
> >       {CURLE_AGAIN, StatusCode::kUnknown},
> >       {CURLE_HTTP2, StatusCode::kUnavailable},
> > ```
> 
> nit: if this compiles everywhere then the comment saying it is not defined in some versions of libcurl is no longer applicable, remove the comment?

Well, in the curl header it says:

https://github.com/curl/curl/blob/ede125b7b7ca8fc5a1fe3d7c1aee6bff2ea0bf24/include/curl/curl.h#L504-L506

```cc
  CURLE_HTTP2,                   /* 16 - A problem in the http2 framing layer.
                                    [was obsoleted in August 2007 for 7.17.0,
                                    reused in July 2014 for 7.38.0] */
```

So there are some old versions of _curl_ where this define won't be available. I don't think we test w/ any of those old versions, so our tests will likely not break. I'm not even sure if our code supports any of those old versions. So I removed the comment anyway.

**Comment by coryan** [comment]
___
*[google/cloud/storage/internal/curl_handle_test.cc, line 50 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5312#-MKHJ7ms8VSGmH6kpoEj:-MKHMD6_5PVHYmfTu_xV:b1oh3mb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/949815c94c76d40722c023e0020293f667e70529/google/cloud/storage/internal/curl_handle_test.cc#L50)):*
<details><summary><i>Previously, devjgm (Greg Miller) wrote…</i></summary><blockquote>

Well, in the curl header it says:

https://github.com/curl/curl/blob/ede125b7b7ca8fc5a1fe3d7c1aee6bff2ea0bf24/include/curl/curl.h#L504-L506

```cc
  CURLE_HTTP2,                   /* 16 - A problem in the http2 framing layer.
                                    [was obsoleted in August 2007 for 7.17.0,
                                    reused in July 2014 for 7.38.0] */
```

So there are some old versions of _curl_ where this define won't be available. I don't think we test w/ any of those old versions, so our tests will likely not break. I'm not even sure if our code supports any of those old versions. So I removed the comment anyway. 
</blockquote></details>

Removing the comment SGTM.

**Review by coryan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5312)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @coryan)

**Review by coryan — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5312)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
