### PR TITLE
chore: update googleapis SHA circa 2022-09-15

### PR DESCRIPTION
**Pull request by devbww**
Mostly to pick up `{Create,Update,Delete}InstanceConfig()`
for the `spanner_admin::InstanceAdminClient`. This should
allow us to merge the "CMMR Phase 2" work.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9860)

### CODE REVIEW

**Comment by devbww** [comment]
> Temporarily edit a generated file to fix the "publish-docs" build

The "generate-libraries" build, of course, undoes that.  So, I guess I'm stuck until I can get an upstream change made.  Sigh.

**Comment by coryan** [comment]
Comment changes upstream move relatively quickly.

With that said, I think we have some places in the generator where we "fix" the comments so Doxygen can consume them. Maybe we need to do the same thing here?

**Review by coryan — APPROVED** [review]
LGTM

**Comment by devbww** [comment]
Thanks.

**Pull request merged**
