### PR TITLE
chore: upgrade googleapis to current head

### PR DESCRIPTION
**Pull request by devbww**
This will facilitate creating trial merges for new features.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5831)

### CODE REVIEW

**Review by coryan — APPROVED** [review]
:lgtm: but @scotthart needs to review the changes related to the micro-generator.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5831#-:-MT2pmHj5q-CS1QRGB3C:b-g9zuxz)* status: all files reviewed, 1 unresolved discussion (waiting on @devbww)

___
*[ci/etc/generator-googleapis-commit-hash.sh, line 18 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5831#-MT2pZzwA9Yx9bi1JdJ4:-MT2pZzx-rcC4PE_PAtV:b-7mhbw9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/de84a36aeee6e815c97b0f0c0e9c331e6c1c7f35/ci/etc/generator-googleapis-commit-hash.sh#L18)):*
> ```Shell
> set -eu
> 
> GOOGLEAPIS_HASH_LAST_USED=5e3dacee19405529b841b53797df799c2383536c
> ```

@scotthart should this be updated after the generated libraries are re-generated?

**Review by devbww — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5831)* status: all files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[ci/etc/generator-googleapis-commit-hash.sh, line 18 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5831#-MT2pZzwA9Yx9bi1JdJ4:-MT2uz4U5m3gdmBCTRur:b-2onift) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/de84a36aeee6e815c97b0f0c0e9c331e6c1c7f35/ci/etc/generator-googleapis-commit-hash.sh#L18)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

@scotthart should this be updated after the generated libraries are re-generated?
</blockquote></details>

I can include the re-generations here if that is the right thing to do.  The fact that none of the presubmits failed gave me pause.

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5831)* status: 3 of 15 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[ci/etc/generator-googleapis-commit-hash.sh, line 18 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5831#-MT2pZzwA9Yx9bi1JdJ4:-MT3-T6-01LqueFzyvGr:b-av04f3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/de84a36aeee6e815c97b0f0c0e9c331e6c1c7f35/ci/etc/generator-googleapis-commit-hash.sh#L18)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I can include the re-generations here if that is the right thing to do.  The fact that none of the presubmits failed gave me pause.
</blockquote></details>

Yes. Regenerated files should be included.

**Review by devbww — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5831)* status: 3 of 15 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[ci/etc/generator-googleapis-commit-hash.sh, line 18 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5831#-MT2pZzwA9Yx9bi1JdJ4:-MT3-nQqDpLSp6rd_F-C:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/de84a36aeee6e815c97b0f0c0e9c331e6c1c7f35/ci/etc/generator-googleapis-commit-hash.sh#L18)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Yes. Regenerated files should be included.
</blockquote></details>

Done.

**Pull request merged**
