### PR TITLE
doc: improve verbiage in packaging.md

### PR DESCRIPTION
**Pull request by theSatvik**
Updated an improvised way to describe sentence, specially for professionals

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5177)

### CODE REVIEW

**Comment by coryan** [comment]
Thank you for sending this PR.  As you may have noticed `packaging.md` is automatically generated by `ci/generate-markdown/generate-packaging.sh`.  Would you consider making the changes there too?  I understand if that gets too tedious, just say so if it is the case.

**Comment by theSatvik** [comment]
Yes coryan, i made your desired changes , thankyou for reminding me

**Comment by theSatvik** [comment]
Hi , is everything looks suitable ? because there are alot of check , some of which i couldn't understand very well

**Comment by coryan** [comment]
Yes, it is all copacetic.  I was going to double check with my colleagues on Monday, as their English is much better than mine.

**Comment by theSatvik** [comment]
Okay Sure ,  although your english is really phenomenal .

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5177#-:-MIt3hnsBy17M_pQavAq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by coryan** [comment]
Thanks for your PR and your patience.

**Comment by theSatvik** [comment]
Thankyou coryan for your consideration

**Pull request merged**
