### PR TITLE
refactor(spanner): Use testing_utils for command-line parsing

### PR DESCRIPTION
**Pull request by remyabel**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
Looks good, I think we can simplify this.  Typically we use these argument parsers in benchmarks that do not have the  gtest functions available, but here we could just use them?  What do you think?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-:-MKl2UVABKnsUC6VtFY2:br0jp3z)* status: all files reviewed, 3 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 26 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKl1xMc6XJsPaTHryJu:-MKl1xMc6XJsPaTHryJv:b-waw582) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/939bd44625d6464775e84f086bd128b43796c054/google/cloud/spanner/integration_tests/client_stress_test.cc#L26)):*
> ```cpp
> #include <thread>
> 
> namespace {
> ```

You can probably move this to the namespace where the test is?
___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 105 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKl1jQO7O6Q8QbUnAdv:-MKl1jQO7O6Q8QbUnAdw:b-9akswq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/939bd44625d6464775e84f086bd128b43796c054/google/cloud/spanner/integration_tests/client_stress_test.cc#L105)):*
> ```cpp
> }
> 
> StatusOr<Config> SelfTest(std::string const& cmd) {
> ```

This `SelfTest` trick is something we do in benchmarks where there is no easy way to integrate with googletest, but here I think we could just do something like:

```cc
TEST_F(ClientStressTest, ParseArgs) {
  // do some simple tests for ParseArgs(), no need to have a separate ParseArgsImpl.
}
```
___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 132 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKl2BlnAFwmHLsrVbHB:-MKl2BlnAFwmHLsrVbHC:bi124qt) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/939bd44625d6464775e84f086bd128b43796c054/google/cloud/spanner/integration_tests/client_stress_test.cc#L132)):*
> ```cpp
> StatusOr<Config> ParseArgs(std::vector<std::string> args) {
>   bool auto_run =
>       GetEnv("GOOGLE_CLOUD_CPP_AUTO_RUN_EXAMPLES").value_or("") == "yes";
> ```

Likewise, this is something we do in the benchmarks to have them automatically run with no arguments.  We can probably remove this code and simplify this test.

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @coryan)

___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 26 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKl1xMc6XJsPaTHryJu:-MKlDUgh2QKVzprH0hlN:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/939bd44625d6464775e84f086bd128b43796c054/google/cloud/spanner/integration_tests/client_stress_test.cc#L26)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

You can probably move this to the namespace where the test is?
</blockquote></details>

Done.
___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 105 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKl1jQO7O6Q8QbUnAdv:-MKlDVlV6J0DhzAJOECR:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/939bd44625d6464775e84f086bd128b43796c054/google/cloud/spanner/integration_tests/client_stress_test.cc#L105)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This `SelfTest` trick is something we do in benchmarks where there is no easy way to integrate with googletest, but here I think we could just do something like:

```cc
TEST_F(ClientStressTest, ParseArgs) {
  // do some simple tests for ParseArgs(), no need to have a separate ParseArgsImpl.
}
```
</blockquote></details>

Done.
___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 132 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKl2BlnAFwmHLsrVbHB:-MKlDWOm0LhZAW36Csbq:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/939bd44625d6464775e84f086bd128b43796c054/google/cloud/spanner/integration_tests/client_stress_test.cc#L132)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Likewise, this is something we do in the benchmarks to have them automatically run with no arguments.  We can probably remove this code and simplify this test.
</blockquote></details>

Done.

**Comment by coryan** [comment]
___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 296 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKlG_1i0U_dZBUGOeY7:-MKlG_1i0U_dZBUGOeY8:b-1t1s3o) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a38c8350dd5bc2f981267273c6caf451c3456e34/google/cloud/spanner/integration_tests/client_stress_test.cc#L296)):*
> ```cpp
>   ::testing::InitGoogleMock(&argc, argv);
> 
>   spanner::config =
> ```

this looks like a typo?

**Comment by coryan** [comment]
___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 296 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKlG_1i0U_dZBUGOeY7:-MKlGgKL2j_5Go3dt7eI:bhry8wl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a38c8350dd5bc2f981267273c6caf451c3456e34/google/cloud/spanner/integration_tests/client_stress_test.cc#L296)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

this looks like a typo?
</blockquote></details>

Ahhh, no, it is fine, sorry.

**Review by coryan — CHANGES_REQUESTED** [review]
Thanks for the quick turnaround, just a few more changes I think.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-:-MKlHlSw0Tyodq6S6xB0:b-8fk0jj)* status: all files reviewed, 3 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 18 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKlHfa9DxCEJsr155db:-MKlHfa9DxCEJsr155dc:b-scffn2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a38c8350dd5bc2f981267273c6caf451c3456e34/google/cloud/spanner/integration_tests/client_stress_test.cc#L18)):*
> ```cpp
> #include "google/cloud/spanner/database.h"
> #include "google/cloud/spanner/testing/database_integration_test.h"
> #include "google/cloud/internal/getenv.h"
> ```

I think you no longer need this include?
___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 57 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKlGzcMDQ-X1nblSSMM:-MKlGzcMDQ-X1nblSSMN:btropzw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a38c8350dd5bc2f981267273c6caf451c3456e34/google/cloud/spanner/integration_tests/client_stress_test.cc#L57)):*
> ```cpp
>   bool show_help = false;
> };
> StatusOr<Config> config;
> ```

The google style guide frowns upon global objects with non-trivial destructors.  I think we want:

```cc
Config config;
```

which (a) has a trivial destructor, and (b) initializes the the right defaults.
___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 296 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKlHIMEA0yM1V_u6w-d:-MKlHIMEA0yM1V_u6w-e:b-comw6s) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a38c8350dd5bc2f981267273c6caf451c3456e34/google/cloud/spanner/integration_tests/client_stress_test.cc#L296)):*
> ```cpp
>   ::testing::InitGoogleMock(&argc, argv);
> 
>   spanner::config =
> ```

if we want the changes to `spanner::config` this would become:

```cc
auto config = spanner::ParseArgs(...);
if (!config) {
  ...
  return 1;
}
if (config->show_help) return 0;
spanner::config = std::move(config);
```

Does that make sense?

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @coryan)

___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 18 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKlHfa9DxCEJsr155db:-MKlLnDZBgjYg8wIM5px:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a38c8350dd5bc2f981267273c6caf451c3456e34/google/cloud/spanner/integration_tests/client_stress_test.cc#L18)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think you no longer need this include?
</blockquote></details>

Done.
___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 57 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKlGzcMDQ-X1nblSSMM:-MKlLncTCDwFc8DvTFRF:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a38c8350dd5bc2f981267273c6caf451c3456e34/google/cloud/spanner/integration_tests/client_stress_test.cc#L57)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

The google style guide frowns upon global objects with non-trivial destructors.  I think we want:

```cc
Config config;
```

which (a) has a trivial destructor, and (b) initializes the the right defaults.

</blockquote></details>

Done.
___
*[google/cloud/spanner/integration_tests/client_stress_test.cc, line 296 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-MKlHIMEA0yM1V_u6w-d:-MKlLonu0OUDGnmFqM2i:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a38c8350dd5bc2f981267273c6caf451c3456e34/google/cloud/spanner/integration_tests/client_stress_test.cc#L296)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

if we want the changes to `spanner::config` this would become:

```cc
auto config = spanner::ParseArgs(...);
if (!config) {
  ...
  return 1;
}
if (config->show_help) return 0;
spanner::config = std::move(config);
```

Does that make sense?
</blockquote></details>

Done.

**Review by coryan — APPROVED** [review]
:lgtm: let's see what the builds say +kokoro:run 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5359#-:-MKlMKib5eWJor1AducU:b-a5la7b)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by coryan** [comment]
Thanks!

**Pull request merged**
