### PR TITLE
chore: add/remove common c++ includes in our headers

### PR DESCRIPTION
**Pull request by devjgm**
Adds/removes includes as necessary _in our header files_ for `<vector>`,
`<string>`, and `<chrono>` only. We could expand this to do more, but
these are the most common headers. Trying to keep this a bit smaller.

Related to #5922

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960)

### CODE REVIEW

**Comment by devjgm** [comment]
Note: there are some places where the new include was added in the wrong place wrt to `//!` comments. I see 14 of these cases, which I can fix by hand. But I'll do that later if we decide we want to cleanup like this.

**Review by coryan — APPROVED** [review]
> Reviewed 227 of 227 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960)* status: all files reviewed, 1 unresolved discussion (waiting on @devjgm)

___
*[google/cloud/bigtable/cluster_list_responses.h, line 19 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960#-MUsfA4D4ccDpuKInCfe:-MUsfA4E2YFb3878UkL8:bazhe7l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/08ead5a70dfe8dcc0102f963803b672e6e8d2c0e/google/cloud/bigtable/cluster_list_responses.h#L19)):*
> ```objc
> 
> #include "google/cloud/bigtable/version.h"
> #include <google/bigtable/admin/v2/bigtable_instance_admin.grpc.pb.h>
> ```

FYI (for a separate PR): if we are looking for wins in build times, replacing `.grpc.pb.h` with their `.pb.h` counterpart (when possible) is probably a good saving.
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h, line 29 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960#-MUsfgZmB0y0Iusw1Z2w:-MUsfgZn5R6iwyYlIFGc:b-x4xynm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/08ead5a70dfe8dcc0102f963803b672e6e8d2c0e/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h#L29)):*
> ```objc
> #include "google/cloud/version.h"
> #include <memory>
> #include <string>
> ```

FYI: I am guessing these need to be fixed in the generator or they will be reintroduced later?
___
*[google/cloud/logging/logging_service_v2_client.gcpcxx.pb.h, line 28 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960#-MUsfxYX7iX9hggkDr9F:-MUsfxYX7iX9hggkDr9G:b-gpusr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/08ead5a70dfe8dcc0102f963803b672e6e8d2c0e/google/cloud/logging/logging_service_v2_client.gcpcxx.pb.h#L28)):*
> ```objc
> #include <map>
> #include <memory>
> #include <string>
> ```

FYI: another candidate for changing the generator.
___
*[google/cloud/testing_util/contains_once.h, line 24 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960#-MUshNX5BufmxRaVnYiJ:-MUshNX698FaN5UTcDj6:b4flqqw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/08ead5a70dfe8dcc0102f963803b672e6e8d2c0e/google/cloud/testing_util/contains_once.h#L24)):*
> ```objc
> #include <type_traits>
> #include <utility>
> #include <vector>
> ```

nit: `std::vector` is only used in a comment here.

**Comment by devjgm** [comment]
> > Reviewed 227 of 227 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960)_ status: all files reviewed, 1 unresolved discussion (waiting on @devjgm)
> 
> _[google/cloud/bigtable/cluster_list_responses.h, line 19 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960#-MUsfA4D4ccDpuKInCfe:-MUsfA4E2YFb3878UkL8:bazhe7l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/08ead5a70dfe8dcc0102f963803b672e6e8d2c0e/google/cloud/bigtable/cluster_list_responses.h#L19)):_
> 
> > ```objc
> > #include "google/cloud/bigtable/version.h"
> > #include <google/bigtable/admin/v2/bigtable_instance_admin.grpc.pb.h>
> > ```
> 
> FYI (for a separate PR): if we are looking for wins in build times, replacing `.grpc.pb.h` with their `.pb.h` counterpart (when possible) is probably a good saving.

How do we know if that's safe? 

> 
> _[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h, line 29 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960#-MUsfgZmB0y0Iusw1Z2w:-MUsfgZn5R6iwyYlIFGc:b-x4xynm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/08ead5a70dfe8dcc0102f963803b672e6e8d2c0e/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h#L29)):_
> 
> > ```objc
> > #include "google/cloud/version.h"
> > #include <memory>
> > #include <string>
> > ```
> 
> FYI: I am guessing these need to be fixed in the generator or they will be reintroduced later?

You're right. I was going to fix all the `generator/...` stuff in a separate PR, because I'll have to regenerate all the libraries and their hashes.

> 
> _[google/cloud/logging/logging_service_v2_client.gcpcxx.pb.h, line 28 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960#-MUsfxYX7iX9hggkDr9F:-MUsfxYX7iX9hggkDr9G:b-gpusr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/08ead5a70dfe8dcc0102f963803b672e6e8d2c0e/google/cloud/logging/logging_service_v2_client.gcpcxx.pb.h#L28)):_
> 
> > ```objc
> > #include <map>
> > #include <memory>
> > #include <string>
> > ```
> 
> FYI: another candidate for changing the generator.
> 
> _[google/cloud/testing_util/contains_once.h, line 24 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960#-MUshNX5BufmxRaVnYiJ:-MUshNX698FaN5UTcDj6:b4flqqw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/08ead5a70dfe8dcc0102f963803b672e6e8d2c0e/google/cloud/testing_util/contains_once.h#L24)):_
> 
> > ```objc
> > #include <type_traits>
> > #include <utility>
> > #include <vector>
> > ```
> 
> nit: `std::vector` is only used in a comment here.

D'oh. Good catch! Turns out, my script was too dumb. I smartened up the script and now it can strip comments before checking if a symbol is used. That caught a few other cases as well where includes were added that shouldn't have been.

**Review by coryan — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[google/cloud/bigtable/cluster_list_responses.h, line 19 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5960#-MUsfA4D4ccDpuKInCfe:-MUthU7O2n43FycvLnEX:bz5d3r8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/08ead5a70dfe8dcc0102f963803b672e6e8d2c0e/google/cloud/bigtable/cluster_list_responses.h#L19)):*
<details><summary><i>Previously, devjgm (Greg Miller) wrote…</i></summary><blockquote>

How do we know if that's safe?  
</blockquote></details>

I do not think you can script that.  You have to do those manually. There are only 42 of them in header files, should be "easy".

**Pull request merged**
