### PR TITLE
cleanup(bigtable): Move bigtable tests to the right namespace

### PR DESCRIPTION
**Pull request by remyabel**
Fixes: #5353

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5420)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
Wow, thanks! A few nits on the benchmark tests, otherwise looks great.

> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5420#-:-MLQrLGx6mqdR36h2T-o:brd4bxi)* status: all files reviewed, 2 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc, line 23 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5420#-MLQs7ct7Fr0oUyRJqR5:-MLQs7ct7Fr0oUyRJqR6:b-sfp4j6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8333fddd49c72de3590f21bfddd02ee765b7b4e0/google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc#L23)):*
> ```cpp
> namespace cloud {
> namespace bigtable {
> namespace benchmarks {
> ```

Here and the other benchmark tests, consider putting them inside an anonymous namespace.
___
*[google/cloud/bigtable/benchmarks/embedded_server_test.cc, line 26 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5420#-MLQs0HnD1UJGXYTCufH:-MLQs0HnD1UJGXYTCufI:bb7fyw2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8333fddd49c72de3590f21bfddd02ee765b7b4e0/google/cloud/bigtable/benchmarks/embedded_server_test.cc#L26)):*
> ```cpp
> namespace bigtable {
> namespace benchmarks {
> ```

probably should put these tests in an anonymous namespace too??

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5420)* status: 26 of 31 files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc, line 23 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5420#-MLQs7ct7Fr0oUyRJqR5:-MLR06mD84zHhco_b-Pl:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8333fddd49c72de3590f21bfddd02ee765b7b4e0/google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc#L23)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Here and the other benchmark tests, consider putting them inside an anonymous namespace.
</blockquote></details>

Done.
___
*[google/cloud/bigtable/benchmarks/embedded_server_test.cc, line 26 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5420#-MLQs0HnD1UJGXYTCufH:-MLR08405PoDEmN7sbFr:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8333fddd49c72de3590f21bfddd02ee765b7b4e0/google/cloud/bigtable/benchmarks/embedded_server_test.cc#L26)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

probably should put these tests in an anonymous namespace too??
</blockquote></details>

Done.

**Review by coryan — APPROVED** [review]
:lgtm: thanks, just waiting for the builds now.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5420#-:-MLR2YL_AzosSS949ChE:b-bhf2y0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5420#-:-MLRDUYj80ZmCqzvwpUL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
