### PR TITLE
ci: use upstream BUILD file in nlohmann json

### PR DESCRIPTION
**Pull request by mering**
This reduces maintenance and unblocks people from using the nlohmann_json dependency from BCR when using Bzlmod.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14310)

### CODE REVIEW

**Comment by mering** [comment]
@scotthart @dbolduc could you please trigger the tests? Thanks!

**Comment by scotthart** [comment]
I'm concerned that the upstream BUILD.bazel file specifies `alwayslink = True`. Our BUILD file does not specify this and does not need it. Adding this flag will only serve to unnecessarily increase the resulting size of the eventual binaries.

**Comment by coryan** [comment]
> I'm concerned that the upstream BUILD.bazel file specifies `alwayslink = True`. Our BUILD file does not specify this and does not need it. Adding this flag will only serve to unnecessarily increase the resulting size of the eventual binaries.

How?  AFAICT, the library is header-only, it does not contain any `.o` files to increase the size of any binaries.  The `alwayslink = True` seems misguided as it makes no difference, but it also does not seem to harm anything.

**Comment by coryan** [comment]
Seems like this PR needs a rebase

**Comment by mering** [comment]
> Seems like this PR needs a rebase

Rebased.

**Review by scotthart — APPROVED** [review]
My understanding is that `alwayslink` functions similarly to `--whole-archive`, perhaps I'm mistaken. But, as you correctly point out, there are no .o files in this header only library (which probably won't deviate from being header only in the future).

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14310#-:-O-6i7ej0tC9sKMkppLg:b-i1ycfh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mering)

**Comment by scotthart** [comment]
The conventionalcommits failure should resolve if you edit the commit message to follow the same pattern as the PR title.

**Comment by coryan** [comment]
> The conventionalcommits failure should resolve if you edit the commit message to follow the same pattern as the PR title.

correct, but we can just edit the squash commit message for the same effect (which I just did).

**Comment by mering** [comment]
Thanks to both of you for your help!

**Comment by coryan** [comment]
On the contrary, thanks for the PR.  We completely missed that this dependency had introduced support for Bazel.

**Pull request merged**
