### PR TITLE
fix: URL encode explicit routing values

### PR DESCRIPTION
**Pull request by alevenberg**
Part of #12232

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12493)

### CODE REVIEW

**Comment by alevenberg** [comment]
I ran `i/cloudbuild/build.sh -t asan-pr `

I'm not sure what unit tests I should change for this change

**Comment by dbolduc** [comment]
* `GENERATE_GOLDEN_ONLY` is good for developing, but we should remove it and rerun `generate-libraries-pr` before sending the PR.
* I would add a new unit test in [golden_kitchen_sink_metadata_decorator_test.cc](https://github.com/googleapis/google-cloud-cpp/blob/main/generator/integration_tests/tests/golden_kitchen_sink_metadata_decorator_test.cc). Look at the `ExplicitRouting*` tests for inspiration.
* We should probably make identical changes to the REST metadata decorator

**Comment by alevenberg** [comment]
I did the first two.

Looking into the rest metadata decorator.

**Review by dbolduc — APPROVED** [review]
> Maybe in a 2nd PR?

SGTM

**Pull request merged**
