### PR TITLE
feat(storage): adding example of using Client::DeleteResumableUpload()

### PR DESCRIPTION
**Pull request by tina80lvl**
Simple example of using DeleteResumableUpload() with running script.

Relates: https://github.com/googleapis/google-cloud-cpp/pull/5004

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5006)

### CODE REVIEW

**Comment by tina80lvl** [comment]
> First, thank you for sending the PR, those are always welcome.
> 
> Second, as you probably noticed, you need to sign the CLA or we would be unable to accept any contributions.
> 
> Third, I know this review is asking for a lot of changes, if it becomes too much no worries, we can close the PR and we (Google) will get to this eventually.
> 
> Last, can you let me know how is this related to #5004 which is a Pub/Sub issue?
> 
> > Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5006#-:-MGDy9ky00Cw5_T_QTVU:b72fldn)_ status: all files reviewed, 3 unresolved discussions (waiting on @tina80lvl)
> 
> _[google/cloud/storage/client_example.cc, line 11 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5006#-MGDyJVV1YOp7h3KMLnG:-MGDyJVV1YOp7h3KMLnH:b-74ovxb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b69fae8ee7e84d731e08b9a5d0e43418c3ad3535/google/cloud/storage/client_example.cc#L11)):_
> 
> > ```c++
> > int main() {
> >   const auto& client_options =
> > ```
> 
> I believe you want `auto` here, otherwise the value returned by `ClientOptions()` goes out of scope and the reference is invalid.
> 
> nit: this is an `east const` project, so that would be `auto const&`
> 
> _[google/cloud/storage/client_example.cc, line 21 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5006#-MGDyHjaBDiUkmR88ZwQ:-MGDyHjb4EyojMGftg2c:b-x7kq3l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b69fae8ee7e84d731e08b9a5d0e43418c3ad3535/google/cloud/storage/client_example.cc#L21)):_
> 
> > ```c++
> >   const auto& session_url = stream.resumable_session_id();
> >   const auto& client_status =
> >       client.DeleteResumableUpload(session_url, client_options);
> > ```
> 
> In general, we like our examples to be:
> 
> * compiled as part of the normal CI build
> * executed as part of the normal CI tests
> * runnable from the command-line
> * placed in a standard location so we can extract them into the Doxygen documentation.
> 
> Would you be able to move this example to this file:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/examples/storage_object_resumable_write_samples.cc
> 
> make it look similar to this example:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/819050d3c3b575484edaf873067dc3191a32147e/google/cloud/storage/examples/storage_object_resumable_write_samples.cc#L29-L47
> 
> and make it run as part of the normal tests:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/819050d3c3b575484edaf873067dc3191a32147e/google/cloud/storage/examples/storage_object_resumable_write_samples.cc#L112-L113
> 
> and make it runnable from the command-line:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/819050d3c3b575484edaf873067dc3191a32147e/google/cloud/storage/examples/storage_object_resumable_write_samples.cc#L142
> 
> _[google/cloud/storage/sc.sh, line 1 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5006#-MGDy_qG6tNn3JB3hrMg:-MGDy_qG6tNn3JB3hrMh:b-5db9q1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b69fae8ee7e84d731e08b9a5d0e43418c3ad3535/google/cloud/storage/sc.sh#L1)):_
> 
> > ```shell
> > #!/bin/bash
> > ```
> 
> This should be unnecessary, the existing build scripts should work.

Thank you for a such quick review! Now I get what did you mean as "example", I'll fix that soon. But the main idea of  such kind of code is that there are huge difficulties with running this rep on Mac especially with benchmark so I have no ability to run tests for now so used my own main and my own script.

**Comment by coryan** [comment]
> Thank you for a such quick review! Now I get what did you mean as "example", I'll fix that soon. 

Oh the contrary, thanks to you.

> But the main idea of such kind of code is that there are huge difficulties with running this rep on Mac

Okay, that seems like a more serious problem than just one missing example.  Could you tell us if the documentation here:

https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/quickstart/README.md

helps?  We tested that on macOS, and continuously test these steps in our CI builds too, but there are always fidelity problems between documentation and test scripts.

> especially with benchmark so I have no ability to run tests for now so used my own main and my own script.

Are there specific issues with benchmarking that we can help you with?

**Comment by tina80lvl** [comment]
Moreover, using of Client::DeleteResumableUpload() causes that kind of mistake:
```
➜  google-cloud-cpp git:(feat/4923) ✗ ./google/cloud/storage/sc.sh
In file included from google/cloud/storage/client_example.cc:1:
In file included from /Users/tina/dev/google-cloud-cpp/google/cloud/storage/client.h:19:
In file included from /Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/logging_client.h:18:
In file included from /Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/raw_client.h:20:
In file included from /Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/bucket_acl_requests.h:19:
/Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/generic_request.h:210:12: error: no matching member function for call to
      'set_option'
    Super::set_option(std::forward<H>(h));
    ~~~~~~~^~~~~~~~~~
/Users/tina/dev/google-cloud-cpp/google/cloud/storage/client.h:1262:13: note: in instantiation of function template specialization
      'google::cloud::storage::v1::internal::GenericRequest<google::cloud::storage::v1::internal::DeleteResumableUploadRequest,
      google::cloud::storage::v1::UserProject>::set_multiple_options<const google::cloud::storage::v1::ClientOptions &>' requested here
    request.set_multiple_options(std::forward<Options>(options)...);
            ^
google/cloud/storage/client_example.cc:21:14: note: in instantiation of function template specialization
      'google::cloud::storage::v1::Client::DeleteResumableUpload<const google::cloud::storage::v1::ClientOptions &>' requested here
      client.DeleteResumableUpload(session_url, client_options);
             ^
/Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/generic_request.h:66:12: note: candidate function not viable: no known
      conversion from 'const google::cloud::storage::v1::ClientOptions' to 'google::cloud::storage::v1::UserProject' for 1st argument
  Derived& set_option(Option p) {
           ^
/Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/generic_request.h:111:12: note: candidate function not viable: no known
      conversion from 'const google::cloud::storage::v1::ClientOptions' to 'google::cloud::storage::v1::UserIp' for 1st argument
  Derived& set_option(Option p) {
           ^
/Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/generic_request.h:111:12: note: candidate function not viable: no known
      conversion from 'const google::cloud::storage::v1::ClientOptions' to 'google::cloud::storage::v1::QuotaUser' for 1st argument
  Derived& set_option(Option p) {
           ^
/Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/generic_request.h:111:12: note: candidate function not viable: no known
      conversion from 'const google::cloud::storage::v1::ClientOptions' to 'google::cloud::storage::v1::IfNoneMatchEtag' for 1st
      argument
  Derived& set_option(Option p) {
           ^
/Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/generic_request.h:111:12: note: candidate function not viable: no known
      conversion from 'const google::cloud::storage::v1::ClientOptions' to 'google::cloud::storage::v1::IfMatchEtag' for 1st argument
  Derived& set_option(Option p) {
           ^
/Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/generic_request.h:111:12: note: candidate function not viable: no known
      conversion from 'const google::cloud::storage::v1::ClientOptions' to 'google::cloud::storage::v1::Fields' for 1st argument
  Derived& set_option(Option p) {
           ^
/Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/generic_request.h:111:12: note: candidate function not viable: no known
      conversion from 'const google::cloud::storage::v1::ClientOptions' to 'google::cloud::storage::v1::CustomHeader' for 1st argument
  Derived& set_option(Option p) {
           ^
1 error generated.
```

So I can conclude that `set_option()` is not implemented for that type of _Options_.

**Comment by coryan** [comment]
> Moreover, using of Client::DeleteResumableUpload() causes that kind of mistake:
> 
> ```
> ➜  google-cloud-cpp git:(feat/4923) ✗ ./google/cloud/storage/sc.sh

[snip]

> google/cloud/storage/client_example.cc:21:14: note: in instantiation of function template specialization
>       'google::cloud::storage::v1::Client::DeleteResumableUpload<const google::cloud::storage::v1::ClientOptions &>' requested here
>       client.DeleteResumableUpload(session_url, client_options);
>              ^
> /Users/tina/dev/google-cloud-cpp/google/cloud/storage/internal/generic_request.h:66:12: note: candidate function not viable: no known
>       conversion from 'const google::cloud::storage::v1::ClientOptions' to 'google::cloud::storage::v1::UserProject' for 1st argument

[snip]

>   Derived& set_option(Option p) {
>            ^
> 1 error generated.
> ```
> 
> So I can conclude that `set_option()` is not implemented for that type of _Options_.

Ugh, that is an ugly error message.  Yes.  You cannot pass `ClientOptions` to the `DeleteResumableUpload()` function, the valid arguments are documented here:


https://googleapis.dev/cpp/google-cloud-storage/latest/classgoogle_1_1cloud_1_1storage_1_1v1_1_1Client.html#ade8d4dc43d3aa3fb7c1a592d2d7493e6

I think `UserProject` is the only thing you could reasonably provide there.


May I ask: what are you trying to do?  Maybe I can point you to an existing example or benchmark that shows what you need.

**Comment by coryan** [comment]
This has gone quiet for a week, please let us know how we can help. Feel free to reopen this PR once you have signed the CLA and addressed the issues above.

**Pull request closed without merging**
