### PR TITLE
chore: use common version_info in all libraries

### PR DESCRIPTION
**Pull request by mr-salty**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5710)

### CODE REVIEW

**Comment by mr-salty** [comment]
WDYT?  oops - I see I'd need to remove the `version_info.h.in` files and associated cmake rules as well, but just the general principle?

Alternatively we could just `s/.*_CLIENT_VERSION/GOOGLE_CLOUD_CPP_VERSION/` everywhere and eliminate the individual `version_info.h` files but technically that's a breaking change.

**Comment by coryan** [comment]
Modulo formatting, LGTM.

**Review by mr-salty — COMMENTED** [review]
`clang-tidy` was triggering on the diff between the generated files and non.  I removed the generate rules (and `version_info.h.in`) so I think this should be ready now.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5710#-:-MRYxgfyBgJx3lX0cPh3:bwju3ei)* status: 0 of 16 files reviewed, all discussions resolved

**Review by devbww — APPROVED** [review]

**Review by devbww — APPROVED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5710)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mr-salty)

**Review by coryan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5710#-:-MRZycWO8ZPK-lYT5ne6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mr-salty)

**Pull request merged**
