### PR TITLE
fix(rest): preserve proto field snake case naming style in json

### PR DESCRIPTION
**Pull request by scotthart**
part of the work for for #12112

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12145)

### CODE REVIEW

**Review by dbolduc — APPROVED** [review]
can we verify this behavior in a unit test?

**Review by scotthart — COMMENTED** [review]
We don't typically write unit tests for functions that we don't maintain and `google::protobuf::util::MessageToJsonString` is part of protobuf and should be tested there. Our existing integration tests should verify that this change does not break any existing behavior. Future improvements that leverage this change will be accompanied by tests that require this `JsonPrintOption` to behave as advertised.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12145#-:-N_ejHidEqnAE7mo_sjm:b-qxni6o)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by dbolduc** [comment]
I think having a test that we pass the correct options to the protobuf function is better than no test. Can't we verify the contents of `json_payload` after the call?

**Review by scotthart — COMMENTED** [review]
This seems like a slippery slope. Do we really want to test that every function we use from our dependencies does what it says it does?

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12145#-:-N_enpZj0cjRyvNT6-dX:blq6ixl)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by dbolduc** [comment]
> This seems like a slippery slope. Do we really want to test that every function we use from our dependencies does what it says it does?

We would not be testing protobuf's function. We would be testing that our function calls their function with the right options.

If we removed the code from this PR, it would be nice if a unit test broke accordingly. :shrug:

**Pull request merged**
