### PR TITLE
feat(pubsub): add publish_with_ordering_keys sample

### LINKED ISSUE #4740: Implement pubsub_publish_with_ordering_keys sample
"This sample shall show how to publish messages with an ordering key." There are no implementations in other languages.

### PR DESCRIPTION
**Pull request by remyabel**
Fixes #4740

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
It might be premature for this example.  The library is missing some important features (see #4803, #5044).  The example will probably look pretty much the same once the features are implemented, so I think we can implement it, but there may be some problem getting it to work in the `AutoRun()`.

The dead letter queue examples are (I think) closer to "ready".

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059#-:-MHI0vZDCJo_k8-5_21Y:bfjgjhn)* status: all files reviewed, 2 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/pubsub/samples/samples.cc, line 555 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059#-MHI04lc1LJRRcXXSyzz:-MHI04lc1LJRRcXXSz--:b-qtgrq2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e7cb38af2c8902a4f4c51d2b9a762ef2d2974236/google/cloud/pubsub/samples/samples.cc#L555)):*
> ```cpp
>       std::string data;
>     } data[] = {
>         {"k0", "data0"}, {"k1", "data1"}, {"k0", "data2"},
> ```

It seems that there are now examples in other languages:

https://github.com/googleapis/python-pubsub/blob/f34e5b5d61f75cceb00d4f13f0e913a88558915e/samples/snippets/publisher.py#L278-L315

https://github.com/GoogleCloudPlatform/golang-samples/blob/4f178324dbb095e8d483dc1ee1d777906d8270dd/pubsub/topics/publish_ordering.go#L17-L102

https://github.com/googleapis/java-pubsub/blob/caf8e967e06edc945291d79d95c45220f0ca7bc1/samples/snippets/src/main/java/pubsub/PublishWithOrderingKeys.java#L19-L100

and they all use:

```cc
{"key1", "message1"},
{"key2", "message2"},
{"key1", "message3"},
{"key2", "message4"},
```

I think we should change this example to match.  Do you mind making these changes?
___
*[google/cloud/pubsub/samples/samples.cc, line 1251 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059#-MHI0kpSEpapHdLhEW6i:-MHI0kpSEpapHdLhEW6j:bjlca50) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e7cb38af2c8902a4f4c51d2b9a762ef2d2974236/google/cloud/pubsub/samples/samples.cc#L1251)):*
> ```cpp
> 
>   std::cout << "\nRunning PublishOrderingKey() sample" << std::endl;
>   PublishOrderingKey(publisher, {});
> ```

I think this would not work.  The topic has to be created with ordering keys enabled, and the publisher too.

**Comment by remyabel** [comment]
> It might be premature for this example. The library is missing some important features (see #4803, #5044). The example will probably look pretty much the same once the features are implemented, so I think we can implement it, but there may be some problem getting it to work in the `AutoRun()`.

That's fair. I can close this if it's too premature. Up to you.

> I think we should change this example to match. Do you mind making these changes?

It is fixed now.

> I think this would not work. The topic has to be created with ordering keys enabled, and the publisher too.

I think it is enabled for the publisher now. I don't know how to create the topic with the ordering keys enabled, let me know if I missed something.

**Review by coryan — CHANGES_REQUESTED** [review]
You did not miss anything, I had forgotten that *subscriptions* need to have ordering keys enabled, topics are fine.

The test failures (against production, most tests are against the emulator) have me worried:

https://source.cloud.google.com/results/invocations/748bdb45-a261-4de4-ad81-ade7e0773564/targets
https://source.cloud.google.com/results/invocations/69e403c9-5e53-49af-a947-7da6543ec81d/targets
https://source.cloud.google.com/results/invocations/76f09db9-cf89-40f5-a706-53dcc4a094b8/targets

I think this means we are not in the EAP for ordering keys.  We need to disable this sample when using it against production.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059#-:-MHJGWPxBvv7tR2OubDX:b-qb67ue)* status: all files reviewed, 2 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/pubsub/samples/samples.cc, line 1203 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059#-MHJG4NN-MgLbPrTK4CJ:-MHJG4NN-MgLbPrTK4CK:b45872m) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7d4aaa32397911497923c9fe0a968bdea8b4370b/google/cloud/pubsub/samples/samples.cc#L1203)):*
> ```cpp
> 
>   auto topic = google::cloud::pubsub::Topic(project_id, topic_id);
>   auto publisher = google::cloud::pubsub::Publisher(
> ```

I think we should create a second `ordered_publisher` with these settings (and use it exclusively in the `PublishOrderingKey()` call below).  Soon a publisher with enabled message ordering will reject messages without an ordering key, and vice-versa.
___
*[google/cloud/pubsub/samples/samples.cc, line 1251 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059#-MHJK3Ya7cOTssgPQ3h7:-MHJK3Ya7cOTssgPQ3h8:b-hg3tkk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7d4aaa32397911497923c9fe0a968bdea8b4370b/google/cloud/pubsub/samples/samples.cc#L1251)):*
> ```cpp
> 
>   std::cout << "\nRunning PublishOrderingKey() sample" << std::endl;
>   PublishOrderingKey(publisher, {});
> ```

To get this to work now we will need to wrap it in something like:

```cc
if (UsingEmulator()) PublishOrderingKey(ordered_publisher, {});
```

and with:

```cc
bool UsingEmulator() {
  return google::cloud::internal::GetEnv("PUBSUB_EMULATOR_HOST").has_value();
}
```

**Comment by remyabel** [comment]
> The test failures (against production, most tests are against the emulator) have me worried:

I lost permissions to see the Kokoro logs.

> I think we should create a second `ordered_publisher` with these settings (and use it exclusively in the `PublishOrderingKey()` call below). Soon a publisher with enabled message ordering will reject messages without an ordering key, and vice-versa.

Done.

> To get this to work now we will need to wrap it in something like:

Done. Thanks for pointing it out.

**Review by coryan — CHANGES_REQUESTED** [review]
>> To get this to work now we will need to wrap it in something like:
>
> Done. Thanks for pointing it out.

I am missing this change?

>> The test failures (against production, most tests are against the emulator) have me worried:
> 
> I lost permissions to see the Kokoro logs.

I was able to open those links in an incognito window.  In any case, the error I was highlighting was:

```
Running PublishOrderingKey() sample
Message k0#data0 published with id=1532856858662867
Standard exception raised: Error in non-idempotent operation FlushImpl: A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0] [INTERNAL]
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Error in non-idempotent operation FlushImpl: A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0] [INTERNAL]
```

If you could share the specific error you get trying to open those links I can try to get that fixed. They are supposed to be "public" logs.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059#-:-MHMls9x1zSuBVC520jp:bq8yt8a)* status: all files reviewed, 1 unresolved discussion (waiting on @remyabel)

___
*[google/cloud/pubsub/samples/samples.cc, line 1251 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059#-MHJK3Ya7cOTssgPQ3h7:-MHMmXVK3yhDoZNQXWDZ:b-qqfczm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7d4aaa32397911497923c9fe0a968bdea8b4370b/google/cloud/pubsub/samples/samples.cc#L1251)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

To get this to work now we will need to wrap it in something like:

```cc
if (UsingEmulator()) PublishOrderingKey(ordered_publisher, {});
```

and with:

```cc
bool UsingEmulator() {
  return google::cloud::internal::GetEnv("PUBSUB_EMULATOR_HOST").has_value();
}
```

</blockquote></details>

I see the new `UsingEmulator()` function, but not see any changes to use it?

**Comment by remyabel** [comment]
> I am missing this change?

Sorry, I've been "slow" lately. I added the missing call now. Thanks for your patience.

> I was able to open those links in an incognito window. In any case, the error I was highlighting was:

That does not work for me. It just says "oops, page not found make sure the address is correct."

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5059#-:-MHN5br2DXoeF7tr73z3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
