### PR TITLE
test(spanner): use MakeInsecureCredentials() in UnifiedCredentials test

### PR DESCRIPTION
**Pull request by devbww**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8058)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
Could you change the other cases of this too?

```
git ls-files | xargs grep -n '"test-only-invalid", std::chrono'
google/cloud/pubsub/integration_tests/schema_admin_integration_test.cc:112:                      "test-only-invalid", std::chrono::system_clock::now() +
google/cloud/pubsub/integration_tests/subscriber_integration_test.cc:449:                      "test-only-invalid", std::chrono::system_clock::now() +
google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc:214:                      "test-only-invalid", std::chrono::system_clock::now() +
google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc:119:                      "test-only-invalid", std::chrono::system_clock::now() +
google/cloud/spanner/integration_tests/client_integration_test.cc:978:                      "test-only-invalid", std::chrono::system_clock::now() +

```

**Comment by coryan** [comment]
Also that list may not be exhaustive... There could be other similar problems with a different pattern

**Comment by devbww** [comment]
> Could you change the other cases of this too?

Done.

> Also that list may not be exhaustive... There could be other similar problems with a different pattern

I don't know enough to know, but I can tell you that these seem to be the only `if emulator` cases that did not already use `MakeInsecureCredentials()`.

**Review by coryan — APPROVED** [review]
Thanks.  That search criteria SGTM.  The PR description is slightly off now, FWIW.

**Pull request merged**
