### PR TITLE
feat(spanner): statistics returned for a committed transaction

### PR DESCRIPTION
**Pull request by devbww**
Introduces `google::cloud::spanner::CommitStats` and adds it as
an optional member of `google::cloud::spanner::CommitResult`.

Adds `google::cloud::spanner::CommitOptions`, which can be
included on any `Commit()` call to request returning `CommitStats`
in the `CommitResult`.

Also adds `ConnectionImplTest.CommitSuccessWithStats` and
`ClientTest.CommitStats` test cases, and `spanner_get_commit_stats`
sample.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5492)

### CODE REVIEW

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 12 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5492#-:-MLzmvvy0Ys-tN2NYmw-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @devbww and @mr-salty)

___
*[google/cloud/spanner/client.h, line 589 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5492#-MLzmzuID2SbcPG8UMwA:-MLzm6o3-BTI_BP0ocTi:b9s8kny) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/869df6222fcf89abaa918225f1ecf62b0e96eeec/google/cloud/spanner/client.h#L589)):*
> ```objc
>    *     commits. All mutations are applied atomically, in the order they appear
>    *     in this list.
>    * @param options The options to apply to the commit.
> ```

nit: above you just used `@param options to apply to the commit.` any reason for the difference?  I prefer the other description.
___
*[google/cloud/spanner/commit_options.h, line 26 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5492#-MLznOgL75baVSVsZM-q:-MLznOgL75baVSVsZM-r:bljun9l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/869df6222fcf89abaa918225f1ecf62b0e96eeec/google/cloud/spanner/commit_options.h#L26)):*
> ```objc
> 
> /**
>  * Set options on calls to `spanner::Client::Commit()`.
> ```

Consider adding Doxygen tags to the existing example and linking them from here in a `@par Example` paragraph.

**Review by devbww — COMMENTED** [review]
PTAL.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5492#-:-MM-OzP5AnkqPMhJiFnr:b-83330m)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @coryan and @mr-salty)

___
*[google/cloud/spanner/client.h, line 589 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5492#-MLzmzuID2SbcPG8UMwA:-MM-O5_y62jGJ-OtmZIV:b-aka8mb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/869df6222fcf89abaa918225f1ecf62b0e96eeec/google/cloud/spanner/client.h#L589)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: above you just used `@param options to apply to the commit.` any reason for the difference?  I prefer the other description.
</blockquote></details>

Done.

I only used the "full sentence" variety here because it was consistent with the `mutations` neighbor.  But either way is fine with me.  Thanks.
___
*[google/cloud/spanner/commit_options.h, line 26 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5492#-MLznOgL75baVSVsZM-q:-MM-Oq10Esqbkuxp4q-L:bkebocg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/869df6222fcf89abaa918225f1ecf62b0e96eeec/google/cloud/spanner/commit_options.h#L26)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Consider adding Doxygen tags to the existing example and linking them from here in a `@par Example` paragraph.
</blockquote></details>

Done (and verified).  Thanks.

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5492#-:-MM0WmN9BaE5AnbO18rj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mr-salty)

**Review by devjgm — APPROVED** [review]
Very complete! Thanks!

**Pull request merged**
