### PR TITLE
feat(pubsub): Implement pubsub_dead_letter_update_subscription sample

### PR DESCRIPTION
**Pull request by remyabel**
Fixes: #4743

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5103)

### CODE REVIEW

**Review by coryan — COMMENTED** [review]
Thanks! One nit, below.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5103#-:-MHkhy8n9x7FPPNQGZPE:b-w1n6hp)* status: all files reviewed, 1 unresolved discussion (waiting on @remyabel)

___
*[google/cloud/pubsub/samples/samples.cc, line 304 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5103#-MHkeQdB-AmhJ4hXS1KS:-MHkeQdC6X7RhS-ai5N0:bskball) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/d779e07402174cb2d94698c03fd43faf8de13327/google/cloud/pubsub/samples/samples.cc#L304)):*
> ```cpp
>               << "\n";
> 
>     std::cout << "It will forward dead letter messages to: "
> ```

nit: what do you think if we merge all these streaming output statements into one?

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5103)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @coryan)

___
*[google/cloud/pubsub/samples/samples.cc, line 304 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5103#-MHkeQdB-AmhJ4hXS1KS:-MHkwE-S2WBbC0oHbNjk:b-s13hx3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/d779e07402174cb2d94698c03fd43faf8de13327/google/cloud/pubsub/samples/samples.cc#L304)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: what do you think if we merge all these streaming output statements into one?
</blockquote></details>

Done. But it looks kind of ugly.

**Comment by coryan** [comment]
___
*[google/cloud/pubsub/samples/samples.cc, line 304 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5103#-MHkeQdB-AmhJ4hXS1KS:-MHl0WNf7LX5sqLlkpQD:b8y7sgu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/d779e07402174cb2d94698c03fd43faf8de13327/google/cloud/pubsub/samples/samples.cc#L304)):*
<details><summary><i>Previously, remyabel wrote…</i></summary><blockquote>

Done. But it looks kind of ugly.
</blockquote></details>

You are right, sorry for the bother, can you revert to the previous version?

**Review by coryan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5103#-:-MHl3s5W2WwWTSf80lo2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
