### PR TITLE
chore: upgrade grpc to 1.34.0

### PR DESCRIPTION
**Pull request by devjgm**
* Also updates protobuf to 3.14.0, because this gRPC required a newer protobuf.
* This gRPC also takes a dep on RE2, which is available as package on many systems, but on some older distros we need to compile it from source.

Note: This upgrade of grpc will enable us to upgrade our dep on Abseil to the [Sept 2020 LTS](https://github.com/abseil/abseil-cpp/releases/tag/20200923.2), which I'll do in a followup PR.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5579)

### CODE REVIEW

**Review by coryan — APPROVED** [review]
:lgtm:  Thanks!

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5579#-:-MNenB9w-zRdTLb790ip:b-e7bejd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by devjgm** [comment]
Bummer. Some breakages here that I need to look at.

**Comment by devjgm** [comment]
I think the Windows build are failing due to https://github.com/grpc/grpc/issues/24904

**Comment by devjgm** [comment]
Closing for now. I'll re-open once the build issues are fixed.

**Pull request closed without merging**
