### PR TITLE
feat(storage): Add `UploadFromOffset` and `UploadLimit` to `UploadFile`

### PR DESCRIPTION
**Pull request by vnvo2409**
This PR is a part of #4437 
I would like to ask where I should write test for this PR. Thank you

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4473)

### CODE REVIEW

**Comment by vnvo2409** [comment]
About `fifo` file, it is a little bit more complicated since we have to have 2 threads, one writes data to `fifo` and one uploads the data to GCS server simultaneously. Please review the current changes first and I will add the test for `fifo` later. Thank you.

**Comment by vnvo2409** [comment]
I will wait for #4408. In the mean time, I will do some tests with upload for irregular file

**Comment by coryan** [comment]
@vnvo2409  we merged #4408 earlier today in case you want to pick this up again.

**Comment by vnvo2409** [comment]
I think that we have to write another helper function like `UploadFileSpecial` to deal with special file. After some experiments, C++ api is really bad at dealing with `fifo`:
- `seekg()` does not work.
- We have to read only 1 byte at a time because `gcount(), tellg()` do not work. 
- when we call `fstream.close()`, it causes the thread which is writing to `fifo` stop too. This may cause some errrors since the thread that is writing to `fifo` isn't related to `google-cloud-cpp`.

So I think we should have a seperate PR for the special file. What do you think ?

**Comment by coryan** [comment]
> So I think we should have a separate PR for the special file. What do you think ?

Yes, it seems that getting those to work should be a separate bug and PR.  We might decide to not have them work at all (as opposed to just warning about them).

**Comment by vnvo2409** [comment]
Test failed because
```
/v/google/cloud/storage/client.cc:131:19: error: comparison of integers of different signs: 'streamsize' (aka 'long') and 'size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
  if (is.gcount() < payload.size()) {
      ~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~
1 error generated.
```

**Comment by vnvo2409** [comment]
Done 🎉

**Pull request merged**
