### PR TITLE
ci: use bazel for the coverage build

### PR DESCRIPTION
**Pull request by devjgm**
Fixes: #5067

This changes our "coverage" build to use bazel rather than cmake. The idea is that since bazel can use a remote cache that's updated from the pre- and post-merge builds, the cache hits may be higher. Bazel also knows how to run coverage tests in parallel, which solves #3530.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5075)

### CODE REVIEW

**Review by coryan — COMMENTED** [review]
I just noticed the integration tests for the generator are not running:

https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5075/src/generator/integration_tests/generator_integration_test.cc

Seems like another missing environment variable? 

https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5075/src/generator/integration_tests/generator_integration_test.cc#L45

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5075#-:-MHScc8k6YFSU7OQz7dv:bxciw2m)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by devjgm** [comment]
> I just noticed the integration tests for the generator are not running:
> 
> https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5075/src/generator/integration_tests/generator_integration_test.cc
> 
> Seems like another missing environment variable?
> 
> https://codecov.io/gh/googleapis/google-cloud-cpp/pull/5075/src/generator/integration_tests/generator_integration_test.cc#L45
> 
> > Reviewed 13 of 13 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5075#-:-MHScc8k6YFSU7OQz7dv:bxciw2m)_ status: :shipit: complete! all files reviewed, all discussions resolved

Thanks. Fixed.

**Review by coryan — APPROVED** [review]
As we discussed, you probably want to run some additional testing, but so far this :lgtm: 

There are some changes in coverage for the `generator/` directory that maybe @scotthart wants to look at. You both can decide if these changes can wait for a future PR.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5075#-:-MHSpnXKCvjpS5n88ipX:b-voryh2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by devjgm** [comment]
> As we discussed, you probably want to run some additional testing, but so far this :lgtm:
> 
> There are some changes in coverage for the `generator/` directory that maybe @scotthart wants to look at. You both can decide if these changes can wait for a future PR.

There was another problem w/ the generator tests that I just fixed and am rerunning the coverage numbers. The generator integration tests were running twice: once with the env set to enable them (which worked), then once again w/ the env set to disable the tests, which skipped them all, and that overwrote the coverage numbers w/ basically no coverage. So maybe that'll address some of the issues.

**Comment by coryan** [comment]
> The generator integration tests were running twice ...  and that overwrote the coverage numbers w/ basically no coverage. So maybe that'll address some of the issues.

I am surprised that running the same binary with different options overwrites the coverage.  We run many many tests over the same library code, and the coverage is cumulative: the final result is the aggregated coverage across all the tests.  I guess it is possible that Bazel treats binary coverage differently, but that is still a surprise.

**Comment by devjgm** [comment]
> > The generator integration tests were running twice ...  and that overwrote the coverage numbers w/ basically no coverage. So maybe that'll address some of the issues.
> 
> I am surprised that running the same binary with different options overwrites the coverage. We run many many tests over the same library code, and the coverage is cumulative: the final result is the aggregated coverage across all the tests. I guess it is possible that Bazel treats binary coverage differently, but that is still a surprise.

My guess is that the issue is related to multiple invocations of the bazel command. Imagine this:

```shell
$ bazel coverage //foo:foo_test  # After this run, there will be a foo/foo_test/coverage.dat file somwhere in ~/.cache
$ bazel coverage --test_env=FOO_SKIP_ALL=1 //foo:foo_test  # This would skip all the tests and would overwrite the same foo/foo_test/coverage.dat file
```
That's a simplified version of what was happening w/ the generator integration tests.

**Comment by devjgm** [comment]
> As we discussed, you probably want to run some additional testing

Ack. I did this test, and it worked correctly.
cov

**Review by coryan — APPROVED** [review]
> My guess is that the issue is related to multiple invocations of the bazel command. Imagine this:

TIL.  I guess we will need to structure our tests differently if we want to test code with two settings for an environment variable or other configuration.  Maybe use `TEST_P()` or something.

:lgtm: 

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5075#-:-MHTFhGq71uvtHBOrKxc:bs6p2hf)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
