### PR TITLE
docs(pubsub): add kinesis sample

### PR DESCRIPTION
**Pull request by alevenberg**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13593)

### CODE REVIEW

**Comment by alevenberg** [comment]
The emulator needs to be updated.

Currently getting

```ingestion_data_source_settings.aws_kinesis.gcp_service_account but got 2024-02-12T19:53:26.779777190Z [DEBUG] <140328757732352> UpdateTopic() >> status=INVALID_ARGUMENT: Invalid update_mask provided in the UpdateTopicRequest: ingestion_data_source_settings.aws_kinesis.gcp_service_account is not a known Topic field. Note that field paths must be of the form 'schema_settings' rather than 'schemaSetings'. (google/cloud/internal/log_wrapper.cc:29)```

**Comment by alevenberg** [comment]
```
Step #5: } (google/cloud/internal/log_wrapper.cc:24)
Step #5: 2024-03-08T19:02:06.763819768Z [DEBUG] <139986183036096> CreateTopic() >> status=NOT_FOUND: Cloud Pub/Sub tried to connect to the ingestion data source but could not find it: Not found; Gaia id not found for email fake-service-account@fake-gcp-project.iam.gserviceaccount.com. (google/cloud/internal/log_wrapper.cc:29)
Step #5: 2024-03-08T19:02:06.764360261Z [DEBUG] <139986183036096> DeleteTopic() << google.pubsub.v1.DeleteTopicRequest {
Step #5:   topic: "projects/cloud-cpp-testing-resources/topics/cloud-cpp-samples-2024-03-08-igbrzaxdlukjxbvcdxebjrkwrfntguwk"
Step #5: } (google/cloud/internal/log_wrapper.cc:24)
Step #5: 2024-03-08T19:02:07.320414091Z [DEBUG] <139986183036096> DeleteTopic() >> status=OK (google/cloud/internal/log_wrapper.cc:29)
Step #5: terminate called after throwing an instance of 'google::cloud::v2_23::Status'
```

**Comment by alevenberg** [comment]
Service team says we need to wait till 3/15 for the integration test to pass

**Comment by alevenberg** [comment]
Ready for review!

**Review by coryan — APPROVED** [review]

**Pull request merged**
