### PR TITLE
cleanup: enable clang-tidy for `storage`

### PR DESCRIPTION
**Pull request by devbww**
Part of #3958.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4075)

### CODE REVIEW

**Comment by devbww** [comment]
Does anyone have ideas about the wacky clang-tidy errors?  Thanks.

**Comment by coryan** [comment]
**TL;DR;** rebase your branch to the latest `master`, the `clang-tidy` build is a bit naive.

The `clang-tidy` build runs `clang-tidy` on any files that are different between the PR and the target branch (typically `master`), your PR is based on an older version of `master`, so the build is running `clang-tidy` in completely unrelated files (which may not be ready for `clang-tidy`).

After rebasing things worked fine for me (locally):

```
KOKORO_JOB_TYPE=PRESUBMIT_GITHUB KOKORO_GITHUB_PULL_REQUEST_TARGET_BRANCH=master ./ci/kokoro/docker/build.sh clang-tidy
```

**Comment by devbww** [comment]
That didn't seem to help.  Perhaps I did something wrong.

For the record, `ci/kokoro/docker/build.sh clang-tidy` has always worked for me.

**Comment by coryan** [comment]
I was able to repro locally, basically the nlohmann::json header is missing when we run clang-tidy in the PR build.  I will send a PR to fix this.

**Comment by coryan** [comment]
See #4078

**Comment by devbww** [comment]
It looks like I broke the rule about only running `update-abi` when `check-abi` fails.  Anyway, restored the old dump file.  Thanks.

**Pull request merged**
