### PR TITLE
refactor(generator): introduce VarsDictionary type alias

### PR DESCRIPTION
**Pull request by scotthart**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056)

### CODE REVIEW

**Review by coryan — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056)* status: all files reviewed, 4 unresolved discussions (waiting on @scotthart)

___
*[generator/internal/descriptor_utils_test.cc, line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-MHGdJ9D6WdU1171yB3-:-MHGdJ9D6WdU1171yB30:bhfn2jn) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5177d058cb70ddb915631cc150f5bb96e3e2205/generator/internal/descriptor_utils_test.cc#L56)):*
> ```cpp
>   }
> 
>   static VarsDictionary vars_;
> ```

nit: seems like this could be a non-static member variable? (unrelated, you can clean that up later)
___
*[generator/internal/descriptor_utils_test.cc, line 60 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-MHGdB-j58lqmpWTTyxI:-MHGdB-j58lqmpWTTyxJ:b-lr2op4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5177d058cb70ddb915631cc150f5bb96e3e2205/generator/internal/descriptor_utils_test.cc#L60)):*
> ```cpp
> 
> VarsDictionary CreateServiceVarsTest::vars_;
> TEST_P(CreateServiceVarsTest, KeySetCorrectly) {
> ```

nit (and unrelated): blank line before the `TEST_P()` line>
___
*[generator/internal/descriptor_utils_test.cc, line 233 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-MHGdWKyC9hTpRBRhhZt:-MHGdWKyC9hTpRBRhhZu:b-wz6zu7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5177d058cb70ddb915631cc150f5bb96e3e2205/generator/internal/descriptor_utils_test.cc#L233)):*
> ```cpp
>   }
> 
>   static std::map<std::string, VarsDictionary> vars_;
> ```

nit: ditto regarding static member variable.
___
*[generator/internal/printer_test.cc, line 55 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-MHGdeoB7YqthU67MVGA:-MHGdeoB7YqthU67MVGB:b-lg110e) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5177d058cb70ddb915631cc150f5bb96e3e2205/generator/internal/printer_test.cc#L55)):*
> ```cpp
>   Printer printer(generator_context.get(), "foo");
>   VarsDictionary vars;
>   vars["name"] = "Inigo Montoya";
> ```

nit:

```cc
VarsDictionary const vars{{"name", "Inigo Montoya"}};
```
___
*[generator/internal/printer_test.cc, line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-MHGe5hb77XedY8LI1PZ:-MHGe5hb77XedY8LI1P_:b-14i83a) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5177d058cb70ddb915631cc150f5bb96e3e2205/generator/internal/printer_test.cc#L56)):*
> ```cpp
>   VarsDictionary vars;
>   vars["name"] = "Inigo Montoya";
>   printer.Print(42, "some_file", vars, "Hello! My name is $name$.\n");
> ```

FYI, maybe you can read `some_file` back and examine the contents?  But consider using a random name so you can several copies of this test in parallel.

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[generator/internal/descriptor_utils_test.cc, line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-MHGdJ9D6WdU1171yB3-:-MHHQEzcCOJUqewsKKYr:b-2n9wov) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5177d058cb70ddb915631cc150f5bb96e3e2205/generator/internal/descriptor_utils_test.cc#L56)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: seems like this could be a non-static member variable? (unrelated, you can clean that up later)
</blockquote></details>

I only wan to be initialized once for all the value parameterized tests that use it. If I use SetUpTestSuite to do this, it has to be static.
___
*[generator/internal/descriptor_utils_test.cc, line 233 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-MHGdWKyC9hTpRBRhhZt:-MHHQbOK3iHrQJFh5H4q:b-ya81ng) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5177d058cb70ddb915631cc150f5bb96e3e2205/generator/internal/descriptor_utils_test.cc#L233)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: ditto regarding static member variable.
</blockquote></details>

Same as above

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[generator/internal/descriptor_utils_test.cc, line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-MHGdJ9D6WdU1171yB3-:-MHHRwt66MYXihN9Zuv4:b2cbfm2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5177d058cb70ddb915631cc150f5bb96e3e2205/generator/internal/descriptor_utils_test.cc#L56)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

I only wan to be initialized once for all the value parameterized tests that use it. If I use SetUpTestSuite to do this, it has to be static.
</blockquote></details>

s/wan/want vars_/

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-:-MHHT8Sk0OUv9A2anebA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[generator/internal/descriptor_utils_test.cc, line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-MHGdJ9D6WdU1171yB3-:-MHHSNYe3p52ypWWOcBw:bvmoyd9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5177d058cb70ddb915631cc150f5bb96e3e2205/generator/internal/descriptor_utils_test.cc#L56)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

s/wan/want vars_/
</blockquote></details>

I think I know how `SetUp()` and `SetUpTestSuite()` work.   Why do you need/want that behavior?  To me it looks like a cheap thing to initialize on each test, and the usual motivation for `SetUpTestSuite()` is that it is expensive to create some state on each test.

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[generator/internal/descriptor_utils_test.cc, line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5056#-MHGdJ9D6WdU1171yB3-:-MHHUTtHEiUQLYZ4o2RC:b-5hy48h) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5177d058cb70ddb915631cc150f5bb96e3e2205/generator/internal/descriptor_utils_test.cc#L56)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think I know how `SetUp()` and `SetUpTestSuite()` work.   Why do you need/want that behavior?  To me it looks like a cheap thing to initialize on each test, and the usual motivation for `SetUpTestSuite()` is that it is expensive to create some state on each test.
</blockquote></details>

It seemed wasteful to perform the exact same work for every test case.

**Pull request merged**
