### PR TITLE
impl(oauth2): refactor AuthorizedUserCredentials transport

### PR DESCRIPTION
**Pull request by scotthart**
part of the work for #9689

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690)

### CODE REVIEW

**Review by coryan — COMMENTED** [review]
Consider something like:

https://godbolt.org/z/ahMPE9MYM

Which remains compatible for `AuthorizedUserCredentials<>` and for `AuthorizedUserCredentails<storage::internal::CurlRequestBuilder>` and requires fewer `#ifdefs` I think.

**Review by scotthart — COMMENTED** [review]
Is this what you were describing?

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-:-N9h9dyH3RH1DNh_iRaC:b-6kcn24)* status: 0 of 6 files reviewed, all discussions resolved

**Review by coryan — CHANGES_REQUESTED** [review]
Yes, the changes to the class is what I was thinking about.  We should try to avoid the `#ifdef` and `#ifndef` blocks if at all possible.

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-:-N9hSkyc6cCwcn_RuI0K:b-ezzrfd)* status: all files reviewed, 3 unresolved discussions (waiting on @scotthart)

___
*[`CMakeLists.txt` line 176 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9hRciQ3VMWGXsE-Hu4:-N9hRciQ3VMWGXsE-Hu5:buqkn0d) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/678b05cfa3b6b9c11529c983f32959cb86f3f831/CMakeLists.txt#L176)):*
> ```CMake
>     set(GOOGLE_CLOUD_CPP_STORAGE_OAUTH2_ENABLE_REST_DEFAULT ON)
> endif ()
> option(GOOGLE_CLOUD_CPP_STORAGE_OAUTH2_ENABLE_REST
> ```

I think we should try to make this change with zero #ifdefs or options.  This is just changing the implementation of some classes .
___
*[`google/cloud/storage/oauth2/authorized_user_credentials.h` line 42 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9hNVJ23r45VX8d3I2O:-N9hNVJ23r45VX8d3I2P:b-w07jgk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/678b05cfa3b6b9c11529c983f32959cb86f3f831/google/cloud/storage/oauth2/authorized_user_credentials.h#L42)):*
> ```objc
> /// Object to hold information used to instantiate an AuthorizedUserCredentials.
> using AuthorizedUserCredentialsInfo =
>     google::cloud::oauth2_internal::AuthorizedUserCredentialsInfo;
> ```

I think this is a violation of our own rule about "don't require customers to understand stuff in `internal`".  But it is our own rule, and I would not feel bad if we had to make an exception, specially if this code is going away in X months.

Consider using `struct AuthorizedUserCredentialsInfo : public google::cloud::oauth2_internal::AuthorizedUserCredentialsInfo {};` I think that might generate better documentation.
___
*[`google/cloud/storage/oauth2/authorized_user_credentials.h` line 54 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9hSJUoELDrV9nGzmCq:-N9hSJUp4W1oCtXPZQpV:bohtx7w) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/678b05cfa3b6b9c11529c983f32959cb86f3f831/google/cloud/storage/oauth2/authorized_user_credentials.h#L54)):*
> ```objc
> /// header and the current time (for the expiration) form a TemporaryToken.
> StatusOr<RefreshingCredentialsWrapper::TemporaryToken>
> ParseAuthorizedUserRefreshResponse(
> ```

For better or worse this is part of the public API.  We should not remove it when `GOOGLE_CLOUD_CPP_STORAGE_OAUTH2_HAVE_REST` is enabled (assuming we still want the `#ifdef`).

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @coryan)

___
*[`CMakeLists.txt` line 176 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9hRciQ3VMWGXsE-Hu4:-N9idjKl-SdTPaIQXgQj:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/678b05cfa3b6b9c11529c983f32959cb86f3f831/CMakeLists.txt#L176)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think we should try to make this change with zero #ifdefs or options.  This is just changing the implementation of some classes .
</blockquote></details>

Done.
___
*[`google/cloud/storage/oauth2/authorized_user_credentials.h` line 42 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9hNVJ23r45VX8d3I2O:-N9idlZL-f54cIxqNbc8:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/678b05cfa3b6b9c11529c983f32959cb86f3f831/google/cloud/storage/oauth2/authorized_user_credentials.h#L42)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think this is a violation of our own rule about "don't require customers to understand stuff in `internal`".  But it is our own rule, and I would not feel bad if we had to make an exception, specially if this code is going away in X months.

Consider using `struct AuthorizedUserCredentialsInfo : public google::cloud::oauth2_internal::AuthorizedUserCredentialsInfo {};` I think that might generate better documentation.

</blockquote></details>

Done.
___
*[`google/cloud/storage/oauth2/authorized_user_credentials.h` line 54 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9hSJUoELDrV9nGzmCq:-N9idmqk2xszzd_T3hko:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/678b05cfa3b6b9c11529c983f32959cb86f3f831/google/cloud/storage/oauth2/authorized_user_credentials.h#L54)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

For better or worse this is part of the public API.  We should not remove it when `GOOGLE_CLOUD_CPP_STORAGE_OAUTH2_HAVE_REST` is enabled (assuming we still want the `#ifdef`).
</blockquote></details>

Done.

**Review by coryan — APPROVED** [review]
A few minor nits and a question for you.  Maybe we should discuss in today's meeting about the inheritance from a private struct.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-:-N9l3NLR9WoS5-rUoXKA:b-uvvrl6)* status: all files reviewed, 2 unresolved discussions (waiting on @scotthart)

___
*[`google/cloud/storage/oauth2/authorized_user_credentials.h` line 84 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9l2lrh5AX-Ax3pqHeV:-N9l2lrh5AX-Ax3pqHeW:b-xe797v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3528acbebd0f410c6aed01c14b3704f8f598b14/google/cloud/storage/oauth2/authorized_user_credentials.h#L84)):*
> ```objc
> class AuthorizedUserCredentials;
> 
> template <>
> ```

FYI: I am not sure how this will render in Doxygen.  Please run the `publish-docs-pr` build locally and take a look.  If needed use `@copydoc`.
___
*[`google/cloud/storage/oauth2/authorized_user_credentials.cc` line 30 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9l34W2437SUnO4d79x:-N9l34W2437SUnO4d79y:b7r8uai) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3528acbebd0f410c6aed01c14b3704f8f598b14/google/cloud/storage/oauth2/authorized_user_credentials.cc#L30)):*
> ```cpp
>       content, source, default_token_uri);
>   if (!info.ok()) return info.status();
>   AuthorizedUserCredentialsInfo i;
> ```

Since there is now some kind of inheritance relation, can we just use `operator=()`?
___
*[`google/cloud/storage/oauth2/authorized_user_credentials_test.cc` line 14 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9l3ER8-uIM8NXLya9W:-N9l3ER8-uIM8NXLya9X:b-3pg18s) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b30c1e19bcb469871c6f03570f6047b043389918/google/cloud/storage/oauth2/authorized_user_credentials_test.cc#L14)):*
> ```cpp
> // See the License for the specific language governing permissions and
> // limitations under the License.
> ```

We normally keep these blank lines.

**Review by scotthart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[`google/cloud/storage/oauth2/authorized_user_credentials.h` line 84 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9l2lrh5AX-Ax3pqHeV:-N9mGIqc5nl5jALwTRv5:btybuao) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3528acbebd0f410c6aed01c14b3704f8f598b14/google/cloud/storage/oauth2/authorized_user_credentials.h#L84)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

FYI: I am not sure how this will render in Doxygen.  Please run the `publish-docs-pr` build locally and take a look.  If needed use `@copydoc`.
</blockquote></details>

Added the copydoc but I think we have to wait on a Doxygen bug regarding template specializations to be addressed before we see any improvements.
___
*[`google/cloud/storage/oauth2/authorized_user_credentials.cc` line 30 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9l34W2437SUnO4d79x:-N9mGRLG0HwcKSMuxqmr:b-47t2ls) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f3528acbebd0f410c6aed01c14b3704f8f598b14/google/cloud/storage/oauth2/authorized_user_credentials.cc#L30)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Since there is now some kind of inheritance relation, can we just use `operator=()`?
</blockquote></details>

Performing a member wise move since the inheritance was removed.
___
*[`google/cloud/storage/oauth2/authorized_user_credentials_test.cc` line 14 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9690#-N9l3ER8-uIM8NXLya9W:-N9mGXWx22T4v9inmIIo:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b30c1e19bcb469871c6f03570f6047b043389918/google/cloud/storage/oauth2/authorized_user_credentials_test.cc#L14)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

We normally keep these blank lines.
</blockquote></details>

Done.

**Pull request merged**
