### PR TITLE
feat: migrates spanner into the monorepo

### PR DESCRIPTION
**Pull request by devjgm**
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/3561

This PR migrates the code from googleapis/google-cloud-cpp-spanner into this repo in the `google/cloud/spanner/` directory. We will not _archive_ the old repo until June 1.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4019)

### CODE REVIEW

**Comment by coryan** [comment]
FWIW, the integration tests and examples are **not** running as part of the code coverage build.  Like all CMake-based builds that build uses the emulators where possible, and production for the builds that cannot use an emulator.  For Pub/Sub we did this:

https://github.com/googleapis/google-cloud-cpp/blob/b2cb0ee35e2a7716a34c1948e03169216336c310/google/cloud/pubsub/integration_tests/CMakeLists.txt#L87

https://github.com/googleapis/google-cloud-cpp/blob/b2cb0ee35e2a7716a34c1948e03169216336c310/google/cloud/pubsub/samples/CMakeLists.txt#L47

so they are picked up here:

https://github.com/googleapis/google-cloud-cpp/blob/b2cb0ee35e2a7716a34c1948e03169216336c310/ci/kokoro/docker/build-in-docker-cmake.sh#L265

**Comment by devjgm** [comment]
> FWIW, the integration tests and examples are **not** running as part of the code coverage build. Like all CMake-based builds that build uses the emulators where possible, and production for the builds that cannot use an emulator. For Pub/Sub we did this:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/b2cb0ee35e2a7716a34c1948e03169216336c310/google/cloud/pubsub/integration_tests/CMakeLists.txt#L87
> 
> https://github.com/googleapis/google-cloud-cpp/blob/b2cb0ee35e2a7716a34c1948e03169216336c310/google/cloud/pubsub/samples/CMakeLists.txt#L47
> 
> so they are picked up here:
> 
> https://github.com/googleapis/google-cloud-cpp/blob/b2cb0ee35e2a7716a34c1948e03169216336c310/ci/kokoro/docker/build-in-docker-cmake.sh#L265

Thanks. I added another commit to this PR to add these labels.

**Comment by devjgm** [comment]
I see I'm missing some environment variables for the integration tests... I'll fix those tomorrow.

**Comment by devjgm** [comment]
Good catch about the "This currently lives in another repo..." comment. As discussed offline, I'll fix that in a followup PR. I filed https://github.com/googleapis/google-cloud-cpp/issues/4020 so I can't forget.

**Pull request merged**
