### PR TITLE
common: fix ambiguous match bazel error on macos 11 intel

### PR DESCRIPTION
**Pull request by vnvo2409**
On macos 11 intel, we will have the following compilation problem:
```
ERROR: Analysis of target '//google/cloud/pubsub/samples:samples' failed; build aborted: /Users/vovannghia/programming/google-cloud-cpp/google/cloud/testing_util/BUILD:43:11: Illegal ambiguous match on configurable attribute "defines" in //google/cloud/testing_util:google_cloud_cpp_testing:
@bazel_tools//src/conditions:darwin_x86_64
@bazel_tools//src/conditions:darwin
```
This PR removes `@bazel_tools//src/conditions:darwin` configuration.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6044)

### CODE REVIEW

**Comment by devjgm** [comment]
Thanks for the PR. I'm guessing we haven't tested on Big Sur, otherwise, we'd probably have caught this. I'm not an expert on this stuff, so let me ask a couple questions, please. Would removing the `conditions:darwin_x86_64` and leaving `@bazel_tools//src/conditions:darwin` also have fixed the ambiguous problem? I can understand why the condition is ambiguous, but I'm wondering which one we want to keep. Keeping `@bazel_tools//src/conditions:darwin` would seem to more closely match the other ones like `:freebsd`.

**Comment by vnvo2409** [comment]
We could remove one of them and it does not make any difference. 

I remove `darwin` because we don't have a M1 machine yet and we don't know if it supports `GOOGLE_CLOUD_CPP_HAVE_GETRUSAGE`, so I think it's better to let it fall to the default condition. What do you think ?

**Comment by coryan** [comment]
> We could remove one of them and it does not make any difference.
> 
> I remove `darwin` because we don't have a M1 machine yet and we don't know if it supports `GOOGLE_CLOUD_CPP_HAVE_GETRUSAGE`, so I think it's better to let it fall to the default condition. What do you think ?

`getrusage(2)` is very widely supported on Unices, regardless of the underlying CPU, let's use the more generic `@bazel_tools//src/conditions:darwin`.

**Comment by vnvo2409** [comment]
> `getrusage(2)` is very widely supported on Unices, regardless of the underlying CPU, let's use the more generic `@bazel_tools//src/conditions:darwin`.

Done, please take a look !

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6044#-:-MVvONvj7Xj03I5eSP6H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vnvo2409)

**Pull request merged**
