### PR TITLE
feat(storage): move nlohmann/json.hpp includes to cc file

### PR DESCRIPTION
**Pull request by remyabel**
Fixes: #2772

This completes the work of removing the `nlohmann/json.hpp` include from public
headers. `storage_include_test.cc` has been amended to test this.
`PatchBuilder` has been changed to follow the Pimpl idiom and some unused
functions were removed. `SetArrayField` no longer takes a vector but now a
`std::string` which represents a stringified array.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5311)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
Thank you for making these changes!  A few nits below, but let's start the builds too +kokoro:run 

> Reviewed 66 of 66 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5311#-:-MKH5DbT2ZCkQwodgd9Z:b-8wt0jm)* status: all files reviewed, 3 unresolved discussions (waiting on @remyabel)

___
*[google/cloud/storage/bucket_metadata.cc, line 233 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5311#-MKH2UHm6zRpUNMksTPK:-MKH2UHm6zRpUNMksTPL:buaof2k) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/cddc6782cc09cc77dd29dd454b8cf313faac92f2/google/cloud/storage/bucket_metadata.cc#L233)):*
> ```cpp
>     return ResetAcl();
>   }
>   nlohmann::json array = nlohmann::json::array();
> ```

here and below:

```cc
auto array = nlohmann::json::array();
```
___
*[google/cloud/storage/object_metadata.cc, line 123 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5311#-MKH36WE-uEAqsaDULau:-MKH36WF2NIx68oadUSl:b-tjpwm3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/cddc6782cc09cc77dd29dd454b8cf313faac92f2/google/cloud/storage/object_metadata.cc#L123)):*
> ```cpp
>     return ResetAcl();
>   }
>   nlohmann::json array = nlohmann::json::array();
> ```

s/nlohmann::json array/auto array/
___
*[google/cloud/storage/internal/access_control_common_parser.h, line 20 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5311#-MKH3QoQ-RLJEH4aAgxX:-MKH3QoR54UncESBKca7:bd5l6mr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/cddc6782cc09cc77dd29dd454b8cf313faac92f2/google/cloud/storage/internal/access_control_common_parser.h#L20)):*
> ```objc
> #include "google/cloud/storage/internal/access_control_common.h"
> #include "google/cloud/status.h"
> #include <nlohmann/json.hpp>
> ```

thanks!

**Review by remyabel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5311)* status: 64 of 68 files reviewed, 3 unresolved discussions (waiting on @coryan and @remyabel)

___
*[google/cloud/storage/bucket_metadata.cc, line 233 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5311#-MKH2UHm6zRpUNMksTPK:-MKHOVuS4-ovkhAq6v1-:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/cddc6782cc09cc77dd29dd454b8cf313faac92f2/google/cloud/storage/bucket_metadata.cc#L233)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

here and below:

```cc
auto array = nlohmann::json::array();
```

</blockquote></details>

Done.
___
*[google/cloud/storage/object_metadata.cc, line 123 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5311#-MKH36WE-uEAqsaDULau:-MKHOWlX6kmmWnA0Y5Wk:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/cddc6782cc09cc77dd29dd454b8cf313faac92f2/google/cloud/storage/object_metadata.cc#L123)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

s/nlohmann::json array/auto array/
</blockquote></details>

Done.

**Review by coryan — COMMENTED** [review]
looks good, +kokoro:run 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5311#-:-MKHR-Fm8q-dgaYIlN7h:b-h7ehr3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by remyabel** [comment]
Maybe file a separate issue for this, but `GOOGLE_CLOUD_CPP_STORAGE_ENABLE_GRPC` is disabled by default (but enabled by default in the CI). It wasn't building locally, hence why I wasn't seeing the compiler errors.

**Comment by coryan** [comment]
Argh, I bet that is annoying.  The GCS+gRPC plugin is not ready for prime time yet, that is why it is disabled by default.

**Comment by devjgm** [comment]
I just merged https://github.com/googleapis/google-cloud-cpp/pull/5313, which may conflict slightly with this. Sorry, but FYI.

**Comment by remyabel** [comment]
> I just merged #5313, which may conflict slightly with this. Sorry, but FYI.

No conflicts as far as I can tell, however the macos builds have flaked.

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5311#-:-MKHuiqk87QTWQRHpSbq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
