### PR TITLE
Add tracking region tag to GetBucketMetadata

### PR DESCRIPTION
**Pull request by frankyn**
cc: @JesseLovelace

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2920)

### CODE REVIEW

**Comment by frankyn** [comment]
Thanks @devjgm. I think I'm hitting a flake failure. Could you help by rerunning Kokoro? I don't have necessary permission to add labels to PRs in this repo.

**Comment by devjgm** [comment]
Triggered rebuild of Windows build.

**Comment by remyabel** [comment]
If you were able to preserve the log for the flake it may be useful to report it here: https://github.com/googleapis/google-cloud-cpp/issues/2113

**Comment by frankyn** [comment]
I can't merge @devjgm, could you help me merge?

**Pull request merged**
