### PR TITLE
impl(bigquery): ListJobs api - request object implementation and unit tests

### PR DESCRIPTION
**Pull request by jsrinnn**
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063)* status: all files reviewed, 4 unresolved discussions (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/internal/job_request.h` line 70 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NQlI4j2AdW7cr0rlXfC:-NQlI4j2AdW7cr0rlXfD:bgse378) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a796b2e02dbb0fa79da4fb3ad61280a90977bbac/google/cloud/bigquery/v2/minimal/internal/job_request.h#L70)):*
> ```objc
> };
> 
> enum class Projection {
> ```

I think we discussed just using strings for these "enums" in the design doc?  Admittedly `Projection` is unlikely to change, but `StateFilter` seems more prone to changes.
___
*[`google/cloud/bigquery/v2/minimal/internal/job_request.h` line 123 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NQlIYKp67TRnug0A9Q5:-NQlIYKp67TRnug0A9Q6:btmtepr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a796b2e02dbb0fa79da4fb3ad61280a90977bbac/google/cloud/bigquery/v2/minimal/internal/job_request.h#L123)):*
> ```objc
>   }
> 
>   ListJobsRequest& set_min_creation_time(std::uint64_t min_creation_time) & {
> ```

In C++ we should represent time using either one of the types from `std::chrono`.  Google uses `absl::Time*`, but we have avoided those in public APIs.

If these are time points, then change them to `std::chrono::system_clock::time_point`.  If they are something else, let's discuss.
___
*[`google/cloud/bigquery/v2/minimal/internal/job_request.h` line 124 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NQlIws3-rbGoK2tTi00:-NQlIws3-rbGoK2tTi01:bibjl9o) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a796b2e02dbb0fa79da4fb3ad61280a90977bbac/google/cloud/bigquery/v2/minimal/internal/job_request.h#L124)):*
> ```objc
> 
>   ListJobsRequest& set_min_creation_time(std::uint64_t min_creation_time) & {
>     min_creation_time_ = std::move(min_creation_time);
> ```

Generally do not `std::move()` primitive times (`int`, `bool`, and aliases of them).  Moreover, do not `std::move()` trivial types like `std::chrono::system_clock::time_point`.

If the compiler is working well these moves do nothing, if the optimizations are not all turned on it may actually be worse:

https://godbolt.org/z/feaE9nPqh
___
*[`google/cloud/bigquery/v2/minimal/internal/job_request.cc` line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NQlHvh95905_TibFrlS:-NQlHvh95905_TibFrlT:b-7mvvvp) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a796b2e02dbb0fa79da4fb3ad61280a90977bbac/google/cloud/bigquery/v2/minimal/internal/job_request.cc#L27)):*
> ```cpp
> GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN
> 
> std::string getJobsEndpoint(Options const& opts) {
> ```

The Google Style Guide says this should be `GetJobsEndpoint`.

**Review by jsrinnn — COMMENTED** [review]
Addressed all feedback. Thanks!

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-:-NR-btXHCFnZ9MIJbqii:b-9vckb4)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @coryan)

___
*[`google/cloud/bigquery/v2/minimal/internal/job_request.h` line 70 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NQlI4j2AdW7cr0rlXfC:-NR-C1k1CmPcF0UzM_rz:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a796b2e02dbb0fa79da4fb3ad61280a90977bbac/google/cloud/bigquery/v2/minimal/internal/job_request.h#L70)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think we discussed just using strings for these "enums" in the design doc?  Admittedly `Projection` is unlikely to change, but `StateFilter` seems more prone to changes.
</blockquote></details>

Done.
___
*[`google/cloud/bigquery/v2/minimal/internal/job_request.h` line 123 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NQlIYKp67TRnug0A9Q5:-NR-Hvvy-QrdikuF75VQ:b6xmgyw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a796b2e02dbb0fa79da4fb3ad61280a90977bbac/google/cloud/bigquery/v2/minimal/internal/job_request.h#L123)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

In C++ we should represent time using either one of the types from `std::chrono`.  Google uses `absl::Time*`, but we have avoided those in public APIs.

If these are time points, then change them to `std::chrono::system_clock::time_point`.  If they are something else, let's discuss.
</blockquote></details>

Done.

AFAICT, min_creation_time and max_creation_time are defined as uint64 values in the job proto and represent the milliseconds value from POSIX epoch which is why I had used  std::uint64_t as that seemed to be the closest comparison. 

I am not familiar with `std::chrono::system_clock::time_point`. Assuming this represents the same granularity and semantics as above, I have modified the min and max creation times to use the chrono::time_point type.

Per the docs (https://screenshot.googleplex.com/4hQxs95a7mDqcco),  the expected string version of the date/time format sent as query parameter is RFC3339,  time_point has a handy format function for this which was nice!
___
*[`google/cloud/bigquery/v2/minimal/internal/job_request.h` line 124 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NQlIws3-rbGoK2tTi00:-NR-BkNp-B9sP8zS0l37:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a796b2e02dbb0fa79da4fb3ad61280a90977bbac/google/cloud/bigquery/v2/minimal/internal/job_request.h#L124)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Generally do not `std::move()` primitive times (`int`, `bool`, and aliases of them).  Moreover, do not `std::move()` trivial types like `std::chrono::system_clock::time_point`.

If the compiler is working well these moves do nothing, if the optimizations are not all turned on it may actually be worse:

https://godbolt.org/z/feaE9nPqh


</blockquote></details>

Done.
___
*[`google/cloud/bigquery/v2/minimal/internal/job_request.cc` line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NQlHvh95905_TibFrlS:-NR-AfJ628JqSAUreZue:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a796b2e02dbb0fa79da4fb3ad61280a90977bbac/google/cloud/bigquery/v2/minimal/internal/job_request.cc#L27)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

The Google Style Guide says this should be `GetJobsEndpoint`.
</blockquote></details>

Done.

**Review by coryan — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063)* status: all files reviewed, 2 unresolved discussions (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/internal/job_request_test.cc` line 105 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NR-ukB9Es0beE-p4ZCG:-NR-ukB9Es0beE-p4ZCH:buyk5b1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5c3bba699437d0b4ed3bb23f5129e90ba467b425/google/cloud/bigquery/v2/minimal/internal/job_request_test.cc#L105)):*
> ```cpp
> TEST(ListJobsRequestTest, Success) {
>   ListJobsRequest request("1");
>   auto const& now = std::chrono::system_clock::now();
> ```

nit: you are extending the lifetime of this object but it would just be simpler to say `auto const now = std::chrono::system_block::now()`.  Thing of `std::chrono::` types as integers (of the right size).  Basically they are integers, their type captures the units and epoch *at compile time*, with zero run-time overhead.

https://en.cppreference.com/w/cpp/language/lifetime
___
*[`google/cloud/bigquery/v2/minimal/internal/job_request_test.cc` line 108 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NR-vF1n9mH2m7UPm3Xj:-NR-vF1n9mH2m7UPm3Xk:b-it55r0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5c3bba699437d0b4ed3bb23f5129e90ba467b425/google/cloud/bigquery/v2/minimal/internal/job_request_test.cc#L108)):*
> ```cpp
>   request.set_all_users(true)
>       .set_max_results(10)
>       .set_max_creation_time(now)
> ```

nit: you probably want to test different values for min and max creation time.  That would detect any crossed wires in the class, e.g., if your `set_min__creation_time()` was actually setting the maximum or vice-versa.

**Review by coryan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063)* status: all files reviewed, 2 unresolved discussions (waiting on @jsrinnn)

**Review by jsrinnn — COMMENTED** [review]
Addressed remaining feedback.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-:-NR3_KCwCiJ4bDATXsJg:b-ppgltf)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @coryan)

___
*[`google/cloud/bigquery/v2/minimal/internal/job_request_test.cc` line 105 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NR-ukB9Es0beE-p4ZCG:-NR3VN8o5YCvmoi1ULXO:bb6un1j) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5c3bba699437d0b4ed3bb23f5129e90ba467b425/google/cloud/bigquery/v2/minimal/internal/job_request_test.cc#L105)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: you are extending the lifetime of this object but it would just be simpler to say `auto const now = std::chrono::system_block::now()`.  Thing of `std::chrono::` types as integers (of the right size).  Basically they are integers, their type captures the units and epoch *at compile time*, with zero run-time overhead.

https://en.cppreference.com/w/cpp/language/lifetime

</blockquote></details>

Done
___
*[`google/cloud/bigquery/v2/minimal/internal/job_request_test.cc` line 108 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11063#-NR-vF1n9mH2m7UPm3Xj:-NR3_G32EMBWqFqSZ6d9:b-b6fkcz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5c3bba699437d0b4ed3bb23f5129e90ba467b425/google/cloud/bigquery/v2/minimal/internal/job_request_test.cc#L108)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: you probably want to test different values for min and max creation time.  That would detect any crossed wires in the class, e.g., if your `set_min__creation_time()` was actually setting the maximum or vice-versa.
</blockquote></details>

Done

Good point!

**Pull request merged**
