### PR TITLE
feat: expose and log ErrorInfo if present 

### PR DESCRIPTION
**Pull request by devjgm**
Fixes: https://github.com/googleapis/google-cloud-cpp/issues/7429

This PR adds a `google::cloud::ErrorInfo` class, which mirrors
[ErrorInfo][error-info-proto], and can also work with an equivalent
type in a REST world. We expose programmatic access to this via the
`g::c::Status::error_info()` accessor. We also log this data when
streaming a `g::c::Status` if it's present.

As of today, very few (if any) GCP services actually return this proto,
so I don't expect to see it much yet.

Alternative options:
* We could move `ErrorInfo` into it's own `error_info.h` file. It's pretty closely related to `Status`, so I'm OK w/ it where it is, but I'm also happy to move it if people think that's preferable.
* We can discuss the logging format that we want to use when streaming the `ErrorInfo`. I chose something in this PR, but we can certainly consider other output formats.

[error-info-proto]: https://github.com/googleapis/googleapis/blob/2e680c6be4b8e48c12f006b945b93edd41be8653/google/rpc/error_details.proto#L112

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640)

### CODE REVIEW

**Review by coryan — CHANGES_REQUESTED** [review]
A few last-minute nits, sorry about that.  I think we should keep #7429 open until the storage library also supports ErrorInfo?  We can fix that in a separate PR, of course.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-:-Moy1YPR2P9N5dfkMCPN:b-ieuzmu)* status: all files reviewed, 5 unresolved discussions (waiting on @devjgm)

___
*[google/cloud/grpc_error_delegate.cc, line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-MoxySI740IKbvDffcZh:-MoxySI740IKbvDffcZi:bxosirm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/grpc_error_delegate.cc#L73)):*
> ```cpp
>     google::rpc::Status const& proto) {
>   for (google::protobuf::Any const& any : proto.details()) {
>     if (any.Is<google::rpc::ErrorInfo>()) {
> ```

nit: what happens if there is more than one ErrorInfo?  Can you include a comment saying why that is not a problem?
___
*[google/cloud/grpc_error_delegate.cc, line 81 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moxyl9aB9dN5_ZsBJAI:-Moxyl9aB9dN5_ZsBJAJ:b8jityt) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/grpc_error_delegate.cc#L81)):*
> ```cpp
> }
> 
> void FillErrorInfo(google::rpc::Status const& status, ErrorInfo& error_info) {
> ```

Why the output argument?  Can we just return `error_info`?
___
*[google/cloud/grpc_error_delegate.cc, line 122 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moy0-GV1AASx5OUNl6c:-Moy0-GV1AASx5OUNl6d:b-am7d5h) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/grpc_error_delegate.cc#L122)):*
> ```cpp
>   }
>   ErrorInfo error_info;
>   FillErrorInfo(proto, error_info);
> ```

For a future PR: I think we should do the same thing for GCS, at least here:

https://github.com/googleapis/google-cloud-cpp/blob/75d5b339f6f3efc3eb5ef74c0dc88eb094bdf81d/google/cloud/storage/internal/http_response.cc#L25

Something like:

```cc
Status AsStatus(HttpResponse const& http_response) {
  if (HttpStatusCode::kMinContinue <= http_response.status_code &&
      http_response.status_code < HttpStatusCode::kMinSuccess) {
    // We treat the 100s (e.g. 100 Continue) as OK results. They normally are
    // ignored by libcurl, so we do not really expect to see them.
    return Status{};
  }
  if (HttpStatusCode::kMinSuccess <= http_response.status_code &&
      http_response.status_code < HttpStatusCode::kMinRedirects) {
    // We treat the 200s as Okay results.
    return Status{};
  }
  // Parse the payload as a JSON object, see https://cloud.google.com/apis/design/errors#http_mapping
  auto parsed = nlohmann::json::parse(http_response.payload, nullptr, false);
  ErrorInfo error_info = ExtractErrorInfo(parsed);
  return Status(/* map HTTP code */, parsed.value("message", ""), error_info);
```
___
*[google/cloud/status.h, line 70 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moy-GuhDaFxgbJE_f9z:-Moy-GuhDaFxgbJE_fA-:balrx38) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/status.h#L70)):*
> ```objc
>  *
>  * @see
>  * https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto
> ```

nit: I would use https://cloud.google.com/apis/design/errors#error_info 
___
*[google/cloud/status.cc, line 159 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moy2E4K5iC-69xQnT1h:-Moy2E4L22UA9GMcFnT7:bo2vcmf) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/status.cc#L159)):*
> ```cpp
>   auto const& error_info = s.error_info();
>   if (!error_info.reason().empty()) {
>     os << "\n    reason: " << error_info.reason();
> ```

Can we print the error in a single line (modulo the contents having `\n` in them)?  It is super annoying to have multi-line error messages when using `grep` to parse them.  Maybe format the ErrorInfo as as single-line JSON string, using the mapping from: https://cloud.google.com/apis/design/errors#http_mapping ?

**Review by devjgm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640)* status: all files reviewed, 4 unresolved discussions (waiting on @coryan)

___
*[google/cloud/grpc_error_delegate.cc, line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-MoxySI740IKbvDffcZh:-MoyFng86sYWEwSRxx7W:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/grpc_error_delegate.cc#L73)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: what happens if there is more than one ErrorInfo?  Can you include a comment saying why that is not a problem?
</blockquote></details>

Done.
___
*[google/cloud/grpc_error_delegate.cc, line 81 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moxyl9aB9dN5_ZsBJAI:-MoyFs34Cvz-WTzvp3yV:bfs2vm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/grpc_error_delegate.cc#L81)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Why the output argument?  Can we just return `error_info`?
</blockquote></details>

Just me being midway through a refactoring and not completing it. Oops. Yes, of course returning by value is better. Fixed.
___
*[google/cloud/grpc_error_delegate.cc, line 122 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moy0-GV1AASx5OUNl6c:-MoyG1uT4vdCEutOn-0W:b-4938az) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/grpc_error_delegate.cc#L122)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

For a future PR: I think we should do the same thing for GCS, at least here:

https://github.com/googleapis/google-cloud-cpp/blob/75d5b339f6f3efc3eb5ef74c0dc88eb094bdf81d/google/cloud/storage/internal/http_response.cc#L25

Something like:

```cc
Status AsStatus(HttpResponse const& http_response) {
  if (HttpStatusCode::kMinContinue <= http_response.status_code &&
      http_response.status_code < HttpStatusCode::kMinSuccess) {
    // We treat the 100s (e.g. 100 Continue) as OK results. They normally are
    // ignored by libcurl, so we do not really expect to see them.
    return Status{};
  }
  if (HttpStatusCode::kMinSuccess <= http_response.status_code &&
      http_response.status_code < HttpStatusCode::kMinRedirects) {
    // We treat the 200s as Okay results.
    return Status{};
  }
  // Parse the payload as a JSON object, see https://cloud.google.com/apis/design/errors#http_mapping
  auto parsed = nlohmann::json::parse(http_response.payload, nullptr, false);
  ErrorInfo error_info = ExtractErrorInfo(parsed);
  return Status(/* map HTTP code */, parsed.value("message", ""), error_info);
```

</blockquote></details>

This sounds like a good idea. I'm inclined to this the current PR close https://github.com/googleapis/google-cloud-cpp/issues/7429, then file a new issue about adding "ErrorInfo" support to GCS, including the details from this comment, and linking to the original https://github.com/googleapis/google-cloud-cpp/issues/7429

WDYT?
___
*[google/cloud/status.h, line 70 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moy-GuhDaFxgbJE_f9z:-MoyGL_MEwyqCIbDdebj:b-fkytnf) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/status.h#L70)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: I would use https://cloud.google.com/apis/design/errors#error_info 
</blockquote></details>

Better. Done.
___
*[google/cloud/status.cc, line 159 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moy2E4K5iC-69xQnT1h:-MoyGQavCM17vGSurB10:b26ehaf) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/status.cc#L159)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Can we print the error in a single line (modulo the contents having `\n` in them)?  It is super annoying to have multi-line error messages when using `grep` to parse them.  Maybe format the ErrorInfo as as single-line JSON string, using the mapping from: https://cloud.google.com/apis/design/errors#http_mapping ?
</blockquote></details>

I can change to json if you think that's better, but first a few clarifying questions about the suggestion.

* Do you mean to print *only* the ErrorInfo stuff as json, and print the existing code and message not in json like it currently does? Or print all of it as json?
* Making this valid json would require that we escape quotes in the contained strings. I could probably stuff this stuff in an nlohmann json object and offload the work to that library. Is this what you had in mind?

**Review by coryan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-:-MoyOGHZ2l3mK4L1P_GX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @devjgm)

___
*[google/cloud/grpc_error_delegate.cc, line 122 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moy0-GV1AASx5OUNl6c:-MoyL6La3dd1gWzk5x-m:b-81nlyc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/grpc_error_delegate.cc#L122)):*
<details><summary><i>Previously, devjgm (Greg Miller) wrote…</i></summary><blockquote>

This sounds like a good idea. I'm inclined to this the current PR close https://github.com/googleapis/google-cloud-cpp/issues/7429, then file a new issue about adding "ErrorInfo" support to GCS, including the details from this comment, and linking to the original https://github.com/googleapis/google-cloud-cpp/issues/7429

WDYT?
</blockquote></details>

SGTM.
___
*[google/cloud/status.cc, line 159 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moy2E4K5iC-69xQnT1h:-MoyLd0Z6p_J9LLnefrG:btooau7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/status.cc#L159)):*
Argh, quoting... 

* Yes, I was thinking just the `ErrorInfo` to format as json.
* Using `nlohmann::json` would add a dep for `common` and thus all the libraries, not sure we want that.

> Is this what you had in mind?

What I had in mind was ignoring the questions around quoting.  It may still work, but I would not call it "JSON" anymore, something like:

```cc
std::ostream& operator<<(std::ostream& os, Status const& s) {
  if (s.ok()) return os << StatusCode::kOk;
  os << s.code << ": " << s.message();
  auto const& ei = s.error_info();
  if (ei.reason().empty() && ei.domain().empty() && ei.metadata.empty()) return os;
  os << ", error_info={reason=" << ei.reason() << ", domain=" << ei.domain() << ", metadata={";
  char const* sep = "";
  for (auto const& e : ei.metadata()) {
      os << sep << '"' << e.first << "\": \"" << e.second << '"';
      sep = ", ";
  }
  return os << "}";
}
```

Anyway, treat this as optional.  I think it is better in that `grep` works, but worse in that it is harder to parse.

**Comment by coryan** [comment]
I restarted the `kokoro/macos/bazel` build.

**Comment by devjgm** [comment]
> I restarted the `kokoro/macos/bazel` build.

Thanks. I'm still playing w/ one-line log formats, so I'll still be pushing another commit to build.

**Review by devjgm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @coryan)

___
*[google/cloud/grpc_error_delegate.cc, line 122 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moy0-GV1AASx5OUNl6c:-MozHiD59oh10_BgKPIW:b-vrt9bg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/grpc_error_delegate.cc#L122)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

SGTM.
</blockquote></details>

https://github.com/googleapis/google-cloud-cpp/issues/7644
___
*[google/cloud/status.cc, line 159 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-Moy2E4K5iC-69xQnT1h:-MozHmEI9T0LVBM-QyAx:b-d58fkv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7c298c06267c2f39abb635e5d1a06b889ad33973/google/cloud/status.cc#L159)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Argh, quoting... 

* Yes, I was thinking just the `ErrorInfo` to format as json.
* Using `nlohmann::json` would add a dep for `common` and thus all the libraries, not sure we want that.

> Is this what you had in mind?

What I had in mind was ignoring the questions around quoting.  It may still work, but I would not call it "JSON" anymore, something like:

```cc
std::ostream& operator<<(std::ostream& os, Status const& s) {
  if (s.ok()) return os << StatusCode::kOk;
  os << s.code << ": " << s.message();
  auto const& ei = s.error_info();
  if (ei.reason().empty() && ei.domain().empty() && ei.metadata.empty()) return os;
  os << ", error_info={reason=" << ei.reason() << ", domain=" << ei.domain() << ", metadata={";
  char const* sep = "";
  for (auto const& e : ei.metadata()) {
      os << sep << '"' << e.first << "\": \"" << e.second << '"';
      sep = ", ";
  }
  return os << "}";
}
```

Anyway, treat this as optional.  I think it is better in that `grep` works, but worse in that it is harder to parse.

</blockquote></details>

Done. The output is one line now. This is more `grep`able, but it's less human readable. I don't think we need these to be perfectly parseable, because if programmatic access is needed, users can inspect the `ErrorInfo` object directly.

**Review by coryan — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640)* status: all files reviewed, 1 unresolved discussion (waiting on @devjgm)

___
*[google/cloud/status.cc, line 166 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-MozN4mQ9GpsdC5htc8B:-MozN4mRDGnH58w6sW8q:bzfwxoi) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/20ac43222766d88700ce63396f4d61af42adb837/google/cloud/status.cc#L166)):*
> ```cpp
>   auto const& e = s.error_info();
>   if (e.reason().empty() && e.domain().empty() && e.metadata().empty())
>     return os;
> ```

nit: braces in this case?

**Comment by devjgm** [comment]
> nit: braces in this case?

I'm not sure I follow. You mean print `{}` to indicate that error_info was empty? I thought we were trying to preserve the property that if error_info was empty, the logged output would be exactly the same as it is today and include nothing about error_info.

**Comment by devjgm** [comment]
You probably meant wrapping the if-body in braces. If so, done.

**Review by devjgm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @coryan)

___
*[google/cloud/status.cc, line 166 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7640#-MozN4mQ9GpsdC5htc8B:-Mozb_Tl4xOOIhtlNb2S:bb6tzbb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/20ac43222766d88700ce63396f4d61af42adb837/google/cloud/status.cc#L166)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: braces in this case?
</blockquote></details>

DOne

**Comment by coryan** [comment]
> You probably meant wrapping the if-body in braces. If so, done.

Yes, that is what I meant.  Sorry if it was unclear.

**Pull request merged**
